### ISSUE TITLE
Export as MHTML

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/DiscordChatExporter#1]
https://en.wikipedia.org/wiki/MHTML

**Comment by slurdge** [comment]
Another option would be to use data URIs ?

**Comment by despair86** [comment]
>export to e-mail
I _think_ you could just tack on a fake e-mail header to an existing HTML export

**Comment by orbitingful** [comment]
So we would be able to save images that are full sized using MHTML? I would love to see this feature implemented :)

**Comment by nodeunit** [comment]
Just found this tool and it works pretty well, but I am wondering if progress has been made toward this issue?

**Comment by Tyrrrz** [comment]
Not really but there's a workaround explained here: https://github.com/Tyrrrz/DiscordChatExporter/issues/21#issuecomment-348706551

**Comment by snoekbaars** [comment]
This is one of the most important features this exporter should have, as I'm pretty sure when messages are deleted their attachments are purged from Discord's servers too.

**Comment by zeutyx** [comment]
Any progress on this one?

**Comment by Tyrrrz** [comment]
I started working on this area and decided that MHTML as an additional option will not be available. Instead, self-contained export will be an option for all formats and will download accompanying media along with the chat log (albeit as separate files, akin to how e.g. Chrome does it).

For that reason, this issue is closed in favor of #21 with the latter extending in scope to other formats, not just HTML.

By the way, this was the first and, as such, the oldest issue ever for this project! It's also the issue that has been open the longest, almost 3 full years.
