### ISSUE TITLE
DiscordChatExporter.CLI crash on launch 

### ISSUE THREAD

**Issue by lblanc-esilv** [Tyrrrz/DiscordChatExporter#1000]
### Version

2.37.2

### Flavor

CLI (Command-Line Interface)

### Details

After playing around with the GUI (which worked as a charm btw), I wanted to use the CLI to be able to scrap threads, but it crashes instantaneously at launch. I tried running in Administrator mode and disabling antivirus but nothing seems to be working. I can barely see the first few command lines before the windows closes. I have tried on 2 PC's (both running Windows 10 with .NET Runtime 7.0.2) and both failed. I have tried with Runtime 7.0.1 still gets the same issue (while the GUI keeps working)

### Steps to reproduce

- Launch the app on Windows 10, .NET Runtime 7.0.2 or 7.0.1 => crashes

**Comment by CanePlayz** [comment]
You're not supposed to launch the .exe file in there. Instead, you have to navigate in the terminal to the location of that .exe and then put in your commands. Everything should be covered [here](https://github.com/Tyrrrz/DiscordChatExporter/blob/master/.docs/Getting-started.md).

**Comment by lblanc-esilv** [comment]
Oh my bad, I missed that part of the documentation. Thanks for the help!
