### ISSUE TITLE
GIFV is still broken 

### ISSUE THREAD

**Issue by cheese529** [Tyrrrz/DiscordChatExporter#1004]
### Version

Latest 

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

.gifv files are exported and displayed correctly in HTML in the version of DCE 2.37.2 but ALL of the releases since then do not export .gifv properly. it shows up as a still image and not a moving gif inside the exported HTML webpage.

### Steps to reproduce

paste any .gifv image link into a discord chat and export it as HTML to reproduce.

**Comment by Tyrrrz** [comment]
Did you try hovering your cursor over it? Gifv videos play only on-demand to reduce performance impact in a potentially large export.

**Comment by cheese529** [comment]
i did try to hover it and still it did not play, also only used 2 gifv files knowing about the performance impact

**Comment by Tyrrrz** [comment]
Can you share the HTML file?

**Comment by cheese529** [comment]
where can i upload it? it is kind of lewd/NSFW fyi

**Comment by Tyrrrz** [comment]
You can post it on our Discord server: https://discord.gg/2SUWKFnHSm

Or anywhere else and attach the link here
