### ISSUE TITLE
After entering token it loads for a very long time

### ISSUE THREAD

**Issue by goosecrash** [Tyrrrz/DiscordChatExporter#1005]
### Version

2.39

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

after using the newest version, the login loads infinitely

### Steps to reproduce

Download latest version
Enter and login with token

**Comment by Tyrrrz** [comment]
You may have triggered rate limiting or something, can you try again after an hour or so?

**Comment by xPolar** [comment]
I can reproduce this.

**Comment by Tyrrrz** [comment]
> I can reproduce this.

Does restarting help?

**Comment by xPolar** [comment]
Nope, I restarted multiple times

**Comment by Tyrrrz** [comment]
> Nope, I restarted multiple times

Can you try resetting your token (sign out & sign in) and see if it changes anything?

**Comment by Lunairayz** [comment]
+1 here

> Can you try resetting your token (sign out & sign in) and see if it changes anything?

Logged in again with pw instead of qr code (if that makes a difference), put in new token, still the same. Maybe it could actually be a rate limit cause my web discord started loading for a long time suddenly, will try again in a few.

**Comment by Teighe** [comment]
I am currently having issues with this as well. I closed the application, logged out of discord, logged back in using user name and password, reset my token, reopened the application, and entered the token. Still no luck.

**Comment by Bluscream** [comment]
I have the same issue, it took **17** minutes to load after clicking the login arrow

**Comment by Nomas-X** [comment]
I noticed the long loading time on my main account where I had too many servers which had too many channels in them.
When I tried using my bot which was only in 1 server, it was almost instant.

Might be related to simply having a lot to load?

**Comment by Tyrrrz** [comment]
I think it might be Discord's rate limiting for user accounts. Sometimes Discord responds with 429 and asks to wait a really long time (instead of the usual <1 second, it can ask for ~10 minutes).

Before v2.37, DiscordChatExporter mostly ignored the `retry-after` headers and Discord still satisfied those requests, but some users were raising concerns that it was getting their accounts flagged.

If you can get this issue reproduced consistently, I ask you to try v2.36.4 and see if it happens there too.

**Comment by Bluscream** [comment]
Could you just add a checkbox in the settings for "ignore rate-limit suggestions (might flag your account, be careful)"

**Comment by Tyrrrz** [comment]
> Could you just add a checkbox in the settings for "ignore rate-limit suggestions (might flag your account, be careful)"

If I can confirm that's what's causing the issue in the first place

**Comment by leumasme** [comment]
Using v2.40, loading after pasting the token with ~100 servers and >>200 dms open took multiple minutes. On a different account with 2 servers and 0 dms, it was effectively instant.
The long load time might be acceptable if its hard to avoid, but some UI feedback should be given to indicate what is happening (or even that anything is even still happening / it isnt stuck).

**Comment by Tyrrrz** [comment]
> Using v2.40, loading after pasting the token with ~100 servers and >>200 dms open took multiple minutes. On a different account with 2 servers and 0 dms, it was effectively instant.
> The long load time might be acceptable if its hard to avoid, but some UI feedback should be given to indicate what is happening (or even that anything is even still happening / it isnt stuck).

If you can get this issue reproduced consistently, I ask you to try v2.36.4 and see if it happens there too.

**Comment by Shroom2020** [comment]
> > Using v2.40, loading after pasting the token with ~100 servers and >>200 dms open took multiple minutes. On a different account with 2 servers and 0 dms, it was effectively instant.
> > The long load time might be acceptable if its hard to avoid, but some UI feedback should be given to indicate what is happening (or even that anything is even still happening / it isnt stuck).
> 
> If you can get this issue reproduced consistently, I ask you to try v2.36.4 and see if it happens there too.

I've been able to reproduce this quite consistently on my machine, even after a token refresh. 2.36.4 does not work any better on my machine.

**Comment by Tyrrrz** [comment]
> 2.36.4 does not work any better on my machine.

Hmm, it means that it's a different issue than I suspected. Are you also in a lot of servers/DMs?

**Comment by Shroom2020** [comment]
@Tyrrrz I’m at the server limit and I have many DMs. That said, this issue appears seemingly at random - there are days when it happens and days when everything is fine.

**Comment by Tyrrrz** [comment]
Try the latest CI build, please. Channels are now pulled lazily when you select a guild. Previously, they would all get pulled for every guild after you submit the token. This should make things much faster for users with a lot of guilds.

**Comment by McReaper** [comment]
I can confirm the fix is working, you just have to be patient on big servers.
