### ISSUE TITLE
Bot tokens without message content intents generate empty messages

### ISSUE THREAD

**Issue by mlomb** [Tyrrrz/DiscordChatExporter#1006]
### Version

v2.39.0

### Flavor

GUI (Graphical User Interface), CLI (Command-Line Interface)

### Details

Exporting chats using a bot token that does not have the "MESSAGE CONTENT INTENT" enabled, all messages in the export are empty (`"content": ""`)
Maybe the bot not having the "Read Message History" intent also causes this.

Of couse this is not something DCE can fix, instead I purpose to try to detect this scenario and show some kind of warning. I recently got pinged for this issue https://github.com/mlomb/chat-analytics/issues/62. This can become a recurrent issue since people may want to export their chats using bot accounts instead of their own.

### Steps to reproduce

Use a bot token that can't read messages

**Comment by Tyrrrz** [comment]
> Maybe the bot not having the "Read Message History" intent also causes this.

Yes. This is covered in the usage instructions.

> Of couse this is not something DCE can fix, instead I purpose to try to detect this scenario and show some kind of warning.

There were attempts to do it in the past, but there is no guaranteed way of checking if the bot has the required intents, at least using the REST API.

**Comment by mlomb** [comment]
Maybe if a significant amount of messages are exported and **none** of them have content maybe show a warning?

**Comment by Tyrrrz** [comment]
> Maybe if a significant amount of messages are exported and **none** of them have text content show a warning?

That was close to the original attempt and lead to many false positives in channels with embeds or system notifications.
