### ISSUE TITLE
Gifs save as mp4

### ISSUE THREAD

**Issue by JustYourJoe** [Tyrrrz/DiscordChatExporter#1008]
### Version

latest

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

not sure if this is intended but when you choose to save assets, all gifs are saved as mp4 files. This makes it hard to separate which files are saved gifs or actual mp4s that were sent

### Steps to reproduce

download a chat and choose to save assets
check the download location of the saved assets and find your gifs to be saved as mp4 with no way to tell if they were previously a gif or mp4

**Comment by Tyrrrz** [comment]
DCE saves the assets in whatever format Discord provides them, so if it saves it as mp4, it means it's stored as mp4 on the CDN. It's possible that the client converts the gif for you, or that you were actually uploading a gifv and not a gif.
