### ISSUE TITLE
Outdated instructions

### ISSUE THREAD

**Issue by Zo-Bro-23** [Tyrrrz/DiscordChatExporter#1010]
### Version

All

### Flavor

GUI (Graphical User Interface)

### Details

The instructions within the app asks you to use Chrome (or Firefox) DevTools to view network requests in order to get the Discord token. This method doesn't seem to work anymore since I didn't see any `messages` network requests when inspecting the Discord web app. Instead, I visited the Application tab, selected Local Storage, and searched for `token`. I had to refresh the web page, but I was able to get my token using this method. Perhaps the in-app instructions can be updated to reflect this?

### Steps to reproduce

NA

**Comment by Tyrrrz** [comment]
What you described are, in fact, the outdated instructions. If you don't see `messages`, make sure you reload the app (`Ctrl+R`) and switch between different servers/channels.

**Comment by Zo-Bro-23** [comment]
You're right. I didn't try switching between channels; my bad! Also, both methods work since they both give me the same token. Other users will likely find your method easier though, so I'll close this issue.
