### ISSUE TITLE
Crashes when exporting a huge chat (150,000+ messages)

### ISSUE THREAD

**Issue by thesupertechno** [Tyrrrz/DiscordChatExporter#1011]
### Version

ver 2.39.0

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

I was archiving a old server I really liked that got discontinued. Went to export the main chat, and after a few minutes, the application just terminates itself, like I killed it from task manager. The main chat is 150,000+ messages, and the application seems to crash whenever it gets to 57mb's in size.

### Steps to reproduce

- Launch and set up app
- Go to big discord server with lots of messages
- Export main chat
- A few minutes later, it will crash.

**Comment by CanePlayz** [comment]
I've had no problems with chats that are over 100 MB in size, so there seems to be another issue.

**Comment by Tyrrrz** [comment]
There was no error message of any sort? Maybe in the Windows event log?

Also, try the CLI version and see if the error persists there.
