### ISSUE TITLE
There is no function to dl images.

### ISSUE THREAD

**Issue by ZenoNiQ** [Tyrrrz/DiscordChatExporter#1015]
### Version

2.39.1

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

There is no function to local save media. Like it was before in pic below.
![img](https://camo.githubusercontent.com/23a64cf9775d471e399546eb05f0b111d4c9ea642b160d476a44144ee652cbe7/68747470733a2f2f692e696d6775722e636f6d2f6d7455466f6a532e706e67)

### Steps to reproduce

1.Start use the program.

**Comment by CanePlayz** [comment]
It is still there, it has meanwhile been renamed to `Download assets`.

![image](https://user-images.githubusercontent.com/81419612/224984988-0b377fff-6137-40c5-af44-89aad27a3451.png)

**Comment by ZenoNiQ** [comment]
Oh yes indeed my mistake. I didn't notice the scroll to the right. The fields fit too organically in the little window. Glory to Ukraine!
