### ISSUE TITLE
  Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by satheshshiva** [Tyrrrz/DiscordChatExporter#1016]
### Version

docker

### Flavor

CLI (Command-Line Interface)

### Export format

HTML

### Details

While doing export of any kind using docker on macos, I am getting the below error,
  Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### Steps to reproduce

❯ `docker run -it -e DISCORD_TOKEN=$DISCORD_TOKEN -v <system-path>:/out  tyrrrz/discordchatexporter export -c <channel-id>`

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
┌────────────────────────────────────────────────────────────────────┐
│   Thank you for supporting Ukraine <3                              │
│                                                                    │
│   As Russia wages a genocidal war against my country,              │
│   I'm grateful to everyone who continues to                        │
│   stand with Ukraine in our fight for freedom.                     │
│                                                                    │
│   Learn more: https://tyrrrz.me/ukraine                            │
└────────────────────────────────────────────────────────────────────┘

Resolving channel(s)...
Exporting 1 channel(s)...

▬Educational content▬ / 📚︱bb´s-guide-to-the-market ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%
                                                                                                  Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at DynamicClass.Regex22_Scan(System.Text.RegularExpressions.RegexRunner, System.ReadOnlySpan`1<Char>)
qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Comment by Tyrrrz** [comment]
This is really weird. I can't reproduce this, do you have any other background information maybe?

**Comment by satheshshiva** [comment]
I am getting this error on Docker 20.10.23 running on host Macbook Pro 2021 with M1 Max processor. 

My guess is the docker image does not support the m1 max processor. Supports only intel (did not test).

I installed the .net arm64 on my host machine and  tried running without docker. It works.

**Comment by Tyrrrz** [comment]
The image _should not_ need to support the host machine's specifics, but it's possible there's some weird edge case between Docker, .NET, and arm64 processors. 🤔

**Comment by rameerez** [comment]
I was getting the exact same error on my Apple M1 Max running Docker Desktop 4.17.0 on macOS 12.6.1

I can confirm @satheshshiva's workaround of installing the .NET runtime for arm64 + then running the cli works.

**Comment by verazuo** [comment]
Same here. Also Apple M1 Max chip

**Comment by Tyrrrz** [comment]
I found this, which might be relevant:

![image](https://user-images.githubusercontent.com/1935960/236688692-22d351d3-c1c8-484f-a855-cd0c2bf0d371.png)

**Comment by Tyrrrz** [comment]
Also created this discussion to make sure I'm not missing something: https://github.com/dotnet/dotnet-docker/discussions/4601/

**Comment by Tyrrrz** [comment]
I believe I fixed it by producing multi-arch Docker images. Please test it by pulling the `latest` tag:

```
$ docker pull tyrrrz/discordchatexporter:latest
```

![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/1935960/48a34b61-b7e5-432a-a8a5-dc5c8a3a5675)

Let me know if it works.

@satheshshiva @rameerez @verazuo

**Comment by satheshshiva** [comment]
Works fine now after pulling the latest docker image. Thank you, @Tyrrrz !
