### ISSUE TITLE
JSON option does not seem to export in-line emoji which are from other servers

### ISSUE THREAD

**Issue by Shadowmech88** [Tyrrrz/DiscordChatExporter#1026]
### Version

2.39.1

### Flavor

GUI (Graphical User Interface)

### Export format

JSON

### Details

When exporting a channel in HTML, all emoji are preserved exactly as they are. When exporting the same channel in JSON, built-in Discord emoji and emoji specific to the server are preserved, as are all emoji in reactions, but emoji which are both embedded in the text of a message _and_ originate from a different server do not seem to be preserved, and simply display in the message as :emoji:.
Due to the way the media files are named I have no way to actually know if they're being downloaded or not, and I also don't really know how the exports are supposed to associate the regular in-line :emoji: with their images since they don't have any explicit imageUrl like the reactions do, but every other emoji is showing up fine and these ones aren't.

Edit: Actually upon further testing, _sometimes_ emoji from other servers display correctly in-line, no idea why, and I've come across at least one instance of an emoji from a different server being rendered in chat, but as a completely different emoji.
I've also seen one instance of an emoji from the exported server failing to render, but just a few messages earlier someone had posted exactly the same emoji with a different name from a different server (which rendered successfully.) I thought it might have something to do with the "reuse assets" toggle, but I disabled it and tried the export again and saw no change.

### Steps to reproduce

- Download section of Discord channel that has emoji which originate from a different server posted in messages as part of the message text, as well as in reactions to messages.
- Open export in a frontend.
- External emoji are shown as plaintext :emoji: while all other emoji show up fine, including the external emoji in reactions.

**Comment by Shadowmech88** [comment]
Updated the description a bit. This issue doesn't seem to be 100% guaranteed - I'm looking right now at an export where I can see some server-external emojis rendering fine right above posts from other users with emojis that are also from different servers and they're only displayed as :text:.
No idea what the dividing factor is. It doesn't seem to be the source server being private, because I found where someone posted an emoji from a different, public server, exported that segment of chat, and that emoji failed to render.

**Comment by slatinsky** [comment]
Inline emojis are not exported in JSON format. Frontend tried to guess them from reactions from other messages - sometimes successfully, sometimes not. 

The solution would be to export them for example in `inlineEmoji` field, like we do with reactions.

**Comment by CrushedAsian255** [comment]
> Inline emojis are not exported in JSON format. Frontend tried to guess them from reactions from other messages - sometimes successfully, sometimes not.

so would using HTML be the best way to keep everything?
