### ISSUE TITLE
Entering token loads eternally when VPN enabled

### ISSUE THREAD

**Issue by josefpoulton** [Tyrrrz/DiscordChatExporter#1030]
### Version

2.39.1

### Flavor

GUI (Graphical User Interface)

### Details

When entering my token using the GUI version 2.39.1, the loading bar scrolls across eternally. I have to turn off my VPN, restart the app and then try again in order for the query to complete.

### Steps to reproduce

- Turn on VPN (I was using NordVPN)
- Enter your token
- Query will load forever

**Comment by ShrootBuck** [comment]
This isn't a bug with the program, it's just Discord ratelimiting the IP.
