### ISSUE TITLE
HTML rendering in email client broken in 2.39 (worked in 2.38)

### ISSUE THREAD

**Issue by andrewlow** [Tyrrrz/DiscordChatExporter#1042]
### Version

ver 2.39 and beyond

### Flavor

CLI (Command-Line Interface)

### Export format

HTML

### Details

I have some scripts invoked by cron that pull down chats from discord and email them to me. This mostly works well.

I'm using the docker container version and mapping the /out directory to my host filesystem.

```
docker run --rm -v $ROOT_DIR/out:/out \
        --name discord-scrape \
        -e TZ="America/Toronto" \
        --user $(id -u):$(id -g) \
        tyrrrz/discordchatexporter:$VERSION export -c 108563222222590854 \
        -t $TOKEN \
        --format HtmlDark \
        --after $SINCE
```

Once downloaded - I just push it through mail (Ubuntu linux)

```
cat $ROOT_DIR/out/* | mail -s "discord chat" -a "FROM:root@mydomain.ca" -a "Content-type: text/html" user@mydomain.ca
```

This has been working for some time. I'm guilty of rarely updating the docker image (and thus the image of the chat exporter) this is why my bug report is a bit late.

The html in email rendering is broken on multiple email clients - specifically K9Mail on Android and OSX 'Mail". 

Screenshots from OSX mail

2.38 worked fine
![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/2952475/efd212c3-59c7-4b79-b9d9-52be0d7be40f)

2.39 (and 2.39.1) are both badly rendered
![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/2952475/eb3dc629-755e-4919-a063-f8796442d3b9)

### Steps to reproduce

- Use docker container to run exporter - map /out onto host filesystem
- Pipe output .html file into email with "Content-type: text/html"
- View in email client

Comparing output from 2.38 to 2.39 we see big visual differences.

Viewing these files in a web browser appears to work as expected - but running the html file through a HTML validator results in multiple errors/warnings.

**Comment by Tyrrrz** [comment]
From what I know, email clients are notorious for having poor support for HTML. Do you have the option to just attach the exports as attachments instead?

Also, to really diagnose the issue, you'd need to find the last version that produced a renderable export. You said 2.38 worked fine, but the output on the screenshot you posted definitely looks broken.

**Comment by andrewlow** [comment]
I tested all the way back to 2.34.1 - and it was 'perfect' - then 2.35.2 was busted .. a little (see red arrow)

![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/2952475/c7ac7ec3-2edc-4d42-9df7-867d4b5c89f1)

But the transition from 2.38 to 2.39 really broke things from being slightly badly formatted - to horribly formatted.

I've pulled down / html formatted the same chat with 2.38 and 2.39. The diff is relatively short (8 lines total). 

I agree email clients are bad at HTML .. _but this mostly worked_ until recently. 

I'll try to isolate the HTML level difference that causes the problem.. the minified content is sort of horrible to sift through.  Give me a few days to find time to track down the specific thing - I'll post updates here.

I also quickly looked at the[ diff between the two versions](https://github.com/Tyrrrz/DiscordChatExporter/compare/2.38...2.39) there isn't much, but enough obviously.

Sorry - no - attachments break the workflow for me. I want to be able to scroll through an email on my phone. I can also just push this to a local web server, then visit that link on my phone.. so I'm not sunk.. but it's so very close to being right.

This is clearly a niche case - but if you're willing to entertain a small tweak to make things mostly work again I'd appreciate it. Nice project btw - very useful.

**Comment by Tyrrrz** [comment]
I think the best way to diagnose it is to compare the actual HTML files. You can use something like [codebeautify](https://codebeautify.org/htmlviewer) to prettify the minified code. If you run it on both files, it should produce a fairly consistent structure, I guess.

> This is clearly a niche case - but if you're willing to entertain a small tweak to make things mostly work again I'd appreciate it. Nice project btw - very useful.

That really depends on what's causing the issue in the first place. If it's a somewhat trivial change, then sure. My biggest concern is adding too much complexity to the HTML template. But we won't know until we find what's causing the issue in the first place.

> I tested all the way back to 2.34.1 - and it was 'perfect' - then 2.35.2 was busted .. a little (see red arrow)

What about 2.35 and 2.35.1?

**Comment by andrewlow** [comment]
Ugh.  [codebeautify](https://codebeautify.org/htmlviewer) is doing something to 'fix' things

If we assume that it's just formatting - then the formatting is fixing the email client rendering.

I take my 'broken' 2.39 generated version from DiscordChatExporter - and email it to myself.. busted.

Then take the same file - beautify it - download that file - and email that to myself - totally fine.

**Comment by andrewlow** [comment]
I wonder if I can just find a CLI version of the beautify code.. and preprocess myself into happiness.

**Comment by andrewlow** [comment]
Well - not easily - I tried installing '[tidy](http://www.html-tidy.org/)' and no luck, the file processed with tidy also failed to render correctly in the email client.

Any chance I can get DiscordChatExporter to NOT minify as much? A command line flag to disable the minification would likely fix this problem.

**Comment by Tyrrrz** [comment]
> Well - not easily - I tried installing '[tidy](http://www.html-tidy.org/)' and no luck, the file processed with tidy also failed to render correctly in the email client.

Can you diff the versions prettified by codebeautify and tidy to identify which parts are responsible?

> Any chance I can get DiscordChatExporter to NOT minify as much? A command line flag to disable the minification would likely fix this problem.

Minification shouldn't affect at all how the layout is rendered

**Comment by Tyrrrz** [comment]
Will close it as it's not actionable right now
