### ISSUE TITLE
--filter option states to support several query arguments, but it fails

### ISSUE THREAD

**Issue by smileBeda** [Tyrrrz/DiscordChatExporter#1045]
### Version

2.39.1

### Flavor

CLI (Command-Line Interface)

### Export format

JSON

### Details

I want to query messages with specific text content as per the DOC combing filters.

### Steps to reproduce

Pass the command as per the DOC should be possible:
`dotnet DiscordChatExporter.Cli.dll exportdm -t TOKE_HERE -f Csv --filter Image Upscaled`

Or `dotnet DiscordChatExporter.Cli.dll exportdm -t TOKE_HERE -f Csv --filter has:image ("Image #" | "Upscaled by" | "Upscaled (Beta) by")`

None of these work. In the second case it says it found no match (but there are messages with those values) and the first case, says `Option --filter expects a single argument, but provided with multiple:
<Image> <Upscaled>`

**Comment by Tyrrrz** [comment]
You have to encapsulate the filter in quotes (`"`) to escape the spaces from being treated as argument delimiters in your command line terminal.

**Comment by Tyrrrz** [comment]
Added more info to the docs
