### ISSUE TITLE
CLI attempts to download voice channels

### ISSUE THREAD

**Issue by DASPELLER4** [Tyrrrz/DiscordChatExporter#1049]
### Version

v2.40.0

### Flavor

CLI (Command-Line Interface)

### Details

Trying to save entire guild, this did previously work on a server without any VCs, but now the server I'm trying to save has VCs and the CLI is attempting to export the channel, once it starts the program keeps on running (text flashes sometimes) but otherwise hangs and never goes onto the next channel.

Error:
```
Exporting 72 channel(s)...

?? Server Stats ?? / Member Count: 7 ----------------------------------------   0%
```

Member Count: 7 is a VC auto created by a discord bot, the chat exporter is trying to export it but fails.

I am running DCE with wine in linux, exporting channels and DMs works perfectly and to export servers I have a solution to get every channel name and to put that into a file and make a command that iterates over every channel individually archiving it, but since this server has 69 text channels it is inefficient.

### Steps to reproduce

Run Command:
```
DiscordChatExporter.Cli.exe exportguild -t <token> -g <guild-id> --media -o ../<server dir>
```

**Comment by Tyrrrz** [comment]
There's a lot going on in this description, so I'll try to narrow it down:
1. Downloading VCs in itself is not a bug, VCs are normal channels with voice capability. They can have text and other types of messages inside them. Is the issue that you can't filter them out?
2. I don't remember off the top of my head, but the channel staying at 0% might just mean that it had no messages, and so it was skipped. Do the rest of the channels get exported correctly? Does the command finish eventually?

**Comment by DASPELLER4** [comment]
1. You're right, sorry absolutely forgot about the VC chat feature, Also the docs make 0 mention of how to filter out VCs so I presume the issue is that I can't filter them out technically.
2. I created a test server with 2 text channels (only 1 text channel would result in that channel being exported first) and one voice channel, if the exporter goes for the voice channel first, the program never ends and no other channel will get exported. I believe the --parallel feature would fix my issue but it just crashes the program with a huge [stack trace](https://daspeller4.xyz/drive/file/1/338b0435089e47df0e936c09b069293e/err.txt)

**Comment by Tyrrrz** [comment]
> 1. Also the docs make 0 mention of how to filter out VCs so I presume the issue is that I can't filter them out technically.

Yeah, there's no way to do it right now, but it could be a nice option to add.


> 2\. I created a test server with 2 text channels (only 1 text channel would result in that channel being exported first) and one voice channel, if the exporter goes for the voice channel first, the program never ends and no other channel will get exported. I believe the --parallel feature would fix my issue but it just crashes the program with a huge [stack trace](https://daspeller4.xyz/drive/file/1/338b0435089e47df0e936c09b069293e/err.txt)

Huh, that's weird. I'll look into it. What environment are you using DCE in?

**Comment by DASPELLER4** [comment]
I am using DCE in wine, it is a basic wine prefix with literally no DLLs manually installed and only using the dotnet and VCredist that DCE links to install, the weird console output format is normal for wine FYI however the stack trace is what it would be on windows, I'll try to dual boot later today onto my windows 7 install (I dont have windows 10 installed right now) and test it there.

**Comment by Tyrrrz** [comment]
You should be able to run DCE natively on any platform without wine. Is there any reason you use wine specifically?

**Comment by DASPELLER4** [comment]
hmm, honestly, no idea, it only took 1 minute of googling to figure out how to use dotnet runtime, I used to use pretty obscure OSs so I just assumed that dotnet didn't support my OS so I defaulted to wine, but now it does just work. I'll close this issue as for me the issue is fixed but if someone does need wine, it might need consideration.

**Comment by Tyrrrz** [comment]
Awesome :)
