### ISSUE TITLE
Multiple / Mass Export

### ISSUE THREAD

**Issue by jorelking** [Tyrrrz/DiscordChatExporter#105]
Is it possible to add a feature to mass export all of your DMs in 1 go instead of clicking multiple times per client? I feel like this would make like so much easier if this is possible. Thanks, love the program!

**Comment by RenanYudi** [comment]
Related to [#12](https://github.com/Tyrrrz/DiscordChatExporter/issues/12)

**Comment by Tyrrrz** [comment]
Yes, duplicate of #12
