### ISSUE TITLE
Don't open exported file after finishing

### ISSUE THREAD

**Issue by wertercatt** [Tyrrrz/DiscordChatExporter#108]
Being able to turn this feature off will be helpful for people exporting many channels at once, as well as people exporting large channels that can cause a large amount of lag when opened in a web browser.

**Comment by RenanYudi** [comment]
Duplicate of [#85](https://github.com/Tyrrrz/DiscordChatExporter/issues/85)

**Comment by wertercatt** [comment]
Whoops.

**Comment by Tyrrrz** [comment]
This will probably be replaced by an entirely different workflow with #85

**Comment by wertercatt** [comment]
Alright
