### ISSUE TITLE
Shared assets directory is used even when option is toggled off

### ISSUE THREAD

**Issue by juh9870** [Tyrrrz/DiscordChatExporter#1099]
### Version

2.40

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

When trying to export a channel, I noticed that `_Files` folder is not generated. Upon further investigation, it turns out that just having shared assets folder path specified leads to app using it for storing assets, regardless of checkbox state

### Steps to reproduce

- Open app
- Select shared assets folder path
- Make sure shared asset folder checkbox is off
- Export a chat with assets

**Comment by Tyrrrz** [comment]
> Make sure shared asset folder checkbox is off

Which checkbox is that?

![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/1935960/aa2aa5bc-cc57-4864-9dc8-6d472199d53a)

**Comment by juh9870** [comment]
"Resuse assets"

**Comment by CanePlayz** [comment]
> "Resuse assets"

"Reuse assets" actually refers to not downloading already downloaded files again.

**Comment by juh9870** [comment]
Oh, so there is no toggle to disable `assets directory path`?
