### ISSUE TITLE
Rendering of "_" is inaccurate

### ISSUE THREAD

**Issue by wertercatt** [Tyrrrz/DiscordChatExporter#110]
The HTML exporter does not properly replicate _'s behavior in Discord's markdown.
Test message:
```
test_test test_test
_test_
_t_est
t_e_st
test_test_
```
Discord's rendering: [view here](https://i.imgur.com/klMruGQ.png)
DiscordChatExporter HTML rendering:
```html
<div class="chatlog__content">
test<i>test test</i>test<br /><i>test</i><br /><i>t</i>est<br />t<i>e</i>st<br />test<i>test</i>

</div>
```

**Comment by Tyrrrz** [comment]
The underlying issue is the same as in #109

**Comment by wertercatt** [comment]
Ah, I wasn't sure if the issues were connected or not, due to the way 109 breaks harder (the ")" character, the second "_" and the "/" character seemingly disappearing in the export.)

**Comment by Tyrrrz** [comment]
I was planning to dump Regex parsers altogether and re-write the whole rendering using [Sprache](https://github.com/sprache/Sprache)-based tokenizers. :D
Unfortunately, I didn't get any time to do that in the past month, but if done right this should fix all similar issues.

**Comment by wertercatt** [comment]
I'm curious how you would know if it was done correctly. Does Discord have a guide on how their markdown works specifically?

**Comment by Throne3d** [comment]
I'm also noticing that `_` is parsed weirdly in the context of using custom emojis with `_`s in their name. Examples:

- `:rainbow_heart: :rainbow_heart:`
  becomes (note the `<i>` and `</i>`)
  `<img class="emoji" title=":rainbow<i>heart:" src="..." /> <img class="emoji" title=":rainbow</i>heart:" src="..." />`
- `_test italics :rainbow_heart: test_`
  becomes (note the `</i>`)
  `<i>test italics <img class="emoji" title=":rainbow</i>heart:" src="..." /> test_` (causing all text after it to be italicized)

Discord displays the first as simply the two emoji images next to each other, and prints the underscores in the latter – `_test italics <img...> test_`.
