### ISSUE TITLE
Cannot export Forum Channels with their containing threads

### ISSUE THREAD

**Issue by QuickWick123** [Tyrrrz/DiscordChatExporter#1100]
### Version

Newest

### Flavor

CLI (Command-Line Interface)

### Export format

HTML

### Details

Cannot export "Forum Channels" with their containing threads

### Steps to reproduce

-t "MYTOKEN" -g 1234
-t "MYTOKEN" -c 1234

**Comment by rabyj** [comment]
I confirm this also happens with the following conditions:

Version 2.40
Flavor: GUI (Windows)
Export format: all

It says "Channel is empty or contains no messages for the specific period"

**Comment by Tyrrrz** [comment]
Yeah it's currently not supported directly. See #999

**Comment by Tyrrrz** [comment]
Closing in favor of #1119.

Exporting forum channels will be supported in the way of shoeing individual threads that belong to those channels, allowing you to export them. In CLI this is already possible with the `channels` command.
