### ISSUE TITLE
Disabled markdown processing should apply to reactions

### ISSUE THREAD

**Issue by jrdnhwll** [Tyrrrz/DiscordChatExporter#1104]
### Version

2.40

### Flavor

CLI (Command-Line Interface)

### Export format

CSV

### Details

with `--markdown False ` set in the CLI arguments, i believe custom emojis in the reactions data should behave in the same way as in the content. currently custom emoji reactions are parsed as their plaintext name, as if the markdown were true or the argument was not supplied.

### Steps to reproduce

- obtain a sample with a message with a custom emoji in the body, and a custom emoji reaction
- export the message with markdown False
- observe the difference between how the two are parsed

**Comment by jrdnhwll** [comment]
also maybe the author field? 
it doesn't apply for the use case I'm targeting with this issue, but it may make sense as well.

**Comment by Tyrrrz** [comment]
The reaction section is written as is. Since there is no markdown there (as there's no actual _content_), the option doesn't apply. The format you're most likely referring to (i.e. `<foobar:123456>`) is only used by Discord within markdown fields.
