### ISSUE TITLE
Cannot export a private channel I have on someone else's server: "Access is forbidden"

### ISSUE THREAD

**Issue by mdonovan5** [Tyrrrz/DiscordChatExporter#1108]
### Version

v2.40.1

### Flavor

CLI (Command-Line Interface)

### Export format

HTML

### Details

I can export channels no problem on my own server, but I have a private channel on a server I don't own. I have access to it. But DCE doesn't allow me to export it.

DiscordChatExporter.Core.Exceptions.DiscordChatExporterException: Access is forbidden.
  at DiscordChatExporter.Core.Discord.DiscordClient.GetJsonResponseAsync(String url, CancellationToken cancellationToken) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\DiscordClient.cs:135
  at DiscordChatExporter.Core.Discord.DiscordClient.GetChannelAsync(Snowflake channelId, CancellationToken cancellationToken) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\DiscordClient.cs:364
  at DiscordChatExporter.Core.Discord.DiscordClient.GetChannelAsync(Snowflake channelId, CancellationToken cancellationToken) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\DiscordClient.cs:371
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExecuteAsync(IConsole console, IReadOnlyList`1 channelIds) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:282
  at DiscordChatExporter.Cli.Commands.ExportChannelsCommand.ExecuteAsync(IConsole console) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelsCommand.cs:26
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in /_/CliFx/CliApplication.cs:153
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in /_/CliFx/CliApplication.cs:193

### Steps to reproduce

dotnet DiscordChatExporter.Cli.dll export -t "token" -c "channel id of private channel"

**Comment by mdonovan5** [comment]
@Tyrrrz You closed my ticket without explanation. Can you at least tell me why?

**Comment by Yudi** [comment]
He fixed the issue in https://github.com/Tyrrrz/DiscordChatExporter/commit/bcf652edbe26753789fa1f1fb2a7516f99e7f1ff.

Download a preview build from the [CI Artifacts](https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/5636622293) and check if it works.

**Comment by mdonovan5** [comment]
Oh sorry! I was confused. Thanks a lot that's really nice!

**Comment by mdonovan5** [comment]
It works!

**Comment by Jhonrodez** [comment]
> It works!

hi, i also having issues, it says "messages?limit=1' failed: forbidden" it's a private channel aswell, but i'm in there, thank you for your help!
![extract discord](https://github.com/user-attachments/assets/c5332332-9ea1-480a-ada1-72e4787675f3)

**Comment by Jhonrodez** [comment]
> He fixed the issue in [bcf652e](https://github.com/Tyrrrz/DiscordChatExporter/commit/bcf652edbe26753789fa1f1fb2a7516f99e7f1ff).
> 
> Download a preview build from the [CI Artifacts](https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/5636622293) and check if it works.

Yudi, boa tarde, poderia dar uma olhadinha e me ajudar? agradeço demais

**Comment by Yudi** [comment]
@Jhonrodez confira se:

1. Você tem acesso ao canal
1. Seu DCE está atualizado

Se você tem as duas coisas, vai precisar descrever o bug de maneira reproduzível, para ele poder ser corrigido 

---

@Jhonrodez check if:

1. You have access to the channel
1. DCE is updated

If both are correct, you'll have to describe reproducible steps so the bug can be fixed

**Comment by Jhonrodez** [comment]
Yudi tem como eu te escrever no twitter ou alguma coisa? eu te dou uma força em crypto assim que consiga, realmente tentei baixar o CLI mas nao entendi como usar na verdade

**Comment by Yudi** [comment]
@Jhonrodez 

1. Baixe o [DCE.CLI Windows x64](https://github.com/Tyrrrz/DiscordChatExporter/releases/download/2.43.3/DiscordChatExporter.Cli.win-x64.zip)
1. Extraia o .ZIP (extraia, não apenas abra)
1. Abra o Terminal ou Powershell (se não encontrar o 1º, tente o 2º)
1. Digite `cd` e aperte <kbd>Espaço</kbd>
1. Arraste a pasta que contém o DCE para a janela do Terminal

![](https://camo.githubusercontent.com/bc9b2dc56130a8db2b71d9022af9595f827362471cbf51c1d5b1412be3929ec3/68747470733a2f2f692e696d6775722e636f6d2f734f705a5141622e676966)

6. Digite `./DiscordChatExporter.Cli` para listar os comandos disponíveis
1. Para exportar um canal, digite:

```
./DiscordChatExporter.Cli export -t <TOKEN> -c <ID_CANAL>
```

> Substitua `<TOKEN>` e `<ID_CANAL>`, tirando os sinais `<>`

Para obter o ID de um canal:
1. Abra as configurações do Discord
1. Vá para a aba "Avançado"
1. Habilite o "modo desenvolvedor"
1. Clique com o botão direito do mouse no canal desejado e clique em Copiar ID do canal (Copy Channel ID)

Se quiser dar uma força, [doe para o Tyrrrz](https://tyrrrz.me/donate), que fez essa ferramenta incrível! :-)
Ele tinha carteiras crypto, mas tirou do site. Dá um @ nele pedindo a wallet, se quiser doar BTC, ETH ou SOL.

E se não conseguir com as instruções, me mande um e-mail, tem o endereço no perfil ou uma mensagem no Discord em @renanyudi  

Se encontrar o bug, abra uma nova issue.

---

[Using the CLI steps](https://github.com/Tyrrrz/DiscordChatExporter/blob/master/.docs/Using-the-CLI.md#using-the-cli)

I'd appreciate if you [donated to Tyrrrz instead](https://tyrrrz.me/donate) :-)

Drop me an email or message me on Discord if you're having trouble following the steps

Open a new issue if you face the same bug

**Comment by Jhonrodez** [comment]
![image](https://github.com/user-attachments/assets/4e0fc05f-5116-4811-abf6-e3c59338bfa7)
obrigado, estou colocando algo errado Yudi?

**Comment by Yudi** [comment]
@Jhonrodez 
Sim, depois do passo 5, mas antes do 6, aperte <kbd>ENTER</kbd>, para executar o comando `cd`

Esqueci desse detalhe
