### ISSUE TITLE
Is a macOS version possible?

### ISSUE THREAD

**Issue by jb365** [Tyrrrz/DiscordChatExporter#111]
Thanks for your time.

**Comment by RenanYudi** [comment]
You can run the CLI via Mono, instructions  [here](https://github.com/Tyrrrz/DiscordChatExporter/wiki/macOS-usage-instructions).

**Comment by Tyrrrz** [comment]
The CLI is currently available on macOS via Mono but eventually will also be available on multiple platforms natively.
The GUI is Windows only and there are no plans to change that.
