### ISSUE TITLE
Server categories not working

### ISSUE THREAD

**Issue by Crossedkiller** [Tyrrrz/DiscordChatExporter#1112]
### Version

2.40.1

### Flavor

GUI (Graphical User Interface)

### Details

The server categories are not properly showing up. The entire server is grouped under a single category as shown in the screenshots below. 

![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/93672063/60c6d0b6-b9a6-4d0a-b385-0c8b624d4f18)
![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/93672063/d0d1a5cf-f909-4c4a-bf1a-cd4247a16ac0)

### Steps to reproduce

- Open DCE
- Login with Token
- Select any server to back up

**Comment by Tyrrrz** [comment]
What is the category called?
