### ISSUE TITLE
Authentication token is invalid

### ISSUE THREAD

**Issue by EvaisaDev** [Tyrrrz/DiscordChatExporter#1114]
### Version

2.40.2

### Flavor

GUI (Graphical User Interface)

### Details

The latest version throws an error when trying to use bot/user authentication token.
Error pulling guilds and channels, Authentication token is invalid.

The token is most definitely not invalid though, version 2.39.1 loads fine using the same token so it must be something related to the newer versions.

### Steps to reproduce

Log in using bot authentication token in version 2.40.2

**Comment by Tyrrrz** [comment]
Hmmm, can you removing the token entirely and then copy-pasting it again?

If that doesn't help, can you try getting a new token from your app? They usually rotate every once in a while.

**Comment by EvaisaDev** [comment]
I did that multiple times, i tried both a bot and user token. The new version just did not want to work on my system

**Comment by Tyrrrz** [comment]
That's really unusual

**Comment by NiciTheNici** [comment]
Works for me using these steps to get the token:
```
To get your Discord token:

    Log into Discord via Chrome on a desktop.
    Open Developer Tools, then click Network.
    Press F5 on your keyboard to reload the page.
    Type /api into the Filter field, then click library.
    Click the Headers tab, then scroll down to authorization to find your Discord token.
```
