### ISSUE TITLE
Dark theme's text is white

### ISSUE THREAD

**Issue by RasmusKallas** [Tyrrrz/DiscordChatExporter#112]
Black text on grey html is bad.

**Comment by RenanYudi** [comment]
What software are you using to view the PDF? It should look whitish on Google Chrome, but Edge can't handle the color properly.

![](https://i.imgur.com/qzfrjS7.png)

**Comment by RasmusKallas** [comment]
Frsh vm, I think it was chrome tough, have to check it..

**Comment by RasmusKallas** [comment]
Yup, Edge needs to catch up.

**Comment by Tyrrrz** [comment]
If there's an easy solution how to fix this in Edge, let me know.
