### ISSUE TITLE
Tenor/otherwise .gifs export as .png

### ISSUE THREAD

**Issue by Nowena** [Tyrrrz/DiscordChatExporter#1120]
### Version

2.40.4

### Flavor

GUI (Graphical User Interface), CLI (Command-Line Interface)

### Platform

Windows 10

### Export format

JSON

### Steps to reproduce

Either method I use, GUI or CLI exports all gifs from tenor/otherwise as png files.

### Details

Is this expected behaviour?

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
I think this is expected for JSON because it references only the thumbnail and not the actual video (it's `gifv` by the way, not ``gif`). HTML references both, so it should download both.

**Comment by Nowena** [comment]
Does the HTML format fetch the image files separately like JSON does and am I able to parse/search within HTML exports?

**Comment by Tyrrrz** [comment]
If you enable "download assets", it will download all assets referenced by the export file (i.e., the `html` file). Note that the purpose of "download assets" is to make the export file usable offline, not to scrape the channel off all multimedia content.

**Comment by Nowena** [comment]
Does DiscordChatExporter-frontend allow you to explore HTML files? If not, could that be made possible?

**Comment by Tyrrrz** [comment]
That's a different project, so you should ask there. But I imagine it only uses JSON for a reason.

**Comment by Nowena** [comment]
Oh, right. It is not by you. I noticed something about .gif exports. Tenor offers both SD/HD .gifs and .mp4 files. DiscordChatExporter fetches the mp4 files for some reason and exports them. Any way to make it fetch .gif files instead?

**Comment by Tyrrrz** [comment]
No, it's what Discord provides so that's what DCE references:

https://github.com/Tyrrrz/DiscordChatExporter/blob/6fb61086106784dbfc57c250bc1ad90c6e0f8bf1/DiscordChatExporter.Core/Exporting/MessageGroupTemplate.cshtml#L464-L476

**Comment by nitrocell** [comment]
Is it possible to make the JSON export fetch the .mp4 urls too?

**Comment by Tyrrrz** [comment]
It might increase the export size significantly without benefit for most users. If you want to scrape media files from a server, using DCE might not be the best choice. What is your use case?

**Comment by nitrocell** [comment]
I mean, speaking about links, it would make more sense to scrape the .mp4 link instead of the .png for Tenor gifs in JSON export since it's more faithful to what is actually shown in the message itself.

**Comment by nitrocell** [comment]
If it shows the .mp4 for Giphy in JSON export, I think it should do the same for Tenor

**Comment by nitrocell** [comment]
What i wanted to ask more specifically, is that if it's possible to JSON export .mp4 links for both Tenor and Giphy
