### ISSUE TITLE
Progess in CLI scrolling down makes it impossible to track progress of some channels

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#1124]
### Version

v2.40.4

### Flavor

CLI (Command-Line Interface)

### Platform

Windows

### Steps to reproduce

Use an export command with a high amount of channels and a parallel limit > 1

### Details

Once some channels are finished, new channels and their progress bars start appearing. After a fixed amount of new channels have appeared at the bottom, the ones at the top start to disappear, sometimes making it impossible to track progress of channels which are still being downloaded.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [X] I have sponsored this project

**Comment by CanePlayz** [comment]
@Tyrrrz What about adding a little "x/y" above or below the channels currently being exported? Like

```
Channels: 7/56
Threads: 0/14

Alles / ranandenrind  ----------------------------------------  61%
Alles / bot-stuff     ----------------------------------------   7%
Alles / musicbot      ----------------------------------------  21%
Alles / mimimimeme    ----------------------------------------  57%
Alles / wm-?         ----------------------------------------  30%
Alles / wieb-??       ----------------------------------------  31%
Alles / ????-monkeeee ----------------------------------------  14%
Alles / stats-archiv  ----------------------------------------  23%
```

(btw don't ask me why the "wm" channel is not on the right column, it's probably some emoji character stuff messing around)

With fully exported channels disappearing, you can now see the channels that are being exported but makes it hard to see how much is already done. 😅

Note that unlike the commit done here, this would not have to be exclusive to parallel exports, but it could, since in not-parallel exports channels don't disappear anyways.

**Comment by CanePlayz** [comment]
I'm just suggesting adding the status bit at the top. That could be added for all exports, yeah, but also just for ones with parallel exporting, whatever one would prefer.

Hiding completed tasks for not parallel exports wasn't necessary because you just need to see the progress bar of the channel which just spawned at the very bottom, which you can surely do.

**Comment by Tyrrrz** [comment]
> Hiding completed tasks for not parallel exports wasn't necessary because you just need to see the progress bar of the channel which just spawned at the very bottom, which you can surely do.

But then you won't see the status at the top
