### ISSUE TITLE
HTML Export strips first line of code block even when it's not a language identifier

### ISSUE THREAD

**Issue by EightAndAHalfTails** [Tyrrrz/DiscordChatExporter#113]
I exported a channel I was in using the HTML Export, and some of the text in codeblocks is missing.

Here's how it looks exported:
![image](https://user-images.githubusercontent.com/1180671/47597470-fee3ff00-d986-11e8-8958-c463e6b0d3ca.png)

And here's how it looks in Discord:
![image](https://user-images.githubusercontent.com/1180671/47597480-1e7b2780-d987-11e8-8644-9ae94bcc806b.png)

Here it is in edit mode:
![image](https://user-images.githubusercontent.com/1180671/47597490-2c30ad00-d987-11e8-98fb-6ba31c842b5f.png)

What I'm guessing is happening (I haven't looked at the code), is that whatever's on the same line as the triple backticks is interpreted as a language identifier for syntax highlighting, but according to Discord's [documentation](https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-), this should be included in the output:
![image](https://support.discordapp.com/hc/article_attachments/115000864611/screen_02.png)

**Comment by EightAndAHalfTails** [comment]
Wait, did Discord change how this renders since these messages? Now it appears Discord also strips the content on the same line as the backticks.

Perhaps I'll just have to go back and add newlines to all those old messages...

**Comment by EightAndAHalfTails** [comment]
Ah, no, I see. It looks like Discord strips the first line if and only if it consists only of a single word (no whitespace). I guess that's their way of parsing language identifiers.

**Comment by Tyrrrz** [comment]
Oh, that's smart enough. I need to implement this too.
