### ISSUE TITLE
Discord keeps deactivating account for suspicious activity

### ISSUE THREAD

**Issue by fferme** [Tyrrrz/DiscordChatExporter#1142]
### Version

2.42

### Flavor

CLI (Command-Line Interface)

### Platform

Windows 11

### Export format

JSON

### Steps to reproduce

- Recover token from Discord account
- Execute command from the program to export channels
- After a while Discord will deactivate account for suspicious activity and you have to redefine password and recover token again

### Details

Discord keeps deactivating my account because it detects suspicious activity. It all happens when I retrieve the token from Discord and use in your API.

![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/37823266/c5522e6d-307e-457d-b5ef-2168244b204f)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Using DCE with a user account is against Discord TOS so these things may happen.

**Comment by Technetium1** [comment]
Maybe it's cause to add a couple smaller sleeps...

**Comment by Tyrrrz** [comment]
DCE already respects Discord's API rate limits. Usually using DCE shouldn't result in suspensions of any kind, but like I said it's always a risk.

Either use a bot token or a throwaway user account, both are much safer and the only recommended options.

**Comment by fferme** [comment]
What is a bot token and how can I configure it? 
A throwaway user account it's like a dummy account? An account only to be used to generate the token?

**Comment by Tyrrrz** [comment]
> What is a bot token and how can I configure it?

You need to register an application with Discord, then create a bot, invite that bot to the target server (you need to be admin) and then use the bot's token to export the chatlog.

> A throwaway user account it's like a dummy account? An account only to be used to generate the token?

Yes. An account you create for the sole purpose of exporting chat logs.
