### ISSUE TITLE
Channel is a forum error

### ISSUE THREAD

**Issue by chaoscreater** [Tyrrrz/DiscordChatExporter#1144]
### Version

v2.42.0

### Flavor

GUI (Graphical User Interface)

### Platform

Windows 11

### Export format

JSON

### Steps to reproduce

Hi there,

I'm trying to export messages from this particular channel and I'm getting this message:

![image](https://github.com/slatinsky/DiscordChatExporter-frontend/assets/18227319/7e856e42-5ddc-46b8-82ad-1504f2cc2c61)

here's the channel in question when I view it in Discord:

![image](https://github.com/slatinsky/DiscordChatExporter-frontend/assets/18227319/10cbd0aa-c056-4664-90dc-9be5223acb2a)

I tried to look up the guides but couldn't find much on this. Could someone point me in the right direction please?

### Details

As above.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Forum channels are not real channels, there are just a collection of threads. So in order to export them, you have to enable the option to pull threads in the settings and then export the threads individually. That is a slow process, so it's not enabled by default.
