### ISSUE TITLE
Export to SQLite database

### ISSUE THREAD

**Issue by tyto-alba-alba** [Tyrrrz/DiscordChatExporter#115]
Hey,

It would be nice to be able to export messages in a SQLite database, so we could be able to do more sorting on it being offline. (By SQLite database, I mean a database created by the program, obviously, with fields like UUID of the sender, name of the sender, time, message...)

Something that would be great is the "continuation" of a database. For example, I am archiving my DMs on a monthly basis. It would be really nice if we were able to select a database and "continue" to fill the same one.

Thanks for the program anyway! It's really useful to me.

**Comment by Tyrrrz** [comment]
Hi,
Thanks for the suggestion.
I don't think there's a need to support more intricate export types like SQLite, being able to convert from PlainText (and eventually also JSON, #103) is enough. There are too many possible options to support them all, so it's more efficient to empower users and let them build their own parsers.
