### ISSUE TITLE
CSV now outputs only minute-precise localized string instead of millisecond-precise UTC timestamp

### ISSUE THREAD

**Issue by metagn** [Tyrrrz/DiscordChatExporter#1152]
### Version

v2.42.2

### Flavor

GUI (Graphical User Interface), CLI (Command-Line Interface)

### Platform

Windows 11

### Export format

CSV

### Steps to reproduce

Export any posts to CSV.

### Details

When exporting to CSV, messages used to have full UTC timestamps with millisecond information (for example, `2023-09-23T13:15:48.3790000+03:00`), but now they output localized strings with minute precision (for example, `10/6/2023 12:37 AM`). There is also no post ID or millisecond column in CSV so there is no way to uniquely identify posts in CSV format anymore without using every column.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Please use the JSON format for automation, CSV is deprecated
