### ISSUE TITLE
Reuse media option causes assets to not load in Firefox

### ISSUE THREAD

**Issue by Prosopho** [Tyrrrz/DiscordChatExporter#1155]
### Version

v2.42.3 (all versions should be affected.)

### Flavor

GUI (Graphical User Interface), CLI (Command-Line Interface)

### Platform

Windows 10

### Export format

HTML

### Steps to reproduce

Server Invite: discord.gg/vSepQdHcNh

Channel id: 1067204769237700638

CLI Options: DiscordChatExporter.Cli.exe export -c "1067204769237700638" -t "YourToken" -o "C:\Tests\No-mic" --media --reuse-media --media-dir "C:\Tests\No-mic\Assets\"

The assets load on both GUI & CLI when --reuse-media is removed. This is especially problematic when exporting larger servers where there are tons of assets reused across different channels.

GUI Options: 
![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/109369903/6bfcbbba-9882-43e5-ac46-daef0fa32c75)

### Details

- Expected behavior: The assets and embeds should load as normal
![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/109369903/cfde5639-cb4b-4e68-b1b2-5835a4a0ffad)

- Actual behavior: Embeds/Assets don't load and instead have "Image attachment, Guild Icon, Avatar"
![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/109369903/e213f7f9-2e96-4d9f-9419-923e47af96c4)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Can you inspect the URLs to see why they're broken? For example, what does `Image attachment` in the second export point to?

**Comment by Prosopho** [comment]
> Can you inspect the URLs to see why they're broken? For example, what does `Image attachment` in the second export point to?
![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/109369903/3250a7fb-8f7a-48f0-b0c7-b2868c727e53)

I found that adding file:/// in front of the asset paths made them load in FF. Chrome/chromium didn't seem to have any difference. 
![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/109369903/56ad1a74-0cc7-46b3-aa14-d67aa7cee165)


Easy to mass replace in Notepad++ so it's not really a big deal for me to replace them. If i didn't select an media export path, they'd load.
![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/109369903/cfd00db4-834c-4b9c-a51f-bf67eecaeca3)

**Comment by Tyrrrz** [comment]
Hmm the src appears to point to a file in the `C:/Games/...` path, but your export and assets are both in `C:/Tests/...`?

**Comment by Prosopho** [comment]
> Hmm the src appears to point to a file in the `C:/Games/...` path, but your export and assets are both in `C:/Tests/...`?

That's not too relevant since the commands in the issue were copypasted from the terminal and the testing in general was pretty messy.

The "non-working" version was with the reuse assets exported to games/test with it getting them from the assets folder in games/discord/pixelgunx/assets.

The "working" version was without re-use media and Asset path in games/test2
The last screenshot was the "working" version without re-use media and media path like mentioned.

1st & 2nd ss were from the games/test export with reused media pointing to the pixelgunx/assets folder.

I hope this cleared up things enough.

**Comment by Tyrrrz** [comment]
I was not able to reproduce this issue in Chrome (works fine) and I don't have Firefox to test.

**Comment by Prosopho** [comment]
> I was not able to reproduce this issue in Chrome (works fine) and I don't have Firefox to test.

The issue only affects FF, not chrome. Chrome was always fine to begin with.

**Comment by Tyrrrz** [comment]
Oh, so the issue is that Firefox needs `file:///` to work?

**Comment by Prosopho** [comment]
> Oh, so the issue is that Firefox needs `file:///` to work?

Exactly.

**Comment by Tyrrrz** [comment]
Try the latest CI build and tell me if it works

**Comment by Prosopho** [comment]
> Try the latest CI build and tell me if it works

Both CLI and GUI work.
