### ISSUE TITLE
Recommended token retrieval method needs adjustment: No network entry for "library"

### ISSUE THREAD

**Issue by snowpoke** [Tyrrrz/DiscordChatExporter#1159]
### Version

master

### Flavor

CLI (Command-Line Interface)

### Platform

Any

### Steps to reproduce

- Log in to discord.com using your login credentials
- Try to follow the steps in this guide under "using the network monitor" (on any browser): https://github.com/Tyrrrz/DiscordChatExporter/blob/master/.docs/Token-and-IDs.md

### Details

- Expected behavior: When entering "library" in the Filter search, a result is found
- Actual behavior: No result for "library" is found, and less technically inclined users cannot follow the rest of the instruction in the Documentation.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
This issue only affects the docs and not the `guide` command, correct?
