### ISSUE TITLE
Discord Forums 

### ISSUE THREAD

**Issue by ProjectCisco** [Tyrrrz/DiscordChatExporter#1161]
### Version

2.42.4

### Flavor

GUI (Graphical User Interface), CLI (Command-Line Interface)

### Platform

Windows 11

### Export format

HTML, TXT, JSON, CSV

### Steps to reproduce

Steps to reproduce
Export threads and use template tokens in the path

### Details

When using both GUI and CLI, I'm meet with error, unable to pull thread... on discord forum section 

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Discord Forums are not channels, so they can't be directly exported as such. You need to pull threads first, then export them individually.

**Comment by ProjectCisco** [comment]
how do pull the threads ?

**Comment by Tyrrrz** [comment]
In CLI, use the `channels` command with `--include-threads all`. In GUI, enable in settings.

**Comment by marwie** [comment]
Hello @Tyrrrz I'm porbably missing something but where should the --include-threads option be added?

e.g.

`dotnet DiscordChatExporter.Cli.dll export --token mydiscordtoken --channel somechannelid --include-threads all -o /Users/some/path`

prints: Unrecognized option(s): --include-threads

**Comment by marwie** [comment]
Ah nevermind I guess that's it: https://github.com/Tyrrrz/DiscordChatExporter/blob/master/.docs/Using-the-CLI.md#list-channels-in-a-server

**Comment by Tyrrrz** [comment]
> Ah nevermind I guess that's it: [`master`/.docs/Using-the-CLI.md#list-channels-in-a-server](https://github.com/Tyrrrz/DiscordChatExporter/blob/master/.docs/Using-the-CLI.md?rgh-link-date=2024-02-09T19%3A46%3A34Z#list-channels-in-a-server)

Yes, that's correct.

The `export` command (currently?) doesn't support `--include-threads`.

**Comment by marwie** [comment]
And do I get it right that I currently have to list all channels on the whole *server* (and I cannot just list channels of a forum?)
