### ISSUE TITLE
How would I go about integrating this as a bot command

### ISSUE THREAD

**Issue by BladeUnlimited** [Tyrrrz/DiscordChatExporter#117]
I've already figured out how to plug in my bot token to the program and utilize it that way; but I'm curious if anyone would be able to give me insight as on how I could incorporate the program so it's generations can be produced by a server bot-command?

**Comment by Tyrrrz** [comment]
Currently you can do that by using the CLI. What are you developing the bot with?

**Comment by BladeUnlimited** [comment]
I'm... not really sure how to answer the question. I just made a bot off of a tutorial on discord that can go online through cmd and has a token I can use for this program. This is my first time attempting to make a bot so I apologize for my novicity with the situation.

**Comment by Tyrrrz** [comment]
You would need to have your bot execute the CLI with proper parameters and then upload the file somewhere to share it. This is not a question specific to this application, but rather a general programming question, so I'm going to close it.
