### ISSUE TITLE
GUI logs in to discord and "runs" - but doesn't save files

### ISSUE THREAD

**Issue by photopauls** [Tyrrrz/DiscordChatExporter#1172]
### Version

2.42.6

### Flavor

GUI (Graphical User Interface)

### Platform

windows 10

### Export format

HTML

### Steps to reproduce

Logged in to discord inside the app as usual.

Discord token was accepted and my servers show up as expected.

After selecting a channel and hitting download - nothing actually saves.

It does run... (on larger channels it takes 30 seconds and has the progress bar).

Have tried on multiple servers and channels. It downloads DM's fine - but wont work on any channels.

### Details

see above

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Does it finish running?

**Comment by photopauls** [comment]
Yeah, I think so!

I tried it on a separate computer and ran into similar issues.

However - I can now get it to export channels that are just full of chat.

But it won't export channels that have threads in them... Which is my main
goal.

Maybe the tool doesn't support threads?

**Comment by Tyrrrz** [comment]
To export threads, you need to enable them in settings -- then they will appear in the end as regular channels. Pulling threads is very slow so it's disabled by default.

**Comment by photopauls** [comment]
Thanks!

I changed the setting and tried logging in again.

Took forever to log in (to be expected I guess).

But - it still doesn't seem to save the channel full of threads.

After hitting the download button I get the black popup "chanel ABC......"
But no progress bars...

No files appear on my computer either.

**Comment by Tyrrrz** [comment]
The threads are grouped by channel and they should appear at the end of the list. After that, you should be able to export them just like regular channels.

What black popup are you referring to? Does it say anything?

**Comment by photopauls** [comment]
Ahhhhh they are at the bottom! Got it! Thank you, it was working fine all along, I was just being a dumbass
