### ISSUE TITLE
Failed to export message System.IO.FileNotFoundexception: Could not load file or assembly

### ISSUE THREAD

**Issue by farsenfsd** [Tyrrrz/DiscordChatExporter#1173]
### Version

v2.42.6

### Flavor

GUI (Graphical User Interface)

### Platform

Windows 11

### Export format

HTML

### Steps to reproduce

1. Select direct message with x user.
2. Export to HTML.
3. Fails

### Details

<img width="317" alt="image" src="https://github.com/Tyrrrz/DiscordChatExporter/assets/41244288/9e6d70b3-9658-4fad-9dbb-51ec3507fe5d">

Re-tried multiple times and always got this error.

Exporting as TXT works fine

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Do you have `AdvancedStringBuilder.dll` in your DCE folder? If not, you may need to re-download the latest version and try again.

**Comment by farsenfsd** [comment]
That fixed it. Thank you

**Comment by farsenfsd** [comment]
Re-downloading it fixed it, thank you.
