### ISSUE TITLE
When trying to close the app after export, it shows this error!

### ISSUE THREAD

**Issue by TheBaby5** [Tyrrrz/DiscordChatExporter#1197]
### Version

v2.42.7

### Flavor

GUI (Graphical User Interface)

### Platform

Microsoft Windows Version 23H2 (0S Build 22631.3085)

### Steps to reproduce

When trying to close the app after export, it shows this error!

### Details

![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/44883516/1dd01a80-b0f8-4f1d-ae4d-e6b77f9edac1)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
It means it can't save settings to the current directory. You should move the application to a directory where you have write access.
