### ISSUE TITLE
Save all channels in a given server

### ISSUE THREAD

**Issue by AlexGreason** [Tyrrrz/DiscordChatExporter#12]
Just to make things easier with servers with huge numbers of channels. It's still _possible_ to do those manually, just inconvenient, so this isn't super important, but it would be nice.

**Comment by 2E0PGS** [comment]
Should be a simple `for (channel in channels) {`

**Comment by Tyrrrz** [comment]
This is far from being that simple.

**Comment by 2E0PGS** [comment]
How you already have a list of channels so you just loop through those and then run the subroutine several times. Emulating a user clicking each one and then downloading each one. You may need to adjust the GUI a fair bit though.

**Comment by Tyrrrz** [comment]
There's no need to emulate the user clicking anything. The biggest issue is that all popup dialogs were designed with one selected channel in mind and would need to be reworked or new ones have to be added.

**Comment by 2E0PGS** [comment]
I didnt actually mean emulate user clicks lol. I meant it would just be a for loop that triggers those subroutines that the buttons would normally trigger. Yes I guessed that was the case hence the "You may need to adjust the GUI a fair bit though."

**Comment by 2E0PGS** [comment]
Maybe add a new GUI menu for the mass download. Then that can just pass the same set of options into each subroutine downloadChannel(general, dark, html, location); I dont know if you have them in subroutines or just directly attached to event listeners. Maybe I will look over your code in a bit.

**Comment by miguelzf** [comment]
Any progress done here for mass export?

Else i might do it myself, but without any GUI

**Comment by Tyrrrz** [comment]
Check out #123
