### ISSUE TITLE
Sticker type not recognised

### ISSUE THREAD

**Issue by NotPiny** [Tyrrrz/DiscordChatExporter#1204]
### Version

2.42.8

### Flavor

CLI (Command-Line Interface)

### Platform

Linux (nix-shell)

### Export format

HTML

### Steps to reproduce

I haven't had the time to be able to reproduce this in a test environment however after reading the error log it seems the error occurs when the program finds sticker type 4 which is a gif so sending a sticker type 4 gif should reproduce the error

### Details

Part way through exporting messages the program will throw a error apon reaching sticker_type 4 instead of getting the GIFs URL

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
It's supported, you're using an outdated version of the application.

https://github.com/Tyrrrz/DiscordChatExporter/blob/master/DiscordChatExporter.Core/Discord/Data/Sticker.cs
