### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by MinniHowl** [Tyrrrz/DiscordChatExporter#122]
I cannot for the life of me figure out how to install this and apply it to my discord plugins. I've downloaded the file about 100 times and run the .exe but it doesn't seem to do anything except bring up the black box for a hot second and disappearing. Nothing changes in my discord. 
I might just be an idiot, this is the first plugin I'm trying, but there's no plugin file like all the YT tutorials show and it doesn't show up on my discord plugin site in discord.

**Comment by RenanYudi** [comment]
Uhh... This isn’t a plugin, but a standalone software. Just download and extract the latest [DiscordChatExporter.zip](https://github.com/Tyrrrz/DiscordChatExporter/releases/latest) and execute the .exe, without copying/modyfiying anything. Making sure you have the latest .NET and Windows updates may also solve your problem.

**Comment by MinniHowl** [comment]
Oh god, I really _am_ an idiot. Okay idk why it didn't work before tho, but it worked now. Thank you!
