### ISSUE TITLE
The date template tokens %a and %b don't work

### ISSUE THREAD

**Issue by Auditormadness9** [Tyrrrz/DiscordChatExporter#1228]
### Version

v2.43.0

### Flavor

CLI (Command-Line Interface)

### Platform

Windows 11

### Export format

HTML

### Steps to reproduce

`DiscordChatExporter.Cli export -t [token] -c [channelID] -o "[directory]\%a - %C.html"`

or

`DiscordChatExporter.Cli export -t [token] -c [channelID] -o "[directory]\%b - %C.html"`

### Details

It should export them with names like eg. `05-05-2024 - Auditormadness9` but it instead exports it with the date part being blank, aka eg. `- Auditormadness9`. It does so on every single DM channel.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [X] I have sponsored this project

**Comment by 96-LB** [comment]
Are you setting the `--after` or `--before` flags?

**Comment by Tyrrrz** [comment]
It only works if you actually specified date boundaries, otherwise there is no concept of `after` or before`.

**Comment by Auditormadness9** [comment]
I see. In that case, is there no template token for just the date of the channel's snowflake?

**Comment by Tyrrrz** [comment]
> I see. In that case, is there no template token for just the date of the channel's snowflake?

Not in the date format, just the snowflake format. The channel ID is just derived from when it was created.
