### ISSUE TITLE
`--partition` option breaks on new trimmed build

### ISSUE THREAD

**Issue by monkecoder42** [Tyrrrz/DiscordChatExporter#1239]
### Version

v2.43.2

### Flavor

CLI (Command-Line Interface)

### Platform

Windows 10

### Steps to reproduce

Trying to run an export using the command
`DiscordChatExporter.Cli.exe export -c [...] --format Json --fuck-russia --markdown false -p 100mb --token [...] --output [...]`
produced the error message
```
Option -p|--partition has an unsupported underlying property type.
There is no known way to convert a string value into an instance of type `DiscordChatExporter.Core.Exporting.Partitioning.PartitionLimit`.
To fix this, either change the property to use a supported type or configure a custom converter.
```

### Details

Switching to the previous version [2.43.1](https://github.com/Tyrrrz/DiscordChatExporter/releases/tag/2.43.1) resolves the issue.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Deastrom** [comment]
Same thing here. Mentioned it in the discord. Thanks for posting an issue 😸
