### ISSUE TITLE
"All" option in Show threads causes program to hang loading server forever

### ISSUE THREAD

**Issue by saladplainzone** [Tyrrrz/DiscordChatExporter#1250]
### Version

v2.43.3

### Flavor

GUI (Graphical User Interface)

### Platform

Windows 10

### Export format

HTML, TXT

### Steps to reproduce

- Turn the **Show threads** option in settings to All
- Click on a server with threads in it

### Details

Expected Behavior: Server loads with threads visible
Actual Behavior: Program hangs, trying to load the server forever

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
It is very slow, especially if the server has a lot of threads, but it will load them eventually.

The way threads were designed is that they are meant to be fetched on demand -- when the client loads a message in a channel that starts a thread, it loads that threads. Threads weren't designed to be fetched in batches, and doing so is only possible through very inefficient means.

If you know the exact thread ID that you want to export, you're better off using the CLI.

Such is life.

**Comment by saladplainzone** [comment]
Found out that doing Ctrl+A on the channel list exports threads anyhow, so my issue is no longer needed

**Comment by goldstargloww** [comment]
out of curiosity, what's the current method for searching for threads?
