### ISSUE TITLE
Option to include Snowflake in filename

### ISSUE THREAD

**Issue by ealgase** [Tyrrrz/DiscordChatExporter#126]
I have multiple friends with the same username on Discord.  When I export all of my DM channels, some of them get overwritten by the others.  An option to add the channel's or user's snowflake to the channel name would fix this issue.

Current:
`Direct Messages - [user].html`
Changed (with flag):
`Direct Messages - [user] - [channel_id].html`

**Comment by Tyrrrz** [comment]
Are you having this problem with CLI or GUI?

**Comment by ealgase** [comment]
CLI.

**Comment by Tyrrrz** [comment]
Done
