### ISSUE TITLE
Chat exported but missed a lot of messages

### ISSUE THREAD

**Issue by benhur90** [Tyrrrz/DiscordChatExporter#1263]
### Version

2.43.3

### Flavor

GUI (Graphical User Interface)

### Platform

Windows 11

### Export format

JSON

### Steps to reproduce

Normally export chat in JSON format with format markdowns

### Details

Expected:
![Screenshot 2024-07-27 165509](https://github.com/user-attachments/assets/1c5b4a
Unexpected:
![Screenshot 2024-07-27 165516](https://github.com/user-attachments/assets/a2365f43-68d3-49b2-8ff0-6c080d2f0261)
94-d92f-4a86-a157-538a967fa806)
chat-analytics

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by benhur90** [comment]
![Screenshot 2024-07-27 165509](https://github.com/user-attachments/assets/fc617a86-fff3-4b17-801d-7f96300757e7)
Weirdly the screenshot doesn't show, ill show it here

**Comment by Tyrrrz** [comment]
It's hard to investigate this issue as it is. Please try to find which exact messages are missing so we may try to figure out what's causing it.

To find the problematic messages in a reasonable time, you can try performing a binary searching by cutting off parts of the chat log using date ranges.

**Comment by benhur90** [comment]
Alright the issue is just chat analytics
