### ISSUE TITLE
Link to Image Error: This content is no longer available.

### ISSUE THREAD

**Issue by radna0** [Tyrrrz/DiscordChatExporter#1266]
### Version

v2.43.3

### Flavor

GUI (Graphical User Interface), CLI (Command-Line Interface)

### Platform

Windows 11

### Export format

JSON

### Steps to reproduce

Orignal Image from Discord:
https://cdn.discordapp.com/attachments/1054962560941694997/1262405807111147621/lewyn9434_80s_anime_stillretro_fashionpastelsgirl_repairing_a_g_4ed9e1df-bb89-4f61-8870-c21129442d44.png?ex=66aa4106&is=66a8ef86&hm=2763886cccfe1e6e29ecf658e413f25c35aabf6421b3d76ef1316086719fc52a&

Exported Image:
https://cdn.discordapp.com/attachments/1054962560941694997/1262405807111147621/lewyn9434_80s_anime_stillretro_fashionpastelsgirl_repairing_a_g_4ed9e1df-bb89-4f61-8870-c21129442d44.png?ex=66967a86&is=66952906&hm=9e4487a2f0fae834ba895d4689779094d01b50978de9116e47bd026acb7e85c8&

### Details

The Image is still available when trying to search the specific image. The Url almost looks identical, the only difference is the query parameters. Is it possible to get these information from anywhere easily?

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by 96-LB** [comment]
Links from Discord's CDN expire after 24 hours. If you want to preserve images, use the `--media` flag on the CLI or enable the "download assets" setting on the GUI to download the files locally.

**Comment by radna0** [comment]
@96-LB Thank you for responding! I want to filter for specific messages before downloading any media. If I were to download all the assets that would take up too much space. Is there anyway I can acess the image link after exporting? Running the Script to export the Discord chat again would take me days. Thanks.

**Comment by 96-LB** [comment]
@radna0 The image links are signed by Discord, so only they can provide new links. However, given an expired image link, I'm aware of two ways to view the image:
1. Paste the link into the Discord client. Discord will automatically refresh the signature for you and display the image anew.
2. Replace "cdn.discordapp.com" with a proxy like "fixcdn.hyonsu.com", which is a website that queries Discord for you to update the signature. I don't know if these proxies will exist for long or if Discord/the owners will eventually decide they want to take them down.

**Comment by Tyrrrz** [comment]
As @96-LB pointed out, CDN links are temporary. For example, both of the links you provided in the original message have now expired. The only reliable way to work around this is to download referenced assets when exporting.
