### ISSUE TITLE
Export stops/hangs after minimizing window

### ISSUE THREAD

**Issue by plopilpy** [Tyrrrz/DiscordChatExporter#1269]
### Version

v2.43.3

### Flavor

GUI (Graphical User Interface)

### Platform

Windows 10

### Export format

HTML

### Steps to reproduce

1. Start an export of a large channel
2. Minimize/restore DCE window
3. Export will now stop (i.e. the progress bar will not progress and Task Manager shows 0MB/s network activity)

### Details

Minimizing the window during an export causes it to hang. This tends to happen, by my experience, with larger channels.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Can't reproduce this. The export continues with the app minimized for me.

**Comment by plopilpy** [comment]
I'm on Windows 10 64-bit if that helps.

**Comment by Tyrrrz** [comment]
Does this only happen with large channels or with everything? Are you on a laptop by any chance?

**Comment by plopilpy** [comment]
Only with large channels, and yes I am on a laptop.

**Comment by Tyrrrz** [comment]
Are you on the "Best performance" power mode?

**Comment by plopilpy** [comment]
No, I'm on best battery. I'll try using best performance, give me a sec.

**Comment by plopilpy** [comment]
Okay, it doesn't freeze after minimizing now. Thanks for the help.
