### ISSUE TITLE
GUI crashes on inputting token due to SSL error

### ISSUE THREAD

**Issue by carictheelf** [Tyrrrz/DiscordChatExporter#1277]
### Version

2.43.3

### Flavor

GUI (Graphical User Interface)

### Platform

Windows 10

### Steps to reproduce

I downloaded the code, extracted with winrar, and opened it on my network. I tried two different tokens, and both produced the error. I also downloaded the cli before and then deleted that

### Details

It crashed after a few minutes, and I have restarted my computer and tried with multiple tokens
 
Screenshots:
![aa](https://github.com/user-attachments/assets/a8e0d185-47c3-4f59-a6ff-4b96b6791161)
![ab](https://github.com/user-attachments/assets/9fb2343a-3766-46ff-a268-eb06136798ad)
![ac](https://github.com/user-attachments/assets/e3a2f1e1-5fea-4d1d-a2d1-b320f469b9c8)
![ad](https://github.com/user-attachments/assets/5f8106ed-3487-4186-a73a-afe47578e3eb)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by phanomgames** [comment]
Get this as well, with fresh token in both cli and gui
![image](https://github.com/user-attachments/assets/0f724ab3-db9d-459c-bc74-236fd5fdd6ef)

including in old versions. Have tried on multiple user accounts (for making userbot), gotten the same token by checking auth under network and token under local storage. Unsure of what could be going wrong.

**Comment by Tyrrrz** [comment]
Judging by the SSL error and the fact that you're using Win10, are you on top of your Windows Updates?

**Comment by phanomgames** [comment]
> Judging by the SSL error and the fact that you're using Win10, are you on top of your Windows Updates?

that was it, my bot's working again. Thanks so much.
