### ISSUE TITLE
After making changes in chat (for example, removing a file), we lose this in our downloaded content because we refer to the Discord address of the file.

### ISSUE THREAD

**Issue by MGabala** [Tyrrrz/DiscordChatExporter#1278]
### Version

newest

### Flavor

GUI (Graphical User Interface)

### Platform

windows 11

### Export format

HTML

### Steps to reproduce

Just download something, delete it from the server, and you will see that our downloaded content becomes broken.

### Details

I think there should be a mechanism that downloads all files to local storage and keeps them.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by 96-LB** [comment]
> I think there should be a mechanism that downloads all files to local storage and keeps them.
Turn on the download assets setting in GUI or use `--media` in the CLI.
