### ISSUE TITLE
Message links should navigate inside the export if possible

### ISSUE THREAD

**Issue by Miepee** [Tyrrrz/DiscordChatExporter#128]
Could there be an option, that Discord Chat references, sent you to the appropriate message in the html, instead of linking to Discord?

**Comment by Tyrrrz** [comment]
Can you give an example?

**Comment by Miepee** [comment]
When you click the 3 dots next to a message and click on "copy link", it will create a link similar to this:
https://discordapp.com/channels/@me/509728160603045898/531064413541629953
That when clicked on in discord, brings you to that message.

And it'd be nice, if in the html, clicking these links would bring you to the message in the html chat, and not linking to discord.

**Comment by Tyrrrz** [comment]
Oh I see.
This could be possible, but obviously only for messages within the same export.

**Comment by Miepee** [comment]
Making that an option for #21 would be neat.
