### ISSUE TITLE
App hangs when exporting some servers

### ISSUE THREAD

**Issue by FlashFried** [Tyrrrz/DiscordChatExporter#1287]
### Version

2.43.3

### Flavor

GUI (Graphical User Interface)

### Platform

Windows 10

### Export format

HTML

### Steps to reproduce

I selected all the channels on one server and it started exporting, after about 7-10 minutes, the exporter stops saving and hangs. Is it because the server or channel has too much data?

### Details

-Complete Export

-Hangs at 50%-60%

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
What do you mean by "hangs"?

**Comment by FlashFried** [comment]
Well, it completely stays on one spot and doesn't export any further. Does it have to do with the MonacoPreviewHandler errror I keep getting?

**Comment by FlashFried** [comment]
![image](https://github.com/user-attachments/assets/c87249fb-fb78-41fb-93bc-0c5bde0fd3b4)

**Comment by FlashFried** [comment]
![image](https://github.com/user-attachments/assets/a8821e2f-0347-4b24-a41f-9a5b3ce8578e)
![image](https://github.com/user-attachments/assets/cf417a14-de40-4061-9980-50f3c738df2f)

**Comment by Tyrrrz** [comment]
Yeah that would imply you don't have access to the specified channel

**Comment by FlashFried** [comment]
I actually don't know why it hangs. All I know is that trying to export a specific server suddenly stalls indefinitely at one point. It's the same with the CLI.

**Comment by Tyrrrz** [comment]
Is the error you posted above from some other export?

Try to isolate the problem by exporting a subset of channels instead of all of them. If the export still hangs, reduce the subset until you identify the channel that causes it. If it doesn't, export a different subset.

**Comment by 96-LB** [comment]
The export progress is also determined by number of channels completed, so if you hit a particularly large channel the progress will slow down considerably. It's possible that what you think is "hanging" is just a really large channel being next in the queue. You can determine if this is the case by actually looking at the output files and seeing which one is currently being exported when it hangs, and seeing whether that specific file is still getting updated.
