### ISSUE TITLE
Docker image missing tzdata package

### ISSUE THREAD

**Issue by andrewlow** [Tyrrrz/DiscordChatExporter#1293]
### Version

v2.43.3

### Flavor

CLI (Command-Line Interface)

### Platform

Docker

### Export format

HTML

### Steps to reproduce

I'm running the docker image. I noticed that my HTML output contains

> Timezone: UTC+0

Despite the fact that I'm providing the environment variable `-e TZ=America/Toronto` to my docker command line. 

I believe this worked in the past, but something has changed.

### Details

**Expected**: Setting the TZ environment variable would provide dates with the right timezone

**Actual**: Docker container always runs in UTC

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by andrewlow** [comment]
I believe that the base alpine image - is either no longer, or has had the `tzdata` package removed.

Extending the example above - you can 'fix' this by adding the tzdata package

```
/out # date
Thu Sep 19 17:29:56 UTC 2024
/out # apk add tzdata
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
(1/1) Installing tzdata (2024a-r0)
OK: 47 MiB in 21 packages
/out # date
Thu Sep 19 13:30:42 EDT 2024
/out # 
```

If the [dockerfile](https://github.com/Tyrrrz/DiscordChatExporter/blob/8519ec0fff01120a3f5e824d8f299d77aa57004a/DiscordChatExporter.Cli.dockerfile#L43C5-L43C8) is modified to include the `tzdata` package - this should resolve the problem.

**Comment by Tyrrrz** [comment]
Please open a PR to add it
