### ISSUE TITLE
Images aren’t Loading for me in the files

### ISSUE THREAD

**Issue by Grenoz** [Tyrrrz/DiscordChatExporter#1295]
### Version

Latest Version

### Flavor

GUI (Graphical User Interface)

### Platform

Windows 11 and IPhone 11

### Export format

HTML

### Steps to reproduce

Step 1: Export Server into .HTML file
Step 2: Leave server that was being exported

### Details

images won’t load for me in any of the archives I have. Some will load, but most will just say “Image Attachment” in blue text, and when clicked on they just bring up a new webpage that says “Image is No longer available”. This seems to be ah issue only effecting me, too, because all the images seem to be loading fine for them. All these issues also only came after i left the server. Please Help 🙏

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by hyzchip** [comment]
Did you enable the "download assets" option?

**Comment by Grenoz** [comment]
> Did you enable the "download assets" option?

I’d assume probably, but I can’t be sure I actually did

**Comment by Tyrrrz** [comment]
You need to export with the "download assets" option enabled
