### ISSUE TITLE
"Last message sent: never"

### ISSUE THREAD

**Issue by wil70** [Tyrrrz/DiscordChatExporter#1298]
### Version

2.43.3 of DiscordChatExporter.win-x64.zip

### Flavor

GUI (Graphical User Interface)

### Platform

Win 10 PRO GUI version

### Export format

TXT

### Steps to reproduce

I connect to my discord by following the instruction to get the Authorization token
I can see all my servers and channels
I go to a private/premium channel
I can download the welcome channel 
I click on a memo channel
it says "Last message sent: never"

Issue: 
I can not download the content of the memo channel
But when I go to the memo discord channel via the browser I can see the content (the content is simple text)

### Details

Hello, I have open channel and channel with membership/premium. I would like to dowload instead of taking notes.
I see all my servers and all channels via my browser. I can connect DiscordChatExporter to my discord, I can see the discord server and channels names. I can download the channels except a few premium channels where it says "Last message sent: never" but there are text content in those channels.

Any idea how I can solve this?

thanks

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [X] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
What is a memo channel? Is that new?

**Comment by wil70** [comment]
One of the server has a channel call "memo" (fi: premium meaning not a free channel)

**Comment by Tyrrrz** [comment]
Does it work differently from a regular channel?

**Comment by wil70** [comment]
@Tyrrrz I was looking at the typse of channel and realize it was a some kind of link to another channel, now that I point to the real channel it work
I will close this issue
TY
Wi
