### ISSUE TITLE
Freezing / stuck on everything I try

### ISSUE THREAD

**Issue by Abbabbabsj** [Tyrrrz/DiscordChatExporter#1304]
### Version

v2.43.3

### Flavor

GUI (Graphical User Interface), CLI (Command-Line Interface)

### Platform

Windows 10

### Export format

HTML

### Steps to reproduce

I'm not sure, I do think it started when I accidentally closed the application halfway through exporting a group chat with 170k messages in it. After that, everything started bugging so that might be the problem. 

### Details

![image_2024-10-05_121146465](https://github.com/user-attachments/assets/019fb4ee-dd18-4e90-aec4-c392c3a13661)
![image_2024-10-05_121241656](https://github.com/user-attachments/assets/39f4d85a-4558-4613-b64d-4ffa59e1179e)

On both the GUI and CLI, any DM or group chat I try will result in being frozen. The only thing that it successfully downloads are chats that have a very small amount of messages (under 1k). I tried chats with only 3,000 messages and left them for 30 minutes with no progress at all. I reinstalled the application, restarted my pc, changed my token, tried a whole different Discord account, and this issue is still happening. I don't think this issue has been reported before because nobody has been frozen on 0% afaik. I'm also on the default settings and didn't change anything. If you guys have any tips that can help me fully reset the app or something I'd appreciate it. 

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by mariodcosta** [comment]
I am experiencing this issue too.
I have a chat since 2020 with thousand messages and the yellow bar frozen starts and frozen in the beginning . 
I am using the same configuration that OP:

Version

v2.43.3

Flavor

GUI (Graphical User Interface)

Platform

Windows 11

Export format

HTML

Thank you very much!

**Comment by Tyrrrz** [comment]
Need a channel invite to test

**Comment by mariodcosta** [comment]
> I am experiencing this issue too. I have a chat since 2020 with thousand messages and the yellow bar started and frozen in the beginning . I am using the same configuration that OP:
> 
> Version
> 
> v2.43.3
> 
> Flavor
> 
> GUI (Graphical User Interface)
> 
> Platform
> 
> Windows 11
> 
> Export format
> 
> HTML
> 
> Thank you very much!
> 
> ![08f8cc24-6a80-4dd6-bd5a-fe7a9eb01adf](https://private-user-images.githubusercontent.com/13469672/374796849-85c25fba-01e4-4dfa-92ef-460511a6276e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzUyOTIsIm5iZiI6MTcyODYzNDk5MiwicGF0aCI6Ii8xMzQ2OTY3Mi8zNzQ3OTY4NDktODVjMjVmYmEtMDFlNC00ZGZhLTkyZWYtNDYwNTExYTYyNzZlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwODIzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGY3ZGQzMDVmMGE1ZmYwMDY4ZTRhNmNkOWQyZmQ3OWExOWJhOGI1M2I1OGI5NTcwY2Y3NjRhZDkzMmIxZWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dtQrfvzkTydZVqVB6KKcxHdOFQgVhFwSFOygqy81Z8g)

Guys , I used the old version 2.30.0 and it downloaded all chat since 2020 until today!

**Comment by Tyrrrz** [comment]
> Same thing for me. Only problem is, I don't know how to keep version 2.30.1 from auto-updating...

You can do so in settings

**Comment by Tyrrrz** [comment]
I don't have a way to reproduce the issue.

Note that channel export may take a very long time to complete, sometimes appearing as having frozen. That's just the nature of things, as there's a lot of work that the application needs to do to preserve your chat logs.

You can use date ranges to export channels in more manageable blocks of messages.
