### ISSUE TITLE
Build with warning: `ServicePointManager` is obsolete: `WebRequest`, `HttpWebRequest`, `ServicePoint`, and `WebClient` are obsolete

### ISSUE THREAD

**Issue by CancanTang** [Tyrrrz/DiscordChatExporter#1309]
### Version

v999.9.9

### Flavor

GUI (Graphical User Interface)

### Platform

Windows 10

### Steps to reproduce

1. Change Targetfamwork from .NET8.0 to .NET 9.0 in Directory.Build.props
`<TargetFramework>net9.0</TargetFramework>`
2. Cd to DiscordChatExporter\DiscordChatExporter.Gui
3. run command "dotnet build" with 9.0.100-rc.2.24470.13

### Details

**Expected Behavior**:
Build successfully without warnings.

**Actual Behavior**:
There is a warning in error list: **'ServicePointManager' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead. Settings on ServicePointManager no longer affect SslStream or HttpClient.'**

**Other info**
We are doing Application compatibility testing with this application against the latest .NET 9 SDK. When retarget the application to net9.0 and build with the latest .NET 9 SDK, it failed with error:` ‘ServicePointManager' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete`

After the investigation, it is related to a .NET 9 breaking change https://github.com/dotnet/docs/issues/43144

Please refer to more information from https://github.com/dotnet/sdk/issues/43621

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Makes sense. I assume the only offending line is this:

https://github.com/Tyrrrz/DiscordChatExporter/blob/abd7adc9e032ae814d7f68bd844a32e1604ee9e4/DiscordChatExporter.Gui/App.axaml.cs#L77-L78

We should remove this code since it no longer does anything in .NET Core. It was a leftover from when DCE was still using .NET Fx.

Open for PRs.
