### ISSUE TITLE
User privacy

### ISSUE THREAD

**Issue by Raj7shekhar** [Tyrrrz/DiscordChatExporter#1326]
### Version

current version.

### Flavor

CLI (Command-Line Interface)

### Platform

Docker

### Export format

TXT

### Steps to reproduce

While exporting the chats, I want to avoid getting the username of the discord users. is there any way possible. thanks.

### Details

Hi Team, is there any way or provision in this repo to mask user details such as username, in order to avoid any user privacy issues?

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
No, it's not possible
