### ISSUE TITLE
Display reaction authors

### ISSUE THREAD

**Issue by Miepee** [Tyrrrz/DiscordChatExporter#133]
It'd be nice to see, from which user(s) the reactions come from.

**Comment by Tyrrrz** [comment]
This looks like it's impossible to do with the API because it doesn't return reaction authors
https://discordapp.com/developers/docs/resources/channel#reaction-object

**Comment by Miepee** [comment]
Oh, well then.
I'll just hope, that the API gets updated sometime, to make that possible.

**Comment by Throne3d** [comment]
The API lets you get the reaction authors, if you give it a channel, a message, and the relevant emoji: <https://discordapp.com/developers/docs/resources/channel#get-reactions>. I'm not sure if this would be too much overhead in terms of separate requests for the data?

**Comment by Tyrrrz** [comment]
Hm, this is 1 call per each reaction emoji per each message, that would a lot of requests. I guess Discord itself queries this every time you hover over specific reaction.

**Comment by Tyrrrz** [comment]
Marking as "wontfix" because of the issue @Throne3d mentioned. Discord queries reaction authors on per-message basis, knowing that it won't need to get it for all messages in the channel. DiscordChatExporter, on the other hand, will have to do it for all messages, which will make it more expensive in terms of time than it's worth.

**Comment by omegasome** [comment]
Why would it have to do it for every single message? Obviously DCE knows which messages have reactions and even which reactions they are—that's how it knows to display them on a message. So why couldn't it query who reacted to the message when (and only when) it knows someone did? Is there something I'm missing here? Maybe about the architecture of this particular program?

**Comment by TheTechRobo** [comment]
@omegasome Late response but in big servers, especially announcement channels, that might blow up to hundreds of requests. That's not terribly efficient.

**Comment by Hate9** [comment]
Once per reaction per message-with-reactions could definitely be a lot, but it's not *horrible* - I think that's the sort of tradeoff that should ideally be left up to the user, by making it an optional (and opt-*in*, not out) feature.
