### ISSUE TITLE
Export Time in 24h format

### ISSUE THREAD

**Issue by Miepee** [Tyrrrz/DiscordChatExporter#134]
An option to export the chat in 24h time format, via the GUI would be nice.

**Comment by Tyrrrz** [comment]
You can configure date format in settings

**Comment by Miepee** [comment]
Thanks, I didn't know that.
But I'd still be nice, if it was possible to do so from within the program.

**Comment by Miepee** [comment]
Somehow, I did not see that icon...
Well, I'll close the issue then.
