### ISSUE TITLE
Can you do a new release?

### ISSUE THREAD

**Issue by ealgase** [Tyrrrz/DiscordChatExporter#135]
It's pretty difficult to compile this on Linux, and many features have been added, so another release would be nice.

**Comment by Tyrrrz** [comment]
Hey.
Thank you for waiting so eagerly for a new release :)
I'm trying to get a new feature in, but worst case scenario I'll release what I have by Friday.

**Comment by ealgase** [comment]
OK, thanks.  Love this project!

**Comment by Tyrrrz** [comment]
Rejoice!

**Comment by ealgase** [comment]
Thank you!
