### ISSUE TITLE
Token not available in Local Storage even after Ctrl+R

### ISSUE THREAD

**Issue by Latias4Ever** [Tyrrrz/DiscordChatExporter#136]
As the title says, I cannot obtain my token despite using Ctrl+R while on the Application tab. I've read that Discord got rid of user tokens entirely, but I'm not sure if that's true or not. Either way, I'm unable to use this since I can't get my token at all. Is there anything that can be done?

**Comment by Tyrrrz** [comment]
Still works for me

**Comment by Latias4Ever** [comment]
It seems it's either an issue with my version of Chrome, or Discord changed something. I actually managed to get it, but I had to Reload, and immediately press the Stop button to keep it from loading anything else, because the token appeared for only a fraction of a second, and as soon as Discord started loading, it'd disappear.

**Comment by Tyrrrz** [comment]
Interesting. Doesn't seem to happen to me on desktop client.

**Comment by RenanYudi** [comment]
It has been like this on web browsers since they hid the tokens. You can press the stop button or just keep reloading until you can copy it.
