### ISSUE TITLE
Program does not export everything

### ISSUE THREAD

**Issue by Miepee** [Tyrrrz/DiscordChatExporter#137]
For some reason, it's unable to export any message that was sent today (9/2/19).
Every message that was sent earlier, works though.
This bug is present in the old and new release.

**Comment by Tyrrrz** [comment]
Just tried to export a random channel and I see messages from today

**Comment by Tyrrrz** [comment]
Are you sure you are not using date ranges?

**Comment by Miepee** [comment]
Yeah, I'm pretty sure.
This is how the command line looks.
![image](https://user-images.githubusercontent.com/38186597/52531346-de606a80-2d13-11e9-8d85-a4dc4c098d2c.png)

**Comment by Tyrrrz** [comment]
Does it only happen in command line?
I have seen this reported a couple of times in the past but nobody has been able to consistently reproduce this.

**Comment by Miepee** [comment]
Nope, happens in the GUI version as well.

**Comment by Tyrrrz** [comment]
So what's the situation now? Considering it's now a new day, does it export messages from 9th of February?
Also, does it happen on all channels?

**Comment by Miepee** [comment]
Nope, it still doesn't export the 9th.
And yes, it happens on all text channels.
If that helps, I didn't test it on DMChannels yet.

**Comment by Tyrrrz** [comment]
Any extra information or patterns you can find me would be nice.
If it's possible I'd like to be able to test it on the same channel that you do, if it's possible to gain access to one of them.

**Comment by Miepee** [comment]
Can you give me your Disdord tag, so I can send an invite?

**Comment by Tyrrrz** [comment]
Tyrrrz#5447

**Comment by DecemAdUnum** [comment]
Still happens for me. Can't go before june 10

**Comment by Tyrrrz** [comment]
Can you please create a new issue detailing the exact problem you have?
