### ISSUE TITLE
All Code Blocks get rendered the same

### ISSUE THREAD

**Issue by Miepee** [Tyrrrz/DiscordChatExporter#138]
For the exporter, the code blocks are rendered all with the same colours and the language identifier gets ignored.
So 
\```cs
Console.WriteLine("Hello World");
\```
looks the same as
\```
Console.WriteLine("Hello World");
\```

**Comment by Tyrrrz** [comment]
Do you know which library is Discord using for syntax highlighting?

**Comment by QuantumToasted** [comment]
Google led me to believe that discord uses https://highlightjs.org/, even if it's not the specific one, it's probably something you might be able to use.

**Comment by Tyrrrz** [comment]
I was lead there as well but couldn't find the theme they use

**Comment by QuantumToasted** [comment]
I think i found it. It's Solarized Dark. 99.99% of everything i tried matches it, except for that one attribute. 
Left codeblock is on the highlight.js site, right is directly in the Discord client.
![image](https://user-images.githubusercontent.com/30324210/53827817-9d89f900-3f41-11e9-8103-e1fdd6d33e7b.png)

**Comment by Tyrrrz** [comment]
@QuantumToasted awesome!
Can you check if they're using the same one for their light theme?

**Comment by QuantumToasted** [comment]
It looks like they're using Solarized Light for light theme, albeit with a slightly different background color. Again, the attributes seem to be missing highlighting, but everything else looks like it matches 1:1.
![image](https://user-images.githubusercontent.com/30324210/53835994-6a049a00-3f54-11e9-9f3a-56cef4a27bed.png)

**Comment by Tyrrrz** [comment]
Cool, thanks!
Actually, the backgrounds are different in both cases, but that's fine. My only concern is the impact of putting a js that will run on all nodes in the DOM, but I guess we will see.
