### ISSUE TITLE
Not all emojis are rendered

### ISSUE THREAD

**Issue by l0c4lh057** [Tyrrrz/DiscordChatExporter#140]
There are some emojis that break when exporting, e.g. the :one: emoji (i think this also applies for the other number emojis)

**Comment by Tyrrrz** [comment]
What happens?

**Comment by l0c4lh057** [comment]
This is the `:one:` emoji in my document
![image](https://user-images.githubusercontent.com/42084688/52563409-9e77b100-2e01-11e9-80f0-36b9d11892da.png)

![image](https://user-images.githubusercontent.com/42084688/52563490-da127b00-2e01-11e9-977b-4f70141f1718.png)

**Comment by Tyrrrz** [comment]
It seems it needs custom font to render
