### ISSUE TITLE
Display progress while downloading in CLI

### ISSUE THREAD

**Issue by 161134050** [Tyrrrz/DiscordChatExporter#143]
It seems like this was requested before, but was never implemented?

The other issue #52 [Tyrrrz](/Tyrrrz) says

> There's no way to show progress, because there's no way to know how many messages there are,

 however this is not true, the search feature will return the exact amount of messages there are within a channel.

Here is the endpoint for searching for messages within a channel
`https://discordapp.com/api/v6/guilds/{GUILD-ID}/messages/search?channel_id={CHANNEL=ID}&include_nsfw=true`

The total amount of messages is the first item in the json response
![image](https://user-images.githubusercontent.com/39843740/52910383-adfb6c00-32d1-11e9-9c39-30d1fb29a699.png)

Cheers

**Comment by 161134050** [comment]
My mistake, it seems like this was implemented for GUI version, but remains missing in CLI (I think)

**Comment by Tyrrrz** [comment]
The search API wasn't available back then so the progress was based on date estimation. And you're right it was never added to CLI.

**Comment by Tyrrrz** [comment]
Interestingly, I still don't see the search API in docs

**Comment by Tyrrrz** [comment]
After debugging in dev tools console, I noticed the search request is also asynchronous. I would say the current implementation, despite less accurate, is more lightweight.

**Comment by Tyrrrz** [comment]
As for your original issue, are you looking for adding progress in CLI?

**Comment by 161134050** [comment]
Yes please, i'm using the CLI to export huge discords and I think it would be very helpful :)
