### ISSUE TITLE
Token no longer showing in Chrome or Edge. 

### ISSUE THREAD

**Issue by JASHIKO** [Tyrrrz/DiscordChatExporter#148]
I have noticed that Chrome and Edge no longer show the Token (code). Thus making the entire process fail. Is this a Chrome/Edge update issue or have Discord changed something to block this process? I love this little piece of software so I'm keen to find a solution :)

**Comment by Tyrrrz** [comment]
Same as #136 ?

**Comment by JASHIKO** [comment]
yes sorry i didnt read further.
