### ISSUE TITLE
Does anyone know what happens to images when both accounts are deleted?

### ISSUE THREAD

**Issue by jicuxaz** [Tyrrrz/DiscordChatExporter#149]
I was wondering what would happen to saved images if both accounts involved were deleted. From what I gather the images are directly linked from discord so eventually they would be deleted.

**Comment by Tyrrrz** [comment]
I think the images will indeed get deleted after some time. To preserve them, you can open the exported HTML in browser and save it again, the browser will download the images. Suggested here: https://github.com/Tyrrrz/DiscordChatExporter/issues/21#issuecomment-348706551

**Comment by jicuxaz** [comment]
Thanks, this works perfect

**Comment by Tyrrrz** [comment]
Awesome :)
