### ISSUE TITLE
Message grouping works differently from Discord

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/DiscordChatExporter#152]
Currently, message grouping seems to function differently from Discord.
[Right now, messages are grouped together if:](https://github.com/Tyrrrz/DiscordChatExporter/blob/dda32d8af2e14e44f7d71345ad71cacd31d30559/DiscordChatExporter.Core/Services/ExportService.TemplateModel.cs#L40)
1. Author is the same
2. Time between first message and current is less than 1 hour
3. First message and current were sent at the same hour of the day
4. Group size is less or equal to message group limit

I need help figuring out the rules that Discord uses.

**Comment by Jefferderp** [comment]
A decent changelog mentioned message grouping as changing from "on the hour" to "every 7 minutes." I assume this means "after every 7 minutes of inactivity."

**Comment by Tyrrrz** [comment]
Ohh, so they changed it. I couldn't find any mention of it on the blog and I'm not using Discord enough anymore to notice it.
Thanks!
