### ISSUE TITLE
IO exception from e493357 (CLI progress indicator) when using bash

### ISSUE THREAD

**Issue by Jefferderp** [Tyrrrz/DiscordChatExporter#155]
Hello,

I believe I've identified a very edge-case issue resulting from commit [e493357](https://github.com/Tyrrrz/DiscordChatExporter/commit/e493357a9f632182060c5f15370da1e66ab78e2d?diff=unified) _(add progress reporting to CLI)_.

My specific setup involves use of the DiscordChatExporter.CLI with bash, via Windows Subsystem for Linux (WSL), instead of cmd.exe or Powershell. Essentially, I run CLI commands with bash.exe instead of cmd.exe, but the resulting output is the same. This just allows for more comfortable scripting operations.

Since [e493357](https://github.com/Tyrrrz/DiscordChatExporter/commit/e493357a9f632182060c5f15370da1e66ab78e2d?diff=unified), I now receive an IO exception in bash, whereas cmd.exe and PowerShell still operate normally. 

Some sample outputs, with sensitive data substituted:

In cmd.exe, run
```batch
DiscordChatExporter.Cli.exe export --channel "999994764689765432" --token "myusertokenredacted" --format HtmlDark --dateformat yyyy-MM-dd
```

and receive...

```batch
Exporting channel [999994764689765432]... Completed √
```

As expected.

Now in bash.exe, run the same command...

```bash
./DiscordChatExporter.Cli.exe export --channel "999994764689765432" --token "myusertokenredacted" --format HtmlDark --dateformat yyyy-MM-dd
```

and receive...

```bash
Exporting channel [999994764689765432]...
Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at DiscordChatExporter.Cli.Internal.InlineProgress..ctor()
   at DiscordChatExporter.Cli.Verbs.ExportChannelVerb.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DiscordChatExporter.Cli.Verbs.Verb`1.Execute()
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at DiscordChatExporter.Cli.Program.Main(String[] args)
```

I believe these errors are directly output by WSL, though this is where my comprehension ends.

Since my case is such an edge one, can I suggest a flag (maybe ```--quiet```) so that ```export```, ```exportdm``` and ```exportguild``` may run silently? I don't fully understand the cause of this, but I believe ```--quiet``` would be a suitable workaround.

Your help much appreciated. Apologies for any mistakes, and thanks for this great piece of software!

**Comment by Tyrrrz** [comment]
Hi!
Thanks for using my software.
It looks like a very interesting edge-case indeed, the error comes from `InlineProgress` constructor, where it tries to get X,Y coordinates of the cursor, which it uses later to go back to and overwrite text. I'm assuming it's being thrown not due to the fact that it's ran from bash, but because the application thinks there's no console attached and thus there's no cursor and no cursor coordinates.
The good thing is that I can replicate this by using bash on Windows directly so I will look into it.
