### ISSUE TITLE
[suggestion] Show current/total messages as part of progress report

### ISSUE THREAD

**Issue by ealgase** [Tyrrrz/DiscordChatExporter#156]
I love the new progress functionality, but it would be somewhat useful to also show the number of messages exported as well as the total number to be exported.

**Comment by Tyrrrz** [comment]
Unfortunately, the total number of messages is unavailable

**Comment by ealgase** [comment]
Really?  I can find it for any channel by doing this:

![image](https://user-images.githubusercontent.com/11603778/54091336-7a9e8100-4355-11e9-845b-e8f8b2c90355.png)

**Comment by Tyrrrz** [comment]
Yes, this feature seems to only be available in the client. There's a way to call that part of the API but if the chat hasn't been searched in for, it will take some time to populate. Also, I don't think it's available to bots.

Overall, I considered it when it was brought up in #143 but decided it was too much of a hassle since it's already showing approximate progress anyway.

**Comment by ealgase** [comment]
In particular, sending a request to https://discordapp.com/api/v6/guilds/GUILD_ID/messages/search?channel_id=CHANNEL_ID&include_nsfw=true sends back the following data:

```json
{  
   "total_results":79130,
   "analytics_id":"0bd013a8be929dba2fc3a65fbd8f6342",
   "messages":[...],
}
```

**Comment by Tyrrrz** [comment]
Is there a particular need you want the number of messages for or is it just for more visibility?

**Comment by ealgase** [comment]
My main use would be to more accurately estimate the time an export would take, and the space it would use.

**Comment by Tyrrrz** [comment]
I would wait until they add a documented and supported [API endpoint for that](https://discordapp.com/developers/docs/resources/channel).

**Comment by ealgase** [comment]
OK.  If that can't be done, could the messages currently downloaded still be displayed?

**Comment by Tyrrrz** [comment]
Yes

**Comment by ealgase** [comment]
Thanks!  BTW, love this project :heart:

**Comment by Tyrrrz** [comment]
The project loves you back :)
