### ISSUE TITLE
100% CPU usage when writing chat log to file

### ISSUE THREAD

**Issue by terorie** [Tyrrrz/DiscordChatExporter#158]
The client jumps to CPU 100% for several minutes when exporting a large channel (18K messages) to CSV  (macOS, Mono).

The final file is just 2,3 MB and Go parses this in under a second.

**Comment by RenanYudi** [comment]
Works perfectly with large channels and CSV here. What are the specs of your Mac and which version of DCE are you using?

![](https://i.imgur.com/xOhTyt3.png)

**Comment by RenanYudi** [comment]
Actually, it does get close to 100% when the file is being generated. So… Can confirm.

![](https://i.imgur.com/z9kXtKt.png)

**Comment by terorie** [comment]
@RenanYudi Just compiled `master`, Visual Studio Community 2017
Imo, Mac specs don't matter much (CSV serializing needs no CPU). MBP Mid 2015 Core i7 2,8 GHz

Channel is `461525479460044800`, which you can access with invite 
https://discordapp.com/invite/cMHemg8 if you want to try yourself

**Comment by terorie** [comment]
I have a suspicion https://github.com/Tyrrrz/DiscordChatExporter/blob/77bf32aa5a811a4515a8eae23c8ca9b26cd07c24/DiscordChatExporter.Core/Services/ExportService.cs#L50-L58 is the slow part

**Comment by terorie** [comment]
@RenanYudi I ended up writing a (streaming) dumper in Go that uses no CPU at all

https://github.com/terorie/discord-dump

Only does guilds in JSON for now, will add all the features of this repo.
Hope it's useful for the author.

**Comment by Tyrrrz** [comment]
I'm guessing the CPU utilization is caused by the new markdown AST parser. In what version did it start to happen?

**Comment by RenanYudi** [comment]
100% utilization starts to get significantly longer with 2.10

**Comment by Tyrrrz** [comment]
Then the 100% utilization will likely be unavoidable for HTML exports but it can at least be improved so it doesn't block UI. The other export formats may need to be brought outside the templating engine to improve the performance. I was hoping having them all under the same engine would make maintaining them convenient, but I guess it hurts performance too much.

**Comment by terorie** [comment]
I don't know C# enough to contribute, but I have an idea how to fix this. How about using a streaming interface with implementations for JSON, CSV and HTML and avoiding templating?
The pseudocode looks like this:

```
interface MessageWriter {
    void SetWriter(Writer wr)
    void Begin() // Writes header (Like <body><div id="messages">)
    void WriteMessage(Message)
    void Close() // Writes footer (Like </div></body>)
}
```

```
void dumpMessages(File file, Message[] msgs) {
    MessageWriter w = getDefaultMessageWriter();
    w.SetWriter(file);
    w.Begin();
    for (Message msg : msgs) {
        w.WriteMessage(msg);
    }
    w.Close()
}
```

Even if it makes the code a bit less clean, `HtmlWriter::WriteMessage` could either escape and write the content by hand (all non-ASCII => HTML numerical escape, writing using String.format) or use a HTML template per message.

**Comment by terorie** [comment]
Also @Tyrrrz would you mind if I take your HTML templates and put them in https://github.com/terorie/discord-dump (MIT license)? I'd give you attribution in source and program help of course.

**Comment by Tyrrrz** [comment]
It used to be a streaming interface without templating, a long time ago: https://github.com/Tyrrrz/DiscordChatExporter/blob/d958f613a377d0a1a4f5b2f41071529df9ebb88b/DiscordChatExporter.Core/Services/ExportService.Html.cs#L252-L365
By looking at the file you can probably guess why we ended up using templates. But even then, the templating doesn't induce *that* much of an overhead, it seems it's mostly [the markdown parsing](https://github.com/Tyrrrz/DiscordChatExporter/blob/77bf32aa5a811a4515a8eae23c8ca9b26cd07c24/DiscordChatExporter.Core.Markdown/Internal/Grammar.cs) which will not go anywhere anyway.

**Comment by Tyrrrz** [comment]
You can use any file in this repository [in accordance with GPLv3](https://github.com/Tyrrrz/DiscordChatExporter/blob/master/License.txt) so yes.

**Comment by terorie** [comment]
@Tyrrrz https://github.com/nginx/nginx/blob/910f330ad0caa49fe901e9426ef00d95d45ba32c/src/http/modules/ngx_http_autoindex_module.c#L446 It might look bad but even Nginx does it
I think hardcoding is worth the performance, would you agree?

**Comment by Tyrrrz** [comment]
Of course. I'll look into it when I get more time...

**Comment by Tyrrrz** [comment]
https://github.com/Tyrrrz/DiscordChatExporter/pull/162#issuecomment-481838594

**Comment by terorie** [comment]
Nice and fast again!

**Comment by Tyrrrz** [comment]
Just to clarify, it doesn't completely solve the problem, but it drastically reduces the impact. I will look into optimizing the exporting process even further in the future.
