### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by kovitikus** [Tyrrrz/DiscordChatExporter#159]
Hey,

I'm not entirely certain if this is the correct place to leave this, but I don't know any other spot.

I'm in a community for Godot (an open source game engine) called GDQuest (offers courses in game development with Godot). The owner recently decided to merge his two servers, but we didn't want to lose all of the valuable discussions and information from the server getting the axe. 

Thankfully we stumbled onto a reddit thread that lead here and I tried out Discord Chat Explorer.

AMAZING!

It looks great and so do the results. It was super easy to use and did exactly what it's supposed to.

Thank you to all of the contributors for your hard work and helping to archive our valuable community! 

I hope that this feedback helps keep this project alive and active.

**Comment by Tyrrrz** [comment]
Thank you and I'm glad you found it useful :)
