### ISSUE TITLE
Export messages with filtering

### ISSUE THREAD

**Issue by silent** [Tyrrrz/DiscordChatExporter#160]
Is there a way to export specific content such as only images or only videos from a channel?

**Comment by Tyrrrz** [comment]
Nope, there is not.

**Comment by silent** [comment]
Could that be added in the future?

**Comment by Tyrrrz** [comment]
Theoretically yes :)

**Comment by silent** [comment]
Alright, well it'd be a cool feature that could be added to at least the CLI Version.

**Comment by Tyrrrz** [comment]
Suggested implementation (by @scattrbrain1994):

> I appreciate your work on this app!
Just want to say that I also wish it were possible to filter chat history similar to how it's done via discord's search bar.
I'm in a chatroom of music makers who often share their original music either as a discord attachment or as a link to any of several music hosting sites. When I can I like to download all of their music and sort it by artist. This has been a manual process but this program has the potential to make it almost automatic. For that potential to be realized I would need the ability to filter out everything except audio file attachments and links to music hosting sites (i.e. soundcloud.com/clyp.it/spotify/bandcamp/youtube etc), along with the ability to filter by user. As-is, I'm forced to download a whole bunch of junk (images, videos, etc), even though I just want audio files, and that takes a long time, much longer than it would take if the program just downloaded audio files. Furthermore, after deleting the junk, I have to sort the remaining files by user. I wouldn't need to do this if there was a way to download audio files from a specified user only.

**Comment by Tyrrrz** [comment]
This should also support filtering by other message attributes, including author.

**Comment by cjlaborde** [comment]
Support this as well would be extremely useful.
To check by username or keyword.

**Comment by pmuybae** [comment]
I'm willing to put a $10 bounty on this, preferably with all the syntax [supported in the discord client](https://support.discord.com/hc/en-us/articles/115000468588-Using-Search) (bonus points and maybe $ for logical operators like AND, NOT and OR)

**Comment by manwhy** [comment]
would it be fine if you added more than just the discord search features? e.g. what i mentioned in #603

**Comment by Tyrrrz** [comment]
@manwhy we'll take it in steps. See also design discussion here: https://github.com/Tyrrrz/DiscordChatExporter/discussions/591

**Comment by Dani21** [comment]
I'm working on something to implement this on the client-side, as well as adding progressive loading. The largest channel I recently exported has an HTML size of 250 MB and media size of 7 GB. It's impossible to effectively use this way. I already have a draft of progressive loading working, where after a few seconds of loading, loading additional messages works instantaneously and keeps RAM sizes low. I'll post the JS code here, but there are other changes needed as well so it's not ideal to use yet.

```
function loadMore(){
    var msgs=window.document2.querySelectorAll('.chatlog__message');
    var ids=Array.prototype.map.call(msgs,e => e.id);
    var el=document.querySelector('.chatlog__message');
    var ind=el?ids.indexOf(el.id):ids.length;
    var load=ind-50;
    if(load<=-50){
        return;
    }else if(load<0){
        load=0;
    }
    ind--;
    var chat=document.querySelector('.chatlog');
    while(ind>=load){
        // Count current element
        var cur=msgs[ind--];
        var top=document.importNode(cur.parentNode.parentNode,true);
        var parent=top.querySelector('.chatlog__messages');
        var el=parent.querySelector('#'+cur.id);
        while(el.nextSibling){
            // Remove messages after target ending chat
            parent.removeChild(el.nextSibling);
        }
        while(el.previousSibling.nodeName!='SPAN'){
            if(ind>=load){
                // Count back up to target beginning chat
                el=el.previousSibling;
                if(el.nodeName=='DIV'){
                    ind--;
                }
            }else{
                // Remove non-targeted chat logs 
                parent.removeChild(el.previousSibling);
            }
        }
        // Correct timestamp:
        if(el.title){
            el.previousSibling.innerText = el.title.substring(14);
        }
        // Add to DOM
        chat.insertBefore(top,chat.childNodes[3]);
		top.querySelectorAll('.pre--multiline').forEach(block => hljs.highlightBlock(block));
    }
}
document.addEventListener('DOMContentLoaded', function(){
    var a=new DOMParser();
    window.document2=a.parseFromString(document.getElementById('chatlog').innerText, 'text/html');
    loadMore();
});
```
In addition to above, the HTML needs to change to become the following:
```
<div class="chatlog">
    <a href="javascript:void(0);" onclick="loadMore();">Load More...</a>
</div>

<script type="text/template" id="chatlog">
    <!-- Insert old .chatlog HTML contents here -->
</script>
```
Last, the `querySelectorAll('.pre--multiline').forEach(block => hljs.highlightBlock(block));` call and its parent can be removed.

This will also need to scroll to the bottom upon page load, `position:fixed` styling for the preamble (much more than that really), and the load link will need to be disabled during loading/automatically used when scrolled into view. If someone can style the preamble to be fixed to the top of the viewport at all times, that would be helpful because I'd rather not do that.
