### ISSUE TITLE
Can't view Emoji reactions by username

### ISSUE THREAD

**Issue by Foxxz** [Tyrrrz/DiscordChatExporter#163]
Can this be implemented? Normally when you highlight over them you'll get the names of the users who reacted, but I don't see this in any export.
Thanks

**Comment by Tyrrrz** [comment]
Hi,
This is a duplicate of #133.
In short: it's possible but will make the whole process of export significantly slower.

**Comment by Foxxz** [comment]
Could it be possible as a separate export option then as an additional file as to not slow down the main export?

And thanks for creating this btw, your work means a lot

**Comment by Tyrrrz** [comment]
Thank you.
I think this will be an unecessary overcomplication. Would you mind sharing why you want reaction authors so much? :)

**Comment by Foxxz** [comment]
Sure, mostly for preservation sake like when you say or release something sometimes people will react as a form of response instead of an actual message. In those cases it's pretty much just alternative communication

**Comment by Miepee** [comment]
In my case, it was because of preservation of polls.
So I could still see who voted for what.

**Comment by Tyrrrz** [comment]
I'll revive the older thread and close this one.
#133
