### ISSUE TITLE
Can't export multiple channels at once

### ISSUE THREAD

**Issue by lachiko** [Tyrrrz/DiscordChatExporter#164]
I've only checked 2.12 and 2.10.2 and the issue exists in 2.12

To reproduce just need to select two channels (holding ctrl) and press download -> export and select a folder. then the following shows only in 2.12

![image](https://user-images.githubusercontent.com/5151792/55959905-17cf3b00-5caf-11e9-947c-e0618fcaa78a.png)

**Comment by Tyrrrz** [comment]
Fixed, thanks for reporting.

**Comment by lachiko** [comment]
No worries thanks for fixing it so fast and sharing this awesome program.

I also spotted another minor issue in 2.10.2 I'll check 2.12 tonight.

basically if you download a bunch of small channels even after they're complete you'll receive notifications of them completing (I'm assuming it's due to it only showing one notification at a time with a minimum delay between each)

**Comment by Tyrrrz** [comment]
Thank you. ;)
Yeah that's still there. Please create a new issue for that one.
