### ISSUE TITLE
Blank messages when exporting embeds in CSV or TXT

### ISSUE THREAD

**Issue by xYaW** [Tyrrrz/DiscordChatExporter#165]
Hey,

I'm trying to export a chat with a lot of messages but they are embedded by a bot. Exporting to HTML works fine but exporting to TXT/CSV gives the messages with empty content.

Cheers

**Comment by Tyrrrz** [comment]
Hi,

Yes, this is true. I couldn't come up with a reasonable way of displaying embeds in plain text, considering they are so rich and flexible, so I just decided not to render them.

If you have a suggestion, I'm all ears. If you can come up with a way to render [this](https://leovoel.github.io/embed-visualizer/) in plain text, that would be amazing. :)

**Comment by Tyrrrz** [comment]
@xYaW do you have any suggestions?

**Comment by xYaW** [comment]
I don't know if it would be possible but maybe getting the full json would be nice? At least that way there would be a way to extract the data, even if you need to parse it later.

Or maybe adding a filter-like section to the exporter where you could pick which fields of the embed to export (like I'm only interested in embed.description and embed.author.name

**Comment by Tyrrrz** [comment]
I'd rather not have JSON there, especially with JSON output format eventually coming out (#103).

The problem with fields is that literally every field in an embed is optional, so it's still possible that the message content can be empty if you only render some of them.

**Comment by Tyrrrz** [comment]
The suggestion by @wankio is to render embeds as links. This of course will work only if the embed has a link and won't work in any other case. This seems fine as a better-than-nothing solution, except that it could result in duplication, e.g. when you post a link in a message Discord will append an embed with the URL's open graph info.

**Comment by wankio** [comment]
so basically, i must run it two times, one with plain text and one with embeds as links?

**Comment by Tyrrrz** [comment]
No, you wouldn't have to run it twice.

**Comment by wankio** [comment]
yeah, that's good but i thought all post have links when you right click on it ? i dont see any post dont have link, atleast it have discord direct link if it directly uploaded

**Comment by Tyrrrz** [comment]
ohhh you mean that link.
so you are saying a link like https://discordapp.com/channels/143867839282020352/286156910804336640/578484538829701120 would be sufficient for you instead of embed?

**Comment by wankio** [comment]
not the same at all ? because i think all post have link, some embed posted by BOT have link too but it can't export.

**Comment by Tyrrrz** [comment]
Can you make a screenshot to explain what you mean?

**Comment by wankio** [comment]
nvm, just render embed as link :)

**Comment by Tyrrrz** [comment]
Added support for embeds in TXT. I have no plans for adding it to CSV because that content is too rich for this format.
