### ISSUE TITLE
Example command for getting direct messages

### ISSUE THREAD

**Issue by NerveCoordinator** [Tyrrrz/DiscordChatExporter#166]
While the following command works for general server channels, it fails for using the ID of a private message:
`docker run --rm -v ${PWD}:/app/out  tyrrrz/discordchatexporter export -t <token> -c <channel ID> -f PlainText`

It gives this error:
```
Exporting channel [259474169610240010]... Failed X

Unhandled Exception: DiscordChatExporter.Core.Services.Exceptions.HttpErrorStatusCodeException: Error HTTP status code: NotFound - NOT FOUND
```

Is there a specific flag I need to use for direct messages?

**Comment by Tyrrrz** [comment]
For some reason, the channel ID that Discord copies when you click RMB->Copy ID on a DM channel is wrong.

If you want to get the actual ID, you can either open the said DM in browser/app, open developer tools (Ctrl+Shift+I or equivalent), open Console, type `window.location.href` and copy the long sequence of numbers at the end of the URL.

Alternatively, you can get IDs of all your DMs in CLI using `dm` command -> `docker run --rm -v ${PWD}:/app/out tyrrrz/discordchatexporter dm -t <token>`

**Comment by NerveCoordinator** [comment]
Okay that worked. However I had to copy the first sequence of numbers instead of the one at the end.
"https://discordapp.com/channels/@me/<numbers>/<numbers>"

**Comment by Tyrrrz** [comment]
Hmm, oops. :D
I remembered it was one of the two.

@RenanYudi would you please update the wiki?
