### ISSUE TITLE
Automating the export process

### ISSUE THREAD

**Issue by orbitingful** [Tyrrrz/DiscordChatExporter#167]
Could you make it possible for the software to automatically refresh the token key and export all channels at scheduled times? This would require no user input other than scheduling the times for export (e.g. every half an hour).

Additionally, having this automatic export process for multiple token keys would be fantastic.

**Comment by RenanYudi** [comment]
You can schedule exports with the [instructions here](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Scheduling-exports-on-Windows). We just don't have a script that gets channels from a text file yet, but for now, you can copy and paste the command for every channel, and create a new task for each token.

**Comment by Tyrrrz** [comment]
When you say "refresh the token", do you mean automatically getting it from a running Discord process?
