### ISSUE TITLE
Export reactions in when using CSV/Plaintext export types

### ISSUE THREAD

**Issue by cortstar** [Tyrrrz/DiscordChatExporter#168]
Reactions aren't exported in CSV or plaintext format, only in HTML.
Even if it's just the server reaction ID, some indication that reactions were left on a message would be perfect.

**Comment by jbax1899** [comment]
I second this. A count of each reaction would be nice also, maybe something like :ok_hand:[42]

**Comment by cortstar** [comment]
I'd prefer it to be a list of users that reacted, the length of the list would provide the count - like :OK_HAND:[user#0001, user#0002..., user#NNNN].

**Comment by Tyrrrz** [comment]
I think we can't easily get reaction authors due to issue #133 but it's possible to implement it how @jbax1899 suggested.

Do you think this kind of output would be fine?

```
[2019-05-27] cortstar
Reactions aren't exported in CSV or plaintext format, only in HTML.
Even if it's just the server reaction ID, some indication that reactions were left on a message would be perfect.
{Reactions:  :.ok_hand:(42) :thinking: }
```

I'm just worried to not overcomplicate the plain text output so it doesn't look like it's part of the message

**Comment by cortstar** [comment]
Yeah the separate line is enough to distinguish.

Could we get a toggle or something for the reaction authors RE: #133 ?

**Comment by jbax1899** [comment]
I think that format looks great!
