### ISSUE TITLE
TrustFailure exception when trying to export a channel

### ISSUE THREAD

**Issue by stuartlangridge** [Tyrrrz/DiscordChatExporter#169]
I'm running 2.12.1 using Mono on Ubuntu, and when I try to export a channel log, I get a `TrustFailure` backtrace:

```
$ mono DiscordChatExporter.Cli.exe export -c 500566493428318208 -t (my token)
Exporting channel [500566493428318208]... Failed X

Unhandled Exception:
System.Net.WebException: Error: TrustFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x00040] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
...and lots more...
```

"Invalid certificate received from server" seems to be the relevant point; do I need some extra certificate from somewhere, perhaps?

**Comment by Tyrrrz** [comment]
Hi,
My guess is that maybe your certificate store is not up to date? I'm not sure how it's handled in Ubuntu, but on Windows it's updated as part of the general system update.
Maybe this can help? https://serverfault.com/questions/151157/ubuntu-10-04-curl-how-do-i-fix-update-the-ca-bundle

**Comment by stuartlangridge** [comment]
It turns out that Mono's cert store needed updating. I ran `mozroots --import --ask-remove` and then after that DiscordChatExporter worked fine on Ubuntu 18.04!

**Comment by Tyrrrz** [comment]
Great to hear!
