### ISSUE TITLE
Embed links can't be extracted

### ISSUE THREAD

**Issue by wankio** [Tyrrrz/DiscordChatExporter#170]
nsfw https://discord.gg/tmSVXw

Every links posted by BOT always blank, every channels, every BOTs

**Comment by Tyrrrz** [comment]
Are you exporting as PlainText?

**Comment by wankio** [comment]
yes,sure, always plaintext and it can't extract embed post by BOT

**Comment by Tyrrrz** [comment]
Same question as in #165 then
How would you want to see them rendered?

**Comment by wankio** [comment]
just normal link ? because when i'm right click on it, i can copy link, it's like https://cdn.boob.bot/Gifs/1956.gif

**Comment by Tyrrrz** [comment]
Let's move to #165, I posted your suggestion there
