### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by quyleanh** [Tyrrrz/DiscordChatExporter#174]
When I try to export chat of a channel in one year, it always throw this error.
Could you please help me? Thank you very much.

My PC has 8GB RAM and enough disk space for one year chat, I think.

https://imgur.com/XUe6evo

**Comment by WAUthethird** [comment]
Seems you need more RAM. Sorry, but there's not much we can do about that problem. The only solution is to buy more RAM.

**Comment by ealgase** [comment]
Increasing SWAP or closing other programs could also work.

**Comment by quyleanh** [comment]
@WAUthethird @ealgase thank you for your reply. 

I think the problem might not be related to the RAM, it's always free 4GB when I run Exporter program only.
I have tried to run CLI file with mono in my Macbook and it work fine. There is no error, exception... (on Macbook I have run other softwares as well: Chrome, Spotify, Office)

If this error happens for me only, please closed this issue.

**Comment by Tyrrrz** [comment]
@quyleanh does this happen on channels with a lot of messages? Currently DCE loads all messages into memory, which means the more messages you want to export the more memory you need.

I have a long standing desire to rework the exporter so it doesn't store messages in memory but it's not trivial. I have created an issue for it at #177.

**Comment by quyleanh** [comment]
@Tyrrrz I think the answer is yes. I try to export in macOS, it takes about 1GB for HtmlDark, and 132MB for Plaintext.

It would be better if the messages can be exported to output file simultaneously with read process, rather than put in to memory then handle it to the end.

Hope you can find out the best way. Thank you very much for your tools.

**Comment by Tyrrrz** [comment]
Closing in favor of #125 and #177
