### ISSUE TITLE
Export links only

### ISSUE THREAD

**Issue by infominer33** [Tyrrrz/DiscordChatExporter#178]
First let me say I'm super stoked about your app! It's helped me to create this [awesome web-resource](https://infominer.id/SourceCrypto) from my discord server.

I'm curious, because my main interest in the app is extracting valuable links, and in some cases the surrounding few lines are valuable, also.

I don't know how hard it would be for *you* to implement, or if you would have any interest in doing so...

I will figure out some solution, maybe a bit of regex.

but I thought i'd mention my thoughts here... and maybe its even possible, already.

Note: I'm using CLI on Ubuntu (AWESOME!!!)

thanks!

**Comment by Tyrrrz** [comment]
Hi,
Thanks for using my app.
I think if we were to implement some sort of filtering, it should be more flexible to let the user configure whatever they want, possibly in a form of a query string. This is related a bit to #28.
I'm all up for a good solution.

**Comment by infominer33** [comment]
idk how hard it would be to integrate Regex, but it is widely used.

**Comment by infominer33** [comment]
how about:

search for "string" and output "string" plus # of messages above and below

**Comment by Tyrrrz** [comment]
Closing this in favor of #160 which also encompasses this use case.
