### ISSUE TITLE
Export into DevDocs

### ISSUE THREAD

**Issue by CrazyPython** [Tyrrrz/DiscordChatExporter#183]
DevDocs turns collections of HTML files into a searchable, offline-able archive. http://devdocs.io https://github.com/freeCodeCamp/devdocs#scraper

**Comment by Tyrrrz** [comment]
Thank you for your idea.

Most likely not going to implement this because I really don't want to add any more formats as it's getting hard to manage.

My plan is to get #103 done and eventually move people away from CSV export. Stretch goal is to get #1 in, but that would probably be it.
