### ISSUE TITLE
Copied my user authorization token, but it still comes up as unauthorized

### ISSUE THREAD

**Issue by Bubby0n0** [Tyrrrz/DiscordChatExporter#185]

**Comment by Tyrrrz** [comment]
How did you copy your token?

**Comment by Bubby0n0** [comment]
I tried multiple things, did the suggested thing of going to the bottom of application and refreshing, However it kept disappearing after a few seconds once I did that and I couldn't copy and paste it. I took a screenshot of it instead and typed it in but it said unauthorized.

I then tried to go to network --> messages?limit=50 --> Authorization and was unable to copy and paste it also, it came up as (empty) when I right clicked it

But now, I redid it hours later and I could copy and paste and it works now, so this is more a headsup and for posterity

Thank you for your time

**Comment by Tyrrrz** [comment]
You should definitely be able to copy-paste it from both the local storage and headers.
