### ISSUE TITLE
Crash while trying to use the token...

### ISSUE THREAD

**Issue by hehe2** [Tyrrrz/DiscordChatExporter#186]
Here is the output message (then I get the crashed app dialog with the close button).

![image](https://user-images.githubusercontent.com/4698769/59856464-3fa9e180-9377-11e9-9979-bc55c5eb2105.png)

**Comment by Tyrrrz** [comment]
Hi, what version of .NET Framework do you have installed?

**Comment by hehe2** [comment]
Hi,

4.5.2

![image](https://user-images.githubusercontent.com/4698769/59859410-f197dc80-937c-11e9-8c36-b851cd289695.png)

**Comment by Tyrrrz** [comment]
DiscordChatExporter actually requires .NET Framework 4.6 to work
