### ISSUE TITLE
Message ids in html export

### ISSUE THREAD

**Issue by mdiller** [Tyrrrz/DiscordChatExporter#187]
@Tyrrrz It would be useful if the messages dumped to html could include their message ids, so that i could programmatically find one given its id. Currently, messages arent even individually wrapped in a div, but it looks like it would be pretty trivial to add a div that wraps each message, and give that div an `id="message_1234567890"`. To be clear, this wouldn't look any different to someone just looking at the rendered html, and is just for if someone wants to be able to find a message programmatically.

I can implement this and create a pull request for it, I just wanted to check with you first to make sure it sounds good to you.

**Comment by David-Wells99** [comment]
Don't stop at ids, make it possible to add links to them too - having them around the current date would be fine.

**Comment by mdiller** [comment]
As far as I know there isn't a way to add a link to a specific message. We could conceivably add an invite link to a channel, but that would probably be doing more than most users are wanting, and would require extra work on the code and is probably a separate issue.

**Comment by Jefferderp** [comment]
+1 for making individual messages readable programmatically (with divs or otherwise). Currently the best solution is to export to CSV.

**Comment by David-Wells99** [comment]
@mdiller Enabled dev mode lets one see a button to copy permalinks to messages and I think they are formed just by joining the channel URL and the message ID, so it should not be that harder.

**Comment by mdiller** [comment]
@David-Wells99 ah, gotcha. I didn't see that but I just checked and im seeing it now. I'd suggest adding it as a separate issue because it seems like a separate feature that we'd have to figure out where to put and stuff. The original issue i posted doesn't affect the UI at all
