### ISSUE TITLE
Couple errors

### ISSUE THREAD

**Issue by lukmodel** [Tyrrrz/DiscordChatExporter#191]
![obraz](https://user-images.githubusercontent.com/52512099/60628355-69401f80-9df1-11e9-8b66-7164538a44c5.png)
 
Sorry for the polish OS but you can see type of errors. I tried do download text channel from my discord server in html light format everything else blank. I dont really know if it matters but this channel is propably big, way bigger than most of the channels

**Comment by lukmodel** [comment]
forgot to add, downloaded file is blank and app crashes after error

**Comment by Tyrrrz** [comment]
It's probably related to #125.
You can try split the export into partitions or by date ranges to make it smaller.

**Comment by lukmodel** [comment]
yes sir, in smaller parts it works well, can i somehow merge them together later?

**Comment by Tyrrrz** [comment]
If it's in HTML then unfortunatealy no
