### ISSUE TITLE
Launching Issue

### ISSUE THREAD

**Issue by Terragon101** [Tyrrrz/DiscordChatExporter#192]
Hello, I just recently installed your Exporter hoping to export a chat that is closing soon due to no one being around. When I found the token and inputted it into the search bar a error message came up. I'm not much of a code reader but I don't believe it's something on my end. Even with the token whenever I reload disappearing I assume it's just moved it somewhere where I can't see the token. Of course I copy it still before it disappears but for some unknown reason to me this error code appears. Thank you for your time reading this if you are able to help it would be great
![Error](https://user-images.githubusercontent.com/52543120/60680007-9f57c080-9e3e-11e9-87f8-913e69eba444.png)

**Comment by Tyrrrz** [comment]
Same as #186 ?

**Comment by Tyrrrz** [comment]
You may need to install NET framework 4.6.2

**Comment by Terragon101** [comment]
Oh sorry I didn't see the #186 on main issues page just #184 to #187 no inbetween.  Yes it worked swimingly sorry for restating a already answered question. Have a nice day Tyrrrz

**Comment by Tyrrrz** [comment]
No problem, have a great day
