### ISSUE TITLE
GUI closes 5 seconds after it opens; acts very strange

### ISSUE THREAD

**Issue by Toadlover404Git** [Tyrrrz/DiscordChatExporter#194]
I'm not exactly an expert at explaining things like this, but Discord Chat Exporter keeps closing, like, 5 seconds after it opens. After it crashes, I can't delete the folder because File Explorer claims that DiscordChatExporter.exe is still running, yet I can't find it in the Details tab in Task Manager.

**Comment by Tyrrrz** [comment]
Is there any error message?

**Comment by Toadlover404Git** [comment]
No error message whatsoever.

**Comment by Tyrrrz** [comment]
This is unusual. Has it worked at all for you before?

**Comment by Toadlover404Git** [comment]
Yes, it has. Now it just freezes every time it opens, then closes 5 seconds
later.

**Comment by Tyrrrz** [comment]
I really have no idea what that could be

**Comment by Tyrrrz** [comment]
Is this still an issue?

**Comment by Toadlover404Git** [comment]
Nope, it's not. Thanks for asking, though.

**Comment by Tyrrrz** [comment]
Glad to hear
