### ISSUE TITLE
[CLI] Group by category

### ISSUE THREAD

**Issue by infominer33** [Tyrrrz/DiscordChatExporter#195]
The core issue is for users who have large servers, a way to organize the output programmatically, rather than manually, after the export.

Including the category information in the title \ csv are the simplest solutions I can think of.

## Related

https://github.com/Tyrrrz/DiscordChatExporter/issues/77

https://github.com/Tyrrrz/DiscordChatExporter/issues/188

**Comment by Tyrrrz** [comment]
Done
