### ISSUE TITLE
Log user ID as well as username+discriminator in CSV

### ISSUE THREAD

**Issue by 161134050** [Tyrrrz/DiscordChatExporter#197]
I could be wrong, but currently it seems that this software will only log a user by their "username" + discriminator, which is no unique way to identify a user. Eg JohnDoe#5555 in January 2017 could be different to a JohnDoe#5555 in January 2019

I think that in Discord the only real way to uniquely identify a user is by their user ID

**Comment by Tyrrrz** [comment]
If you're exporting in HTML, there's also `data-user-id` attribute.

**Comment by 161134050** [comment]
I didn't realise that - I still think it should be shown in CSV and perhaps plaintext, or even as an option, just for completeness sake :)

**Comment by Tyrrrz** [comment]
With plaintext it's always a challenge to add extra information without ruining readability...

**Comment by 161134050** [comment]
True, but at least let us have it in the CSV, for us data nerds :P
