### ISSUE TITLE
Export fails silently in Windows

### ISSUE THREAD

**Issue by moridinamael** [Tyrrrz/DiscordChatExporter#198]
Using the CLI, I import a docker command of the form:

```docker run --rm tyrrrz/discordchatexporter export -t [TOKEN] -c [CHANNEL] -o [OUTPUT_DIR]```

with valid input for TOKEN, CHANNEL and OUTPUT_DIR.

The CLI gives me the message:
```Exporting channel [CHANNEL]... Completed [?]```

No error is reported, but no file is created at the destination that I give in OUTPUT_DIR. I have tried many different things - different target directories, different channels, I've tried giving a directory or giving a filename as the target. It all behaves the same way.

This would be fine if I could find where the tool was storing the file by default, but I can't find that either.

**Comment by Tyrrrz** [comment]
Given that you're running it in docker, did you mount the output directory to your host machine?

**Comment by Tyrrrz** [comment]
In case you didn't, there's a great wiki page written by @RenanYudi here: https://github.com/Tyrrrz/DiscordChatExporter/wiki/Docker-usage-instructions
