### ISSUE TITLE
Situation about this program

### ISSUE THREAD

**Issue by chibiusagi** [Tyrrrz/DiscordChatExporter#201]
A friend of mine has this program and he told me he could backup my chat, so I gave him the small "code" for him needed to search my servers and do that. There's a small chance that he might keep that "code" for him to use later and stalk my chats or am I wrong? Can I feel safe about this?

**Comment by Tyrrrz** [comment]
If you change your password, it will reset your user token, I believe.

**Comment by chibiusagi** [comment]
Ah thank you, and wow, such a fast reply!

**Comment by Tyrrrz** [comment]
You're welcome :)

**Comment by RenanYudi** [comment]
Just to clarify, a token gives full access to one’s account, not only the chats. Treat it like a password.
