### ISSUE TITLE
Partitioning shouldn't happen in memory

### ISSUE THREAD

**Issue by jman005** [Tyrrrz/DiscordChatExporter#202]
When partitioning servers, rather than outputting partitions immediately after they are finished, partitions are kept in memory until completion of the entire archive. They are then saved into their respective files all at once. This removes the advantage of saving memory, which is a large reason for using partitions in the first place.

**Comment by Tyrrrz** [comment]
Related to #177

**Comment by Tyrrrz** [comment]
Also related to #125

**Comment by Tyrrrz** [comment]
Closed by side-effect of implementing #177.
