### ISSUE TITLE
Images are being lost when being converted to HTML

### ISSUE THREAD

**Issue by Mudacido** [Tyrrrz/DiscordChatExporter#203]
My goal for my moderators had been to use this as a way to right up an incident and then use the DCE to archive it for a condensed easy to search version for future reference.
So, the process goes as follows: An incident is typed up in a empty channel. Part of what is typed up includes screenshots pertaining to the incident. When the process is done The DCE is used and the file created is saved in a separate channel. Once complete the channel used to type the incident up is cleared out so as to have a blank slate for the next use.1
The image below shows how 1 image is still visible, but the other is broken?
![image](https://user-images.githubusercontent.com/54619673/63837958-15aa0800-c942-11e9-93f4-1e5042affcd0.png)
If the broken image is selected the following message is what appears:
![image](https://user-images.githubusercontent.com/54619673/63838116-5dc92a80-c942-11e9-9e56-815395440065.png)

Any help with this would be appreciated. 
Thanks - Mud

**Comment by Tyrrrz** [comment]
It's fair to assume that images that were inside deleted messages will be deleted as well. This might not be instant, or might not affect all images at the same time (the two images could be on different blob storages or exposed through different CDNs, hence the discrepancy).
Until #21 will be implemented, your best bet is to not delete messages from that channel.

**Comment by Tyrrrz** [comment]
I can't be 100% certain about what Discord is doing with images when message gets deleted.
There're no target dates per se, I just work on what I feel like. :)
#21 is fairly far off but it has an acceptable workaround: https://github.com/Tyrrrz/DiscordChatExporter/issues/21#issuecomment-348706551

**Comment by Tyrrrz** [comment]
No problem, and thank you, I hope you have a great day as well.
