### ISSUE TITLE
A task was canceled crash

### ISSUE THREAD

**Issue by Purethunder32** [Tyrrrz/DiscordChatExporter#205]
Hello there. Today I began getting this error partway through exporting channels in my server, around the 60-70% mark, and this happened twice. Now, this happens as soon as I try to access my user token. Thank you for any recommendations or fixes you can provide.
![image](https://user-images.githubusercontent.com/53958549/64300751-0e8b8700-cf4c-11e9-9406-fb54c84a9564.png)

**Comment by Tyrrrz** [comment]
That could mean the HTTP request timed out. Hard to say why, either Discord is having issues or maybe your internet?

**Comment by tntmod54321** [comment]
I having this same issue and I had a large download in the background, restarting the chat export after the file was downloading fixed it for me.

**Comment by ElectroYan** [comment]
Had the same problem and disabling the VPN I'm using helped

**Comment by Tyrrrz** [comment]
Closing as this is not related to DCE directly but rather a local connectivity issue.
