### ISSUE TITLE
wine linux black window

### ISSUE THREAD

**Issue by chwba** [Tyrrrz/DiscordChatExporter#209]
I followed the linux wine installation guide and rebooted then when i start it with the command give in the wiki i see a black screen of the window only and the terminal is spammed with `0036:fixme:win:EnumDisplayDevicesW ((null),0,0x641f914,0x00000000), stub!`

**Comment by RenanYudi** [comment]
DCE on Wine is reeeally buggy. But I tested the instructions more than once and it worked every time.
Try reinstalling everything and see if it works.
Not sure if @Tyrrrz could do anything here.

**Comment by chwba** [comment]
Alright I will try btw very nice work i used it on windows already its awesome

**Comment by chwba** [comment]
Oh am one question I would have how do I remove all the wine stuff I installed?

**Comment by RenanYudi** [comment]
For a quick reinstall delete the wine folder that probably is at your user home and run
`sudo apt-get --purge remove winehq-stable`
[To do a **complete** uninstall follow this](https://askubuntu.com/questions/15551/how-to-remove-wine-completely)

**Comment by chwba** [comment]
perfect, thanks

**Comment by chwba** [comment]
Ok, I tried the complete remove and reinstalled, same result. I had the feeling while reinstalling that it didnt remove everything though, especially the .net stuff, because it asked one time if i wanted to repair it.

**Comment by RenanYudi** [comment]
Wine installs stuff (net included) in /home/user/.wine by default, winetricks has its own prefix I think, but the WINEPREFIX env changes everything to /home/user/wine, deleting this folder should’ve “uninstalled” .NET 🤔. 
Since it didn’t work, let’s wait for @Tyrrrz. :-(

**Comment by RenanYudi** [comment]
By the way, which OS are you using? Is it a Raspberry Pi?

**Comment by chwba** [comment]
debian 10 (buster) thx for the hint ill look for the remainings and reinstall everything again

**Comment by Tyrrrz** [comment]
I can't really do much here as I don't even use Linux :(
The GUI version was never meant to run on non-Windows OS because it uses a Windows-specific graphics library for rendering UI. Generally, it's recommended to use the CLI version on other platforms, as it's crossplatform and can run via Mono/.NET Core/Docker.

**Comment by chwba** [comment]
yeah ill just use it on windows then. i cleaned all the wine stuff and tried running it again still getting the black screen.

![image](https://user-images.githubusercontent.com/22568014/65195399-716a3b80-da7f-11e9-94a7-12747cb49ca8.png)
