### ISSUE TITLE
Could not load type of field 'DiscordChatExporter.Cli.Program+<>c__DisplayClass1_0:container'

### ISSUE THREAD

**Issue by Kgriffin314** [Tyrrrz/DiscordChatExporter#210]
Everytime I try to export I get this
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'DiscordChatExporter.Cli.Program+<>c__DisplayClass1_0:container' (0) due to: Could not load file or assembly 'Stylet, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at DiscordChatExporter.Cli.Program.<Main> (System.String[] args) [0x00000] in <6ba85239f0c84d89b58b832da6f17478>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'DiscordChatExporter.Cli.Program+<>c__DisplayClass1_0:container' (0) due to: Could not load file or assembly 'Stylet, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at DiscordChatExporter.Cli.Program.<Main> (System.String[] args) [0x00000] in <6ba85239f0c84d89b58b832da6f17478>:0 

And I am unable to install Stylet because I use linux , I tried Nuget, I got nothing.

**Comment by Kgriffin314** [comment]
Please help

**Comment by Tyrrrz** [comment]
Fixed now I assume?

**Comment by Kgriffin314** [comment]
No I accidently closed this issue , I would gladly appreciate any help you can offer. thank you

**Comment by Tyrrrz** [comment]
Have you unpacked the contents of the downloaded zip archive to a separate directory? Can you make a screenshot of the list of files in e.g. File Explorer?

**Comment by Kgriffin314** [comment]
This is in linux though, but I did unpack the contents to a separate directory

**Comment by Tyrrrz** [comment]
Ah, sorry, I missed that it was on Linux.
You did follow the instructions [here](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Linux-usage-instructions), correct?

**Comment by Kgriffin314** [comment]
Yes I did exactly as what the wiki shown but as soon as I enter my token and channel ID and export I get this error;
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'DiscordChatExporter.Cli.Program+<>c__DisplayClass1_0:container' (0) due to: Could not load file or assembly 'Stylet, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at DiscordChatExporter.Cli.Program.<Main> (System.String[] args) [0x00000] in <6ba85239f0c84d89b58b832da6f17478>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'DiscordChatExporter.Cli.Program+<>c__DisplayClass1_0:container' (0) due to: Could not load file or assembly 'Stylet, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at DiscordChatExporter.Cli.Program.<Main> (System.String[] args) [0x00000] in <6ba85239f0c84d89b58b832da6f17478>:0 
[Quick Export] Something went wrong.
Exiting...

**Comment by Kgriffin314** [comment]
The problem I am encountering is that Stylet isn't compatible with linux, that is something designed for windows systems and I am stuck, i tried installing the Stylet package using nuget-cli for linux but I cant install it.

**Comment by Tyrrrz** [comment]
Is it possible for you to run the CLI in Docker?

**Comment by Kgriffin314** [comment]
I haven't tried that but now I will.

**Comment by Tyrrrz** [comment]
I would recommend using Docker if it's possible because all the platform-specific dependencies are already taken care of. Just follow [the guide here](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Docker-usage-instructions) to make sure you mount the output directory so that it can write the export.

**Comment by Kgriffin314** [comment]
I am installing it right now, I will let you know if it works. thank you

**Comment by RenanYudi** [comment]
I get the same error when the `Stylet.dll` is missing. Perhaps unzip failed.

**Comment by Kgriffin314** [comment]
Ok I used Docker and it appeared to be successful, I just got to find where the file was exported to.

**Comment by RenanYudi** [comment]
https://github.com/Tyrrrz/DiscordChatExporter/wiki/Docker-usage-instructions

**Comment by RenanYudi** [comment]
https://github.com/Tyrrrz/DiscordChatExporter/wiki/Docker-usage-instructions#file-output

**Comment by Kgriffin314** [comment]
Ok thanks.

**Comment by Tyrrrz** [comment]
You can use
```$ docker run --rm -v PATH_TO_OUTPUT_DIRECTORY_ON_YOUR_MACHINE:/app/out tyrrrz/discordchatexporter export -t TOKEN -c CHANNEL```

**Comment by Kgriffin314** [comment]
It functions perfectly, Thank you all for the help and support. I appreciate it!

**Comment by Tyrrrz** [comment]
Glad it worked :)
