### ISSUE TITLE
Add TOS warning in the readme/in app "tutorial"

### ISSUE THREAD

**Issue by edo9300** [Tyrrrz/DiscordChatExporter#211]
I used this tool some time ago to export some chats, and today i recieved a mail from the discord team issuing a warning for having violated the TOS. I was pretty amazed, as the message said as reason 

> Automating normal user accounts ("self-bots") outside of the OAuth2/bot API is forbidden, and can result in an account termination if found.

 so i thought what could have been and i realized this tool could have done something that could have been related to the bot api. And my worries were confirmed by this comment in another issue https://github.com/Tyrrrz/DiscordChatExporter/issues/171#issuecomment-489333889.
So please, for the sake of ignare users, put a warning saying that using the user token is a bad idea as it's plainly breaking the TOS, and they should use a bot token instead.

**Comment by Tyrrrz** [comment]
Thank you for reporting this, as it's the first case of someone getting warned that I know of.
Adding a warning seems like a good idea.
