### ISSUE TITLE
Batch exporting/crash if you select multiple chats at once

### ISSUE THREAD

**Issue by tntmod54321** [Tyrrrz/DiscordChatExporter#212]
A batch export function would be really helpful especially if you could have it save the last selected chats or be able to save presets, also you can select multiple chats at once by shift clicking or ctrl clicking them, which causes the app to crash if you try to export them, I'm not a programmer but judging by the list of libraries in the readme, one of the libraries supports shift-clicking multiple items and wasn't accounted for in the chat exporting portion of the code.

**Comment by Tyrrrz** [comment]
You can export multiple chats at once as long as they are from the same guild.
For recurring batch exports you may want to use cron jobs or similar https://github.com/Tyrrrz/DiscordChatExporter/wiki/Scheduling-exports-on-Windows

**Comment by tntmod54321** [comment]
Oh ok, I only use the exporter for DMs, I wasn't aware there was a CLI version of discord chat exporter, that's pretty handy, that'll be pretty handy if I can use batch files with it.

**Comment by Tyrrrz** [comment]
Have you been able to make a multi-channel export?

**Comment by tntmod54321** [comment]
I haven't tried yet as I only export my chats like twice a month

**Comment by Tyrrrz** [comment]
Ok, please re-open the issue if you encounter a problem doing it
