### ISSUE TITLE
Program not running

### ISSUE THREAD

**Issue by Obamium** [Tyrrrz/DiscordChatExporter#213]
Everytime i try to run the chat exporter it stops responding and then closes any help?

**Comment by Tyrrrz** [comment]
It's hard to say without any more details. Does [this version](https://github.com/Tyrrrz/DiscordChatExporter/suites/298988131/artifacts/260397) work?

You will have to install .NET Core 3.0 runtime.

**Comment by Obamium** [comment]
Hello! sorry for not giving you enough details about my error as i didn't have much to work with other than giving my pc details which i did not want to i will try it out and if possible make a more detailed report thank you for your reply!

**Comment by Tyrrrz** [comment]
Closing this now, please re-open if you still have issues.
Also, maybe you have similar issue to #232 or #234
