### ISSUE TITLE
Export entire server/group

### ISSUE THREAD

**Issue by calderJamNet** [Tyrrrz/DiscordChatExporter#214]
this would be VERY convenient if it could be incorporated.

I'd say there would be 2 general ways to do this:

1. export results in multiple files

2. export results in 1 single file with additional column (for csv, not sure how this would work with html...) to identify the source channel.

i guess option 1 makes the most sense as it would work with all file types, and the file sizes would be more manageable for large exports.

**Comment by calderJamNet** [comment]
i tried to add an "enhancement" label but i guess i don't have permission to do that.

**Comment by Tyrrrz** [comment]
Have you tried multi-selecting with ctrl/shift?

**Comment by calderJamNet** [comment]
sorry @Tyrrrz i'm not sure what you mean, is this something that must be done in the UI? I'm using the CLI, (side question, is the UI available for mac os? i couldn't find instructions for how to set that up on mac)

**Comment by Tyrrrz** [comment]
Ah, you didn't mention you were using CLI so I assumed GUI. In CLI there are also a command to export an entire guild. Try `--help` option to see the list of available commands.

**Comment by RenanYudi** [comment]
GUI is Windows-only
The command to export is [exportguild](https://github.com/RenanYudi/DiscordChatExporterTest/wiki/GUI,-CLI-and-Formats-explained#exportguild)
