### ISSUE TITLE
Is it possible to get seconds or even milliseconds on the datetime field?

### ISSUE THREAD

**Issue by calderJamNet** [Tyrrrz/DiscordChatExporter#215]
currently it only displays the date, hours, and minutes

**Comment by RenanYudi** [comment]
[Yes, in CLI](https://github.com/RenanYudi/DiscordChatExporterTest/wiki/GUI,-CLI-and-Formats-explained#date-ranges)

**Comment by calderJamNet** [comment]
thanks!
