### ISSUE TITLE
Problem after keying in token

### ISSUE THREAD

**Issue by penguinsoba** [Tyrrrz/DiscordChatExporter#216]
![image](https://user-images.githubusercontent.com/56390590/66559757-e3223a80-eb90-11e9-89ea-9b2402c27e2e.png)

I keep seeing this after I type in my token. Also, I've tried installing a lower version (2.10) other than using 2.14 and 2.15 but I still see the same thing. I've also tried running it with administrator too. Any way I can resolve this?
Ps: if it might help, I'm using Windows 7

**Comment by RenanYudi** [comment]
[Is .NET 4.6 or newer installed?](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Troubleshooting#it-crashesfails)

**Comment by penguinsoba** [comment]
Thanks for the speedy reply!
Installed .NET 4.8, solved everything! Thanks
Also, I read FAQ and realized there was a solution there too sorry bout that

**Comment by RenanYudi** [comment]
No problem. Glad to help :-)
