### ISSUE TITLE
TXT Exporting Failure

### ISSUE THREAD

**Issue by CyberneticSquid** [Tyrrrz/DiscordChatExporter#217]
Using `-f txt` when exporting (MacOS, CLI with Mono) causes the program to return the error:
`Can't convert value [txt] to type [DiscordChatExporter.Core.Models.ExportFormat].`
The error also occurs with `-f "txt"`. The command was structured perfectly, and worked when the -f argument was removed.

**Comment by Tyrrrz** [comment]
You should specify `-f PlainText` instead

**Comment by CyberneticSquid** [comment]
Probably should change the documentation then. https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#changing-the-format uses `-f txt`

**Comment by Tyrrrz** [comment]
Updated
