### ISSUE TITLE
unable to save any export, File not found

### ISSUE THREAD

**Issue by RenewedRS** [Tyrrrz/DiscordChatExporter#218]
No matter which file type I choose to save as, I get the same error as if I'm trying to open a file?

https://i.imgur.com/Wf2AzDO.png

What am I doing wrong?

edit: I've tried using the discord client, multiple browsers with different tokens and I get the same result. File not found.

**Comment by Tyrrrz** [comment]
This is... interesting.
Can you try a different file name or directory? Try saving it on the desktop as `1.html`.

**Comment by RenewedRS** [comment]
It turned out to be that I had Windows Defender Controlled Folder Access turned on, which was blocking changes to folders. Sorry to trouble you!

**Comment by Tyrrrz** [comment]
Good that you got it working!
