### ISSUE TITLE
Unix timestamp support

### ISSUE THREAD

**Issue by fynnay** [Tyrrrz/DiscordChatExporter#220]
It would be amazing to have the option to use unix timestamps. This would make it much easier to migrate channel data to slack via csv import.

**Comment by Jefferderp** [comment]
I would also enjoy this just for posterity's sake

**Comment by fynnay** [comment]
I _really_ wanted to get the data into slack but am not good with C#. So I wrote a python script to do the unix timestamp and also convert the csv data that DiscordChatExporter outputs to Slack's csv import format. For anyone who is interested: [here you go](https://gitlab.com/pyfynn/discordToSlack/tree/master) ✌️

**Comment by Tyrrrz** [comment]
Would #103 help solve your issue? Assuming the dates are stored in ISO format.

**Comment by Tyrrrz** [comment]
Also, if UTC date format is good enough for you, you can set custom date format in settings to `u` or `U` (according to [this](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings)).

**Comment by fynnay** [comment]
Closing #103 wouldn't resolve this particular issue. JSON would definitely be easier to process but I didn't have any problems reading the CSV file format in particular. The challenge was simply to convert the .NET timestamp to a unix timestamp (a single integer), because it's what the Slack CSV import requires.

In Python this was luckily quite easy to do. when exporting the CSV using DiscordChatExporter I left the time format at the default 
```python
date = row[1] # the original date entry from the CSV file from DiscordChatExporter
convDate = datetime.datetime.strptime(date, "%d-%b-%y %I:%M %p") # 06-Dec-18 08:51 AM
unixDate = int(convDate.replace(tzinfo=datetime.timezone.utc).timestamp())
```

**Comment by Tyrrrz** [comment]
This could be implemented by using a custom format provider that would accept and handle additional date formats, such as `unix` for unix time.
