### ISSUE TITLE
Method for exporting last X days of log?

### ISSUE THREAD

**Issue by JustinCEO** [Tyrrrz/DiscordChatExporter#223]
Hi, I love the program and use it regularly for some chat rooms i administrate. I would like the ability to export the last X days of chat, as opposed to exporting stuff from a specific date. That way I could automatically run a script every day to export a log with, say, the last week of chat messages. Is this possible to do with the existing program? If so, how? If not, it'd be nice to add. Thank you.

**Comment by Tyrrrz** [comment]
Currently not possible to do as you described but I imagine it would easy if you're running it from a script. Simply get the date that was X days ago and use that as `--after` parameter.
