### ISSUE TITLE
Include channel category in export metadata

### ISSUE THREAD

**Issue by dcrime** [Tyrrrz/DiscordChatExporter#226]
While using a user account in the client it states what's a group and what's a dm however in the export it counts it all as dms and the only way I was able to differentiate them was:

Text/Html/CSV
1. looking at the file name and how many people are listen in it (if any)
2. looking if anyone was added or left
3. Counting how many usernames are in the chat

Text/Html

4. Looking at how many people are listed in the channel (if any)

Anyway my point is it would be nice if it would notify the user that it's a group and not just a dm
If I'm wrong and it does say it somewhere I'm sorry for wasting your time
Thanks in advance

**Comment by Tyrrrz** [comment]
Implemented.
