### ISSUE TITLE
Functional token receives the following error

### ISSUE THREAD

**Issue by tarek-j-a** [Tyrrrz/DiscordChatExporter#227]
The token is valid, ive tested myself through a custom application, however when i try to export chat i receive the following error:
Other tokens work and i am able to export, just this specific user token fails for some reason.
![image](https://user-images.githubusercontent.com/54114094/68059952-d054de80-fcd4-11e9-9552-bc71a949cfc0.png)

**Comment by Tyrrrz** [comment]
Does this happen on all chats or only on some specific channels?
