### ISSUE TITLE
Way to specify numbering of partitioned messages?

### ISSUE THREAD

**Issue by JustinCEO** [Tyrrrz/DiscordChatExporter#229]
Is there a build in way to specify how partitioned exported logs are numbered?

I have chat logs that are ```Chat name - chat id -- 1 of 4``` and I'd like to drop the ```of 4``` part so that they just read ```Chat name - chat id -- 1```.

**Comment by Tyrrrz** [comment]
Not currently, no

**Comment by Tyrrrz** [comment]
It's now slightly different in the new version, due to the fact that the number of partitions isn't known ahead of time. Check it out.

**Comment by Tyrrrz** [comment]
Is this still relevant?
