### ISSUE TITLE
Run from command line

### ISSUE THREAD

**Issue by MuffinMedic** [Tyrrrz/DiscordChatExporter#23]
Is there an option to run this completely from the command line with a GUI? Something to the effect of `DiscordChatExporter.exe --token=<token> --channel=<channel-id> --theme=<theme> --datetime=<format>`. It would be very helpful for automating the process.

I'm essentially trying to run this is as a cron job on a headless server.

Thank you!

**Comment by Tyrrrz** [comment]
Version 1.0 was actually purely CLI, but 80% of users were having problems using it so I turned it into a GUI application.

**Comment by MuffinMedic** [comment]
Thanks! Would there be any way to get the CLI features back?

**Comment by Tyrrrz** [comment]
It's possible and shouldn't be hard to do if you extract the business logic into a different class library and make a console project that uses it. DCE is currently pretty far down on my priority list, so it will take a while until I get to it myself, so you're welcome to do it. :)

**Comment by 2E0PGS** [comment]
I'm guessing this project wont run under mono? If it does than CLI support would be more useful since Linux servers can run this as mentioned via cron. Otherwise it's Windows server and task scheduler. Eitherway +1 for command line support.

**Comment by 2E0PGS** [comment]
Brilliant will try it later!
