### ISSUE TITLE
Is there logging real-time or by request only? 

### ISSUE THREAD

**Issue by thatrelevantperson** [Tyrrrz/DiscordChatExporter#231]
Like when you download a log file, will it show deleted messages as well in that channel?

**Comment by thatrelevantperson** [comment]
I know this would take up a lot of space for logging every time on automated internals, but it could be cached and then deleted everyday at around like midnight.

**Comment by Tyrrrz** [comment]
Deleted messages won't show up.
It's "by request" at its core but you should look into export scheduling on the [wiki](https://github.com/Tyrrrz/DiscordChatExporter/wiki).
