### ISSUE TITLE
Discord please

### ISSUE THREAD

**Issue by Red09discord** [Tyrrrz/DiscordChatExporter#232]
I need your discord please how to install it? 
![image](https://user-images.githubusercontent.com/54461947/68992375-881aec00-0890-11ea-9c51-bcf15c6d63d3.png) see?

**Comment by RenanYudi** [comment]
[Is .NET 4.6 or newer installed?](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Troubleshooting#it-crashesfails)

**Comment by Tyrrrz** [comment]
Closing as there's no feedback from the user.
Please re-open if the suggested fix didn't help.
