### ISSUE TITLE
"Error while copying content to a stream."?

### ISSUE THREAD

**Issue by Shadow9000low** [Tyrrrz/DiscordChatExporter#234]
![Capture](https://user-images.githubusercontent.com/57967767/69193433-abde6c00-0af4-11ea-8f08-f00073cf08cc.PNG)

So, this happens after I enter my token.

**Comment by Tyrrrz** [comment]
Sounds like an SSL issue. Are you getting it consistently? Can you open `discordapp.com` in browser?

**Comment by Shadow9000low** [comment]
Yes, and I can open discordapp.com in my browser.

**Comment by Tyrrrz** [comment]
Seems explained/fixed in #235
