### ISSUE TITLE
Suddenly getting errors and program crashes

### ISSUE THREAD

**Issue by LonerPrime** [Tyrrrz/DiscordChatExporter#235]
Hi,
    Foremost, thank you for this handy little program you wrote. It has saved me a lot of headache managing my old server. Coming to the issue at hand, I downloaded the latest version of this program at the start of this month. At the time, I followed the instructions to the letter and everything went smoothly as I was able to backup four channels without a hitch. Then today, I fired up the program again, but I started getting stream errors whenever I tried to download a channel:
![69193433-abde6c00-0af4-11ea-8f08-f00073cf08cc](https://user-images.githubusercontent.com/58160375/69516035-7dd6ad00-0f76-11ea-8e51-8ce6dcbbd067.PNG)

I did basic troubleshooting first. Downloaded the whole program again and tried to run it fresh. This time, it got worse as I started getting the above error right at Token authentication. The program won't even display channel list.

Finally I searched through the "Issues" database and found you linking a few topics that described a similar theme but the original posters stopped short of describing the issue in detail. In that I found you mentioning trying [this version](https://github.com/Tyrrrz/DiscordChatExporter/suites/298988131/artifacts/260397) and installing [.NET Core 3.0](https://dotnet.microsoft.com/download/dotnet-core/3.0) to make it work. I'm happy to the report, this version worked perfectly.

Sadly I'm not sure why the above error is popping up, but I hope my post helps you figure out what's going on.

Kind Regards,
LonerPrime

**Comment by Tyrrrz** [comment]
Good thing it's fixed. The version built against .NET Core 3 will become stable soon.

**Comment by Tyrrrz** [comment]
Closing in the advent of tomorrow's release
