### ISSUE TITLE
Exported embeds miss the embed content in .csv files

### ISSUE THREAD

**Issue by Mattis6666** [Tyrrrz/DiscordChatExporter#237]
I am trying to export embeds with author, thumbnail, multiple fields and reactions to .csv. Everything is working flawlessly except the message content, it just isn't included in the exported file. [Here's the embed](https://prnt.sc/q2riux) and [this is what the tool exports](https://prnt.sc/q2riab). The message content is included in all other formats.

**Comment by Tyrrrz** [comment]
This is related to #225. There were multiple posts like this and ultimately it was impossible to come up with a viable way to render embeds to CSV due to their varying and rich nature.
In the future, I plan to drop CSV entirely in favor of JSON (#103).

**Comment by Mattis6666** [comment]
Ah, that's a shame! Thanks for the quick response and sorry for not looking this issue up before asking, I only checked the recent issues. Great tool anyway, good work!

**Comment by Tyrrrz** [comment]
No problem Glad you like it.
