### ISSUE TITLE
CSV Export does not support Russian language (UTF-8-SIG)

### ISSUE THREAD

**Issue by Wrascon** [Tyrrrz/DiscordChatExporter#238]
I did the same with the txt text format and it worked with the Cyrillic alphabet, but I need to display messages line by line, and only CSV has this option. I think it's UTF-8-SIG (with BOM) encoding. Please correct, thanks in advance.
![Example](https://cdn.discordapp.com/attachments/574957968769155073/650388604626927638/unknown.png)

**Comment by Tyrrrz** [comment]
Hi, I just looked into this issue.
It seems that MS Excel incorrectly recognizes the underlying text encoding. [As you can see](https://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically) it's a fairly popular issue. The gist of it is that you need to force it to treat the file as UTF8.
If you have/use Libre Office, you can select the correct encoding when you open the file:
![image](https://user-images.githubusercontent.com/1935960/69916516-7f1b4480-1464-11ea-9b89-a317cc8ec851.png)

**Comment by Tyrrrz** [comment]
[This answer might help](https://stackoverflow.com/a/23366350/2205454)

**Comment by TheSunIsADeadlyLaser** [comment]
this aged like milk, coming to think of it
