### ISSUE TITLE
Add support for new News Channels

### ISSUE THREAD

**Issue by Toby4213** [Tyrrrz/DiscordChatExporter#240]
Discord implemented a new channel type which allows users to add the news from that server to you own.
For example the beatsaber modding server([https://discord.gg/beatsabermods](https://discord.gg/beatsabermods)) as 4 news channels which do not show up in the Exporter.

**Comment by Tyrrrz** [comment]
Already done, will be in the next release.
Duplicate of #222

**Comment by Toby4213** [comment]
Sorry, forgot to check closed issues, thanks.
