### ISSUE TITLE
System.Net.HttpRequestException

### ISSUE THREAD

**Issue by AtlosPrime** [Tyrrrz/DiscordChatExporter#242]
Hello, I just have this error when I logon with my token on the 2.16 version. I already had this error on 2.15 when I tried to archive one dm

**Comment by AtlosPrime** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/50601202/70395628-ec008280-1a00-11ea-80d0-35cb1911f1e1.jpg)

**Comment by AtlosPrime** [comment]
I was hoping that maybe this will be fixed in the new version, but it's worse now. I guess it's a problem with my pc configuration, but I can't guess what is wrong. Thank you for your awesome application (Even if don't work for me now lol) and thank you again if you help me

**Comment by Tyrrrz** [comment]
Hi, this looks like the same issue as #235 but @LonerPrime said the new version fixed it for them.

My only guess is that maybe your certificate store is out of date. Which version of Windows do you have and which build?

**Comment by AtlosPrime** [comment]
I'm on Enterprise build 1903

And I noticed that if I logon with another token/account, it works, but not mine, strange

**Comment by AtlosPrime** [comment]
*Win 10

**Comment by Tyrrrz** [comment]
Try changing the password on your account and try again. Changing password should reset your token.

**Comment by AtlosPrime** [comment]
I changed my token, and put it on the app, and same error happened

**Comment by AtlosPrime** [comment]
Well, I tried on a virtual machine, same windows enterprise 1903, with the same token, and it worked. So, guess it's something in my pc that break everything, But I don't know what.

**Comment by Tyrrrz** [comment]
I'm not sure what to suggest here, I don't know what causes this error.

**Comment by AtlosPrime** [comment]
I updated my certificates, and it still doesn't work, so... too bad. Well, thanks you a lot for trying to help me^^

**Comment by Tyrrrz** [comment]
Do you have any sort of proxy or anything else intercepting traffic, by any chance?

**Comment by AtlosPrime** [comment]
No, I'm on a residential network, no firewall, no restriction, no port forwarded, etc

**Comment by AtlosPrime** [comment]
And it work, when it's for others tokens on my pc, but when I insert mine, it crashes.

**Comment by Tyrrrz** [comment]
I'm out of ideas :(
Googling around your error yields scarce but completely different results.
It's very weird that it both works on other tokens and with your token on a virtual machine.

**Comment by AtlosPrime** [comment]
Yeah...
I tested something,
With account #2 (A token who work)  I can archive anything, but when I archive the dm with the account #1 (Mine who doesn't work), it crashes as well

Like my account is cursed or something

**Comment by AtlosPrime** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/50601202/70396885-469fdb80-1a0d-11ea-9d6e-871c0e661c06.jpg)

And it's almost the same error
At least the type

**Comment by AtlosPrime** [comment]
I don't know if this can help

**Comment by AtlosPrime** [comment]
I updated to 1909, and it still the same btw

**Comment by Tyrrrz** [comment]
Is this reproducible on latest version?
