### ISSUE TITLE
Latest release appears to be built for 64 bit rather than 32 bit

### ISSUE THREAD

**Issue by MeatPony** [Tyrrrz/DiscordChatExporter#243]
And the release page hints that it is supposed to work for 32 bit, noting the link to the 32 bit .net 3.1 installer.

**Comment by Tyrrrz** [comment]
Are you trying to run it on a 32bit OS and having issues?

**Comment by despair86** [comment]
yes

**Comment by Tyrrrz** [comment]
Hmmm. The binary should run in 32 bit mode on x86. Can you give me a screenshot of an error if there's any? Or an entry in Windows event log?

**Comment by PBJF** [comment]
![why are you looking for alt text?](https://user-images.githubusercontent.com/42769969/71769406-87feaa80-2f29-11ea-8b3e-76d47fa09a97.PNG)

**Comment by Tyrrrz** [comment]
Can you guys please check if you can run DiscordChatExporter.Cli or if it gives the same error? That would help me narrow down the problem.

**Comment by Tyrrrz** [comment]
Also can you try launching it from a command line like so instead of the .exe file?

```cmd
dotnet DiscordChatExporter.dll
```

**Comment by MeatPony** [comment]
Sorry i recently upgraded laptops since Christmas and no longer am having this issue, however it appears other 32 bit users have had the same issue, looking at the replies.

**Comment by Tyrrrz** [comment]
Yeah it seems there are problems with 32bit systems, but I wasn't able to find a solution. If anyone has ideas, please ping me. It *should* work from what I've read at least

**Comment by fattestpanda726271343274438476327362718** [comment]
are you compiling this on a x64 or x86 system?

**Comment by Tyrrrz** [comment]
For future reference for myself: https://docs.microsoft.com/en-us/dotnet/core/deploying/

**Comment by Tyrrrz** [comment]
Nevermind, that didn't fix the problem. Looks like Microsoft offers no way to have an app that runs both on 64bit and 32bit via the same executable, like it did with .NET Framework.

The workaround for 32bit systems is to run the app via command line, `dotnet DiscordChatExporter.dll`.
