### ISSUE TITLE
[TXT] More faithful representation of Block Quotes

### ISSUE THREAD

**Issue by JustinCEO** [Tyrrrz/DiscordChatExporter#253]
H,l I'm having an issue with the plain text output format.

On Discord you can use `>>>` to indicate a block quote, and then all the text after that will have a quote level applied, though attachments and embeds will not have a quote level.

So e.g. if you write something like this in Discord:

```
Line1, above block quote
>>> Line2, in block quote
and a link https://constitutionus.com
```

It will render as something like this within Discord:

Line1, above block quote
> Line2, in block quote
> and a link https://constitutionus.com

...with an embedded website preview following the quote if you have those set to display

But the plain text output from DiscordChatExporter looks like this:

```
Line1, above block quote
>>> Line2, in block quote
and a link https://constitutionus.com

{Embed}
https://constitutionus.com
Constitution of the United States - We the People
A highly accessible, easy to use online version of the U. S. Constitution with the full text including the Bill of Rights and the rest of the Amendments includes both sequential and subject indexes.
http://constitutionus.com/we_the_people_fb.jpg
```

What I would prefer is if the output is was something like this:

```
Line1, above block quote
> Line2, in block quote
> and a link https://constitutionus.com

{Embed}
https://constitutionus.com
Constitution of the United States - We the People
A highly accessible, easy to use online version of the U. S. Constitution with the full text including the Bill of Rights and the rest of the Amendments includes both sequential and subject indexes.
http://constitutionus.com/we_the_people_fb.jpg
```

(and actually I'd like to be able to suppress embedded website previews from the text log, but that's a separate request :) )

Now interestingly, DiscordChatExporter can output what I want, *if* I have "Preview emojis, mentions, and markdown syntax as you type" beta feature turned on Discord. Here's an example of plain text output with the beta Preview stuff turned on, followed by explanation:

```[29-Dec-19 10:02 PM] JustinCEO#3132
Line1, above block quote
> Line2, made a block quote with markdown preview off
> Line 3, hit shift then then enter, then started typing this line, then enabled markdown preview before sending
```

So to be clear, on Line2 in the above, I had actually input `>>>` with Markdown Preview off, then turned it on before sending my message. And the plain text output I got was reasonable and what I'd like.

But:
1. I'm not a big fan of the beta preview features overall
2. Everyone else doing block quotes in a chat would have to use beta preview features for a whole chat log to not have the problem I'm discussing
3. There would still be the issue of past messages having suboptimal quoting

Some context for why I care:

I'm on a server that is really into detailed discussions, heavy quoting, and also posting snippets of Discord logs to markdown-supporting blogs. It'd be easier to do this if the output coming out of DiscordChatExporter were refined in the way I discuss above. This change would avoid the problem posting a snippet of a Discord log to a blog and of e.g. the first paragraph in a multiparagraph block quote being rendered as having three levels of quotes, and the rest having no quoting.

So far I've just been adjusting my chat logs manually, but since I noticed that in Markdown preview mode, Discord apparently has the ability to output the format I want, *even when a Discord message "in draft" was composed with the `>>>` to indicate a block quote`, I figured perhaps this change wouldn't be too hard to implement from a technical perspective.

Thanks for all the work on this program, I make serious use of it :)

**Comment by qaisjp** [comment]
> On Discord you can use `>>>` to indicate a block quote, and then all the text after that will have a quote level applied, though attachments and embeds will not have a quote level.

Btw you only really need one `>`, even though `>>>` is parsed as a single `>`

**Comment by Tyrrrz** [comment]
The TXT output (and every other except HTML) intentionally doesn't render markdown in any specific way, so that the text appears exactly as you typed it on the client. The only exception is mentions, which get parsed and resolved so that the user's/role's/channel's name is shown instead of an ID.

Closing as this is out of scope.
