### ISSUE TITLE
Suppressing embeds and reactions

### ISSUE THREAD

**Issue by JustinCEO** [Tyrrrz/DiscordChatExporter#254]
Is it possible to suppress things like Embedded website previews and Reactions from showing up in the plain text log, or is that perhaps a feature that could be added?
So eg for website previews you'd just have the bare link someone sent instead of the preview, and for reactions you'd just have nothing in the plain text.

Note that for my purposes I'd definitely to keep the discord image link generated when you attach an image. So I wouldn't want to suppress all content outside the main body of the message, just some selectively.

**Comment by Tyrrrz** [comment]
Hi.

Unfortunately there is no way to reliably tell if an embed is coming from open graph or not, they all look the same. Granted, it's possible to put in place some rules, e.g. URLs that don't start with `discordapp.com/`, embeds that are posted by non-bots and not via webhooks, etc etc, but it's volatile.

Image attachments are separate from embeds.

**Comment by pokeball99** [comment]
any potential update on the possibility of this?

**Comment by Tyrrrz** [comment]
Closed as out of scope
