### ISSUE TITLE
App will no longer launch

### ISSUE THREAD

**Issue by sathanas65** [Tyrrrz/DiscordChatExporter#255]
After error when exporting large channel, the app will no longer launch at all. Even after full restart. Redownloaded app in case it was corrupted. Ran as admin. Fresh Windows install. Disable antivirus. No luck. Running 64 bit Windows 10 v1903.

**Comment by sathanas65** [comment]
Reinstalled .net core runtime and now it works.

**Comment by Tyrrrz** [comment]
Glad to see it solved
