### ISSUE TITLE
Feature to download discord attachments (for offline viewing)

### ISSUE THREAD

**Issue by TempleOfHorus** [Tyrrrz/DiscordChatExporter#259]
Have feature which would allow us to download all discord attachments (files - images, videos, zip, etc..) in channel.

**Comment by TempleOfHorus** [comment]
Duplicate

**Comment by RenanYudi** [comment]
I think you might be referring to the recent replies on #21. Otherwise, for now, you can [save attachments by doing this](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Storing-HTML-locally)

**Comment by TempleOfHorus** [comment]
Thank you for tip @RenanYudi
