### ISSUE TITLE
When a channel is removed, are the attachments in the exported logs removed as well?

### ISSUE THREAD

**Issue by Elikill58** [Tyrrrz/DiscordChatExporter#260]
Hello,

Firstly, i want to tell you: THANKS YOU.
Your creation really help me, and that's very cool !

I just want to know if when we remove a discord channel, all file from this channel are removed ?
Maybe you don't have the reply, i understand !

Thanks you.

**Comment by RenanYudi** [comment]
Images and other attachments are deleted, but the text isn’t. [Learn how to save the images here.](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Storing-HTML-locally)
