### ISSUE TITLE
"Started a call" message in groups/DMs does not include call length after completion

### ISSUE THREAD

**Issue by Bzly** [Tyrrrz/DiscordChatExporter#261]
A 'bug', I think. Steps to reproduce:

1. Call a friend in Discord
2. Notice the auto-message says "<username> started a call."
3. End call after a few minutes and notice message now reads "<username> started a call that lasted x minutes/hours"
4. Export conversation, message log shows original "<username> started a call."

The use of having the updated message is of course being able to track how long you speak to friends. These messages are not searchable in Discord itself, so AFAIK there is no other way to easily scrape them. 

Presumably this is caused by Discord handling this case slightly oddly.

**Comment by Tyrrrz** [comment]
I think this information is not available in Discord API.

https://discordapp.com/developers/docs/resources/channel#message-object-message-types

**Comment by Bzly** [comment]
Hmmm. 

Is "edited_timestamp" populated when the message updates, though? It's probably just for user edits, but you never know.

**Comment by Tyrrrz** [comment]
Nope, it doesn't get populated on calls. There's only a message for when the call started, not when it ended.

**Comment by Bzly** [comment]
Bollocks. Submitted an issue here for now: https://github.com/discordapp/discord-api-docs/issues/1343

**Comment by ahmedwalid05** [comment]
The ending time might not be included in the documentation, but it's still retrieved with every message of type call.
 
![image](https://user-images.githubusercontent.com/9282818/90641646-22ea9180-e23a-11ea-9455-f6af3e9f2486.png)

inside call there is an ended_timestamp value

**Comment by Tyrrrz** [comment]
Please create a new issue for that.
