### ISSUE TITLE
Help I cant get my discord bot to run this lib

### ISSUE THREAD

**Issue by Zekhap** [Tyrrrz/DiscordChatExporter#263]
Hello i need help with my Discord Bot.
Sry for my english.

Im using this library on C#

```
<PropertyGroup>
     <OutputType>Exe</OutputType>
     <TargetFramework>netcoreapp3.1</TargetFramework>
</PropertyGroup>
```
Everything works on my windows pc but not my Ubuntu
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

Im using "mono BotName.dll" to start it(thats working)
Everything works until i run a discord command and it outputs
[Exception](https://i.imgur.com/IAmqQJR.png) <-- idk why it does not say any lines or whats wrong

I heard that you can use dotnet but i could not get it to be installed..

So any tips would be helpful.
If i have missed something just tell me and i get it.

**Comment by Tyrrrz** [comment]
Hello.
This is not a library, it's an executable program.

**Comment by Zekhap** [comment]
oh, im using those files in here to execute it

**Comment by Tyrrrz** [comment]
The exception message doesn't have DiscordChatExporter in it.

**Comment by Zekhap** [comment]
I know it does not say but my files have
[Link](https://i.imgur.com/HQCCyLo.png)

**Comment by Tyrrrz** [comment]
Sorry, I can't help you. This project is not distributed as a library, if you're trying to use the source code yourself, you're on your own.

**Comment by Zekhap** [comment]
Ok then
