### ISSUE TITLE
Export multiple chats in parallel

### ISSUE THREAD

**Issue by MatiasMFM2001** [Tyrrrz/DiscordChatExporter#264]
Hi!

This tool is awesome! But it could be accelerated if the number of server/DM channels is big.

**Workaround:** I've made a Bash script which uses GNU Parallel to externally implement this feature, but it's designed to cover only my needs (using a Bot token for exporting all channels of a given Guild in HTML dark, HTML light, CSV and plain text). Here I'll share the code:
```bash
TOKEN="YourToken"; ID_Server="YourServerID"

mkdir -p Output/
dotnet DiscordChatExporter.Cli.dll channels -t "$TOKEN" -b -g "$ID_Server" | cut -d '|' -f 1 > Output/ChannelsList$ID_Server.txt

parallel dotnet DiscordChatExporter.Cli.dll export -t "$TOKEN" -b -c {1} -f {2} -o Output/BackupServer_{2} ::: $(<Output/ChannelsList$ID_Server.txt) ::: "HtmlDark" "HtmlLight" "PlainText" "Csv"
```
Save it in the same folder DiscordChatExporter.CLI is extracted, make it executable and run it.

Exporting a server with ~3 millon messages, on an AMD Ryzen 2400g it reduced total export time from ~12h to ~1h 30m (I don't have precise data, sorry about that). I think I could improve export time even more, adding more `parallel` jobs (default is "CPU count" amount), increasing CPU usage.

**Comment by 161134050** [comment]
Good idea for bot accounts only, would probably get a normal account banned/suspended quite quickly

**Comment by MatiasMFM2001** [comment]
Oh, that's true!
I didn't want to risk my account so I used the bot

**Comment by jaxblax** [comment]
> Oh, that's true!
> I didn't want to risk my account so I used the bot

Hi Matias, I know absolutely nothing about coding. I’m wondering if you’d be willing to archive some discord servers for me and I could pay for your time. Let me know please :)

**Comment by 161134050** [comment]
> > Oh, that's true!
> > I didn't want to risk my account so I used the bot
> 
> Hi Matias, I know absolutely nothing about coding. I’m wondering if you’d be willing to archive some discord servers for me and I could pay for your time. Let me know please :)

add me on discord wilbo007#0007

**Comment by jaxblax** [comment]
> Hi!
> 
> This tool is awesome! But it could be accelerated if the number of server/DM channels is big.
> 
> **Workaround:** I've made a Bash script which uses GNU Parallel to externally implement this feature, but it's designed to cover only my needs (using a Bot token for exporting all channels of a given Guild in HTML dark, HTML light, CSV and plain text). Here I'll share the code:
> 
> ```shell
> TOKEN="YourToken"; ID_Server="YourServerID"
> 
> mkdir -p Output/
> dotnet DiscordChatExporter.Cli.dll channels -t "$TOKEN" -b -g "$ID_Server" | cut -d '|' -f 1 > Output/ChannelsList$ID_Server.txt
> 
> parallel dotnet DiscordChatExporter.Cli.dll export -t "$TOKEN" -b -c {1} -f {2} -o Output/BackupServer_{2} ::: $(<Output/ChannelsList$ID_Server.txt) ::: "HtmlDark" "HtmlLight" "PlainText" "Csv"
> ```
> 
> Save it in the same folder DiscordChatExporter.CLI is extracted, make it executable and run it.
> 
> Exporting a server with ~3 millon messages, on an AMD Ryzen 2400g it reduced total export time from ~12h to ~1h 30m (I don't have precise data, sorry about that). I think I could improve export time even more, adding more `parallel` jobs (default is "CPU count" amount), increasing CPU usage.

Hi Matias, I know absolutely nothing about coding. I’m wondering if you’d be willing to archive some discord servers for me and I could pay for your time. Let me know please :)

**Comment by MatiasMFM2001** [comment]
> > Hi!
> > This tool is awesome! But it could be accelerated if the number of server/DM channels is big.
> > **Workaround:** I've made a Bash script which uses GNU Parallel to externally implement this feature, but it's designed to cover only my needs (using a Bot token for exporting all channels of a given Guild in HTML dark, HTML light, CSV and plain text). Here I'll share the code:
> > ```shell
> > TOKEN="YourToken"; ID_Server="YourServerID"
> > 
> > mkdir -p Output/
> > dotnet DiscordChatExporter.Cli.dll channels -t "$TOKEN" -b -g "$ID_Server" | cut -d '|' -f 1 > Output/ChannelsList$ID_Server.txt
> > 
> > parallel dotnet DiscordChatExporter.Cli.dll export -t "$TOKEN" -b -c {1} -f {2} -o Output/BackupServer_{2} ::: $(<Output/ChannelsList$ID_Server.txt) ::: "HtmlDark" "HtmlLight" "PlainText" "Csv"
> > ```
> > 
> > 
> > Save it in the same folder DiscordChatExporter.CLI is extracted, make it executable and run it.
> > Exporting a server with ~3 millon messages, on an AMD Ryzen 2400g it reduced total export time from ~12h to ~1h 30m (I don't have precise data, sorry about that). I think I could improve export time even more, adding more `parallel` jobs (default is "CPU count" amount), increasing CPU usage.
> 
> Hi Matias, I know absolutely nothing about coding. I’m wondering if you’d be willing to archive some discord servers for me and I could pay for your time. Let me know please :)

Yes, I could! But i will prefer that money going to @Tyrrrz , he made a great job here.

**Comment by MatiasMFM2001** [comment]
(Off-topic)

Wait, I've misread this email from GitHub and contacted to @161134050 via Discord thinking he was @jaxblax 
![imagen](https://user-images.githubusercontent.com/46432351/74492455-b61ec500-4ead-11ea-93cf-6ececc28f2ea.png)

Sorry for the inconvenience and what we talked via Discord's DM
