### ISSUE TITLE
Issues running the project with `dotnet run`

### ISSUE THREAD

**Issue by madtwinsis** [Tyrrrz/DiscordChatExporter#266]
(MacOS 10.14.5, Terminal 2.9.5)
If you use -c for channel it will not work, same for -f for format as those are predefined for the terminal for "-c, --configuration <CONFIGURATION> The configuration to run for. The default for most projects is 'Debug'.
-f, --framework <FRAMEWORK> The target framework to run for. The target framework must also be specified in the project file."

So each time you try "dotnet run export -t (actual token) -c (actual channel)" you get the error: "One or more required options were not set: channel."

Anyway, easy fix by going into the commands files and giving the channel another unique letter (I used -u for channel) 
Just posting this for mac-users who are ripping their hair out getting the same error message.

**Comment by RenanYudi** [comment]
Can you give us the exact command you're using? Don't forget to redact sensitive data.

**Comment by Tyrrrz** [comment]
When you use `dotnet run`, you have to separate the arguments passed to that command from the arguments passed to the actual application with two dashes (`--`). Example:

```
dotnet run -- export -t ... -c ...
```

Otherwise you will encounter ambiguities, like you mentioned.

**Comment by RenanYudi** [comment]
But you can run it without the `run` like ‘dotnet DCE.dll export`

**Comment by Tyrrrz** [comment]
Yeah, I updated my comment to mention that. You only use `dotnet run` when running from source code.

**Comment by madtwinsis** [comment]
Well, actually I'm not used to use the terminal at all as I never needed it before (I just needed to backup the channels of my discord server) and there is NO WHERE a decent how-to for mac, you just get the how-to for windows and you have to wing it from there on. I did follow the steps given, that does not work for Mac. Hence me looking for why it just didn't work at all. All I can say is, my small adaptation fixed it and now runs smoothly. I'm super grateful to have a way to backup my channels.
So please bare with me if I'm giving stupid answers to your questions/remarks. ;-)

**Comment by madtwinsis** [comment]
Well "dotnet" or "dotnet run" both gave the same issue for me.

**Comment by Tyrrrz** [comment]
Hm. Have you looked [at these instructions](https://github.com/Tyrrrz/DiscordChatExporter/wiki/macOS-usage-instructions)? If yes and you found them insufficient, what was it that you would like to see added?

**Comment by madtwinsis** [comment]
<img width="1280" alt="Schermafbeelding 2020-02-16 om 16 12 02" src="https://user-images.githubusercontent.com/61108200/74607339-7851b480-50d8-11ea-86f6-58d5c9a9044b.png">
<img width="1280" alt="Schermafbeelding 2020-02-16 om 16 15 31" src="https://user-images.githubusercontent.com/61108200/74607346-830c4980-50d8-11ea-892b-f6efefe48d36.png">

**Comment by madtwinsis** [comment]
> Hm. Have you looked [at these instructions](https://github.com/Tyrrrz/DiscordChatExporter/wiki/macOS-usage-instructions)? If yes and you found them insufficient, what is it that you would like to see added?

well if you follow those you get the error channel not set. Hence me looking for solutions ;-)

**Comment by Tyrrrz** [comment]
But you downloaded the source code instead of the release artifacts. The instructions tell you exactly what you need:

![image](https://user-images.githubusercontent.com/1935960/74607367-295c4d00-50e1-11ea-876e-fd25d4519e68.png)
![image](https://user-images.githubusercontent.com/1935960/74607373-34af7880-50e1-11ea-9942-c497c7ab5a71.png)

If you use that instead, you should be able to use `dotnet` without `dotnet run` and there shouldn't be any conflicts.

**Comment by madtwinsis** [comment]
> But you downloaded the source code instead of the release artifacts. The instructions tell you exactly what you need:
> 
> ![image](https://user-images.githubusercontent.com/1935960/74607367-295c4d00-50e1-11ea-876e-fd25d4519e68.png)
> ![image](https://user-images.githubusercontent.com/1935960/74607373-34af7880-50e1-11ea-9942-c497c7ab5a71.png)
> 
> If you use that instead, you should be able to use `dotnet` without `dotnet run` and there shouldn't be any conflicts.

But I did that and it did not work! Otherwise I would not have gone looking for a solution to my by then pressing issue.

**Comment by madtwinsis** [comment]
<img width="1265" alt="Schermafbeelding 2020-02-16 om 16 30 39" src="https://user-images.githubusercontent.com/61108200/74607536-e5197e80-50d9-11ea-9068-8223581b3c8d.png">

**Comment by madtwinsis** [comment]
If you follow the instructions of the link you provide to the letter: https://github.com/Tyrrrz/DiscordChatExporter/wiki/macOS-usage-instructions
it just doesn't do a thing at all. Nothing. So or there are some steps missing to the instructions or it doesn't work like that for macOS. My way works just fine, only you can't use the "-c" or "--c" for channel. 

No where on my whole computer is the html file to be found of the channel I just wanted to download
<img width="1280" alt="Schermafbeelding 2020-02-16 om 16 51 17 c" src="https://user-images.githubusercontent.com/61108200/74607927-43942c00-50dd-11ea-8f80-5e6974d7645d.png">

**Comment by RenanYudi** [comment]
Oh I see. A sec.

**Comment by RenanYudi** [comment]
You should press ENTER/RETURN after dropping the folder

**Comment by madtwinsis** [comment]
well then you get this
<img width="1280" alt="Schermafbeelding 2020-02-16 om 17 01 00" src="https://user-images.githubusercontent.com/61108200/74608032-30359080-50de-11ea-9bae-efc273697c66.png">

**Comment by RenanYudi** [comment]
Don’t `dotnet run`, just `dotnet`

**Comment by madtwinsis** [comment]
Oops, sorry.. indeed now it works! Thanks! Please add that step to the instructions ;-) 
 wow... when a noob is not noob enough to try the simple things first :-D 

<img width="1276" alt="Schermafbeelding 2020-02-16 om 17 09 12" src="https://user-images.githubusercontent.com/61108200/74608181-47c14900-50df-11ea-8879-99888f71359a.png">

**Comment by RenanYudi** [comment]
No problem! I’ll try to edit the wiki to make it a bit more noob-friendly.

**Comment by madtwinsis** [comment]
Again thank you! 
Super grateful you made it possible to export the channels!
