### ISSUE TITLE
Program isn't exporting entire DM log

### ISSUE THREAD

**Issue by opticaldelusion** [Tyrrrz/DiscordChatExporter#267]
Hello,

I used the GUI version to export a single DM log. It ends at September 19, 2018. There are DM messages to present day in this log. How do I get this to export the entirety of the DM?

Thank you.

**Comment by Tyrrrz** [comment]
Hi
That is weird. Is there anything notable about the messages coming after September 19, 2018?
Are you using the latest version of DiscordChatExporter?

**Comment by opticaldelusion** [comment]
I don't think there is anything notable after Sept 19, 2018. I am using the
latest version.
I also thought it was odd, so I figured it wouldn't hurt to ask.

**Comment by Tyrrrz** [comment]
Does it work if you specifically set the end date to now?

**Comment by opticaldelusion** [comment]
On this specific DM I don't get the option of a date range when I click on
it, which also seems odd.

**Comment by Tyrrrz** [comment]
Can you take a screenshot of the GUI when you try to select the date range?

**Comment by opticaldelusion** [comment]
Alright with many reboots I think I got it working so now it pops the date
window up. I suspect the issue may have been with a Windows Update not
being completed and for me, that always seems to mean things don't run
correctly. I uninstalled the program, updated windows, reinstalled the
latest version and now it appears to work.

Thank you for your assistance

**Comment by Tyrrrz** [comment]
Still weird but I'm glad it's sorted.
