### ISSUE TITLE
Net core required, but net core's installed

### ISSUE THREAD

**Issue by NuclearVampire** [Tyrrrz/DiscordChatExporter#269]
Exactly as the title says, it's giving a popup that net core is required to run this, however net core is installed.  

![unknown](https://user-images.githubusercontent.com/33501446/75228861-121b0080-576e-11ea-8063-d52733e76d6c.png)

I've used this exporter multiple times without an issue on this computer until tonight, so not exactly sure what changed. 

Running windows 10. Let me know what other information you need, and thank you in advance.

**Comment by Tyrrrz** [comment]
Hi.
Can you open `cmd` and run `dotnet --version`?

**Comment by NuclearVampire** [comment]
Hey, yes, ran that, and got back  
"It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

So for whatever reason it's 1. no longer being counted as installed, and 2. not able to reinstall it and fix it. 

I realize this probably is a computer error, not a script error, but if you can give me any clues on which direction to poke around in to fix this, even a little info would be super appreciated.

**Comment by Tyrrrz** [comment]
> 2. not able to reinstall it and fix it.

Do you mean the installer doesn't work or that when you click "yes" on "Would you like to download it now?" it does nothing? Does it work if you download and install it manually [from here](https://dotnet.microsoft.com/download/dotnet-core/current/runtime)?

Otherwise, can you open "Programs and features" and see if it finds anything like "Microsoft .NET Core Runtime"?

**Comment by NuclearVampire** [comment]
Well, when I run the installer, it all goes well, says it's installed, but then. the exporter won't work, and command prompt doesn't find it installed, so....

And apps and features isn't showing it at all-

That's what I was going to say, but I decided to try running the installer again, and chose repair installation. Command prompt still can't find it, but the chat exporter works, so?  I guess....all's okay? Ish?  

Anyway, sorry for wasting your time, my computer is confused apparently, but the exporter works, so solved I guess! *shrugs ruefully*

**Comment by Tyrrrz** [comment]
Cool, at least it works :)
