### ISSUE TITLE
Can't find a command that matches arguments [].

### ISSUE THREAD

**Issue by happysmash27** [Tyrrrz/DiscordChatExporter#270]
I need to back up a server by Thursday night, and when trying to do this, after installing docker, discordchatexporter in docker, and .net core runtime, I still get the following error: 

`Can't find a command that matches arguments [].`

My command is as follows: 

`docker run tyrrrz/discordchatexporter --exportguild -t "<token pasted from browser>" -g "<guild address, in numbers>" --it` 

What am I doing wrong here? I haven't found any other issues mentioning this. 

This is on Gentoo Linux, with a fresh kernel to enable everything from Docker and the .net overlay to install .net core (which I will probably edit instructions to use in the Wiki at some point).

**Comment by happysmash27** [comment]
As a workaround, I decided to try the generic CLI version, and get the following much more descriptive error: 

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '3.1.0'.

```

To fix this, I will add 31 to my dotnet targets and reinstall dotnet.

**Comment by happysmash27** [comment]
That didn't work. 

For that issue, I think I may actually need to install dotnetcore-sdk-bin instead of dotnetcore-runtime-bin, as the sdk-bin appears to use the same slot as the runtime-bin and is on the right version.

**Comment by happysmash27** [comment]
Switching to this, I no longer get the version error, but the exact same vague error I get with Docker: 

`Can't find a command that matches arguments [].`

**Comment by happysmash27** [comment]
Aha! I need to simply use `exportguild`, without the -- in front! That is the solution!

**Comment by Tyrrrz** [comment]
Glad you figured out the issue :)
