### ISSUE TITLE
Where are exports saved in Docker image?

### ISSUE THREAD

**Issue by biblioallen** [Tyrrrz/DiscordChatExporter#277]
I ran `docker run tyrrrz/discordchatexporter export` but I cannot find where the file is. Help?

**Comment by Tyrrrz** [comment]
You need to bind the output directory in the container.

More info on the wiki: https://github.com/Tyrrrz/DiscordChatExporter/wiki/Docker-usage-instructions

**Comment by caio-vinicius** [comment]
Thank you for asking this, searching many times and the flags don't appeer in `--help` command.
