### ISSUE TITLE
Export message history from a specific discord user 

### ISSUE THREAD

**Issue by koblihh** [Tyrrrz/DiscordChatExporter#28]
I was wondering if it would be possible to add a new search feature `from: user` - which would allow us to filter/limit messages and essentially only export message history from a specific user on a discord server.

**Comment by SharpOB** [comment]
Would be nice if this could be extended to save all messages from a single user across all servers.

**Comment by kingphantom** [comment]
This is a feature I hope to see as well. An idea would be to separate the user by [DATE] [SERVER, CHANNEL]

Date could be used to determine the server and channel order for the user.

**Comment by panhartstuff** [comment]
I would love to have this feature too.
Any hope for revival?

**Comment by Tyrrrz** [comment]
It hasn't died :)

**Comment by panhartstuff** [comment]
Oh nice.
Are there any complications or difficulty with this kind of feature?

**Comment by Tyrrrz** [comment]
I want to make this more generic by being able to specify a query that allows to filter messages.
Currently this is lower in priority than some other things but I'll get to it eventually.

**Comment by thewizardofyorke** [comment]
I also would like if it were possible to filter chat history similar to how it's done via discord's search bar.

I'm in a chatroom of music makers and I like to keep folders of their original music. I used to do this manually but this program helps alot. What would make it perfect for my purpose is the ability to download sound attachments, or retrieve links from a certain website (i.e. soundcloud.com/clyp.it/instaud.io, etc), that were posted by a specified user. 

Thanks for making this neat app.

**Comment by Tyrrrz** [comment]
@scattrbrain1994 this is pretty much how I want it myself, i.e. using Discord's search query syntax. However, while search is used mostly to find specific messages, it will have to be extended for this use case.

I'm going to close this issue in favor of #160 which pretty much encompasses this and other use cases as well.
