### ISSUE TITLE
[HTML] Multi-line block quotes are not rendered correctly

### ISSUE THREAD

**Issue by FM-96** [Tyrrrz/DiscordChatExporter#288]
In Discord, multi-line blockquotes can be made in two ways:

1. Starting a line with `>>>` will turn everything that follows into a blockquote:
```
>>> Multi-line quote using >>>, line 1.
Multi-line quote using >>>, line 2.
```

2. Starting multiple subsequent lines each with `>` will turn those lines into one cohesive multi-line blockquote:
```
> Multi-line quote using multiple >, line 1.
> Multi-line quote using multiple >, line 2.
```

1\. is rendered correctly by this program, but 2. is not.

How it looks in Discord:
![image](https://user-images.githubusercontent.com/4470619/78688820-f28f0000-78f5-11ea-85b5-be456dd576d7.png)

How it looks in DiscordChatExporter:
![image](https://user-images.githubusercontent.com/4470619/78688791-e73bd480-78f5-11ea-83c5-26aa794e0e4d.png)

As you can see, 2. is rendered as two separate single-line blockquotes, which also breaks any markdown formatting inside it that spans over multiple lines.

**Comment by FM-96** [comment]
While this fixed the issue of it not rendering as a single multi-line quote, it did not fix the formatting inside the quote being broken if it spans multiple lines.

![image](https://user-images.githubusercontent.com/4470619/79322300-ec5bdd80-7f0c-11ea-8642-7a4d4b12cbdc.png)

Please reopen this.

**Comment by Tyrrrz** [comment]
Fixed
