### ISSUE TITLE
Framework 'Microsoft.WindowsDesktop.App' not found after install of Net Core Runtime

### ISSUE THREAD

**Issue by EJFores** [Tyrrrz/DiscordChatExporter#289]
Hello,
I am having some trouble with initial startup. I have installed version 3.1.0 of .NET Core 3.1 Runtime however I receive this error upon startup. 
![image](https://user-images.githubusercontent.com/32749043/78947023-e20f8e80-7a89-11ea-9e3d-ad40c15d21ce.png)
I have noticed that C:\Program Files\dotnet\shared has the name "Microsoft.NETCore.App" not WindowsDesktop. Changing the DiscordChatExporter.runtimeconfig to have this name instead has prevented the error from showing, however the program will still not run. Attempting to update to version 3.1.3 has yielded the same result.

Am I missing something?

**Comment by Tyrrrz** [comment]
Have you installed .NET Core Runtime or .NET Core Runtime for Desktop Apps?

**Comment by EJFores** [comment]
.NET Core Runtime

**Comment by Tyrrrz** [comment]
You need the desktop runtime.
