### ISSUE TITLE
Output file name options

### ISSUE THREAD

**Issue by FangsMcWolf** [Tyrrrz/DiscordChatExporter#29]
Please add option to automatically add dates to the filename when using date ranges.

Btw, LOVE the interface, it makes it so easy!

**Comment by Tyrrrz** [comment]
You can edit the file name yourself

**Comment by FangsMcWolf** [comment]
I know, but that's per file.  An option to auto-add the date(s) would make it easier.  Like a checkbox that can be toggled.  If no date ranges are selected, it doesn't add any dates, otherwise it uses the date(s) picked.
