### ISSUE TITLE
Separate message groups by author nickname instead of just ID

### ISSUE THREAD

**Issue by C1ffisme** [Tyrrrz/DiscordChatExporter#290]
Tupperbox allows for the creation of "characters" for the sake of roleplay, etc. through the use of webhooks. If one character speaks after another character, however, the conversation gets "jumbled":

Original:

![Screenshot_20200411_020244](https://user-images.githubusercontent.com/9893266/79037646-a8797900-7b98-11ea-8b24-32d16ad39a93.png)

Export:
![Screenshot_20200411_020315](https://user-images.githubusercontent.com/9893266/79037648-a9aaa600-7b98-11ea-9bad-f54c1ffd9fed.png)

**Comment by Tyrrrz** [comment]
Hi.
Can you try the same but with 8+ minutes between the two "Test" messages? I'm curious what it'd look like.

**Comment by C1ffisme** [comment]
This one did actually work:
![Screenshot_20200411_104949](https://user-images.githubusercontent.com/9893266/79048363-3a59a400-7be2-11ea-9e5c-1699f788521e.png)

Original:
![Screenshot_20200411_105028](https://user-images.githubusercontent.com/9893266/79048368-49d8ed00-7be2-11ea-9d26-d15df77c6fa6.png)

**Comment by Tyrrrz** [comment]
Can you link me an invite to the server where I can test on these messages?
You can message me at Tyrrrz#5447

**Comment by C1ffisme** [comment]
This is a personal server I use for testing bots and I'd rather not use that particular server, but you can [invite the bot to your own server](https://top.gg/bot/431544605209788416) if you need to, or I can try and set up another server with the bot if you need me to

**Comment by Tyrrrz** [comment]
> ...or I can try and set up another server with the bot if you need me to
That would be great :)

**Comment by C1ffisme** [comment]
@Tyrrrz https://discord.gg/mrdkhS

**Comment by C1ffisme** [comment]
@Tyrrrz I'll DM it to you
