### ISSUE TITLE
[CLI] CLI instance closing immediately after running

### ISSUE THREAD

**Issue by AlexKersjes** [Tyrrrz/DiscordChatExporter#292]
Hi. The GUI version is working great for me but I wanted to explore the CLI options. When I try to run the CLI the interface pops up then closes immediately. I tried running as administrator, it didn't help. A bit of text flashes explaining how to use the help command. Am I doing something wrong?

**Comment by RenanYudi** [comment]
[Please refer to these instructions](https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#using-the-cli-)

**Comment by Tyrrrz** [comment]
Run your terminal first, then run the CLI. It doesn't wait for user input.

**Comment by AlexKersjes** [comment]
Thank you.
