### ISSUE TITLE
Download DCE in a Mac

### ISSUE THREAD

**Issue by madechita** [Tyrrrz/DiscordChatExporter#293]
Hi, I am trying to get the the discordchatexporter, i already downloded the file and dotnet, but whenever i open the discordchartexporter doc the exe file doesn't work and my computer (a mac) says it can't open a microsoft file, but I already downloaded the dotnet thing... i don't know what else can i do... please, help.

**Comment by RenanYudi** [comment]
Make sure you have downloaded DiscordChatExporter**.CLI** and then follow [these instructions](https://github.com/Tyrrrz/DiscordChatExporter/wiki/macOS-usage-instructions). <br/>
If you need more help, feel free to ask us :-)
