### ISSUE TITLE
Comparison with other software

### ISSUE THREAD

**Issue by DonaldTsang** [Tyrrrz/DiscordChatExporter#294]
What is the difference between this repo and https://github.com/chylex/Discord-History-Tracker ?
Is it simply replacing JS with C#, and that it only downloads but not tracks/auto-updates?

**Comment by MakaylaTheLovin** [comment]
from my experience of using both, the main difference between the 2 is that one is JS code run in browser and one is a native application, if you try to export a big enough channel using DHT, it crashes the browser rendering it useless for channels over a certain limit which the dev was very specific on it being only used for exporting dms, never for entire servers, it also crashes the browser when you reach a certain amount of messages, this doesnt happen with DCE anymore thankfully. while the perks of DCE are updating and being able to do easily in the browser window, in my use case, its not worth spending hours on hours just for my browser to crash scrolling up over 1 million messages, 

at the end of the day its just what your use case is. some work better with DHT and some work better with DCE

**Comment by DonaldTsang** [comment]
Would it be possible to add an updating feature to DCE such that you can progressively download the logs? If not, are there any way of de-duplicating chat logs assuming there are two logs of the same channel?

**Comment by Tyrrrz** [comment]
What you're referring to as progressive download is actually quite difficult to implement and currently there are other issues that have higher priority (I can share that after the next release, [this issue](https://github.com/Tyrrrz/DiscordChatExporter/issues/21) will have highest priority). Generally, anything can be implemented, but it's always a question of priority and how much its worth compares to the effort it requires.
