### ISSUE TITLE
Update exported files - gradual exports

### ISSUE THREAD

**Issue by makeworld-the-better-one** [Tyrrrz/DiscordChatExporter#295]
It'd be nice if there was a flag that would allow for gradual exports, where it would look at the last message in some output files, and then look for all the new messages in the dm/channel/guild, and then add the new messages on to the bottom. That way you wouldn't end up with many export files over time.

For example, my workflow with `youtube-dl` is to download new videos from whatever channels I want, every day. I use the `--download-archive` flag so it will only download new videos. It'd be nice to be able to do the same with DCE.

**Comment by Tyrrrz** [comment]
Descoping this to avoid complexity. Gradual exports would imply that the app will need to be able to load existing exports, parse them, and then extend them. This may be simple enough for TXT and CSV formats, but is more challenging with HTML and JSON. Additionally, when exporting with partitioning, it becomes more difficult.

The recommended approach is to not try to put all messages into a single file anyway, as they can get unnecessarily big, which prevents them from opening in a text viewer or a browser. Instead, use partitioning and date ranges to export messages in batches.
