### ISSUE TITLE
Partition based on file size

### ISSUE THREAD

**Issue by makeworld-the-better-one** [Tyrrrz/DiscordChatExporter#296]
Right now there is an option to partition based on the number of messages in a file. It'd be nice to have an option that would accept text like `2G` or `300M`, where the file the would be partitioned after (or just before) reaching that size limit. Ideally the size limits would follow powers of 2, where 1024 bytes equals 1 KiB, etc.

**Comment by Tyrrrz** [comment]
Descoping as it's unlikely to ever get implemented.
