### ISSUE TITLE
[GUI] NotImplementedException on launch

### ISSUE THREAD

**Issue by jonbarbara** [Tyrrrz/DiscordChatExporter#297]
I am supporting a colleague in getting this on their Windows 10 machine. 
I walked her through the downloading of the .NET Core and its installation but running the DiscordChatExporter results in the following error. They are running it locally, not on Remote Desktop (as I saw elsewhere where this scenario was pointed out as being a possibly reason) 
![image](https://user-images.githubusercontent.com/54844670/80502231-a6713180-8970-11ea-9bc5-d9f5c5bf6cd9.png)

Any ideas?

**Comment by Tyrrrz** [comment]
No idea

**Comment by Tyrrrz** [comment]
Reported this on WPF repo, nothing much that can be done from this side. Hopefully they will get it fixed eventually.
