### ISSUE TITLE
[GUI] Add dark theme to the app

### ISSUE THREAD

**Issue by dcrime** [Tyrrrz/DiscordChatExporter#298]
I searched and didn't see anyone requesting dark theme for the app itself so here I am, same as discord I can't stand light theme without some sunglasses so having an option in the app to switch to dark theme would really make me love this even more

**Comment by Tyrrrz** [comment]
You can try the CI build here: https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/289595843
