### ISSUE TITLE
.NET Core installation issue

### ISSUE THREAD

**Issue by lachiko** [Tyrrrz/DiscordChatExporter#299]
Testing on version 2.20
Clicking Yes does nothing even as an administrator, the program just closes and repeats the same message upon launching again.
No closes as expected

![image](https://user-images.githubusercontent.com/5151792/81625179-6fece980-943b-11ea-85ef-9fcb2824fa41.png)

Ended up grabbing the .net core runtime linked from https://github.com/Tyrrrz/DiscordChatExporter

**Comment by Tyrrrz** [comment]
There are some bugs with it unfortunately on Microsoft's end. Not much I can do about it though :/

**Comment by lachiko** [comment]
Ah yes I should have realised, thanks!
