### ISSUE TITLE
Better link for downloading .NET

### ISSUE THREAD

**Issue by JuicyJuuce** [Tyrrrz/DiscordChatExporter#300]
I think for novice users, the current link to download an updated .NET Core can leave them confused about how to download the correct think. So instead of linking to

https://dotnet.microsoft.com/download/dotnet-core/

link here instead:

https://dotnet.microsoft.com/download/dotnet-core/current/runtime

This might also reduce support demand because you will be more sure of what the user downloaded.

**Comment by RenanYudi** [comment]
Hm… Are you talking about the wiki or this message?
![](https://user-images.githubusercontent.com/5151792/81625179-6fece980-943b-11ea-85ef-9fcb2824fa41.png)
