### ISSUE TITLE
Newline issues when exporting to CSV

### ISSUE THREAD

**Issue by Sajidur78** [Tyrrrz/DiscordChatExporter#301]
When exporting to csv via the tool it will write \\n to the csv in place of \\\\n.
Example Output:
```
"143768624711073794","Sajid#1744","14-May-19 09:48 PM","A Message
With a new line","",""
```

Intended Output:
```"
143768624711073794","Sajid#1744","14-May-19 09:48 PM","A Message\nWith a new line","",""
```

**Comment by Tyrrrz** [comment]
Why do you think that's the intended output?

**Comment by Sajidur78** [comment]
I think that's the intended output because when you have a new line in a csv file it usually stands for a new row and because of how the entries are formatted it can cause headaches for parsers.

**Comment by Tyrrrz** [comment]
[From wikipedia](https://en.m.wikipedia.org/wiki/Comma-separated_values): 
![image](https://user-images.githubusercontent.com/1935960/82039675-04f71900-96ae-11ea-9f37-8cbba64208e3.png)

In this case the new lines are inside fields which are encapsulated by quotes, so there should be no ambiguity regarding new rows. Excel and [this random online website](https://www.convertcsv.com/csv-viewer-editor.htm) handle this just fine.
