### ISSUE TITLE
Can't automatically export on linux server

### ISSUE THREAD

**Issue by Haz226** [Tyrrrz/DiscordChatExporter#302]
Hello;
I'm probably just doing everything wrong, but i can't export the chat using a bot on my linux server ...
I saw that i might have to use docker ? But I don't know how it work... 
Could somebody please tell me how I can implement the bot on my Discord Bot on a Linux machine ? 
(PS: I managed to make it work on my pc automatically but not on the server)

**Comment by Tyrrrz** [comment]
Have you looked at wiki?

https://github.com/Tyrrrz/DiscordChatExporter/wiki/Linux-usage-instructions
