### ISSUE TITLE
This shit could save me if I saved it

### ISSUE THREAD

**Issue by kirkgutierrdd** [Tyrrrz/DiscordChatExporter#303]
Anyways can you make the software keep pictures as base64 encode 
so that way the picture wont be hosted on dickord servers?

**Comment by RenanYudi** [comment]
[Try this for now](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Storing-HTML-locally)

**Comment by kirkgutierrdd** [comment]
> [Try this for now](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Storing-HTML-locally)

Good idea, also would like to see something of saving all of your people hash id's

**Comment by RenanYudi** [comment]
> your people hash id's

You mean User IDs?

**Comment by Tyrrrz** [comment]
Duplicate of #1 and #21
