### ISSUE TITLE
User mentions in embeds show up as "@Unknown" when exported if the mentioned user does not appear earlier in the chat log

### ISSUE THREAD

**Issue by JuicyJuuce** [Tyrrrz/DiscordChatExporter#304]
Compare actual channel with exporter output:

(edit: if you want to test this on the channel in question, here is an invite link https://discord.gg/byfy6yf and the channel is #wallet-log)

![image](https://user-images.githubusercontent.com/24610831/83363500-92e62b80-a35f-11ea-9985-112f2761b291.png)

![image](https://user-images.githubusercontent.com/24610831/83363502-97aadf80-a35f-11ea-8da0-7581491613e8.png)

**Comment by Tyrrrz** [comment]
This only happens on mentions of users who haven't participated in the chat log previously, due to limitations in Discord API. To work around it we'd need to put markdown parsing earlier in the pipeline and make additional requests for each mention.

**Comment by dennislo16** [comment]
Ya I think this is an important issue to deal with. It has been giving me such a headache as I have to manually cross reference wallet movements with my own records. It would be great if this can be bumped up!
