### ISSUE TITLE
Create a landing page with all channels and sections

### ISSUE THREAD

**Issue by yellowturban** [Tyrrrz/DiscordChatExporter#306]
I suggest creating a landing page that links to the channels exported and their sections accordingly. This helps to easily navigate between channels just like on Discord.
Also, an improvement to show user roles instead of just the colour.

**Comment by CatchMeIfYouCan4401** [comment]
If somebody could get the roles from discord through this software, that person will actually solve a pretty big problem.  
I'll praise the person :)

**Comment by Tyrrrz** [comment]
Closing this as "won't fix" because it adds a lot of complexity and is out of scope.
