### ISSUE TITLE
Permission denied cannot pull docker

### ISSUE THREAD

**Issue by santiagodemierre** [Tyrrrz/DiscordChatExporter#307]
me$ docker pull tyrrrz/discordchatexporter
Using default tag: latest
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=tyrrrz%2Fdiscordchatexporter&tag=latest: dial unix /var/run/docker.sock: connect: permission denied
$me

**Comment by RenanYudi** [comment]
Try running with `sudo` or try this: 
https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by RenanYudi** [comment]
And prefer to use the stable tag, like this:
`sudo docker pull tyrrrz/discordchatexporter:stable`

**Comment by santiagodemierre** [comment]
Hi that worked.
I followed the steps. Docker is installed, dotnet works on the terminal but
when I
follow these steps

1. Download DiscordChatExporter.CLI.zip
<https://github.com/Tyrrrz/DiscordChatExporter/releases/latest> and extract
it to a folder.
2. Open Terminal.
3. cd into the extracted folder. You can do this in Terminal by typing cd,
then press the SPACE key, drag and drop the extracted folder into the
Terminal window, and press the ENTER key.
4. Replace TOKEN and CHANNEL, then execute this command to export:

dotnet DiscordChatExporter.Cli.dll export -t TOKEN -c CHANNEL


Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but
dotnet-DiscordChatExporter.Cli.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed
executable with this name could not be found on the PATH.

Twitter <http://twitter.com/santidemierre> Facebook
<http://www.facebook.com/SantiagoDemierre> Youtube channel
<http://www.youtube.com/santiagodemierre> Blog
<http://www.consultoriamarketing.org/?emailsignature>

**Comment by RenanYudi** [comment]
If you have docker installed you should follow [these instructions](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Docker-usage-instructions).

The Linux usage instructions are only if you don't want to use Docker.

If you use Docker, you don't need to install dotnet.
If you follow the Linux instructions, you don't need to install Docker.

**Comment by santiagodemierre** [comment]
Dude, have pitty on me :-)

I got this far>
sudo docker run --rm -v $PWD:/app/out tyrrrz/discordchatexporter:stable
export -t "somestuff.mostuff.somemorestuff" -c 123456788

also tired:

sudo docker run --rm -v $PWD:/code tyrrrz/discordchatexporter:stable export
-t "somestuff.mostuff.somemorestuff" -c 123456788
And I get

DiscordChatExporter.Domain.Exceptions.DiscordChatExporterException: Not
found.
   at
DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String
url) in /src/DiscordChatExporter.Domain/Discord/DiscordClient.cs:line 78
   at
DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelAsync(String
channelId) in /src/DiscordChatExporter.Domain/Discord/DiscordClient.cs:line
194
   at
DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole
console, String channelId) in
/src/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs:line 55
   at
DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole
console) in
/src/DiscordChatExporter.Cli/Commands/ExportChannelCommand.cs:line 14
   at CliFx.CliApplication.HandleCommandExecutionAsync(ApplicationSchema
applicationSchema, CommandLineInput commandLineInput, IReadOnlyDictionary`2
environmentVariables)
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments,
IReadOnlyDictionary`2 environmentVariables)

I replaced the
-v $PWD:/app/out in Mac/Linux
Twitter <http://twitter.com/santidemierre> Facebook
<http://www.facebook.com/SantiagoDemierre> Youtube channel
<http://www.youtube.com/santiagodemierre> Blog
<http://www.consultoriamarketing.org/?emailsignature>

**Comment by Tyrrrz** [comment]
Sounds like the channel doesn't exist.
