### ISSUE TITLE
Better display of export progress

### ISSUE THREAD

**Issue by schlangz** [Tyrrrz/DiscordChatExporter#308]
Please add a better display of export progress, some % in the titlebar or a small popup or something. Thanks

**Comment by rwdsfgds** [comment]
nigge

**Comment by rwdsfgds** [comment]
nigger

**Comment by Tyrrrz** [comment]
Are you referring to CLI or GUI?

**Comment by schlangz** [comment]
GUI, haven't tried CLI yet

**Comment by Tyrrrz** [comment]
Closing as this likely won't get implemented.
