### ISSUE TITLE
Being able to export without time stamps or user numbers

### ISSUE THREAD

**Issue by EnderPartyLord** [Tyrrrz/DiscordChatExporter#309]
I'd like to use this program to archive DnD/RP Servers to export the stories in a digestible format, without having to do much further editing. At the moment, I need to manually remove the time stamps and the discord user numbers that appear after every user name. I'd like for this to be down via the .TXT export. Any help with this would be appreciated. Thank you for your time.

Also adding a colon after every user name, to separate dialog from the user name with punctuation, would also be very nice.

**Comment by Tyrrrz** [comment]
If you want to export in a processable format, then CSV or JSON are your best options. TXT maintains a good balance between the amount of information it provides and clarity.

I'm not planning to add "minimal" or "light" versions to existing formats.
