### ISSUE TITLE
Don't break words when wrapping

### ISSUE THREAD

**Issue by nayanayaa** [Tyrrrz/DiscordChatExporter#31]
Love your app! It's easy to use and the result html looks neat. However, I'm using your app to export RP logs. The sentences run pretty long (they often go over one line), but when a line runs longer than the html viewer width, it gets broken pretty awkwardly. Like, 

"...Before this, “X” was only a far island that xxxx has never visited, only heard in passi
ng news, a place that’s closer to an abstract concept. But as xxxx listens to xxxx’s wor
ds, the abstract emptiness turns into big farmland,..."

The issue still persist even when the html viewer window is already maximized. I think it would be nice if the broken word could appear in its entirety in the next line instead...

**Comment by Tyrrrz** [comment]
The issue is that very long words would remain unbroken, such as links for example.
