### ISSUE TITLE
No .NET Core version mentioned in Readme

### ISSUE THREAD

**Issue by occultus73** [Tyrrrz/DiscordChatExporter#312]
It would be helpful if the exact version of .NET Core that's required (3.1.0?) was mentioned in the Readme; thus saving the user from having to go through the drama of downloading the wrong version six different times like I did.

Cheers.

**Comment by Tyrrrz** [comment]
The links in the readme should take you to the correct version, which is 3.1. Any later version in the same major will do as well.
