### ISSUE TITLE
Exporting a number of last messages

### ISSUE THREAD

**Issue by quazuo** [Tyrrrz/DiscordChatExporter#316]
I need an option to export only the last, or a few latest messages on a channel. I can't just use the timestamp of the last message, because I'm using this exporter for something else and there's just no way to do it by manually getting the time when the last message was sent. Would it be possible to do that?

**Comment by Murkur** [comment]
this would be nice or an option to log to one file and it only updates that one file with new messages instead of reexporting the entire text chat

**Comment by Tyrrrz** [comment]
@Quazuo just to reference this:

> I can't just use the timestamp of the last message, because I'm using this exporter for something else and there's just no way to do it by manually getting the time when the last message was sent.

Which format are you exporting in? HTML, JSON, or TXT?

**Comment by Tyrrrz** [comment]
Closing as out of scope/low interest
