### ISSUE TITLE
Can't get past "you must install .NET Core."

### ISSUE THREAD

**Issue by SuperShadowPlay** [Tyrrrz/DiscordChatExporter#318]
I've installed the desktop and dotnet runtime for 3.1.5 and 3.1.4, and the program will still not launch correctly. I don't have any experience with .NET, so this is probably my bad.

**Comment by Tyrrrz** [comment]
Hi.
What operating system and bitness are you using?

**Comment by SuperShadowPlay** [comment]
Hahaha don't I look like an idiot. I thought I was on x86 but I'm on x64. Installed the right version and it worked.

Thanks for baring with me.
