### ISSUE TITLE
"Could not execute because the specified command or file was not found."

### ISSUE THREAD

**Issue by ljodell** [Tyrrrz/DiscordChatExporter#320]
Hey, on Mac OS X Catalina, I input this and get:
dotnet DiscordChatExporter.Cli.dllexport -t "token" -c channelid
**Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-DiscordChatExporter.Cli.dllexport does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.**

**Comment by ljodell** [comment]
Nevermind, I can't proofread.

**Comment by paulsseminaraccount** [comment]
What was the problem?

**Comment by Yudi** [comment]
dotnet DiscordChatExporter.Cli.dll**export**
It’s missing a space

**Comment by ljodell** [comment]
The problem was I didn't have a space between dll and export so it wasn't
working. Sorry to bother you!

Em qui, 16 de jul de 2020 às 13:32, Renan Yudi <notifications@github.com>
escreveu:
