### ISSUE TITLE
[HTML] Discord fonts are blocked by CORS policy

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/DiscordChatExporter#322]
Recently Discord decided to finally enable CORS policy on their CDN which prevents Whitney fonts from loading in HTML exports:

![image](https://user-images.githubusercontent.com/1935960/87853159-9e41e600-c910-11ea-852f-a5bf9ad68b3c.png)

There are a couple of ways to deal with this but each comes with certain drawbacks:

1. Embed fonts directly in the export file. This would mean that the fonts are going to be part of the page, which pushes the minimum size of the export file up to ~500kb since the fonts are quite large.

2. Embed only one font directly in the export file. Instead of using all fonts, we can only use the most common one (Whitney Regular, which is used for text content) and extrapolate the others with font weight. This pushes the minimum size to ~100kb.

3. Host the fonts on another CDN that allows any CORS origin. This would fix the problem, but someone will have to care of the hosting and it won't be me.

4. Leave things as they are. That means the fonts will likely not work on modern browsers, unless you launch them with special settings that ignore CORS for locally stored files or use extensions that help with that on per-page basis. In worst case scenario, Whitney fonts are automatically replaced with Helvetica variants which are similar-ish but will still look different than original Discord fonts.

This thread is open for discussions, votes, and suggestions.

**Comment by Tyrrrz** [comment]
For comparison, here's the difference between fonts.

Whitney fonts (which currently cannot be loaded normally):
![image](https://user-images.githubusercontent.com/1935960/87853676-ae5bc480-c914-11ea-97cd-3f6c5abc5ed1.png)

Helvetica fallback:
![image](https://user-images.githubusercontent.com/1935960/87853662-98e69a80-c914-11ea-8e1e-fc3bdcb504cb.png)

**Comment by Jefferderp** [comment]
I'm personally completely OK with the Helvetica fallback - it's quite close, and in my opinion doesn't retract from the "integrity" of an export.

That said, I think the best solution would be to exclude all fonts by default, with an optional flag to embed the full font set. 

Thanks again for this software, and for maintaining it!

**Comment by Tyrrrz** [comment]
Helvetica it is then!
