### ISSUE TITLE
Ubuntu16.04 Linux: Error on invocation since v2.2.1

### ISSUE THREAD

**Issue by Jefferderp** [Tyrrrz/DiscordChatExporter#323]
Hello!

Until today's update (v2.2.1), I've executed DiscordChatExporter on Linux with:

`mono DiscordChatExporter.exe`

However, I understand that v2.2.1 is built against *.NET Core 3.1*. I have installed the appropriate runtime:

```
$ dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

...however when performing `mono DiscordChatExporter.exe` I'm met with the following error:

`Cannot open assembly 'DiscordChatExporter.exe': File does not contain a valid CIL image.`

Have I misunderstand how the application should be invoked? Or is this a runtime issue?

Thanks!

**Comment by Yudi** [comment]
Mono is no longer supported.
(You should install .NET Core instead)[https://github.com/Tyrrrz/DiscordChatExporter/wiki/Linux-usage-instructions]

**Comment by Jefferderp** [comment]
> Mono isn't supported since the migration to .NET Core in the 2.16 release.
> [You should run it with `dotnet` instead](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Linux-usage-instructions)

Just what I was wondering - so it was an invocation issue! And here I thought they were one and the same.

Executing with `dotnet DiscordChatExporter.Cli.dll` is working as expected!

Thanks very much :).
