### ISSUE TITLE
Fatal exception in 'ResolveUrl' when passing --media flag

### ISSUE THREAD

**Issue by Jefferderp** [Tyrrrz/DiscordChatExporter#326]
Hello,

When passing the new `--media` flag, DiscordChatExporter v2.21 will occasionally throw a fatal exception:

```
Exporting channel 'foo'... <input>(127,101) : error : Unexpected exception when calling ResolveUrl
Exporting channel 'bar'... 
Done.
```

The issue is consistently reproducible when exporting the channel 'foo.' Occurs both via the Windows GUI, and Linux CLI. And as evident above, not all channels are affected.

Unfortunately, the only workaround is to not pass `--media` at all. Otherwise, the export will halt completely, leaving behind an incomplete file.

Ideally, the export would continue when an attachment is unable to be collected. I'm loving the ability to package media locally within exports, but the current error handling means the feature can't be used safely/unattended.

Please let me know if there are any debug logs I can collect.

Thank you in advance!

**Comment by Yudi** [comment]
It's a known issue.
A fix is coming soon.
Thanks for reporting! :-)

**Comment by TheRenegadist** [comment]
Good to here, just encountered that myself.
