### ISSUE TITLE
Detailed logging

### ISSUE THREAD

**Issue by TheRenegadist** [Tyrrrz/DiscordChatExporter#328]
Before downloading attachments was native to this I was using a Python batch to download and save images for HTML and I loved that a window showed up showing everything you were downloading as well as the line it was on and the percentage, something like this would be very cool to have open alongside the main app.

![image](https://user-images.githubusercontent.com/31916442/87867752-23df8900-c945-11ea-901a-d241c6809f6f.png)

Or instead of a pop-up window, when you click the export button the main applet extends down showing each thing it's downloading and more info. Could even have a small preview box showing each image and file as it goes, for music/video attachments it could display an icon.

**Comment by Tyrrrz** [comment]
Do you want this in CLI or GUI?

**Comment by Mhowser** [comment]
CLI please.

**Comment by samueljmorris** [comment]
I agree with this. I just downloaded the GUI and I'm using it to do a very large archive and I have no idea if it's progressing or how long it will take. I think for the GUI, having a selected channel change color once it's done archiving would be sufficient visual feedback.

**Comment by Tyrrrz** [comment]
There are actually two indicators, one in the progress bar below the token box and another in the taskbar.

**Comment by samueljmorris** [comment]
I only see the taskbar progress bar on mine, running win 10, latest .zip release of the app, and the latest .net core

**Comment by Tyrrrz** [comment]
Descoped
