### ISSUE TITLE
Can DCE export past direct channels?

### ISSUE THREAD

**Issue by Unknow0059** [Tyrrrz/DiscordChatExporter#335]
For example, I talk to someone who's not my friend for an entire day through our direct channel. I close it.

Sometime after, I leave the server I met that person in.

I can no longer open our direct channel because I need to click their username in order to reaccess it.

But the history is still there, I'm sure.

So, title.

**Comment by Tyrrrz** [comment]
Have you tried?

**Comment by Unknow0059** [comment]
No, that's why I'm asking. Because I need it for this purpose and I'm wondering if it supports the feature.

But since you're asking, I'll assume it is an implied yes.

**Comment by Tyrrrz** [comment]
I have no idea, I never tried doing that.

**Comment by Yudi** [comment]
Yes it can, but you’ll have to open the chat or find the DM ID (not user ID). Try CTRL+K in Discord.

**Comment by Unknow0059** [comment]
That's assuming I have notifications from said person. Which I do not.

**Comment by Tyrrrz** [comment]
In that case, you probably can't, you need the ID. I'm not sure whether Discord deletes the contents of a DM channel when the participants leave it, this is something you'd have to try and find out yourself.
