### ISSUE TITLE
Built-in search feature

### ISSUE THREAD

**Issue by yellowturban** [Tyrrrz/DiscordChatExporter#339]
Good to have built in search feature, that allows searching between different channels of the same Discord server and also across servers. Allow search according to user tags, etc.

**Comment by Tyrrrz** [comment]
Do you mean in GUI? You can search by simply typing the channel name, it should jump to it.

**Comment by yellowturban** [comment]
I meant the exported HTML can include a search box which helps find items across channels

**Comment by Tyrrrz** [comment]
This would require some sort of "frontpage", but that's out of scope for the project, sorry.
