### ISSUE TITLE
Incomplete exporting

### ISSUE THREAD

**Issue by eridanired123** [Tyrrrz/DiscordChatExporter#340]
When using the Docker image ('tyrrrz/discordchatexporter:stable')  with the `exportguild` command, only the first message for each channel is exported.
Likewise, when using the `export` command, only the first 2 messages are exported for the specified channel.

This is the command used:

    exportguild -t my.token -g 123456 --media -o coolName -p 99

**Comment by Tyrrrz** [comment]
Any chance you can share an invite to the guild? It doesn't seem reproducible for me.

**Comment by eridanired123** [comment]
I discovered the problem with this: https://discord.gg/WD2npS but then I tested with 3 more plus one of my own (to see if it was a problem with user roles) but all gave the same results, so I ruled what you are thinking out =P

So I imagine is either a problem with the docker image or a problem with my configuration, even if I double checked to be following the documentation I may have missed something, can PM you my token+guild/channel IDs or user and password if needed.

**Comment by Tyrrrz** [comment]
That shouldn't be an issue with Docker. Can you tell me which channel on that server did you try to export, that ended up missing some messages? Ideally, please send me an existing export where that happened.

**Comment by eridanired123** [comment]
Yes, I tried to export all channels within that server, also tried exported a few single channels, and also tried my account server to rule out permission issues. all with the same result.

Here is an export for the server I linked above, the command used for this was:

```bash

docker run -d --name cont-TEMP_discord_exporter \
    --rm -it \
    -v /my/local/volume:/app/out \
    tyrrrz/discordchatexporter \
    ### tried stable tag too ^
    exportguild -t MY.TOKEN -g 727530615460724786 --media -o megaten_tips_for_beginner -p 99
```

[megaten_tips_for_beginner.zip](https://github.com/Tyrrrz/DiscordChatExporter/files/4983841/megaten_tips_for_beginner.zip)

**Comment by Tyrrrz** [comment]
I tried it one channel and couldn't reproduce, it exported everything there was. Can you try running it outside of docker?
