### ISSUE TITLE
Improve whitespace management in HTML exports

### ISSUE THREAD

**Issue by EPOXUHA** [Tyrrrz/DiscordChatExporter#345]
Привет, понравился ваш проект.
Обнаружил небольшой нюанс, экспортированные сообщения кривовато добавляются в html страницу.
поясню, вот участок из полученной страницы:
![image](https://user-images.githubusercontent.com/51716710/88923552-953f0600-d27a-11ea-9194-e06256a25612.png)
А хотелось бы видеть вот такой вот выхлоп:
![image](https://user-images.githubusercontent.com/51716710/88923573-9a9c5080-d27a-11ea-8a3f-7e10aa41ce2c.png)
Если сразу не понятно, то:
1) Пустые строки.
2) Блоки "chatlog__message-group" не должны налазить друг на друга.
Спасибо за ваше внимание.
ну и заодно могли бы 
![image](https://user-images.githubusercontent.com/51716710/88923609-a8ea6c80-d27a-11ea-9190-d35fdd71d848.png)
пофиксить пробел в  "chatlog__message " ->"chatlog__message"

**Comment by ActualBird** [comment]
Кстати, еще очень нужна опция выгрузки сообщений из каналов конкретного пользователя.

**Comment by Tyrrrz** [comment]
The files are autogenerated, so the indentation and whitespace doesn't matter. Browsers will be able to open them regardless.

**Comment by ActualBird** [comment]
yea, but still if I want to seek for one person... I somehow need to parse all file throw, and it's a little bit large as f if it contains so much white lines... naaahhh
aw yea, some of them are just blank
![image](https://user-images.githubusercontent.com/51716710/88955314-6c336b00-d2a4-11ea-8ac4-e6794f4d93c7.png)

**Comment by ActualBird** [comment]
yea thx bro

**Comment by ActualBird** [comment]
but still, can you add options for uploading only ONE user in entire chat?
like:
User
User+ping
gotta be usefull

**Comment by Tyrrrz** [comment]
There's an issue for that: #28. Assuming that's what you mean.

**Comment by ActualBird** [comment]
yea, absolutely it

**Comment by ActualBird** [comment]
simpliest way I did it is just simlply sorting entire html for messages, same you can do i think...
and yea, i dont know which browser can operate with 300 mb of 7.3 million lines

**Comment by CarJem** [comment]
Just saying as someone who likes to go through the html and correct the text of roleplays, it be nice if the HTML could be reduced to a single line per message because it's a nightmare at the moment to manually edit the exported HTML

**Comment by CarJem** [comment]
I don't have a solution to propose at the moment though.... saddly.

**Comment by andrewkolos** [comment]
Getting rid of extra whitespace doesn't seem too difficult (at least easier than agreeing on what is "extra" vs helpful when reading the output). We would just have to delete these lines in the cshtml. I'm guessing double/triple-blank lines is not something anyone would particularly like, so getting rid of those seems pretty safe. However, getting entire messages down into a single line of HTML would be more complicated and/or result in a really hard-to-read lines of HTML.

**Comment by andrewkolos** [comment]
However, it might be the case that @Tyrrrz likes having the blank lines in the cshtml to keep different portions of it more separated.

**Comment by Tyrrrz** [comment]
Yeah, the blank lines are likely a side-effect of how the template is formatted. It's possible, however, to implement some whitespace-control features in the template engine: https://github.com/Tyrrrz/MiniRazor.

**Comment by Tyrrrz** [comment]
Created https://github.com/Tyrrrz/MiniRazor/issues/2 that's possibly related to this.

**Comment by nmz787** [comment]
I just wrote this script that converts logs to plaintext, so I could more easily `grep` them:
```
import os
import argparse
from bs4 import BeautifulSoup
import pdb

def slimmerize(input_path):
    print(f'Opening {input_path}')
    with open(input_path) as f:
        soup=BeautifulSoup(f, 'lxml')
    outfilepath = f'{os.path.splitext(input_path)[0]}.log'
    print(f'Saving as {outfilepath}')
    with open(outfilepath, 'w') as out:
        user_blocks = soup.find_all('span', {'class':'chatlog__author-name'})
        #pdb.set_trace()
        for user_block in user_blocks:
            timestamps = user_block.parent.find_all('span',{'class':"chatlog__timestamp"})
            for ts in timestamps:
                timestamp_text = ts.text
                chats = ts.parent.find_all('div',{'class':"chatlog__message"})
                for chat in chats:
                    contents = chat.find_all('div',{'class':"chatlog__content"})
                    for content in contents:
                        msgs = content.find_all('span',{'class':"preserve-whitespace"})
                        for msg in msgs:
                            if msg.text:
                                out.write(f'{timestamp_text} <{user_block["title"]}> {msg.text}\n')
                    attachments = chat.find_all('div',{'class':"chatlog__attachment"})
                    for attachment in attachments:
                        hrefs = attachment.find_all('a')
                        for href in hrefs:
                            out.write(f'{timestamp_text} <{user_block["title"]}> {href["href"]}\n')
    

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='DiscordChatExporter slimmerize - convert into plaintext logs for easier grepability!')
    parser.add_argument('input_path',
                        help='an HTML filepath')
    args = parser.parse_args()
    slimmerize(args.input_path)
```

**Comment by ActualBird** [comment]
Nice job! now can easilly handle all sht n stuff! rapid n fast!

**Comment by Tyrrrz** [comment]
Decided to go with full minification of the HTML export as it reduces the final size of the file by upto 40%
