### ISSUE TITLE
Save icons in full resolution

### ISSUE THREAD

**Issue by MatthewA-dev** [Tyrrrz/DiscordChatExporter#346]
Discord saves icons in full resolution, and its possible to access them by adding powers of 2 in the size:
Example:
https://cdn.discordapp.com/avatars/358697846611902474/91039c8ef840530b00df237c9b501407.png?size=128
produces this image:
![91039c8ef840530b00df237c9b501407](https://user-images.githubusercontent.com/63163986/89065328-ad6d5e80-d328-11ea-985b-7a55e7cfd0a5.png)
But:
https://cdn.discordapp.com/avatars/358697846611902474/91039c8ef840530b00df237c9b501407.png?size=4096
Produces this image:
![wefwef](https://user-images.githubusercontent.com/63163986/89065401-d261d180-d328-11ea-90cd-ce2aa3a9cd0f.png)
Even though there is no image that is 4096 in size.
Can you add this feature to the saving html function?

**Comment by Tyrrrz** [comment]
The goal is to preserve external resources used by the export, so it makes sense to download exactly what is linked.
