### ISSUE TITLE
Threat found - action needed

### ISSUE THREAD

**Issue by iratekalypso** [Tyrrrz/DiscordChatExporter#347]
Threat detected: Trojan:Win32/Emaili.A!cl

**Comment by Yudi** [comment]
Windows Defender is incorrectly flagging `DCE.exe` and `DCE.dll` from the 2.21.2 release. 
[Virustotal 2.21.2](https://www.virustotal.com/gui/file/b4c956e29bfc9efe76bfbdcaacdc515ad8e0b385fdf6b85896c5994059291e50/detection) and [2.21.1](https://www.virustotal.com/gui/file/0e52db8846c239b87ccaf48cc0f14542cffa40f66161ae29fd502220c9ec4aa7/detection).

**Comment by xXnikosXx** [comment]
Same issue here, dce.exe is getting flagged by win Defender as trojan.
