### ISSUE TITLE
Tupperbox messages are exported with incorrect names

### ISSUE THREAD

**Issue by wertercatt** [Tyrrrz/DiscordChatExporter#348]
Any messages posted using the Tupperbox bot will show up with the name of whatever the first Tupper used was.
Steps to reproduce:
1) Add Tupperbox to a server
2) Register 2 tuppers
3) Send a message with each.
4) Export the messages, the name of the first Tupper you used will show up for both.

**Comment by Tyrrrz** [comment]
Which version of DCE are you using?

**Comment by wertercatt** [comment]
I'm using version 2.21.2

**Comment by Tyrrrz** [comment]
That used to work, at least, so maybe Discord changed something.

**Comment by CarJem** [comment]
I did some investigation into myself.... and I believe I may be able to solve the problem!

**Comment by CarJem** [comment]
Well... looking internally... the users are seperated... but the nicknames aren't handled as they should be.....

**Comment by CarJem** [comment]
I purpose a workaround edit to Line 17 of **DiscordChatExporter.Domain.Exporting.Writers.Html.MessageGroupTemplate.cshtml**

What this will do is allow for Tupperbox Bots to ALWAYS use their real names in HTML export!

```cs
var userNick = (Model.MessageGroup.Author.IsBot ? Model.MessageGroup.Author.Name : (userMember?.Nick ?? Model.MessageGroup.Author.Name));
```

**Comment by Tyrrrz** [comment]
Do I understand it correctly, `Model.MessageGroup.Author.Name` evaluates to the correct impersonated name, while `userMember?.Nick` doesn't?

**Comment by CarJem** [comment]
Yeah.. because the username changes when the id doesn't and the utility only scans nicknames once.

**Comment by Tyrrrz** [comment]
I see, so the nick gets evaluated to what it was set when the first message was sent? I'm surprised that the bot's name actually gets changed between messages, in addition to nick. But if that's the case, then your suggested fix makes sense. The question though, could it backfire somehow? Could there be a situation where the export would show bot's name, but we'd rather have it show bot's nick.

**Comment by CarJem** [comment]
I definitely could backfire.... which is why I presented it as a temporary fix....

**Comment by Tyrrrz** [comment]
Can you make a PR with your fix?

**Comment by CarJem** [comment]
Sure!

**Comment by CarJem** [comment]
You should re-open this for the fact that it's a temporary fix... which is bound to have issues down the road

**Comment by Tyrrrz** [comment]
Someone will open a new issue again then, it's fine. There are no permanent fixes in software development.

**Comment by CarJem** [comment]
Ok then, I just feel like this fix was applied willy nilly.
