### ISSUE TITLE
[GUI] Select Messages by Time & Date

### ISSUE THREAD

**Issue by CarJem** [Tyrrrz/DiscordChatExporter#349]

**Comment by Tyrrrz** [comment]
Can you explain what you mean?

**Comment by CarJem** [comment]
Like the GUI can be used currently to get messages between start date and end date, but not start date and time and end date and time.

**Comment by Tyrrrz** [comment]
This looks like a duplicate of #36

**Comment by CarJem** [comment]
Yeah it does... any idea if we could push progress towards this... it would be really useful
