### ISSUE TITLE
[CLI] Export by category?

### ISSUE THREAD

**Issue by Sysnomid** [Tyrrrz/DiscordChatExporter#351]
I was trying to group export some messages via category, and I was not able to do so. I can't find anything on the wiki pertaining to exporting via category(or maybe I haven't looked hard enough)

What is the CLI way to export by category?

Related Issues:
#77 
#195

**Comment by Tyrrrz** [comment]
You can get a list of all channels, regex them by category followed with a slash, then get the corresponding IDs, then export them.

**Comment by Tyrrrz** [comment]
There's an example on Wiki that can get you started: https://github.com/Tyrrrz/DiscordChatExporter/wiki/Scheduling-exports-with-Cron
