### ISSUE TITLE
[GUI] Collapsible categories in channel list

### ISSUE THREAD

**Issue by CarJem** [Tyrrrz/DiscordChatExporter#353]
I've made some minor modifications to the current source to allow for it...
May request for a pull request if I can get used to how to always match a fork with the current branch....
![image](https://user-images.githubusercontent.com/18092668/89458498-1d1e8780-d735-11ea-8b60-0ba382e7d660.png)

**Comment by Tyrrrz** [comment]
Looks nice, a PR would be cool :)

**Comment by CarJem** [comment]
Also, heads up I'm also working on Time Offsets as well!

**Comment by CarJem** [comment]
And we are done with that too!
![image](https://user-images.githubusercontent.com/18092668/89460639-9a97c700-d738-11ea-9806-d25f40febb1e.png)

**Comment by CarJem** [comment]
These changes are now in #354
