### ISSUE TITLE
Want to add exporter to my bot

### ISSUE THREAD

**Issue by xPolar** [Tyrrrz/DiscordChatExporter#357]
How would I be able to add the exporter to my own bot that's written in discord,py, so for example I would do `?export (Message Count)` and it'll export the amount of messages.

**Comment by Tyrrrz** [comment]
You would use the CLI (probably running in Docker) and use your bot to execute it as a spawned process.

**Comment by xPolar** [comment]
Hey there, could you further explain this, kind of confused about how to do so.

**Comment by xPolar** [comment]
Nevermind.
