### ISSUE TITLE
About getting more accuracy in time

### ISSUE THREAD

**Issue by CatchMeIfYouCan4401** [Tyrrrz/DiscordChatExporter#358]
I have used the software it's amazing, but how to get messages for a particular time interval in hours or maybe in minutes if possible.  
Currently we get messages in a particular day which for active servers is just too much, hence I opened this issue.  
Given the amount of amazing work done by you, it should be a piece of cake :)

**Comment by Tyrrrz** [comment]
Try the latest CI build: https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/199571800
