### ISSUE TITLE
Export all Channel in a server / category in a row

### ISSUE THREAD

**Issue by Mara-Li** [Tyrrrz/DiscordChatExporter#359]
I wanna know if it possibles to add the function to export all Channel from a server and or a category in a row (maybe with some limits...). It will be very usefull if it possibles !

**Comment by Tyrrrz** [comment]
If you are using GUI, you can multiselect channels with Ctrl/Shift.

**Comment by Mara-Li** [comment]
Oh ! 
Nice ! Thanks
