### ISSUE TITLE
Issue with the new version. It doesn't recognize NETcore

### ISSUE THREAD

**Issue by CananaMan** [Tyrrrz/DiscordChatExporter#360]
I attempted reinstalling netcore, reinstalling the discord chat exporter, deleting everything and restarting, but I get the same issue.
![image](https://user-images.githubusercontent.com/46144221/90015824-bd613880-dc6e-11ea-9392-ec243365eab7.png)

**Comment by CananaMan** [comment]
![image](https://user-images.githubusercontent.com/46144221/90016033-06b18800-dc6f-11ea-8bc5-d6030d066f7d.png)
Using Windows 10

**Comment by Tyrrrz** [comment]
Did you download the Desktop Runtime or the Base Runtime?
