### ISSUE TITLE
Field to export only text containing

### ISSUE THREAD

**Issue by ChrisWylie80** [Tyrrrz/DiscordChatExporter#361]
I have a project where it would be very useful to be able to extract only text entries from a discord channel that contain a certain term.  For example, it would be great to only be able to export any entries that contain or start with 'REPORT:'.

I was thinking it could possibly be an additional 'text contains' field in the advanced settings below the date range fields.
Could possibly be useful for other people also,  thought i would suggest it.

**Comment by Tyrrrz** [comment]
Probably won't be a separate field, but implemented as part of #160.
