### ISSUE TITLE
User token doesn't work

### ISSUE THREAD

**Issue by sj-dan** [Tyrrrz/DiscordChatExporter#362]
I'm not sure if discord themselves did this, but putting in any user token results in "Authentication token is invalid".

**Comment by Tyrrrz** [comment]
Can you try opening Discord in browser and logging in? Maybe you have to complete 2FA.

**Comment by flleeppyy** [comment]
I'm getting this too, but its a bot token? How am I supposed to do 2FA with a bot?

**Comment by Tyrrrz** [comment]
You shouldn't need to do 2fa with a bot.
