### ISSUE TITLE
Download multiple servers at once

### ISSUE THREAD

**Issue by lorenzyet** [Tyrrrz/DiscordChatExporter#363]
I know there is the option to download all chats in a server, but how can I download all chats of all servers?

**Comment by Tyrrrz** [comment]
![You can't do that](https://media1.tenor.com/images/6fe8ef8b3b4cd1853fff45826cf3cd23/tenor.gif?itemid=18020168)

**Comment by wyattscarpenter** [comment]
@lorenzyet I made a bash script to do this, hope this helps! https://github.com/Tyrrrz/DiscordChatExporter/issues/274#issuecomment-638386963
