### ISSUE TITLE
Auto export after period of time

### ISSUE THREAD

**Issue by gmanc2** [Tyrrrz/DiscordChatExporter#364]
It would be extremely useful to auto-export to a file every x minutes or days. I'm using a script to read the messages sent in that file. Unless anyone has a better way of using your acct token and not a bot to read messages off discord I would like to continue to use thing script but I need it to be automatically updating.

**Comment by Tyrrrz** [comment]
See **Export Scheduling with CLI** on [wiki](https://github.com/Tyrrrz/DiscordChatExporter/wiki#guides).
