### ISSUE TITLE
Are there drawbacks to using a Bot token instead of a User token? 

### ISSUE THREAD

**Issue by B-Knight49** [Tyrrrz/DiscordChatExporter#371]
Using the Bot is safer since it technically doesn't break Discord's TOS. Is it therefore just a blanket advantage over the User method, or are there drawbacks to using it?

If using the API, Bot's are limited to 100 API requests in a short period. Any more and it's classed as spam and can get your access revoked. Does this use the Discord API or does it merely "read" the channel like a User might?

**Comment by Tyrrrz** [comment]
Besides the tighter rate limits, when using bot tokens, you also can't get direct messages because they are not available using REST API.

> Does this use the Discord API or does it merely "read" the channel like a User might?

Not sure what "merely "read" the channel like a User might" means. I guess the answer is "yes" to both.

**Comment by B-Knight49** [comment]
Apologies, I was just making simplified assumptions about the way the program works. 

Given Discord's rate limits, I expected the program to work similarly to if a User just scrolled-up on their chat logs - as opposed to fetching the messages from the API. Not sure what the reality is but I managed to use our bot just fine to get a full chatlog of 1000+ messages, so am happy.

Will close. Thanks

**Comment by Tyrrrz** [comment]
> Not sure what the reality is

It uses the same API in both cases.
