### ISSUE TITLE
Categories export?

### ISSUE THREAD

**Issue by ljodell** [Tyrrrz/DiscordChatExporter#375]
Is there a way using the CLI to export all channels in a category on a guild? To clarify, I see that #195 is marked as done, but I don't see anything in the wiki explaining if selecting by category for export is possible on the CLI, or if it's just that the outputs are marked with the category they're from.

**Comment by Tyrrrz** [comment]
The `channels` command prints categories in addition to channel names. You can use it to parse the IDs of the channels you want to export.
