### ISSUE TITLE
Exporting messages using user ID

### ISSUE THREAD

**Issue by Liz-chan** [Tyrrrz/DiscordChatExporter#376]
Hi, would it be possible to add a feature where you could export a DM, channel, or server, just by using the corresponding ID?

**Comment by Tyrrrz** [comment]
Hi. Not sure what you mean by that. How would that work?

**Comment by Liz-chan** [comment]
Well, let's say you have someone's user ID, if someone wants to download the conversation associated with that person, you could prompt a dialog where they could input the ID and then it starts downloading the conversation between them.

For example, let's say we had a conversation but I removed you from my DM list, but I still had your ID, therefore if I wanted to download our conversation I could just use your ID instead of trying to bring your conversation back to the DM list.

**Comment by Tyrrrz** [comment]
Unfortunately, I don't think that's possible. Discord doesn't provide a way to resolve a channel ID based on a user ID.

**Comment by Liz-chan** [comment]
Hmm, wouldn't you be able to open the channel with the ID, and then now that the channel is open, you can then start to export it?

**Comment by Tyrrrz** [comment]
The channels have their own IDs, they are not associated with a user.
