### ISSUE TITLE
Mac OSX Instructions

### ISSUE THREAD

**Issue by spydmobile** [Tyrrrz/DiscordChatExporter#377]
Hi, it would seem I am to:
- install the dotnet for mac
- download the CLI zip
- Extract it.... then what?

**Comment by Yudi** [comment]
Try [these instructions](https://github.com/Tyrrrz/DiscordChatExporter/wiki/macOS-usage-instructions).

**Comment by spydmobile** [comment]
> Try [these instructions](https://github.com/Tyrrrz/DiscordChatExporter/wiki/macOS-usage-instructions).

Thank you! Thats what I needed!
