### ISSUE TITLE
 Overwrite function

### ISSUE THREAD

**Issue by byspeece** [Tyrrrz/DiscordChatExporter#378]
I have created a script to automatically download images from channels on my Discord server.
But after the second download, I get file_name1.jpg and file_name1 (1) .jpg, and it's the same photo. Can you apply overwrite functions?
System - Linux Arch

**Comment by Tyrrrz** [comment]
It's not a good idea to overwrite files without explicit user confirmation. If you're running this from a script, just delete the directory yourself.

**Comment by byspeece** [comment]
I save everything in one folder and i get the same photo in two files.

**Comment by byspeece** [comment]
Although it could be more said that it would be useful to have a function that would either not allow you to download files that already exist, or would create a new folder when it detects files with the same name and puts all duplicates there.

**Comment by Tyrrrz** [comment]
Generally, I try to avoid additional options or branching workflows and just stick to the safest path of least resistance and let the user deviate on their own if they need to.

**Comment by byspeece** [comment]
Of course, you are the developer of the software, and it is up to you what development path will go. Your program suited me because of the way it works, stability and convenience. But unfortunately I miss this one feature, after the 11th script launch, I have 11 the same photos in the catalog. And still looking for a solution to this.

**Comment by Tyrrrz** [comment]
Can you not delete the directory as part of your script? The name is always `{file_name}_Files`.

**Comment by byspeece** [comment]
Yes, I can, but I don't really want to download every time 100 files + more new ones every time

**Comment by Tyrrrz** [comment]
Ah so what you want is not an "overwrite" function but a "don't download if exists" function.
