### ISSUE TITLE
Feature Request: direct export to mysql

### ISSUE THREAD

**Issue by rygos** [Tyrrrz/DiscordChatExporter#383]
Hello,

is it possible to create a export directly to a mysql database? For now i have to export to csv and use a additional software to import this csv to a mysql database.
Maybe with skipping of already imported Messages?

**Comment by Tyrrrz** [comment]
This was requested in #257 and closed as out of scope.

Please read this comment for more info: https://github.com/Tyrrrz/DiscordChatExporter/issues/257#issuecomment-692212385
