### ISSUE TITLE
[HTML] Emoji Issue

### ISSUE THREAD

**Issue by alhassanv** [Tyrrrz/DiscordChatExporter#385]
Hey, I have an issue with this emoji: 🛡️

NOTE: The emoji is used as a reaction.
![](https://pixelz.cloud/287164043591024641/4d036e3b-9315-408e-986a-b7e6cc1112eb.png)

**Comment by andrewkolos** [comment]
I failed to reproduce this issue. Running newest version, 2.23.
![image](https://user-images.githubusercontent.com/9027551/94494517-6206ed80-01bd-11eb-9f43-7badb423218c.png)

**Comment by alhassanv** [comment]
> I failed to reproduce this issue. Running newest version, 2.23.
> 
> ![image](https://user-images.githubusercontent.com/9027551/94494517-6206ed80-01bd-11eb-9f43-7badb423218c.png)
> 
> edit: Used GUI.

I used the CLI

**Comment by Tyrrrz** [comment]
CLI/GUI work the same in terms of the output they produce.
Are you using latest version @alhassanv?

**Comment by alhassanv** [comment]
> CLI/GUI work the same in terms of the output they produce.
> Are you using latest version @alhassanv?
> Did you have the `--media` flag as well?

I'm not sure which version I'm on and I did not use the `--media` flag

**Comment by Tyrrrz** [comment]
You can run `--version` to find out.

**Comment by alhassanv** [comment]
I'm way back - I'm at 2.14

**Comment by Tyrrrz** [comment]
Downloading a new version will likely fix your issue.
