### ISSUE TITLE
Option to disable avatar and reactions export for media download

### ISSUE THREAD

**Issue by AlexanderRitter02** [Tyrrrz/DiscordChatExporter#386]
Arguably, neither reactions to messages nor user avatars convey a lot of meaning.
However they can clutter up your export folder really easily.

I suggest adding **fine grained options** for media downloads to selectively disable downloading of user avatar pictures and reaction pictures.

This may look like this, with everything checked by default:
- [ ] Also export media
  - [ ] User avatars
  - [ ] Reactions/Emojis
  - [ ] Other media

You can then unselect what you don't want.

**Comment by thecakeisalie25** [comment]
I'd also recommend splitting reactions/emojis into custom emojis and default emojis, because at present it downloads stock discord emojis as well.

**Comment by PatPeter** [comment]
With "Also export media" it needs to be separated into:

- [ ] Download attachments (image uploaded to attachment)
- [ ] Download embeds (someone pastes an image link)
- [ ] Download thumbnails (website preview like Twitter)
- [ ] Download emojis
- [ ] Download avatars

Downloading attachments is a necessity, downloading embeded links can be useful if they're Discord links, and downloading thumbnails is honestly not very useful unless the website is ephemeral.

**Comment by Tyrrrz** [comment]
Closing as out of scope / low interest
