### ISSUE TITLE
Export with quoting

### ISSUE THREAD

**Issue by ArawnDA** [Tyrrrz/DiscordChatExporter#39]
Can you add a way to export with quoting? We are trying to export an audit log channel and it is only exporting the bot name etc like this 

Dyno#0  [26-Mar-18 07:24 PM]

Dyno#0  [26-Mar-18 10:13 PM]

Dyno#0  [26-Mar-18 11:25 PM]

In the actual channel there is data between each of those lines that is not being exported.

Thank you.

**Comment by Tyrrrz** [comment]
Maybe also related to #30

**Comment by Tyrrrz** [comment]
Closed as duplicate because #42 is the main underlying issue
