### ISSUE TITLE
Add to bot

### ISSUE THREAD

**Issue by liscuate** [Tyrrrz/DiscordChatExporter#390]
I would like to add this directly in my bot using messageid. (Grabs the text from the messageid then saves it to a html page on a certain folder, is this possible?) So pretty much only save an exact message not an entire chat.

The bot is written in Java

**Comment by Tyrrrz** [comment]
No, you're better off crafting your own solution.

**Comment by liscuate** [comment]
Alright, no worries! Thanks for the help tho.
