### ISSUE TITLE
Option to partition messages by day

### ISSUE THREAD

**Issue by Milton1688** [Tyrrrz/DiscordChatExporter#393]
In DCE, there is an option to partition files by number of messages (100, 200, etc.). If one were saving a week's worth of data (ex.: March 3-9, 2020), could an option be there to split messages into partitions of days (March 3, March 4, March 5, etc.) rather than message numbers?

That would be very useful to me. My use case may be pretty particular and it may entail a lot of work on your part, so disregard as necessary. But I thought it would be worth mentioning.

Thanks for the great program you've created!

**Comment by Tyrrrz** [comment]
Decided to descope this, as it introduces quite a bit of complexity. The suggested approach is to automate such kind of delicate exports through CLI, by using `--after` and `--from` with a shifting window of one day. The GUI is designed to be simple to use, so it likely won't have this kind of functionality added.
