### ISSUE TITLE
System.IO.IOException: The response ended prematurely

### ISSUE THREAD

**Issue by Chipsum** [Tyrrrz/DiscordChatExporter#399]
![image](https://user-images.githubusercontent.com/37517008/95527487-58effa80-09cd-11eb-9a8c-6c8475d2faf0.png)

**Comment by Tyrrrz** [comment]
I guess it's time to expand this again:

https://github.com/Tyrrrz/DiscordChatExporter/blob/2a432c0ed2ed3750f059e881a5528abb9d107ee9/DiscordChatExporter.Domain/Exporting/ExportContext.cs#L87-L90

cc: @andrewkolos this is what I was talking about :)
