### ISSUE TITLE
Some formatting not exporting correctly

### ISSUE THREAD

**Issue by Xyrexus** [Tyrrrz/DiscordChatExporter#40]
So to make italics in discord you put an asterix at the beginning and end of the sentence, this exports in the log correctly as italics. 

But if you want to put a sentence between asterisks, and have it appear as a sentence between asterisks, in discord you type \*sentence* and then it will appear as *sentence* rather than italics. But the exported log will appear as \ and then the sentence in italics. 

Would it be possible to account for this?

**Comment by Tyrrrz** [comment]
Related to #20
