### ISSUE TITLE
Is it possible to incorporate deletion functionality?

### ISSUE THREAD

**Issue by ylluminate** [Tyrrrz/DiscordChatExporter#400]
One thing that would be very useful would be to have a delete after export function.  Eg, `dotnet DiscordChatExporter.Cli.dll export -t TOKEN -c CHANNEL --delete-after-export`

Is something like this possible?

**Comment by Tyrrrz** [comment]
No, this would be out of the project's scope.
Maybe this video will help you instead: https://www.youtube.com/watch?v=kvfXYJ7Vt20
