### ISSUE TITLE
System.IO.IOException: Unable to read data from the transport connection

### ISSUE THREAD

**Issue by Chipsum** [Tyrrrz/DiscordChatExporter#402]
`Exporting 60 channels... 0.00 %System.IO.IOException: Unable to read data from t
he transport connection: An established connection was aborted by the software i
n your host machine..
 ---> System.Net.Sockets.SocketException (10053): An established connection was
aborted by the software in your host machine.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(Soc
ketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 to
ken)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|
215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initia
l)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter
 adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination
, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync
(Task copyTask, CancellationToken cancellationToken)
   at DiscordChatExporter.Domain.Internal.Extensions.HttpClientExtensions.Downlo
adAsync(HttpClient httpClient, String uri, String outputFilePath) in D:\a\Discor
dChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Internal\Extensions
\HttpClientExtensions.cs:line 17
   at DiscordChatExporter.Domain.Internal.Extensions.HttpClientExtensions.Downlo
adAsync(HttpClient httpClient, String uri, String outputFilePath) in D:\a\Discor
dChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Internal\Extensions
\HttpClientExtensions.cs:line 17
   at DiscordChatExporter.Domain.Exporting.MediaDownloader.DownloadAsync(String
url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\
Exporting\MediaDownloader.cs:line 37
   at DiscordChatExporter.Domain.Exporting.ExportContext.ResolveMediaUrlAsync(St
ring url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Do
main\Exporting\ExportContext.cs:line 95
   at DiscordChatExporter.Domain.Exporting.Writers.Html.MiniRazorTemplate.Execut
eAsync()
   at MiniRazor.MiniRazorTemplateDescriptor.RenderAsync(Object model)
   at DiscordChatExporter.Domain.Exporting.Writers.HtmlMessageWriter.WriteMessag
eGroupAsync(MessageGroup messageGroup) in D:\a\DiscordChatExporter\DiscordChatEx
porter\DiscordChatExporter.Domain\Exporting\Writers\HtmlMessageWriter.cs:line 44

   at DiscordChatExporter.Domain.Exporting.Writers.HtmlMessageWriter.WriteMessag
eAsync(Message message) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordC
hatExporter.Domain\Exporting\Writers\HtmlMessageWriter.cs:line 64
   at DiscordChatExporter.Domain.Exporting.MessageExporter.ExportMessageAsync(Me
ssage message) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExport
er.Domain\Exporting\MessageExporter.cs:line 68
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(Ex
portRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordCh
atExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 56
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(Ex
portRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordCh
atExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 40
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(Ex
portRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordCh
atExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 62
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.<>c__Displ
ayClass4_0.<<ExportMultipleAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\D
iscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBa
se.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.<>c__DisplayClass2_0`
1.<<ParallelForEachAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordCh
atExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.ParallelForEachAsync[
T](IEnumerable`1 source, Func`2 handleAsync, Int32 degreeOfParallelism) in D:\a\
DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\Asy
ncExtensions.cs:line 29
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.ExportMult
ipleAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporte
r\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleComman
dBase.cs:line 68
   at DiscordChatExporter.Cli.Commands.ExportGuildCommand.ExecuteAsync(IConsole
console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli
\Commands\ExportGuildCommand.cs:line 18
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadO
nlyDictionary`2 environmentVariables)`

.....
![image](https://user-images.githubusercontent.com/37517008/95649720-d3587180-0ad6-11eb-8a50-3a543c8ce31a.png)

It was about 76% when it crashed

**Comment by Tyrrrz** [comment]
Sounds like something aborted the connection. Antivirus? Firewall? Network change?

**Comment by Chipsum** [comment]
A network change yes.
So basically it doesn't resume ?

**Comment by Tyrrrz** [comment]
No, it doesn't.

`IOException` could be potentially added into retry policy here: https://github.com/Tyrrrz/DiscordChatExporter/blob/c4007d4a8020ce185e87057ae3f2e5dc09718374/DiscordChatExporter.Domain/Discord/DiscordClient.cs#L31-L46

Not sure how exactly it would work out though. Would have to test if it helps it recover from network changes.

**Comment by Tyrrrz** [comment]
Actually, nevermind, this happened as part of media downloader which doesn't use the same retry policy, so it would have to be changed somewhere else or generalized.

Are network changes something that happens really often for you?

**Comment by Chipsum** [comment]
> Are network changes something that happens really often for you?

Yeah , I suffer from that we have a bad ISP in the country I live in.
