### ISSUE TITLE
Group names are incorrectly shown as list of participants

### ISSUE THREAD

**Issue by BoltPow3r** [Tyrrrz/DiscordChatExporter#41]
Is this a bug/missing feature or is this program not intended for this purpose?

thanks :p

**Comment by Tyrrrz** [comment]
Should work although I never tested it. What happens?

**Comment by BoltPow3r** [comment]
Okay that was quick.  So, uhh, group chats kinda don't show up.

[Some #](https://i.imgur.com/UYA4NVf.png)  are empty, I am guessing because all the people except me, left the group.  

Now, our group name changed to something else and it doesn't show up in the exporter. On second look I do see 2 group chats, but they are named by people who are in the group chat and not by the group chat name

**Comment by Tyrrrz** [comment]
I see. But can you still export them, it's just that it doesn't show or shows incorrect name?

**Comment by BoltPow3r** [comment]
Seems like I can still export them no problem, yes.

Okay, I found the current group chat I am in that I want to export, it is labelled by people in the group and not by the group name.

**Comment by BoltPow3r** [comment]
Would it be possible to have one-click export all chat feature?

I'm gonna hit the sack soon, so if you have any more questions...

**Comment by Tyrrrz** [comment]
It was suggested in #12
