### ISSUE TITLE
DiscordChatExporter.Domain.Execptions.DiscordChatExporterException: Failed to perform an HTTP request.

### ISSUE THREAD

**Issue by QuantumRange** [Tyrrrz/DiscordChatExporter#412]
When the export was complete (it looked like this), it just crashed

![grafik](https://user-images.githubusercontent.com/49843948/96348519-be1cad80-10a9-11eb-9423-189babaebf18.png)

Settings:
```
{
  "DateFormat": "dd-MMM-yy hh:mm tt",
  "IsAutoUpdateEnabled": true,
  "IsTokenPersisted": true,
  "ParallelLimit": 20,
  "LastToken": {
    "Type": 0,
    "Value": ""
  },
  "LastExportFormat": 0,
  "LastPartitionLimit": null,
  "LastShouldDownloadMedia": true
}
```

DiscordChatExporter.runtimeconfig.json
```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.WindowsDesktop.App",
      "version": "3.1.0"
    }
  }
}
```

**Comment by Tyrrrz** [comment]
Ha. The Discord server told you to wait for 30 minutes before making another request.

**Comment by QuantumRange** [comment]
Oh, FUCK.
My discord token was still there.
You can't see the history, right?

**Comment by Tyrrrz** [comment]
No. But for safety, I'd suggest changing your password.
To clarify on your original request: the export crashed because Discord rate limited you and asked to try again in 30 minutes.

**Comment by QuantumRange** [comment]
Okay, thanks
