### ISSUE TITLE
The response ended prematurely

### ISSUE THREAD

**Issue by xenomew2** [Tyrrrz/DiscordChatExporter#414]
When im exporting something, it only exports some of it, and then this happens.  i get this error that says this, and i have no idea why it happens, this has happened every single  time i try to export anything, i reinstalled and restarted my laptop and nothing changed. this issue also happened on my pc. i have no idea why this happens 
![image](https://user-images.githubusercontent.com/18221092/96522842-2b0a8180-1229-11eb-92b7-766ba05ce4ff.png)

**Comment by xenomew2** [comment]
update, im connected to my phone's hotspot which is on mobile data only and i didnt get this error. its probably my router blocking excessive requests or something

**Comment by Tyrrrz** [comment]
Yes, this is some connectivity issue.

**Comment by Tyrrrz** [comment]
Can you try a CI build from here?
https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/312666736

**Comment by Tyrrrz** [comment]
Duplicate of #399
