### ISSUE TITLE
Export format changes

### ISSUE THREAD

**Issue by IdyllicDestroyer** [Tyrrrz/DiscordChatExporter#419]
I have been exporting bulk messages on a weekly basis, and processing them in a google sheet that has been specially set up to handle the data directly copied from a .txt file. Unfortunately, the format of the text in those exports keeps changing, causing errors in my spreadsheet down the line. First, it was a bunch of extra header information at the bottom of the file for some reason, and now messages are exported with two carriage returns between each entry. Since my spreadsheet was setup to delete every third line to ready the data for processing, these rather massive format changes are casing significant problems for me.

Thank you for this awesome app.

**Comment by Tyrrrz** [comment]
Hi.

The plain text format is not meant to be used for automation. If you need to consume output from another program, json is more recommended. There are also no breaking changes in json either.

**Comment by IdyllicDestroyer** [comment]
That actually makes a lot of sense. Thanks.
