### ISSUE TITLE
Modular exporting options

### ISSUE THREAD

**Issue by byurqx** [Tyrrrz/DiscordChatExporter#420]
Love the app. Very close to what I am looking for. I have a learning disability that makes certain reading difficult. I listen to a lot of text to speech in iOS with this app: https://www.voicedream.com/

I was able to successfully use the Discord Chat Exporter GUI version, export to HTML, import into Voice Dream, and it plays via audio. Is there a way to strip out the date and time (and maybe also optionally the usernames)? 

Otherwise it repeats date and time with each message and becomes tedious to listen to.

My ultimate goal is to be able to regularly export a date range of messages I need to catch up on and play them in Voice Dream. 

I am not a programmer though can try and follow instructions if anyone has suggestions about how to accomplish this by modifying the exported file with another program.

Any suggestions are greatly appreciated and thank you again for a wonderful app.

**Comment by Tyrrrz** [comment]
Hi.

There are no plans to add additional formatting options, as it's impossible to support all of the permutations that each individual may be interested in.

I would say your best bet is to use the structured export, i.e. the JSON format, and try to work with that. You can either try to configure your voice over software to read from JSON if it can, or write a script to convert the data inside of it into a format that fits your needs. For the second option, any language capable of working with JSON will do. You can then even use the CLI to create a custom automated pipeline.
