### ISSUE TITLE
Can't run GUI version under WINE

### ISSUE THREAD

**Issue by DouglasDC-3** [Tyrrrz/DiscordChatExporter#421]
[erros.zip](https://github.com/Tyrrrz/DiscordChatExporter/files/5501129/erros.zip)

Hello

I tried to run it under Debian using WINE but the Windows error comes up both in wine and wine64 even though I have .Net Core installed in WINE and Linux . Is this something to be expected? Do I need to compile the source code under Linux to make it work and if so how?

**Comment by Tyrrrz** [comment]
Hi.
I don't think the GUI can be ran under WINE. Maybe @Yudi can chime in.

**Comment by Yudi** [comment]
I'm able to run the latest GUI release with `winehq-stable` on Debian 10 (both freshly installed), so I'm not sure what it could be.

I usually install .NET Core Desktop Runtime by running the installer with wine, then the GUI runs fine.
