### ISSUE TITLE
Ability to export associated roles within a server

### ISSUE THREAD

**Issue by mikeion** [Tyrrrz/DiscordChatExporter#422]
Greetings,

I saw this as a closed issue, but I'm working on a project where it would be important to not only have the user ids associated with the authors of the content, but also the roles that they might hold on the server. Do you think it might be possible to extract these with the data export?

Thanks!

**Comment by Tyrrrz** [comment]
Hi.

This application is only focused on extracting messages. If you need the roles, it would be easier to just use Discord's API yourself to query them.

**Comment by mikeion** [comment]
OK, no worries. Thank you for your work on this :)
