### ISSUE TITLE
Is it possible to download hidden channels restricted by role restriction?

### ISSUE THREAD

**Issue by betrqy** [Tyrrrz/DiscordChatExporter#423]
I know it sounds stupid, but when I was downloading one of my servers, it never said that it couldn't download the channels. Only that it failed to export(showing access denied **after** downloading 100% of the channels. Meaning, that if the exporter can access the channels, is there a way to change the code so you can download these hidden channels? I know its stupid, but I was just wondering.

**Comment by Tyrrrz** [comment]
Nope, you can only see them in the list.
