### ISSUE TITLE
Wiki documentation out of sync with latest CLI flag updates "--reuse-media"

### ISSUE THREAD

**Issue by F-0PS** [Tyrrrz/DiscordChatExporter#424]
Per Latest update V2.24 new argument was added for CLI as well as GUI, this being "--reuse-media".

The wiki though doesn't have documentation regarding this and I feel this is a huge time/data saving function. I am playing with it currently for my exports, but do not feel comfortable to update the wiki regarding it.

It seems at this time you can run the "--reuse-media" without the "--media" argument, but I am not sure if that is intended, or if it enables the --media flag since the --reuse-media flag wouldn't do anything without it.

**Comment by Tyrrrz** [comment]
The wiki is open for edits, so anyone is welcome to improve it.

**Comment by Yudi** [comment]
The _Getting started_ page has been partially updated. <br>It still needs new screenshots and a better proofreading. I'll finish everything later.

**Comment by Tyrrrz** [comment]
The wiki seems to be updated with the new option, so I'm closing the issue.
