### ISSUE TITLE
"Partitions"? not working

### ISSUE THREAD

**Issue by McBobb** [Tyrrrz/DiscordChatExporter#427]
Whatever the option is to "partition" exported chat text doesn't seem to be working. I tried to export a section of a chat that had about 600 messages, but I only got an HTML file with 214 messages. I couldn't find any way to access other "partitions". I've had to set the Messages per Partition to 10 000 just to get all the posts I wanted, but if this "partition" thing actually works, I sure can't figure it out.

**Comment by Tyrrrz** [comment]
The partitions are separate files in the same directory as the first export.
