### ISSUE TITLE
Channel sorting options

### ISSUE THREAD

**Issue by McBobb** [Tyrrrz/DiscordChatExporter#428]
A previous version of the Exporter started sorting the channels in each category of each server by the order they appeared on the Discord Server, and I thanked the Digital Gods for that. It made it so much easier to find the channel I wanted to export, but the latest release went back to sorting the channels in a server category alphabetically.

Please, include an option to toggle between sorting channels, and the channel server categories Alphabetically and By Original Order.

I would greatly appreciate this if you could do this.

**Comment by Tyrrrz** [comment]
> A previous version of the Exporter started sorting the channels in each category of each server by the order they appeared on the Discord Server...

Which version are you talking about? The ordering didn't change for years. Groups were added recently which made the ordering local to groups, but it's still alphabetical.

The choice to have alphabetical ordering was made precisely to make it easier to find channels.

**Comment by McBobb** [comment]
2.24.0 is the one I'm using now, so it would have been the previous version released.

Honestly, I found it so much easier if both the server categories and the channels within the categories were listed in the order they were on Discord. If adding an option to toggle between Alphabetical and Original Order was added, I would be ever so grateful.

**Comment by Tyrrrz** [comment]
Channels are being sorted by their server order for some time now, so I suppose this issue can be closed 🙂
