### ISSUE TITLE
How to partition existing HTML export/file by date?

### ISSUE THREAD

**Issue by Clonemaster641** [Tyrrrz/DiscordChatExporter#429]
I wasn't sure how to figure out this more particular of a situation, and this isn't necessarily an issue with the application itself, but is there a way to partition an existent HTML file by date? I exported an archive of an entire chat recently, that was quite large (1.50 GB) as it goes back to February of 2019 and I instantly realized I was going to need a reasonably sized way to be able to look at it.

So I decided to start exporting it by month and only got as far as the first two before not coming back to it to finish and that chat was deleted on the server it was from before I could do so. 

And I have it all but in that oversized file, but no way to work with any of it from the source by and from which things are typically exported, and it obviously and eventually crashes in my browser when I try to view it - is there a way for this to be sized down into parts so it can be reasonably sized and viewed? I know nothing at all about HTML, so that doesn't help, but I thought to ask. My operating system is Windows.

**Comment by Tyrrrz** [comment]
No, the app can't edit existing exports.

You can do it manually. Open the export in an editor capable of loading large files (e.g. Sublime Text or Notepad++) and split it at message group boundaries. Example:

```html
<div class="chatlog__message-group">
   <div class="chatlog__author-avatar-container">
      <img class="chatlog__author-avatar" src="https://cdn.discordapp.com/avatars/128178626683338752/6c93270b9757fa306faace307018b3bc.png" alt="Avatar">
   </div>
   <div class="chatlog__messages">
      <span class="chatlog__author-name" title="Tyrrrz#5447">Tyrrrz</span>
      <span class="chatlog__timestamp">27-Nov-17 12:12 AM</span>
      <div class="chatlog__message " data-message-id="384466565027987461" id="message-384466565027987461">
         <div class="chatlog__content">
            <div class="markdown"><a href="http://i.img_ur.com_/d7sXMiF.jpg">http://i.img_ur.com_/d7sXMiF.jpg</a> <span class="chatlog__edited-timestamp" title="27-Nov-17 12:13 AM">(edited)</span></div>
         </div>
      </div>
      <div class="chatlog__message " data-message-id="384467309311295488" id="message-384467309311295488">
         <div class="chatlog__content">
            <div class="markdown">* a * </div>
         </div>
      </div>
   </div>
</div>

<!-- Cut after here -->
```

Of course, ideally you'll need to know the basics of HTML to do it properly. Generally browsers' HTML parsers are really lenient so you may get away with some corrupted content though.
