### ISSUE TITLE
Only supports 14-15 days history message to export

### ISSUE THREAD

**Issue by roger125** [Tyrrrz/DiscordChatExporter#43]
Hi  @Tyrrrz 
After testing around 20 times(different time range)
the 2.3/2.4 version only support 14-15 days' history message to export, if surpass 14-15 days, then it will crack out(stop working).
i don't know if it's the program's limit or the discordapp.com's limit to cause it.

Can you address this issue?

Thanks.

**Comment by Tyrrrz** [comment]
Huh that's weird, I'll check

**Comment by Tyrrrz** [comment]
I was not able to reproduce it, I successfully exported several months of chat logs.

**Comment by roger125** [comment]
hi Tyrrrz, 
    i was able to successfully exported several months of chat logs as you last night after seeing your reply, so i can't reproduce it either, so now i think there's some variables which i don't noticed to cause the crack out, actually it does well since the 2.2 version, so it's the 1st time i met the crack.

    Thanks for your test for this issue and this amazing tool, anyway, i will try to capture the screen/log next time if i encounter it again.

**Comment by Tyrrrz** [comment]
Thank you for using it. 😉 
I'll close the issue for now, if you manage to reproduce it, please feel free to re-open it.
