### ISSUE TITLE
CSV format does not convey embed content

### ISSUE THREAD

**Issue by zeroeightysix** [Tyrrrz/DiscordChatExporter#431]
I run a bot that exports a minecraft chat to discord. Its messages look like this:
![image](https://user-images.githubusercontent.com/27009727/99008249-124e6c80-2546-11eb-8dc4-1b561d77d7c6.png)

I'd like to export the logs to CSV, but the content is empty:

```csv
AuthorID,Author,Date,Content,Attachments,Reactions
"709752386108784690","Francis#1542","17-May-20 02:21 AM","","",""
"709752386108784690","Francis#1542","17-May-20 02:21 AM","","",""
"709752386108784690","Francis#1542","17-May-20 02:21 AM","","",""
"709752386108784690","Francis#1542","17-May-20 02:21 AM","","",""
```

**Comment by Tyrrrz** [comment]
Yes, CSV doesn't support embeds.

**Comment by zeroeightysix** [comment]
> Yes, CSV doesn't support embeds. It's a very primitive format.

Yes, but is it too far fetched to introduce a way to e.g. generate a meaningful 'raw string' representation of the embed, or at extra CSV fields for each embed field?

**Comment by Tyrrrz** [comment]
Yeah, because embeds support rich formatting options (columns, inline) and multiple text layers (title, author, content, fields, footer, etc).

It's better to use JSON instead.

**Comment by Tyrrrz** [comment]
Related #225 #237

**Comment by zeroeightysix** [comment]
Alright, thanks. Sorry for not having checked different issues.
