### ISSUE TITLE
Time mismatch in exported chats

### ISSUE THREAD

**Issue by DakshKK** [Tyrrrz/DiscordChatExporter#438]
My timezone is IST, which is +0530 from UTC.

If I export my chats, it shows UTC time instead of IST, and even with the `--dateformat` option it shows the same time. Is it supposed to show only UTC time?

If I put my `--dateformat` as `--dateformat "dd/MM/yyyy HH:mm (ISTK) (UTCK)"` then the date in exported chat shows both as `+00:00`.

**Comment by Tyrrrz** [comment]
The timezone used for formatting dates is taken from the locale settings configured on your operating system.

**Comment by DakshKK** [comment]
`locale` is configured to my current locale of India, and even `timedatectl` shows my time zone to be set to IST, yet it exports with UTC time settings.

**Comment by Tyrrrz** [comment]
That sounds like a bug then. You can try debugging and see what causes it.

The relevant pieces are here:

https://github.com/Tyrrrz/DiscordChatExporter/blob/9df98b0405eaac0857b4e0d14cf2604a8210d966/DiscordChatExporter.Domain/Exporting/ExportContext.cs#L40-L45

https://github.com/Tyrrrz/DiscordChatExporter/blob/9df98b0405eaac0857b4e0d14cf2604a8210d966/DiscordChatExporter.Domain/Internal/Extensions/DateExtensions.cs#L14-L15
