### ISSUE TITLE
Timed backups

### ISSUE THREAD

**Issue by urmommagey** [Tyrrrz/DiscordChatExporter#439]
Is there any idea to add a option to let the user set a timer to have a server get auto downloaded? I want to keep a log of one of my servers and just have it go automatically.

**Comment by Tyrrrz** [comment]
No, such functionality will not be built-in. You can already do scheduling via CLI and native tools in your operating system. See wiki: https://github.com/Tyrrrz/DiscordChatExporter/wiki#guides.
