### ISSUE TITLE
Not able to find .exe file

### ISSUE THREAD

**Issue by TheFurryFeline** [Tyrrrz/DiscordChatExporter#442]
Basically on the tin there. I just downloaded this app but per the wiki's instructions, I'm unable to find the .exe file to be able to begin using it. I downloaded the .zip, extracted, but no .exe file seems to be present.

**Comment by santiagocasasrey** [comment]
You can find .exe and .dll files in [https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/379170580](https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/379170580) artifacts

**Comment by TheFurryFeline** [comment]
I'd've thought it would have been included onto the main code files that I downloaded. Nonetheless, thank you for the help!
