### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by bestlinuxgamers** [Tyrrrz/DiscordChatExporter#443]
Hello,
Thank you very much for this wonderful project.
I have used the project and now I would like to share my wishes/suggestions.
First of all it would be helpful to include the exportguild command from the CLI into the GUI.
I noticed that the media is not downloaded. I think that this "problem" has already been mentioned here, but for the sake of completeness I will mention it again.
Now a bigger wish:
I would like to see an export option that copies the complete discord-guild, including voice-channels, roles, permissions, etc. Afterwards in the export the design will look like the original server, being available offline, but that you can view it's whole structure and all the settings, not just the individual chats of the channels

**Comment by Tyrrrz** [comment]
Hello.

> First of all it would be helpful to include the exportguild command from the CLI into the GUI.

You can multi-select channels in the GUI.

> I noticed that the media is not downloaded. I think that this "problem" has already been mentioned here, but for the sake of completeness I will mention it again.

Not sure what you mean here.

> I would like to see an export option that copies the complete discord-guild, including voice-channels, roles, permissions, etc. Afterwards in the export the design will look like the original server, being available offline, but that you can view it's whole structure and all the settings, not just the individual chats of the channels

This has been mentioned, but it goes outside of the scope of the project and will likely never be implemented.

**Comment by bestlinuxgamers** [comment]
> You can multi-select channels in the GUI.

Yes, that's why I also said

> it would be **helpful** to include

Especially on guilds with a lot of chats it is a bigger effort to click all channels manually. (not downloading it separately)

> Not sure what you mean here.

This is just the fact that media such as images, audio etc. are not downloaded, only a link with a reference to it is saved.

> This has been mentioned, but it goes outside of the scope of the project and will likely never be implemented.

A pity. Would such a function theoretically be added to the project if someone else programmed it and made a pull request?

**Comment by Tyrrrz** [comment]
> Especially on guilds with a lot of chats it is a bigger effort to click all channels manually. (not downloading it separately)

Try pressing Ctrl+A:

![dce](https://user-images.githubusercontent.com/1935960/100654144-0fc78180-3352-11eb-9702-379b1ac0afd1.gif)

> This is just the fact that media such as images, audio etc. are not downloaded, only a link with a reference to it is saved.

Have you tried the "Download media" option?

![image](https://user-images.githubusercontent.com/1935960/100654199-2241bb00-3352-11eb-84cb-9411dad339e4.png)

> A pity. Would such a function theoretically be added to the project if someone else programmed it and made a pull request?

Most likely not, unless the implementation would be unexpectedly small.

**Comment by bestlinuxgamers** [comment]
Many thanks for the answers.
I didn't know until now that the functions are already implemented.
Thank you very much.

**Comment by Tyrrrz** [comment]
You're welcome.
