### ISSUE TITLE
Incremental updates when exporting a channel/conversation

### ISSUE THREAD

**Issue by Hawpe** [Tyrrrz/DiscordChatExporter#444]
This would have two benefits:

- Automatically download only new content/messages
- Prevent the loss of content/messages when something gets deleted from a channel/conversation you have already exported, then you overwrite that same file

**Comment by Tyrrrz** [comment]
Hi.

This feature has been already suggested at #295 #32.
Updating existing exports is out of scope and probably won't be implemented. Your best bet is to do regular exports partitioned by timespans (for example every day). You can use the CLI to automate this process with the help of various scheduling utilities.
https://github.com/Tyrrrz/DiscordChatExporter/wiki/Scheduling-exports-on-Windows

**Comment by para-droid-ai** [comment]
is there a current solution/idea regarding this?
