### ISSUE TITLE
DCE not launching despite multiple tries across multiple versions

### ISSUE THREAD

**Issue by SpookRooster** [Tyrrrz/DiscordChatExporter#445]
hello. it's been a while since i have been able to launch and run a logging process using this software (since january 26th of this year). since then, i have tried on and off, but have not been able to. the program, upon executing it, does not respond in any way. it does not crash, nor does it show up as a process in task manager. 

this is a snapshot using piriform speccy just moments ago - http://speccy.piriform.com/results/VjCgKTVgsuXhZ6UW57beUn3

i have tried to launch this with and without discord running, as i seem to recall it needing to be closed for DCE to function.

**Comment by Tyrrrz** [comment]
Did you install .NET Runtime?
https://github.com/Tyrrrz/DiscordChatExporter/wiki/Install-.NET-Core-runtime

**Comment by SpookRooster** [comment]
> Did you install .NET Runtime?
> https://github.com/Tyrrrz/DiscordChatExporter/wiki/Install-.NET-Core-runtime

welp...i almost had .NET 3.1. sad that it was that simple. thanks
