### ISSUE TITLE
Can DCE download a conversation with a Deleted User#0000 with only User ID? 

### ISSUE THREAD

**Issue by Haitaroo** [Tyrrrz/DiscordChatExporter#446]
Title explains itself

**Comment by Tyrrrz** [comment]
If you can see it in the app itself, then most likely yes. Have you tried?

**Comment by Haitaroo** [comment]
I can't see it in the app, because I closed it, but I still have The USER ID

**Comment by Tyrrrz** [comment]
Then you can't I guess.

**Comment by ischoonover** [comment]
you can get message history with deleted users in this circumstance by doing a data request through discord account settings. doesn't include local media, instead links to discord cdn, but if the files werent deleted by the user, you can fetch them yourself remotely.
