### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object Error

### ISSUE THREAD

**Issue by Karl-von-Karl** [Tyrrrz/DiscordChatExporter#447]
Hi,
This error happens when I have my token in the submit box and press the button to execute the program:
![discord Exporter bug report](https://user-images.githubusercontent.com/50247630/101202555-6e814980-3637-11eb-823d-f2913ca8cadc.png)

I followed the installation instructions found on the wiki. Looked through the known issues section and didn't find a similar problem, so figured I would report. System: Windows x64 with the x64 .NET Core v3.1 runtime.

**Comment by Tyrrrz** [comment]
It looks like an exception happened while trying to handle another exception. Does this error appear consistently?

**Comment by Karl-von-Karl** [comment]
Yes every time I hit the button to execute the program with my discord token in the token field.

**Comment by Tyrrrz** [comment]
Try the latest CI build. This error should be gone, but given that it was happening consistently, it may reveal some other issue.

https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/406027080
