### ISSUE TITLE
Maybe add an option to get all messages before/after a certain date?

### ISSUE THREAD

**Issue by miclol** [Tyrrrz/DiscordChatExporter#449]
This has several benefits like if you just want to log today's chat, you don't need to go through an entire month's chat just to get the final day.

**Comment by Tyrrrz** [comment]
Are you referring to a feature that's already implemented?

![image](https://user-images.githubusercontent.com/1935960/101674896-be11ac00-3a61-11eb-912f-c42cdd1f8497.png)

**Comment by miclol** [comment]
Ah. I see my mistake. Good day to you, and thank you for your support.
