### ISSUE TITLE
Make it work with bot token

### ISSUE THREAD

**Issue by thisisjvgrace** [Tyrrrz/DiscordChatExporter#45]
Currently it only accepts user tokens, but it would be great if you can make it work with bot tokens as well.

**Comment by yonilerner** [comment]
Im not experienced enough with .NET at all to provide a complete solution for this, but I was able to get it working with a bot token by adding the following line to the very start of `DataService#GetStringAsync`:
```csharp
_httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bot", "BOT TOKEN HERE");
```
(Obviously replace `BOT TOKEN HERE` with the actual token)

**Comment by fortepc** [comment]
Currently using this app puts your discord account at risk, as it's use goes against discord TOS. Making the same exact functionality except remove the ability to use a user token, and instead replace it with a bot token.

**Comment by Tyrrrz** [comment]
This is scheduled for next release

**Comment by thisisjvgrace** [comment]
um where is `DataService#GetStringAsync`? I can not find it @yonilerner

**Comment by yonilerner** [comment]
@thisisjvgrace It looks like that method was removed in https://github.com/Tyrrrz/DiscordChatExporter/pull/63 The best equivalent now is probably `DataService#GetApiResponseAsync`, but I have not tested it, and do not have time to

**Comment by KaKi87** [comment]
Hello, I'm using v2.20.0, and trying to use a bot token returns
> Authentication token is invalid.
Thanks

**Comment by Tyrrrz** [comment]
@KaKi87 
consult with the wiki: https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs#how-to-get-a-bot-token

**Comment by jvluso** [comment]
I followed that process but am still seeing this error. Is there something I need to do to specify that it is a bot?

**Comment by Tyrrrz** [comment]
On GUI, you need to click on the icon to the left of the token until it shows a robot.
On CLI, you need to specify `--bot`.
