### ISSUE TITLE
[JSON] Don't escape non-control and non-special Unicode characters in strings

### ISSUE THREAD

**Issue by Sanqui** [Tyrrrz/DiscordChatExporter#450]
Hello, I'm looking into operating DiscordChatExporter for personal backups.  From the perspective of an archivist, I want to use the JSON format to preserve as much metadata as possible.  A secondary goal is ease of searching (i.e. grep).  Currently DiscordChatExporter seems to escape non-ASCII characters in strings, e.g. as follows:
```json
  "channel": {
    "id": "286894854376783882",
    "type": "GuildTextChat",
    "category": "Text",
    "name": "oznameni-announcements",
    "topic": "Zde se stru\u010Dn\u011B dozv\u00EDte o v\u0161em d\u016Fle\u017Eit\u00E9m: akce, \u010Dl\u00E1nky, zm\u011Bny..."
  },
```

For readability and grepability it would be much more useful if DiscordChatExporter stored real UTF-8, i.e.
```json
    "topic": "Zde se stručně dozvíte o všem důležitém: akce, články, změny..."
```
It would surely help reduce file-size too, particularly for languages that don't use the Latin alphabet.

Would an option for UTF-8 JSON export be feasible?

**Comment by Tyrrrz** [comment]
Hi @Sanqui.
I don't think that can be changed on the JSON writer that DCE uses. However, any JSON parser should be able to unescape those automatically anyway. It's probably a better idea to use a more structured approach and parse the content first instead of using grep directly.

**Comment by Sanqui** [comment]
Looks like it's [possible](https://stackoverflow.com/a/58003397) by using `UnsafeRelaxedJsonEscaping`, the linked case is a bit different, but in case of the [used Utf8JsonWriter](https://github.com/Tyrrrz/DiscordChatExporter/blob/master/DiscordChatExporter.Domain/Exporting/Writers/JsonMessageWriter.cs#L13) it should be possible by passing [JsonWriterOptions](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonwriteroptions?view=net-5.0) with a custom encoder.  I might look into it if it would be welcome.  The name "Unsafe" sounds scary but in case of saving a file to disk there's no risk, quotes and control characters look to be escaped as normal.

**Comment by Tyrrrz** [comment]
Hm, I wonder why they called it "unsafe". Can you investigate what are the potential drawbacks?
If there aren't any, I'm happy with implementing a change to make this the default behavior (no need to introduce an option).

**Comment by Tyrrrz** [comment]
Looking at the JSON spec, it seems only `"`, `\` and control characters must be escaped.

![image](https://user-images.githubusercontent.com/1935960/101995651-3bdcee00-3cd4-11eb-9693-aaff934ae6a8.png)

**Comment by Sanqui** [comment]
So there is an article on this topic in the dotnet docs: [How to customize character encoding with System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-character-encoding).  Under *Serialize all characters*, a caution is provided about the potential risks.  They concern output into JavaScript or HTML files.  Since DiscordChatExporter outputs into a JSON file which will always be parsed by further tools as JSON there is no risk for anything like a XSS vector.

The advantages are more readable files and smaller file sizes.
There should be no downside to this, but the change might break somebody's workflow.

**Comment by Tyrrrz** [comment]
@Sanqui very well 👍
