### ISSUE TITLE
[CLI] Display more information when "Access is forbidden."

### ISSUE THREAD

**Issue by Sanqui** [Tyrrrz/DiscordChatExporter#451]
It would be useful if DiscordChatExporter could show the channel ID and perhaps name printing the "Access is forbidden." error.

I'm interested in working on this as a first issue, so I'm mostly posting this as a note to myself.  🙂

**Comment by Tyrrrz** [comment]
Are you referring to CLI or GUI?

**Comment by Sanqui** [comment]
Sorry, this is concerning the CLI.  Example output for exporting a server:

```Exporting 20 channels... 0,00 % %
Access is forbidden.
Access is forbidden.
Access is forbidden.
Access is forbidden.
Access is forbidden.
Access is forbidden.
Access is forbidden.
Access is forbidden.
Access is forbidden.
Access is forbidden.
Access is forbidden.
Successfully exported 9 channel(s).
```

**Comment by Tyrrrz** [comment]
That would be here:

https://github.com/Tyrrrz/DiscordChatExporter/blob/61d0ddeced2205482bdcbb501260df7b75a61cf3/DiscordChatExporter.Cli/Commands/Base/ExportMultipleCommandBase.cs#L64
