### ISSUE TITLE
[JSON] Field name consistency with the official API

### ISSUE THREAD

**Issue by Sanqui** [Tyrrrz/DiscordChatExporter#454]
The JSON export currently uses fields with different capitalization rules and sometimes even wording differences compared to the official API.  For instance, `timestampEdited` and `isPinned`, which are subtly different from the official `edited_timestamp` and `pinned`.  I feel like this is unnecessary and confusing for everybody who has to work with it.  While it would be a breaking change for the project, I would seriously consider introducing consistency with official fields where possible.

**Comment by Tyrrrz** [comment]
This is on purpose actually. There is no attempt to keep the field names in sync because DCE's domain representation is vastly different from the Discord's API in several places.
