### ISSUE TITLE
DiscordChatExporter (v2.25) not opening

### ISSUE THREAD

**Issue by cumm16** [Tyrrrz/DiscordChatExporter#457]
Hi, when trying to open the latest release of Discord chat exporter(2.25) I keep getting a popup saying that .NET core is not installed, when I have installed it, multiple times. 

Pop-up:
https://i.imgur.com/pG5HJre.png

Dotnet installed:
https://i.imgur.com/qfjF2eu.png

**Comment by Tyrrrz** [comment]
Looks like you installed x86 version of .NET on a x64 system. That's probably why it doesn't work.
