### ISSUE TITLE
How to modify to copy text from channels and paste to a different server?

### ISSUE THREAD

**Issue by aimtech-exe** [Tyrrrz/DiscordChatExporter#460]
This is such a dope program. Instead of exporting the whole log, I wanted to modify what you've done here.

**My Goal:** Copy **new messages** from **multiple designated channels** in one server, paste them into designated channels in **another server**.

I'm new to coding for the most part, so please let me know if you can help me with this or point me in the right direction for what to edit. I've been trying to build a web scraper to do this but no luck yet, and it looks like the code you've written would be the perfect foundation.

Thank you and take care!

**Comment by Tyrrrz** [comment]
This is out of scope of this project. Your best bet is just to read the docs on Discord API and try to use it yourself. This project is not a good foundation for what you described.
