### ISSUE TITLE
Wonder if this works on a android phone 

### ISSUE THREAD

**Issue by kaboo312** [Tyrrrz/DiscordChatExporter#461]
I've downloaded this github zipfile on my dell pc and it works wonders 
I'm just trying to find a way to get it on my mobile device and can't seem to have any solutions 
If you can help clarify and give a step by step process of downloading it on my phone that would be of great help I already have the discordexportchat.zip downloaded on my phone in my  internal storage and can't seem to do anything about it. Please help

**Comment by Tyrrrz** [comment]
No, it doesn't.

**Comment by cancerousname69** [comment]
Actually, yes it does, if you use the Termux terminal emulator.

**Comment by Tyrrrz** [comment]
@cancerousname69 hm, have you tried? can you install .NET Runtime there without issues?
