### ISSUE TITLE
How to export csv in the mac command line?

### ISSUE THREAD

**Issue by moneypigtrading** [Tyrrrz/DiscordChatExporter#463]
how can I export csv in the Mac command line? don't see any instruction in Read.me or --help

dotnet DiscordChatExporter.Cli.dll export -t token -c channel-ID 

seems to only return HTML

dotnet DiscordChatExporter.Cli.dll export -t token -c channel-ID  > test.csv

seems to return a non-readable csv

Thank you!

**Comment by Tyrrrz** [comment]
https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#using-the-cli-

**Comment by moneypigtrading** [comment]
Thank you @Tyrrrz ! This works perfectly. perhaps also update the README so it is easier to find?

**Comment by Tyrrrz** [comment]
![image](https://user-images.githubusercontent.com/1935960/102724937-bd0f3300-431b-11eb-8d14-8bf2104c8333.png)
