### ISSUE TITLE
Access is Forbidden: Able to download from GUI on windows, Error on Docker CLI

### ISSUE THREAD

**Issue by mitch-karch** [Tyrrrz/DiscordChatExporter#464]
Trying to export a channel using user-token is unsuccessful with the Docker CLI but successful with the GUI. Error message below from CLI:

`ERROR: DiscordChatExporter.Domain.Exceptions.DiscordChatExporterException: Access is forbidden.
  at DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String url) in
    /src/DiscordChatExporter.Domain/Discord/DiscordClient.cs:57
  at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelCategoryAsync(String channelParentId) in
    /src/DiscordChatExporter.Domain/Discord/DiscordClient.cs:166
  at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelAsync(String channelId) in
    /src/DiscordChatExporter.Domain/Discord/DiscordClient.cs:175
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, String channelId) in
    /src/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs:81
  at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in
    /src/DiscordChatExporter.Cli/Commands/ExportChannelCommand.cs:18
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) `

**Comment by mitch-karch** [comment]
Running in Ubuntu 18 (non-docker) results in same error so it does not seem to be a docker specific issue

**Comment by Tyrrrz** [comment]
IIRC, forbidden means you don't have access to the channel. It doesn't depend on the operating system you're using.

**Comment by mitch-karch** [comment]
Sorry, I wanted to show that the export of that specific channel worked in the GUI (windows) while unsuccessful in CLI (docker and ubuntu)

**Comment by Tyrrrz** [comment]
Are you sure the token is actually the same?

**Comment by mitch-karch** [comment]
Double checked and yes, they are identical. It seems that other channels in the guild are able to download with the CLI. There's no lock on this specific channel either.

**Comment by Tyrrrz** [comment]
Sorry, no idea then :/
The CLI and GUI work in exactly the same way as far as this is concerned.

**Comment by mitch-karch** [comment]
Is there any debug flags that can be used in the CLI to further investigate?

**Comment by Tyrrrz** [comment]
No, the only way is to clone the repo and debug the code manually.

**Comment by nikukyugamer** [comment]
The same (Docker and Ubuntu 20.04).
FYI: In my case, some private channels were forbidden.

**Comment by Tyrrrz** [comment]
@nikukyugamer by "the same" you mean you also tried and it works in GUI?
"Access forbidden" may also mean that you have access to the channel in some capacity (i.e. read and write messages), but you don't have access to the channel's history (which is required to pull messages via API).

**Comment by nikukyugamer** [comment]
Yes.
OK: Windows GUI
NG: CLI (Docker and Ubuntu 20.04)

And I'll check 'pull messages' and so on.

**Comment by Tyrrrz** [comment]
Actually, I think I know what the issue is. The CLI attempts to get the channel category, which fails for some reason. On GUI, it seems to work because it doesn't get the category directly but gets the full list of channels? Weird.

**Comment by fjanicki** [comment]
I can also attest that I am having the same issue. Tried in a Windows VM and it works there. The exportguild seems to work though. From what I can see in the code, it gets all channel info from a different API than a single channel, which might be the issue.

**Comment by Tyrrrz** [comment]
> it gets all channel info from a different API than a single channel, which might be the issue

Indeed. It's still weird why the error happens only in case of one of them.
