### ISSUE TITLE
feature request: export member list

### ISSUE THREAD

**Issue by nmz787** [Tyrrrz/DiscordChatExporter#465]
After exporting a server, I had to do this:
`ls SERVER_NAME\ -\ Text\ Channels\ -\ * | xargs -I {} grep "chatlog__author-name" {} | grep -oP '(?<=title=")([^"]+)' | sort | uniq > member_list`

where `SERVER_NAME` is the actual name of the chat server you've got HTML files for.

The command goes through all exported channels in the given server, filter the author names, perform a substring match on the actual field containing the name, then sort and de-duplicate, finally outputting to a text file.

**Comment by Tyrrrz** [comment]
Duplicate of #276

**Comment by nmz787** [comment]
At least paste that one liner into the wiki under a linux heading for us, please.
