### ISSUE TITLE
Access is Forbidden

### ISSUE THREAD

**Issue by afakacnt** [Tyrrrz/DiscordChatExporter#468]
I have accounts, linked through 1 phone number - therefore I have been locked out by discord. Just wondering if this tool can still view my messages if locked behind 2FA or not. Based on the access being forbidden message I have received, I would assume that it can not, however I just wanted to make sure in case there was maybe another reason for this error.
Thanks

**Comment by Tyrrrz** [comment]
Well you wouldn't be able to get a token if you were locked out, so the answer is no. For reference, the authorization token, when using 2FA, should start with `mfa.`.
