### ISSUE TITLE
Wiki links don't work

### ISSUE THREAD

**Issue by Davidgithub1** [Tyrrrz/DiscordChatExporter#469]
Many links are not working. Example:
https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs

**Comment by Tyrrrz** [comment]
Thanks for bringing this to my attention. Apparently, someone made a malicious edit to delete this page, so I restored it. I guess that's the downside of having an open wiki, some people are just assholes.

Are there any other links that aren't working? You said "many" but I only see one.
