### ISSUE TITLE
Reupload exported messages to another channel

### ISSUE THREAD

**Issue by kirjorjos** [Tyrrrz/DiscordChatExporter#470]
Is it possible to use this tool to export all messages from channel1, then reupload them to channel2?

**Comment by 96-LB** [comment]
Discord doesn't support reuploading of messages, unfortunately.

**Comment by kirjorjos** [comment]
Is it possible to setup a bot to change its nickname and pfp before very message?

**Comment by 96-LB** [comment]
I have seen it done, though I'm not entirely sure how. If you dig around, you may be able to find some documentation (I think you may be able to get it done with webhooks), and program something to read from the exporter's JSON output to recreate messages.

**Comment by kirjorjos** [comment]
Looking further into it, a bot account seems to update the pfp on every message when the pfp changes where as the nickname stays the same.  I'm not sure whether or not it's the same with web hooks.

**Comment by 96-LB** [comment]
The [developer docs](https://discord.com/developers/docs/resources/webhook) show that you can override the default username and avatar of a webhook. I'd imagine that there are some libraries that can automate this, but even if not it's probably feasible to make some raw POST requests.

**Comment by kirjorjos** [comment]
Thank you, looking at web hooks now, it should in theory be as simple as looping over every I guess element, I'm not very familiar with JSON terminology, and sending the message with the correct parameters.

**Comment by 96-LB** [comment]
Update: [discord.py provides good support for webhooks](https://discordpy.readthedocs.io/en/latest/api.html#discord.Webhook). I was able to very quickly patch a few dirty lines of code onto a pre-existing bot with the help of [this StackOverflow post](https://stackoverflow.com/questions/64294581/how-to-make-a-webhook-to-send-a-message-with-the-avatar-and-nickname-of-the-user).
![image](https://user-images.githubusercontent.com/21089343/104108343-b710d000-5291-11eb-95bf-47e61ee23753.png)
Notice that both the username and profile picture change (and persist on refresh). You need a url for the avatar, so I lazily copied the url of the screenshots on the aforementioned StackOverflow post. The relevant lines of code:
```py
@commands.command()
async def webhook(self, ctx):
    webhook = await ctx.channel.webhooks() 
    webhook = webhook[0] if webhook else await ctx.channel.create_webhook(name='a', reason='b')    
    await webhook.send(ctx.message.content, username=ctx.message.content, avatar_url=f'https://i.imgur.com/{"HnaVinm" if ctx.message.content.endswith("a") else "inB92Oa"}.png')
```
With this, I'm sure it's possible to pull the necessary data from DiscordChatExporter's output and recreate the chatlogs.

**Comment by kirjorjos** [comment]
The sending the web hook half of it made perfect sense to me with discord.js (Javascript being the language I'm most familiar with, but I have 0 problems using a different language if it would be easier or more efficient (especially as my JSON file was too big to upload to even github)), the main thing that's taking me a bit to understand is reading and parsing the JSON file.

**Comment by 96-LB** [comment]
Ah, JavaScript has perfect JSON support! In fact, JavaScript is where JSON (JavaScript Objection Notation) comes from. Simply call [JSON.parse()](https://www.w3schools.com/js/js_json_parse.asp) and you should have a more familiar JavaScript object to work with.

**Comment by kirjorjos** [comment]
Thank you, I'm still trying to find a way to loop over it though as it does seem to be quite a bit harder without every element(?) having a number key(?).

**Comment by 96-LB** [comment]
Assuming `data` is your parsed object, `data["messages"]` should be a list of messages that you can iterate over. Each item in that list should be another object with all the relevant data.

**Comment by Tyrrrz** [comment]
Answering the original question, DCE is explicitly "read-only" and everything else is out of scope for the project.
