### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by hwalker928** [Tyrrrz/DiscordChatExporter#471]
Hey there,
I am trying to use DCE in CLI on Centos 7, but I get this error while attempting to run:
`Error:
  An assembly specified in the application dependencies manifest (DiscordChatExporter.Cli.deps.json) has already been found but with a different file extension:
    package: 'DiscordChatExporter.Cli', version: '2.26'
    path: 'DiscordChatExporter.Cli.dll'
    previously found assembly: '/root/chatexport/DiscordChatExporter.Cli.exe'`

Thanks.

**Comment by Tyrrrz** [comment]
Umm. Try deleting `DiscordChatExporter.Cli.exe`.
