### ISSUE TITLE
[FEATURE] Custom CSV output

### ISSUE THREAD

**Issue by cancerousname69** [Tyrrrz/DiscordChatExporter#473]
The CSV output format currently lacks some information compared to the json output format. Adressing this by adding either custom CSV support or making the CSV format equivalent to the JSON format in data shown would be amazing.

**Comment by 96-LB** [comment]
The changelog contains the following text deep down in it (about a year ago):

> Please note that CSV export is most likely not going to receive future updates and will remain only as an option for those who wish to use it for text analysis. In other words, it won't contain any of the rich media features like embeds. If you're currently using CSV as a structured output to feed into your program, JSON output will replace that in the future.

The CSV export seems to be a predecessor to the JSON output and is now only intended for text features.

**Comment by Tyrrrz** [comment]
Yeah, there's simply no good way to include the extra stuff in CSV, so it's not expanded anymore.
