### ISSUE TITLE
Show Progress in GUI?

### ISSUE THREAD

**Issue by larryqiann** [Tyrrrz/DiscordChatExporter#481]
Hi,

I'm currently attempting to use the GUI version of this application on Windows. It seems to work fine, but I was wondering if there was any way to view the log/progress of the GUI application as it downloads the messages. it appears that the CLI is able to do so

Thanks!

**Comment by larryqiann** [comment]
Seems like in another issue, someone has mentioned that the progress is shown in the task bar

**Comment by Tyrrrz** [comment]
It also shows it underneath the token text box.
