### ISSUE TITLE
Force Twitter images to original resolutions and correct extensions

### ISSUE THREAD

**Issue by ImportTaste** [Tyrrrz/DiscordChatExporter#483]
I've noticed that the exporter, while it will download twitter images, tends to change everything to .jpg_large or .png_large and doesn't target the original resolutions. Additionally, the old URL format that doesn't use parameters might be deprecated eventually, Twitter is rather fickle so it could be tomorrow for all we know.

I'd like to suggest that all jpg urls that resemble the following...
https://pbs.twimg.com/media/Eb0qnyjUcAAahUb.jpg
https://pbs.twimg.com/media/Eb0qnyjUcAAahUb.jpg:small
https://pbs.twimg.com/media/Eb0qnyjUcAAahUb.jpg:med
https://pbs.twimg.com/media/Eb0qnyjUcAAahUb.jpg:medium
https://pbs.twimg.com/media/Eb0qnyjUcAAahUb.jpg:large
https://pbs.twimg.com/media/Eb0qnyjUcAAahUb.jpg:orig
https://pbs.twimg.com/media/Eb0qnyjUcAAahUb?format=jpg&name=small
https://pbs.twimg.com/media/Eb0qnyjUcAAahUb?format=jpg&name=medium
https://pbs.twimg.com/media/Eb0qnyjUcAAahUb?format=jpg&name=large

be redirected to...
https://pbs.twimg.com/media/Eb0qnyjUcAAahUb?format=jpg&name=orig

And finally, be given the jpg extension upon saving.

Then, with png urls, essentially the same as above but with jpg swapped out with png.

**Comment by Tyrrrz** [comment]
> I've noticed that the exporter, while it will download twitter images, tends to change everything to .jpg_large or .png_large and doesn't target the original resolutions.

It doesn't change the URLs.

**Comment by ImportTaste** [comment]
> > I've noticed that the exporter, while it will download twitter images, tends to change everything to .jpg_large or .png_large and doesn't target the original resolutions.
> 
> It doesn't change the URLs. They are what Discord API returns.

I know. I'm saying you should make it change the URLs, so that it always points to the highest resolution version of the image that's hosted. It makes using the Download media option much more useful.

**Comment by Tyrrrz** [comment]
> It makes using the Download media option much more useful.

Perhaps for your particular use case, but the intended purpose of that option is to preserve the sidecar media files used within the export file. The export file doesn't reference full size images (nor should it, as the originals on Discord don't either and it would unnecessarily increase overall file size). Remember, this application is intended to be used to export Discord chat logs, not scrap Twitter images in highest available quality (there are likely others that do that).
