### ISSUE TITLE
Fallback extension for media files based on content type header

### ISSUE THREAD

**Issue by ImportTaste** [Tyrrrz/DiscordChatExporter#484]
Occasionally, a file will be downloaded that doesn't have an extension. I'd like it if the header could be checked so the proper extension can be given to it before saving.

There's probably a C# library that can do it, but if you'd like to check for it with your own custom code, here are the headers:

Headers for jpg files:
https://file-extension.net/seeker/file_extension_jpeg
https://file-extension.net/seeker/file_extension_jif

Headers for png files:
https://file-extension.net/seeker/file_extension_png

Headers for gif files:
https://file-extension.net/seeker/file_extension_gif

Header for webp files:
https://file-extension.net/seeker/file_extension_webp

**Comment by Tyrrrz** [comment]
If someone wants to submit a PR, the relevant bits are here:

https://github.com/Tyrrrz/DiscordChatExporter/blob/6365e0a080d7ae6f4158f62df344b41a8a9f50cc/DiscordChatExporter.Core/Exporting/MediaDownloader.cs#L51-L70

**Comment by Tyrrrz** [comment]
After looking into it more closely, it appears this is not as easy as it seems. The reason being, we rely on the file name for caching with the "reuse media" option, which means that the file name must be established before the request to the resource is even made, which in turn means that we can't use the `Content-Type` header to set the file extension. We could exclude the file extension and use only file name for resolution with "reuse media", but it might get messy if we'll end up having multiple media files that differ only in extension. Plus it would be a breaking change for users that already have exports made by current version.

**Comment by Tyrrrz** [comment]
Closing as "wontfix" because it's pretty much impossible to do cleanly given the "reuse media" limitations I pointed out earlier.
