### ISSUE TITLE
Program instantly crashes

### ISSUE THREAD

**Issue by Niwaeka** [Tyrrrz/DiscordChatExporter#486]
Hi, I'm not a coder or anything and don't consider myself to be super tech savvy either but I do hope you guys can help me out.
So, if I wanna start the program whether it's the GUI or CLI one, the program either doesn't open up at all (GUI) or crashes instantly (CLI). I have downloaded Runtime, restarted it, run the exporter again, it crashed, reinstalled Runtime, restarted it again and it just won't work. So, I have seen someone once use the event viewer for a similar issue, again I'm not a coder I don't know if it's a reasonable thing to use the event viewer for this. So, essentially what the event viewer says, is that there is a file missing: "DiscordChatExporter.dll" Now, I did scour all the folders in the hopes that I had to drag it into the main folder or something but no luck, I tried changed what I call the suffix i.e. the letter behind the dot of the file from .pdb to .dll of files who had very similar names because, well, I'm pretty desperate to get this to work. If any of you could help me out or just theorise what might be going on, it'd be much appreciated. Also, sorry for the wordy explanation but I'd rather give too much information on the issue than not providing you with enough.

**Comment by andrewkolos** [comment]
Did you download the program [from the releases page](https://github.com/Tyrrrz/DiscordChatExporter/releases/tag/2.26)? I downloaded the zip, extracted it, and opened `DiscordChatExporter.exe` (the GUI) and it worked fine. I am running on Windows 10.

**Comment by Tyrrrz** [comment]
There **should** be files ending in `.dll`. If you downloaded and extracted the archive correctly, they should be there.

**Comment by Niwaeka** [comment]
Thanks for the reply, I did redownload it and now the file isn't missing anymore. I don't how I did that, but hey at least it's working. Thank you guys a lot! :)
