### ISSUE TITLE
System.FormatException: Invalid snowflake when mentioning deleted channel

### ISSUE THREAD

**Issue by eat-it** [Tyrrrz/DiscordChatExporter#489]
![image](https://user-images.githubusercontent.com/46140778/106362724-f909c080-62e9-11eb-94f8-7e369beccbfa.png)
I'm exporting 8 million messages at 10k partition in TXT file format. When I retry the export it fails every time it gets to a particular message so I have to change it to only get messages after that message. Been able to download 1.9 million messages through 2 tries but they seem to fail quicker and quicker. The message it fails on contains "<@586788617482010643>" or "@!3848489393846>" or "#deleted-channel"

**Comment by 96-LB** [comment]
This bug has been fixed. You can [download one of the the recent CI builds](https://github.com/Tyrrrz/DiscordChatExporter#download) to get a working copy of the application.

**Comment by Tyrrrz** [comment]
Fixed in stable now.
