### ISSUE TITLE
DiscordChatExporter v2.26.1 not opening 

### ISSUE THREAD

**Issue by SoyNoob21** [Tyrrrz/DiscordChatExporter#498]
Its my first time using it. When I double click on the exe and run it, it doesnt open. There is no pop up nothing. I also reinstalled .NET core/framework and also trying running as Administrator. Any fix?

**Comment by lucubrator** [comment]
Same issue here.

**Comment by Tyrrrz** [comment]
Are you trying to run GUI or CLI? Which operating system are you using? Did you use the exact links in [this table](https://github.com/Tyrrrz/DiscordChatExporter#download) to download prerequisites for your system?
