### ISSUE TITLE
Using bot token in Discord API

### ISSUE THREAD

**Issue by De96UtopiaLife341** [Tyrrrz/DiscordChatExporter#501]
I've noticed that, apparently, Discord doesn't allow self-bots outside of their API/Oauth2 system. Assuming that this is a self-bot, is there a way for the code to be used as a bot in Discord API system?

**Comment by Tyrrrz** [comment]
Yes.

**Comment by De96UtopiaLife341** [comment]
Right, you can only use it for a bot and not a user account, but is there a way to make a chat exporter inside Discord's API system? That way, it would be legal on Discord.

**Comment by Tyrrrz** [comment]
No.
