### ISSUE TITLE
Export JSON takes exceptionally long

### ISSUE THREAD

**Issue by Fyko** [Tyrrrz/DiscordChatExporter#502]
Hello! I'm the maintainer of https://github.com/fyko/export-api
With the upcoming release of our v2 API, users will be able to export to JSON.

During testing, it took 79 seconds to export 300 messages. The resulting file was about 300kb, but I don't see why it should take this long. I'm not extremely confident in my C# skills, so I couldn't direct exactly where this is coming from.

**Comment by Tyrrrz** [comment]
That sounds abnormal. Writing JSON (or any other format) should not take that long. Are you sure it's not a latency issues? Is it consistent? Are the other formats faster to export?

**Comment by Fyko** [comment]
After some benchmars, here are some results I came to:
1. Plaintext (0) - 1584ms
2. HTML Dark (1) - 2322ms
3. HTML Light  (2) - 1578ms
4.  CSV (3) - 1482ms
5. JSON (4) - 73455ms (73.455 seconds)

**Comment by Tyrrrz** [comment]
Hm, so is flush taking up most of that time? Everything is 0ms all the way until the end.
No idea what could be causing it.

**Comment by Fyko** [comment]
I don't think it's flushing because the log says it takes 0ms.

**Comment by Fyko** [comment]
I stand corrected, after a little rewrite of the diag:
```
Starting 642601055862915112
Wrote 642601055862915112 meta after 0ms
Wrote 642601055862915112 content after 0ms
Wrote 642601055862915112 author data after 0ms
Wrote 642601055862915112 attachments after 0ms
Wrote 642601055862915112 embeds after 0ms
Wrote 642601055862915112 reactions after 0ms
Wrote 642601055862915112 mentions after 0ms
Flushed after 91ms
Wrote message 642601055862915112 after 91ms
```

**Comment by Fyko** [comment]
I'm not sure if anything can be done to fix this

**Comment by Tyrrrz** [comment]
If the biggest delay comes from flushing, that means it's on the side of `System.Text.Json`.
However, what you're describing is abnormal, but I don't know what could be causing it.
Maybe try to export to a file instead and see if it's faster? If it is, then the problem may be with the stream.

**Comment by Tyrrrz** [comment]
Nevermind, I see you're exporting to a file, thought you were streaming directly.
I have no clue then 🤷

**Comment by r1bnc** [comment]
Is this not fixed yet?

**Comment by Tyrrrz** [comment]
@r1bnc did you fix it?

**Comment by r1bnc** [comment]
? i was just asking whether this issue was fixed.

**Comment by 96-LB** [comment]
Has anyone else encountered this? I haven't been able to reproduce it. @Fyko, does this happen on every channel that you export, or just one/a few?
