### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Natemo6348** [Tyrrrz/DiscordChatExporter#506]
I keep trying, but I either can't copy my token in time, or it tells me I have an invalid token

**Comment by Tyrrrz** [comment]
Try double-clicking the field, should be faster to copy that way.
Can also throttle your connection in the Network tab.

![image](https://user-images.githubusercontent.com/1935960/109083869-635a2900-770f-11eb-9982-09a69c7d5e25.png)

**Comment by 96-LB** [comment]
> or it tells me I have an invalid token

Are you accidentally leaving the quotes in when you input the token into DiscordChatExporter? Another cause could be trying to log in as a bot account with your user token.

**Comment by Tyrrrz** [comment]
> Are you accidentally leaving the quotes in when you input the token into DiscordChatExporter?

That shouldn't matter.

**Comment by 96-LB** [comment]
Hmm, I could have sworn that I previously had that problem with the GUI, but I tried it again and it worked just fine. Guess I was mistaken.

**Comment by Natemo6348** [comment]
nvm, i figured out that it didn't select the whole token, sorry
