### ISSUE TITLE
Docker image hangs at `Exporting xx channels...` with no further output

### ISSUE THREAD

**Issue by l1ving** [Tyrrrz/DiscordChatExporter#507]
I get 
```
user@server:~/discord-msgs$ docker run tyrrrz/discordchatexporter exportguild -b -t "$DISCORD_TOKEN_BOT" -g SOME_ID --dateformat "yyyy/MM/dd HH:mm" --parallel 4 -f Csv
Exporting XX channels... 
```
and no further output at all.
I've tried waiting 10 minutes before killing it and it does not export anything to the folder.

System info:
```
user@server:~/discord-msgs$ docker run tyrrrz/discordchatexporter --version
v2.26.1
user@server:~/discord-msgs$ docker --version
Docker version 19.03.8, build afacb8b7f0
user@server:~/discord-msgs$ uname -a
Linux server 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I'm not sure how to troubleshoot this but I'm happy to provide whatever information I can get.

**Comment by Tyrrrz** [comment]
It's only able to write progress if you run it in interactive mode, IIRC.

**Comment by l1ving** [comment]
That fixed it! Might be helpful to add to the readme in the docker section. Thanks for the quick response

**Comment by Tyrrrz** [comment]
It is actually mentioned on the wiki:

https://github.com/Tyrrrz/DiscordChatExporter/wiki/Docker-usage-instructions#usage

![image](https://user-images.githubusercontent.com/1935960/109175671-b4f5c880-778e-11eb-8c0f-10437b94dd5c.png)

**Comment by l1ving** [comment]
Ahh okay, my bad. Thank you!
