### ISSUE TITLE
File export location

### ISSUE THREAD

**Issue by myrcury** [Tyrrrz/DiscordChatExporter#508]
I'm new to Docker and am using the CLI, where does the file export to?

My code is `sudo docker run tyrrrz/discordchatexporter exportdm --token [TOKEN]`

**Comment by Tyrrrz** [comment]
Please read the wiki:
https://github.com/Tyrrrz/DiscordChatExporter/wiki/Docker-usage-instructions

**Comment by myrcury** [comment]
Ah, didn't see that page, sorry. Thanks!
