### ISSUE TITLE
Move the GUI from WPF to Avalonia

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/DiscordChatExporter#509]
The goal is to make GUI cross platform, so that less technical users don't have to rely on CLI to get simple tasks done (see #504 as an example of such a task).

Need to investigate if this is viable at all. In particular:

- What options do we have regarding MaterialDesignInXAML that we currently rely on? Does it support Avalonia or will we have to use another UI library (and redo the entire UI)?
- (some other things I haven't though of yet)

Any outside input or sharing of experience is welcome.

**Comment by Tyrrrz** [comment]
Reopening because it looks like #813 isn't feasible.

**Comment by Mrxx99** [comment]
If you want I can try this after the YoutubeDownloader port

**Comment by Tyrrrz** [comment]
> If you want I can try this after the YoutubeDownloader port

Sure!

**Comment by ctrlcctrlv** [comment]
I compiled and ran with `wine` and it does almost work with some caveats:

* You must use a 32-bit WINEPREFIX and set WINEARCH=win32.
* You must install lib32-mesa and lib32-gnutls.

However, it seems Wine does not yet support the security magic windows does:

```
0134:fixme:winsock:GetAddrInfoExW Unsupported namespace 0
0134:fixme:winsock:GetAddrInfoExW Unsupported cancel handle
0170:fixme:winsock:setsockopt Ignoring SO_REUSE_UNICASTPORT
0170:fixme:secur32:get_cipher_algid unknown algorithm 23
0170:fixme:secur32:get_mac_algid unknown algorithm 200, cipher 23
0170:fixme:secur32:get_cipher_algid unknown algorithm 23
0170:fixme:secur32:get_mac_algid unknown algorithm 200, cipher 23
0170:fixme:secur32:get_cipher_str unknown cipher 23
0170:fixme:secur32:get_cipher_len unknown cipher 23
0170:fixme:secur32:get_hash_str unknown mac 200
0170:fixme:secur32:get_chaining_mode_str unknown cipher 23
0170:fixme:secur32:get_hash_str unknown mac 200
```

The cipher is too new and Wine's secur32.dll can't handle it. Hmm.

![image](https://user-images.githubusercontent.com/838783/227120733-0e61e521-e4e0-4dd7-a806-14c70b0f4042.png)

**Comment by ctrlcctrlv** [comment]
After trying a while crashes with:

```
0194:fixme:wininet:InternetSetCookieExW flags 40 not supported
012c:fixme:wininet:InternetSetCookieExW flags 40 not supported
0194:fixme:wininet:set_cookie secure not handled
Fatal error. 0xC0000005
0180:fixme:ntdll:RtlGetCurrentProcessorNumberEx (1B56F854) :semi-stub
0194:err:seh:NtRaiseException Unhandled exception code c0000409 flags 1 addr 0x41d7c59
wine client error:24: write: Bad file descriptor
```

Probably not worth trying to fix.

**Comment by qwertychouskie** [comment]
Right now I have it working on a 64bit Wine prefix and the latest Wine-Staging, `winetricks wininet` seems to have things running correctly.  `secur32` still complains in the logs but if I try to use `winetricks secur32` then DiscordChatExporter just freezes upon launch.
