### ISSUE TITLE
Show error when exporting a deleted channel

### ISSUE THREAD

**Issue by KcrPL** [Tyrrrz/DiscordChatExporter#51]
When trying to dump a channel that has been deleted, it crashes. 

--- Steps to reproduce ---
1. Load your Discord token
2. Delete a channel on your Discord server
3. Try to dump it
4. It crashes

**Comment by Tyrrrz** [comment]
Hi
What did you expect would happen?

**Comment by KcrPL** [comment]
Hi Tyrrrz,

~~I was expecting it to say that an error occurred~~

**Comment by KcrPL** [comment]
👌
