### ISSUE TITLE
System.Net.Http.Http.RequestException Error

### ISSUE THREAD

**Issue by Moschaa** [Tyrrrz/DiscordChatExporter#512]
So I don't know the exact problem because I just have no idea about it, it says that it is an error, maybe it is due to some software that is not yet installed on me.

I tried it with a token from myself and someone else, from whom I also got the consent, but after a lot of trying nothing works.

I also tried to look for solutions, but of course others don't have these errors that I keep getting, so I can't really find anything about them.

would be nice if someone could help me.

![Don't know what it means](https://user-images.githubusercontent.com/79769674/109401801-1796c200-7951-11eb-9a0d-eb61dd67dae3.png)

**Comment by Tyrrrz** [comment]
Looks like an SSL certificate issue.
Are you latest on Windows updates?
