### ISSUE TITLE
[Feture Request] Docker Image

### ISSUE THREAD

**Issue by Ryonez** [Tyrrrz/DiscordChatExporter#513]
Would it be possible to get a docker image for the cli please?

**Comment by WebSpider** [comment]
Already exists:

`$ docker run --rm tyrrrz/discordchatexporter:stable
DiscordChatExporter.Cli v2.26.1

Usage
  dotnet DiscordChatExporter.Cli.dll [command] [options]

  ... exportall --token <value> [options]
  ... export --channel <value> --token <value> [options]
  ... exportdm --token <value> [options]
  ... exportguild --guild <value> --token <value> [options]
  ... channels --guild <value> --token <value> [options]
  ... dm --token <value> [options]
  ... guilds --token <value> [options]
  ... guide [options]

Options
  -h|--help         Shows help text. 
  --version         Shows version information. 

Commands
  exportall         Export all accessible channels.
  export            Export a channel.
  exportdm          Export all direct message channels.
  exportguild       Export all channels within specified guild.
  channels          Get the list of channels in a guild.
  dm                Get the list of direct message channels.
  guilds            Get the list of accessible guilds.
  guide             Explains how to obtain token, guild or channel ID.

You can run `dotnet DiscordChatExporter.Cli.dll [command] --help` to show help on a specific command.
`

**Comment by Ryonez** [comment]
Brilliant.I missed the page the first time I looked at the wiki and looked again. Found it here for those interested: https://github.com/Tyrrrz/DiscordChatExporter/wiki/Docker-usage-instructions

Thank you Web.
