### ISSUE TITLE
How to translate mentions IDs to names

### ISSUE THREAD

**Issue by vg-fractral** [Tyrrrz/DiscordChatExporter#515]
Hey guys, 

So first of all, big props for what you are doing, much respect.
Second of all, I wish to inform you that this isn't an issue, more of a question that I seek the answer to.

So without beating around the brush for any more than I already have, my question:
As the title suggests, I am looking for a way to get the name or 'text' of the mentions in a message.

For example, if in discord the message with the text of  `@Vilian` may appear perfectly normal, the discord API returns it like this : "content : `815664984830771230`.", mentioned_roles ["815664984830771230"] 

But I saw that your application perfectly translates this into its original form ('@Vilian').
So, I cloned the repo and poked around the code for myself...However, my C# is kind of not on that expert level, so even though I looked through the files, I couldn't see how exactly you guys achieve this.

So yes, this is my question. How can I get the name of the mentioned role by having its ID.
Once again, this is not an issue with your application and I once again apologize for having to post this here.
I just couldn't find anywhere else an answer to my problem, (as far as I know, after reading Discord's developer portal docs, they do not explain it anywhere).

Best,
Vilian

**Comment by Tyrrrz** [comment]
For roles and channels, DCE just pulls the entire list before exporting, and then cross-references it with mention IDs.
For users, it just keeps track of users that posted messages prior to the mention and cross-references it with that. You could also pull the list of users in a guild as well, but unlike roles and channels, their number may be much much higher.
