### ISSUE TITLE
"Failed to create CoreCLR, HRESULT: 0x80004005" on Ubuntu 20.10 using CLI

### ISSUE THREAD

**Issue by Batimius** [Tyrrrz/DiscordChatExporter#518]
Hello there. As you may have guessed from the tittle, I am having an issue with the CLI Chat Exporter. I have been using the CLI for a while on this system and I had no issues with it whatsoever until a few days ago where it started bringing up that error.

Every time I run the command, I get a `Failed to create CoreCLR, HRESULT: 0x80004005` error which I am unsure how to fix. The command I run is `dotnet /home/ubuntu/Discord/MyBot/ChatExporter/DiscordChatExporter.Cli.dll export -t "BOT_TOKEN (Not gonna show)" -b -c CHANNEL_ID -f HtmlDark -o "/home/ubuntu/Discord/MyBot/Receipts/Ticket.html" --dateformat "MMMM d, yyyy h:mm tt"`.

This command seemed to have worked for the past few months that I've been using it, but it just stopped working all of the sudden and gave me that error every time I ran it. If you are interested on my OS, I am using Ubuntu 20.10 and have .NET v3.1 runtime installed as well. If someone could help me fix this, that would be amazing. Thank you for your time and help.

**Comment by Tyrrrz** [comment]
https://github.com/dotnet/runtime/issues/44417

Can you try restarting your machine?

**Comment by Batimius** [comment]
> [dotnet/runtime#44417](https://github.com/dotnet/runtime/issues/44417)
> 
> Can you try restarting your machine?

Aye. Restarting the machine seemed to have fixed it. Thank you for the help, I greatly appreciate it. (And I apologize for creating an entire issue thread that could be solved with a single restart, that idea did not even cross my mind.) Again, thank you very much.
