### ISSUE TITLE
Show progress

### ISSUE THREAD

**Issue by roger125** [Tyrrrz/DiscordChatExporter#52]
Dear Tyrrrz,
    the 2.4.1.0 version works like a charm, amazing!
    and just a enhancement suggestion expected:
    show progress bar(0%->1%->99%->100%) when exporting, bcz currently there's no such kind of indication, to show how much the progress is already, makes it confusing if it got stuck or are going its normal way.
    Thanks for the consideration.

**Comment by Tyrrrz** [comment]
There's no way to show progress, because there's no way to know how many messages there are

**Comment by roger125** [comment]
ok, if there's something that can be noticeable what's it working might be a bit clearer, thanks for the prompt reply.

**Comment by Tyrrrz** [comment]
Hmm. On another thought, it could show progress by, say, days of parsed messages.

**Comment by MysteryPancake** [comment]
You could also subtract the message timestamp from the channel creation date for a rough estimate

**Comment by Tyrrrz** [comment]
That's not a bad idea. Currently it works more accurately by getting the first and last messages before the rest.
