### ISSUE TITLE
Update from .NET Core 3.1 to .NET 6.0

### ISSUE THREAD

**Issue by mcglk** [Tyrrrz/DiscordChatExporter#521]
The current version of DiscordChatExporter.CLI only runs on older version of dotnet. Are there any plans to update it to Microsoft's recommended version (currently 5.0.201)?

**Comment by Tyrrrz** [comment]
There are plans. Currently, I'm blocked by the fact that [Onova](https://github.com/Tyrrrz/Onova), my autoupdate library, is not capable of updating .NET Runtime as well. If a new version of DCE were released now targeting .NET 5.0, it would stop working majority of the users after an autoupdate.

**Comment by TekuSP** [comment]
Well, there will be soon .NET 6.0 as we have preview already....
So maybe create new bug in Onova and reference it here?

**Comment by Tyrrrz** [comment]
https://github.com/Tyrrrz/Onova/issues/46

**Comment by Tyrrrz** [comment]
This has now been resolved with the addition of [DotnetRuntimeBootstrapper](https://github.com/Tyrrrz/DotnetRuntimeBootstrapper) so this issue is no longer blocked. Let's skip .NET 5 meanwhile and wait until .NET 6 is release since it's not very far off.

**Comment by ureru** [comment]
DiscordChatExporter needs to remain compatible with Linux at minimum.

**Comment by Tyrrrz** [comment]
> DiscordChatExporter needs to remain compatible with Linux at minimum.

That won't change. Althoug the requirements for .NET 6 might be higher.

**Comment by TekuSP** [comment]
@ureru .NET 6 has linux support. What is the issue?

**Comment by ureru** [comment]
That's confusing if so, I thought I specifically remembered that around .net 4.5 or 4.6 it was removing linux support. Maybe that was only for using them in wine...?

**Comment by Tyrrrz** [comment]
> That's confusing if so, I thought I specifically remembered that around .net 4.5 or 4.6 it was removing linux support. Maybe that was only for using them in wine...?

You're confusing it with the legacy ".NET Framework" instead of ".NET". It's not your fault, it really is confusing, thanks to Microsoft. But .NET 5 and .NET 6 are completely different platforms from .NET 4.5 or .NET 4.6.
