### ISSUE TITLE
Export the message link too

### ISSUE THREAD

**Issue by midadami** [Tyrrrz/DiscordChatExporter#523]
Allow to choose to export the message link so that we have the history of the chat plus an instant access to any message.
I'm not sure if its possible by using message.jump_url

Thanks

**Comment by Tyrrrz** [comment]
In HTML I suppose?

**Comment by midadami** [comment]
Preferably on JSON/CSV as a new field. I want to have the data logged (excel, etc..) and able to access the original discord message quickly if needed.

**Comment by 96-LB** [comment]
If it helps, all message links are of the format `https://discord.com/channels/<server ID>/<channel ID>/<message ID>` (e.g. https://discord.com/channels/808389554183864340/808389554183864344/808389630260936834), and thus should be reconstructable from the ID. Direct messages are a little different, using `@me` in place of the server ID and the DM's ID as the channel (obviously, this only works for the involved users).

**Comment by midadami** [comment]
> If it helps, all message links are of the format `https://discord.com/channels/<server ID>/<channel ID>/<message ID>` (e.g. https://discord.com/channels/808389554183864340/808389554183864344/808389630260936834), and thus should be reconstructable from the ID. Direct messages are a little different, using `@me` in place of the server ID and the DM's ID as the channel (obviously, this only works for the involved users).

Thanks very much for the info, with the current information on json export I can recreate the links for any message.
