### ISSUE TITLE
Error upon launch due to `ITaskBarList.HrInit()` throwing `NotImplementedException`

### ISSUE THREAD

**Issue by troutcannon** [Tyrrrz/DiscordChatExporter#530]
I receive the following errors when I try to run DCE.  I just had the computer wiped during a repair, and was using it previously with no issues, but see this when launching the app now.  It's incredibly handy for channel mods/admins, and I really want it back!  I have installed the appropriate .NET core.
![DiscordChatExplorer](https://user-images.githubusercontent.com/76674737/112180087-9dfd9700-8bd1-11eb-96f1-3bbcac070016.png)

**Comment by Tyrrrz** [comment]
Hi.

Did something change with your OS setup?

Relevant: #297

**Comment by troutcannon** [comment]
It doesn't appear so, but I installed the .NET core again and it seems to have resolved.  I was able to use the program without fault.  It's really a great tool.  Thanks!

    On Tuesday, March 23, 2021, 7:05:16 PM EDT, Alexey Golub ***@***.***> wrote:  
 
 


Hi.

Did something change with your OS setup?

Relevant: #297

**Comment by Tyrrrz** [comment]
Great!
