### ISSUE TITLE
Export layout

### ISSUE THREAD

**Issue by Kami-Sama-Desu** [Tyrrrz/DiscordChatExporter#531]
Sorry for not being a expert or anything, but I'd to add my 2 cents here. Just wondering of there's a layout for the exported chat. For example, lets say we'd like to export it to a website, add embed a conversation to a online journal, or embed it on a website like wordpress through a plugin or just straight up copy-paste code, as an offline document, but still with the conversation structure, including gifs and so on. Much like a multilayered image were there's the conversation layer and the image, or gif active on loop, or a embed video in it that can be manually changed thought a link embed by the user. of course that'd make another turbulent and excruciating brainstorm and coding for you guys but while making something why not make it awesome you know?

Cause it would be pretty pointless to go through all the work to make a general plain tasteless straight export text kind of thing

**Comment by Tyrrrz** [comment]
I'm not sure what you're asking. If you want to include the HTML export inside another HTML document, either use an iframe or embed the body + styles manually.
