### ISSUE TITLE
All messages from guild are redownloaded when exporting guild with --after flag provided

### ISSUE THREAD

**Issue by Layerex** [Tyrrrz/DiscordChatExporter#532]
All messages from guild are redownloaded when exporting guild with `--after` flag provided and are filtered only after downloading, even if there are no new messages in guild channels.
For example, when running such command all messages from all channels of guild are redownloaded despite there are even no new messages.
```
$ dotnet DiscordChatExporter.Cli.dll exportguild --after '2021-03-25 12:00:00' -t ... -g ...
Exporting 3 channels...
Channel 'channel1': No messages for the specified period.
Channel 'channel2': No messages for the specified period.
Channel 'channel3': No messages for the specified period.
Successfully exported 0 channel(s).
```

**Comment by Tyrrrz** [comment]
I'm confused. You say "All messages from guild are redownloaded" but your snippet shows that all 3 channels were not downloaded because they had no messages.

**Comment by 96-LB** [comment]
I'm interpreting this issue as "all messages are downloaded even if they won't be included in the final output."

I don't know if this is true (on the latest release version, at least). I just tried exporting a channel with 100K messages, downloading media, and the export was almost instant when the `--after` flag was set to exclude all messages. I also tried exporting only the final day, and it still took very little time. When I export the entire chat, it can take minutes.

**Comment by Layerex** [comment]
Sorry for wasting your time, it is probably just my internet connection being bad. I should have done more testing; I just got very confused because exporting a relatively small guild took about the same time for program as checking that there are no new messages and exporting nothing.
