### ISSUE TITLE
Suggestions/improvements

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#533]
Hi,
I'm the one who talked to you on Twitter, so I want to share some of my improvement ideas with you. I have very little coding experience, so I have no clue if these things are even possible to code and how much time it would take, but I think it's always good to share your thoughts, the app is really really good anyways already.
- Maybe a feature to access pinned messages quickly, to whatever degree it's possible. Maybe with just one line of text saying "Jump to that and that message" if it's too much work otherwise. My friends and I use pinned messages as sort of a "best-of" of our chats, so if they will ever get lost it would be good to also have that saved.
- Quite some times that little author icon at the top left (as shown in the attached image) isn't shown (the 2nd image shows how it's done if it works)
![Screenshot 2021-03-26 124729](https://user-images.githubusercontent.com/81419612/112627115-74db4180-8e31-11eb-9e44-6f4d6424ef61.jpg)
![Screenshot 2021-03-26 124807](https://user-images.githubusercontent.com/81419612/112627178-8b819880-8e31-11eb-8661-db8bd501f0db.jpg)
- If Discord has messages from the same user in a certain timeframe, it groups them into a block. In Discord itself, you can obviously see the date and the time of the first message right beside the name of the person who sent that message. For the other messages of that group, you can hover of them and then the time will appear at the left side of the message. I think it would be good if the HTML had some way to see that time as well.
- Last of all for now, I don't really know if that's possible, but a way to play GIFs in the HTML file just like images are shown and videos are played without having to access an external website. (also: if you click on the little preview under the link to the GIF it only shows an image and not the GIF itself)

**Comment by Tyrrrz** [comment]
Hi!
Since you've put multiple issues into one, I will split them out.

> Maybe a feature to access pinned messages quickly, to whatever degree it's possible. Maybe with just one line of text saying "Jump to that and that message" if it's too much work otherwise. My friends and I use pinned messages as sort of a "best-of" of our chats, so if they will ever get lost it would be good to also have that saved.

That would only be possible to end towards the end of the export, due to the streaming nature of the exporter. I don't know if it's very useful at this point.

> Quite some times that little author icon at the top left (as shown in the attached image) isn't shown (the 2nd image shows how it's done if it works)

That usually means the URL that points the icon is broken. Can you check if you can open the image manually?

> If Discord has messages from the same user in a certain timeframe, it groups them into a block. In Discord itself, you can obviously see the date and the time of the first message right beside the name of the person who sent that message. For the other messages of that group, you can hover of them and then the time will appear at the left side of the message. I think it would be good if the HTML had some way to see that time as well.

Good point. Created #536.

> Last of all for now, I don't really know if that's possible, but a way to play GIFs in the HTML file just like images are shown and videos are played without having to access an external website. (also: if you click on the little preview under the link to the GIF it only shows an image and not the GIF itself)

Created #537.

**Comment by CanePlayz** [comment]
Thanks for opening the separate issues, I will do that directly myself next time. Regarding the broken author icons: I got the link to the icon by looking at the HTML code and as you assumed, the URL doesn't exist, so it makes sense that the icon isn't shown properly. Taking a look at the messages where the icon doesn't appear in Discord itself, they aren't shown there anymore as well, so it appears there's nothing that could be done there.
![Screenshot 2021-03-30 162339](https://user-images.githubusercontent.com/81419612/113005050-66b05c80-9174-11eb-84ce-bc38a9212d3a.jpg)

**Comment by CanePlayz** [comment]
Actually, I think it would be good to display the missing author icon like Discord does it with just nothing instead of how it's shown at the moment, if that is possible.

**Comment by Tyrrrz** [comment]
Unfortunately, I'm not aware of a way to completely hide the "broken image" artifact.

**Comment by CanePlayz** [comment]
Oh ok, unfortunate then
