### ISSUE TITLE
Show who reacted to a message

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#539]
Currently, the HTML file only shows the total number of reactions with a certain emote, but when you hover over the reaction in Discord, you can see the names of three users who have reacted to a message. Discord also displays all the names of the users who have reacted when you open the specific reactions window for a message, but I think that would be too complicated to be fully integrated into the HTML file and I think giving a simple list of the users who reacted would be enough.

**Comment by Tyrrrz** [comment]
Duplicate of #133

**Comment by CanePlayz** [comment]
Oh sorry, my bad
