### ISSUE TITLE
Be able to change the filename and directory location

### ISSUE THREAD

**Issue by Mirrorshadez** [Tyrrrz/DiscordChatExporter#54]
I'd like to be able to change the default file name.  Used and the default directory location.

Use case is that I use this to export the chat daily.  At the moment I export the chat then manually move the file and rename it to the required file name for the day.

**Comment by Tyrrrz** [comment]
Do you know you can click the "Browse" button to change the output file path?

**Comment by Mirrorshadez** [comment]
Ah Thank you.  I don't know how I missed that.
