### ISSUE TITLE
Can’t execute without the sdk.

### ISSUE THREAD

**Issue by arantesxyz** [Tyrrrz/DiscordChatExporter#540]
I’ve created an image with DotNet runtime 3.1 as the wiki said but it gives me the above message when i run `dotnet DiscordChatExporter.Cli.dll`:

```
Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

I don’t think we should need the whole SDK to just execute the program.

The Dockerfile for reference: https://github.com/arantesxyz/pterodactyl-nodejs-dotnet31/blob/main/Dockerfile

**Comment by Tyrrrz** [comment]
> I don’t think we should need the whole SDK to just execute the program.

You don't. The error above probably means the file doesn't exist.

**Comment by arantesxyz** [comment]
I added .net core to the image and i worked fine with the same command.

**Comment by Tyrrrz** [comment]
Check the Dockerfile in this repo for reference:

https://github.com/Tyrrrz/DiscordChatExporter/blob/master/Dockerfile

**Comment by arantesxyz** [comment]
Yeah, i inspired my Dockerfile on that one, but i had to add .net core for it to work properly.

Maybe it was how the developer was running the command in the code so i'll close this one.

Thank you tho. :D
