### ISSUE TITLE
Missing conversations

### ISSUE THREAD

**Issue by SolXX** [Tyrrrz/DiscordChatExporter#542]
Hello. I noticed that the last time I downloaded my chats, some of the bigger chats were missing. But because even bigger ones were exported successfully, I don't think the problem is the size of the chats. These chats were exported successfully in February still, but completely missing in the list of available chats in March.

Is this a known issue? Will this be fixed?

**Comment by Tyrrrz** [comment]
What was the error?

**Comment by SolXX** [comment]
There's no error, the chats are simply missing from available conversations to export.

**Comment by Tyrrrz** [comment]
So a channel that exists in a Discord server is not visible in the app? Can you show a screenshot that illustrates this? You should be able to see all channels, even those you don't have access to.

**Comment by SolXX** [comment]
No, I'm talking about private conversations. For example, conversation from A, B and D is there, but the one with person C is missing in the list.

**Comment by 96-LB** [comment]
Is this a bulk export that you're running automatically each month? I have a task scheduled to export several guilds each day, and I sometimes have missing channels as well. It's not that anything skipped, but rather that the exporting process is stopped at some point and the remaining channels don't get outputted (and I can find an incomplete file too). The process returns exit code 0.

I've always attributed this to turning off my computer, as sometimes I open it for only a brief moment in the morning, but I admittedly haven't investigated further.

**Comment by Tyrrrz** [comment]
Ok, afaik private conversations may disappear if you "close" the chat in the app:

![image](https://user-images.githubusercontent.com/1935960/114391010-a24d1c80-9b9f-11eb-83c1-d83bb901eca2.png)

Not 100% sure tho

**Comment by 96-LB** [comment]
@Tyrrrz Just did a quick test and this does seem to be the case. Even in the GUI, the private conversation does not appear in the list of exportable chats.

**Comment by Tyrrrz** [comment]
The bottom line is that it's not a bug, we just consume the list of channels/chats that Discord provides through its API.

**Comment by SolXX** [comment]
Hi, I don't know what "bulk" means. I just run the Exporter and see a list of available conversations to download, then click on each of them. And no, it's not a closed chat or anything, they appear just fine in my Discord but the Exporter seems to fail to pull them.

**Comment by Tyrrrz** [comment]
Yes, as mentioned above, it's probably because you closed the chat.

**Comment by SolXX** [comment]
As I said, I did NOT close the chat.

**Comment by Tyrrrz** [comment]
Didn't see, sorry. No idea then.

**Comment by 96-LB** [comment]
If you check the exporter right now and cross-reference the list with your Discord client, are you able to find any missing chats? Are they the same ones that were missing in your March export?

**Comment by SolXX** [comment]
Hi, I exported again today, some of the previously missing conversations are now showing up again in the list, but some others are still missing. This is truly weird.
