### ISSUE TITLE
Show spoiler first when clicking on referenced message in reply

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#545]
When I click on a message that is marked as a spoiler in Discord, it removes the black bar and I can read the message. However, if that spoiler tag only appears as part of something that was replied to, clicking on the spoiler tag only sends me to the message originally including the spoiler and does not remove the black bar in the reply. But if I click on a spoiler bar that was part of something that was replied to in the HTML file, it not only sends me to the location of the original message but also reveals the spoiler, which should not be the case, as it's not done like that in Discord itself.

**Comment by Tyrrrz** [comment]
Please include screenshots, it's really difficult to understand the problem description from text.

**Comment by CanePlayz** [comment]
Yeah, my bad. So when you click on this in Discord, it just jumps to the original messages that was replied to and does not remove the black bars anywhere:
![image](https://user-images.githubusercontent.com/81419612/114439485-52834b00-9bc9-11eb-87e4-f1378bd0cc78.png)
If you perform the same action in the HTML file, it also removes the black bars here instead of just jumping to the first message:
![image](https://user-images.githubusercontent.com/81419612/114439799-aee66a80-9bc9-11eb-9729-87cd390b72dc.png)
I hope that's easier to understand.

**Comment by Tyrrrz** [comment]
I had no idea we even showed spoiler bars in replies
