### ISSUE TITLE
Replies to embedded content are not formatted correctly

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#546]
When you reply to a GIF or any embedded content on Discord, it returns the following:
![image](https://user-images.githubusercontent.com/81419612/114428769-e4d12200-9bbc-11eb-9a52-7f0b7bf7a564.png)
In the exported HTML file, it instead shows the following:
![image](https://user-images.githubusercontent.com/81419612/114428893-0d591c00-9bbd-11eb-868e-14ec068cb87d.png)
Is there any reason why those two notes are worded differently? If not, the text in the HTML file should be changed to the text that Discord shows. 
Also, currently the HTML file returns the following if you reply to a GIF, instead of giving the aforementioned note:
![image](https://user-images.githubusercontent.com/81419612/114429117-4abda980-9bbd-11eb-9d8c-b5befcd3b06f.png)
However, I think the HTML will also show the note properly when replying to GIFs once GIFs will be shown embedded in the HTML file.

**Comment by Tyrrrz** [comment]
`Click to see original message` is shown when the referenced message contains no text content. We don't have a special case that shows `Click to see attachment`. Frankly, I don't find it that important since the call for action is the same in both cases.

As for the link to the GIF appearing on the right side, that looks like a bug. Can you isolate that message and attach the HTML file here?

**Comment by CanePlayz** [comment]
To your first point: I'm still wondering why our text here is "Click to see original message," and not "Click to see attachment," when the second one is the only one I ever see being used on Discord. Or am I wrong here and the first one is actually used on Discord in some places and I just don't see it? Then 

I would understand that it might be too complicated here to differentiate between those two cases, but otherwise, I would be wondering why we're not just using "Click to see attachment."

To the second point: That does not just appear for that one message but for every single time someone responds to a link to a GIF. (I have an HTML file of a chat where that issue appears, unfortunately though GitHub doesn't allow me to attach HTML files saying "We don't support that fily type.")
