### ISSUE TITLE
Localization for Discord status messages

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#547]
In some situations, there are notes by Discord (there's probably a word for it that fits way better, feel free to tell me), like when Discord says that someone pinned a message, someone changed the group icon or the "Click to see attachment" for replies. Those messages are different for everyone based on which language their Discord is set to. However, DCE always shows those notes in English, therefore limiting users' possibility to export their chats 1:1 how they're displayed for them. I think it would be good to add a language setting for those things in the DCE settings and enable users to export the chat in their language.

**Comment by Tyrrrz** [comment]
Unfortunately, Discord doesn't provide us with text for those messages. We'd have to embed translations ourselves.
This really is probably out of scope for this project and not worth the effort.

**Comment by CanePlayz** [comment]
I see ^^
