### ISSUE TITLE
Render emojis by code

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#549]
I just stumbled upon some messages where this problem occurs:
The bot sends a message:
![image](https://user-images.githubusercontent.com/81419612/114442241-a3e10980-9bcc-11eb-8ccf-f83b1a58a551.png)
The HTML file shows the following:
![image](https://user-images.githubusercontent.com/81419612/114442508-e73b7800-9bcc-11eb-92c1-d8528b1372a9.png)
As you can see, that emoji is somehow not displayed correctly. That problem has occurred quite often in that HTML file, however, it only appears if the :thumbsup: is the first word of a message
![image](https://user-images.githubusercontent.com/81419612/114442992-7a74ad80-9bcd-11eb-89cc-1df786323903.png)
(here it's not the first part of the message and therefore the emoji is displayed correctly)
and for messages sent after 02-Mar-21.
![image](https://user-images.githubusercontent.com/81419612/114443792-67161200-9bce-11eb-92db-5dda0f4eff07.png)
(as you can see here it, messages sent before that day are displayed correctly)

(And yeah, I see that the thing with commands on the very first screenshot is also not working yet, but that is something for another time and another issue)

**Comment by Tyrrrz** [comment]
It might not be related to whether it's the first word or not. I think what might be happening is that in some messages the bot sends the emoji as an actual emoji (👍🏻) and in some other cases using its code (`:thumbsup:`). I didn't know Discord automatically parses those codes and renders the corresponding emoji. If that's the case, we may have to do it too.

**Comment by 96-LB** [comment]
Just tested this with a bot account and I can confirm that this is the case. Though the Discord client seems to convert `:thumbsup:` to Unicode when a user sends a message (unless it's in code blocks), bot messages can contain a literal `:thumbsup:` in their content and Discord will still render it.

**Comment by Tyrrrz** [comment]
Yeah. We'd need to extract the conversion table they're using somehow. Then probably extend the markdown parser to parse those special codes as emojis, unless they are in code blocks.

**Comment by 96-LB** [comment]
I did some searching but I wasn't able to find their naming scheme anywhere. It doesn't seem to align perfectly with any "official" names I could find, and some emoji have multiple names anyway.
