### ISSUE TITLE
Ability to select all channels inside a server

### ISSUE THREAD

**Issue by DankMemeGuy** [Tyrrrz/DiscordChatExporter#556]
I'm not sure what the formal terms are, but when you load a server theres the main title, such as "Trading" then there's like a dozen channels inside that. When I load the software all the main titles are shown, then when you click it it expands to show you the channels inside it. 

I have to manually select all the channels. Would be nice to be able to just select the main title and have everything under selected, and have a select all button to select every channel on the server in one go.

There's servers with like 10-20 channels per title and like dozens of titles

**Comment by 96-LB** [comment]
If you hold shift when you click, it selects every channel between the currently selected one and the one you click on. You can select all the channels in a category or server by selecting the first channel, holding the shift button, and then selecting the last one.

**Comment by Tyrrrz** [comment]
Just like @96-LB explained, this is already possible using native Windows shortcuts.

**Comment by DankMemeGuy** [comment]
> If you hold shift when you click, it selects every channel between the currently selected one and the one you click on. You can select all the channels in a category or server by selecting the first channel, holding the shift button, and then selecting the last one.

thank you!!
