### ISSUE TITLE
Integrate into a Discord Bot to avoid ToS violation

### ISSUE THREAD

**Issue by BinToss** [Tyrrrz/DiscordChatExporter#559]
### Flavor

CLI (Command Line Interface)

#### Drawback
A bot can be invited to Servers and Groups, but the only DMs it would have access to would be useless (user-bot DMs).

#### Note
The Discord Bot does not need to be a feature of DiscordChatExporter. If anyone wants to fulfill this request by creating a bot that relies on DCE, that's fine as well.

An existing example of this would be [Discord Archive Bot](https://github.com/milutinke/Discord-Archive-Bot) which is great, but it doesn't list support for archiving Groups.

**Comment by Tyrrrz** [comment]
DiscordChatExporter already supports bot authentication. Making a bot is out of scope of the project though.

**Comment by BinToss** [comment]
Ah, that's good to hear!

I'm okay with this issue being either closed now or left open for people
who want to take up this request.

**Comment by 96-LB** [comment]
An easy way to avoid breaking TOS is to create a bot account yourself on the [Discord Developer Portal](https://discord.com/developers) and invite it to any servers you want to backup. You can then just take its token and use the application as usual. No scripts required, and you can have full control over which servers it's on by turning off the "public bot" setting.
