### ISSUE TITLE
Options in the filename template

### ISSUE THREAD

**Issue by donmerendolo** [Tyrrrz/DiscordChatExporter#563]
### Details

It would be nice to have the possibility to change the filename template. If I wanted to save channels in a folder structure, for example, `$guild [$guild_id]/$category/$channel/`, the guild and category in the filename would be redundant.

A good example of what I'd want is [youtube-dl](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template-examples). Changing the media folder name would be nice too, so two exports with different formats can share it.

**Comment by 96-LB** [comment]
See [this section](https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#generating-the-filename-and-output-directory-dynamically) on the wiki.

**Comment by donmerendolo** [comment]
Ahh, sorry and thank you!!!
