### ISSUE TITLE
Slash commands not displayed correctly

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#569]
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

Some time ago, Discord introduced slash commands for bot developers which after being used are displayed like this by Discord:

![image](https://user-images.githubusercontent.com/81419612/117990620-9c349200-b33d-11eb-9241-4db0bf096075.png)

However, since that feature is still pretty new, the commands are not shown at all in the HTML file as of now:

![image](https://user-images.githubusercontent.com/81419612/117990682-ab1b4480-b33d-11eb-9046-47a69faeaccf.png)

**Comment by Tyrrrz** [comment]
Thanks for including screenshots @CanePlayz 🙂

**Comment by Tyrrrz** [comment]
@CanePlayz can you please replicate this in the test cases sever, under `# reply-specs`?

**Comment by CanePlayz** [comment]
> @CanePlayz can you please replicate this in the test cases sever, under `# reply-tests`?

Sure, however, we need a bot supporting slash commands on that server and I cannot add one with current permissions.

**Comment by Tyrrrz** [comment]
> > @CanePlayz can you please replicate this in the test cases sever, under `# reply-tests`?
> 
> Sure, however, we need a bot supporting slash commands on that server and I cannot add one with current permissions.

I'm not sure which permission is responsible for that, so just let me know which bot I should invite and I'll do it.

**Comment by CanePlayz** [comment]
> > > @CanePlayz can you please replicate this in the test cases sever, under `# reply-tests`?
> > 
> > 
> > Sure, however, we need a bot supporting slash commands on that server and I cannot add one with current permissions.
> 
> I'm not sure which permission is responsible for that, so just let me know which bot I should invite and I'll do it.

Ok, let's just invite https://easypoll.bot/, it's the first one that came to my mind. 😄

**Comment by Tyrrrz** [comment]
> > > > @CanePlayz can you please replicate this in the test cases sever, under `# reply-tests`?
> > > 
> > > 
> > > Sure, however, we need a bot supporting slash commands on that server and I cannot add one with current permissions.
> > 
> > 
> > I'm not sure which permission is responsible for that, so just let me know which bot I should invite and I'll do it.
> 
> Ok, let's just invite [easypoll.bot](https://easypoll.bot/), it's the first one that came to my mind. 😄

Done!
