### ISSUE TITLE
"User pinned a message" not displayed correctly

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#571]
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

If someone pins a message, it's shown like this in the HTML currently:

![image](https://user-images.githubusercontent.com/81419612/117994884-26322a00-b341-11eb-8b22-02c3ee092df4.png)

This is how it's normally shown in Discord:

![image](https://user-images.githubusercontent.com/81419612/117995050-4bbf3380-b341-11eb-938e-3492890418ae.png)

**Comment by gan-of-culture** [comment]
Looks like something I could do and would love to have supported. Came up with a prototype already and will create a draft PR tomorrow!
