### ISSUE TITLE
Documentation about .NET formatting rules

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#572]
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

This probably isn't the most important addition to the application and it might be "out of the scope of the project" by your definition, but since I think it wouldn't take that much time to implement it and since I and a couple of friends have run across that problem ourselves already, I think it would be really helpful to link to a page with documentation about .NET date formatting. I think it could be really helpful for newer users without much background knowledge or even more experienced users who might have forgotten something. It could be put into the app via a little "info" icon in the app settings that either opens a small window with the link when you click it or immediately opens your browser and sends you to the website. Alternatively, the link could be put into the wiki here on GitHub. I think the best page with simple and full documentation on this is https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings. Again, I don't think that's really important but in case someone thinks this could be useful as well, I just wanna throw it in here, can't do any damage, right. :P

**Comment by Tyrrrz** [comment]
There is some coverage for that in the wiki here: https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#settings

**Comment by CanePlayz** [comment]
Oh sorry, my bad, that should be enough, no clue how I missed that.

**Comment by Tyrrrz** [comment]
No problem
