### ISSUE TITLE
No column separation in CSV export

### ISSUE THREAD

**Issue by Cyberpaul88** [Tyrrrz/DiscordChatExporter#58]
Dear Tyrrrz,

Your DiscordChatExporter is great, just what I needed for my research.
But there is a little issue: when I download the chat in CSV format, it is shown in one column 

![problema con discordchatexporter](https://user-images.githubusercontent.com/39853040/40872944-929a76e6-6657-11e8-84af-08ce4411ff04.png)

I would like to separate data in 4 columns as it is indicated in the first cell: Author, Date, Content and
 Attachments.

**Comment by paradoxpotato** [comment]
this is not a bug but intended behaviour of excel. the separator on your system is set to use semicolon instead of comma. It's the same on my device. If you go to "Data" --> Text to Columns you can set comma as separator.

**Comment by Cyberpaul88** [comment]
You are right. I just did what u suggested and it works!
