### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#581]
### Version

2.27.0

### Flavor

GUI (Graphical User Interface)

### Details

When I close the app, I get the following error message:

![image](https://user-images.githubusercontent.com/81419612/118373447-250a3280-b5b7-11eb-9d3e-b43f7e2fee7a.png)

When I start the app again, my settings are reset to default.

### Steps to reproduce

Just restart the app in my case, I guess.

**Comment by Tyrrrz** [comment]
Don't put DiscordChatExporter into a folder where it doesn't have write permissions (such as Program Files).

**Comment by CanePlayz** [comment]
Oh okay thanks, working now.
