### ISSUE TITLE
Make HTML export save profile pictures locally.

### ISSUE THREAD

**Issue by Dragonshadow14** [Tyrrrz/DiscordChatExporter#589]
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

HTML

### Details

When using the HTML export, if a user changes their profile picture the url goes invalid and their profile picture no longer shows. But if each pfp is saved locally, it would stay.

**Comment by Yudi** [comment]
Toggle the "Download media" option.  

![](https://i.imgur.com/p0PlvWz.png)

**Comment by Dragonshadow14** [comment]
> Toggle the "Download media" option.
> 
> ![](https://camo.githubusercontent.com/357dddb7a2ccbcf1fd0e09fc53207e8d32709fbadb8b606233865d91e48659f0/68747470733a2f2f692e696d6775722e636f6d2f7030506c76577a2e706e67)

Thanks, I didn't know this. But after using it I have another suggestion. Sort the media. Something simple like a folder for profile pictures and a folder for user-uploaded media

**Comment by Tyrrrz** [comment]
> But after using it I have another suggestion. Sort the media. Something simple like a folder for profile pictures and a folder for user-uploaded media

Out of scope sorry.
