### ISSUE TITLE
Export csv in 24h Format

### ISSUE THREAD

**Issue by paradoxpotato** [Tyrrrz/DiscordChatExporter#59]
Hey there,
either I am doing sth. wrong or the export to csv via the CLI is not working 100%. I find no way to make 24h format for date in csv. What dateformat do I have to enter for the --dateformat paraemter to get 24h format?
HH:mm does not work, HH:mm:tt doesnt aswell.
If that helps: I am using powershell.

**Comment by Tyrrrz** [comment]
Hi
Can you copy the entire command you're running in PowerShell to do this?

**Comment by paradoxpotato** [comment]
Sorry, my mistake. I forgot to put quotation marks around it. now it works. stupid me. Maybe some readme for the cli would be appreciated though :)
