### ISSUE TITLE
Use Discord CDN URLs for retrieving embedded content

### ISSUE THREAD

**Issue by Liz-chan** [Tyrrrz/DiscordChatExporter#590]
### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

In the latest version, if you open an HTML export that you've made, it connects to every domain that has been used for sending media instead of using Discord's proxy like the official client uses. This is a security issue since those endpoints can change in the future, or more likely, they could also be IP loggers that you were smart enough not to click, but have inadvertently visited it because you didn't know your backups would connect to every 3rd-party media domain.
 
I think it would be a massive improvement if the HTML files would use Discord's proxy URL for showing the images, and when you click on them, it takes you to the actual domain where the image is hosted, like in the official client. Not only for privacy reasons, but it's probably better for performance to connect to 1 fast proxy domain rather than a bunch of different ones.

**Comment by Tyrrrz** [comment]
Good point. Discord API already provides these CDN URLs in the form of `proxy_url` field on most objects:

https://discord.com/developers/docs/resources/channel#embed-object-embed-image-structure

![image](https://user-images.githubusercontent.com/1935960/119557678-545a3580-bd55-11eb-82da-f2c3215d31ff.png)

We can then use the actual URL inside `<a href="...">` and use the proxy URL as the source.
