### ISSUE TITLE
Make the GUI show up every single DM channel you have ever had

### ISSUE THREAD

**Issue by Auditormadness9** [Tyrrrz/DiscordChatExporter#594]
### Flavor

GUI (Graphical User Interface)

### Details

Currently the GUI only shows up the currently open DMs in your Discord, but I learned that literally any DM channel that you have ever had can be easily exported since all the snowflakes of all your DMs are stored in Discord data, as when you request to get your data package, you can find an index.json file which lists the IDs of all DMs you have ever had. At first I thought what's been closed has been closed and is gone forever, but apparently I tried out CLI and used an id from the index.json file of a DM long closed and gone, and it worked! So the GUI doesn't list it not simply because it's not retrievable, but simply because it hasn't been considered.

Solution: Make GUI list all the DMs you have had using your Discord data, just like index.json could retrieve them, and just like using them in CLI worked.

**Comment by 96-LB** [comment]
I think DiscordChatExporter makes a request to the Discord API to get the list of available DMs, so it can only work with the information that Discord provides. Requesting your data package from Discord takes weeks, no?

**Comment by Auditormadness9** [comment]
> I think DiscordChatExporter makes a request to the Discord API to get the list of available DMs, so it can only work with the information that Discord provides. Requesting your data package from Discord takes weeks, no?

Umm that's how it's "advertised" but I always get it within a day.

**Comment by Tyrrrz** [comment]
That would still involve a manual step for the user to request the data package, then wait for it to arrive, then manually "load" it in DiscordChatExporter, which would be a completely separate flow from the "click button to get the list of channels" we have now. Not saying that getting closed channels wouldn't be nice, but this is not a good solution, unfortunately.
