### ISSUE TITLE
Export channels based on the GDPR data dump

### ISSUE THREAD

**Issue by Auditormadness9** [Tyrrrz/DiscordChatExporter#597]
### Flavor

CLI (Command Line Interface)

### Details

Update the _exportall_ command, or make a new one, that takes the **index.json** file that a user obtained through requesting their data package from discord, the said file containing all the IDs of literally every DM they have had in their account lifetime (listed or closed, doesn't matter), and use it to read all the IDs and export all of the DMs, not just the currently open ones.

Since this app cannot request a data package on its own (especially since a data package takes hours/days/weeks to arrive), it would be much more suitable and simpler for it to merely use the **index.json** file that came from the request.

**Comment by rebane2001** [comment]
As a bodge, I made a quick script that helps achieve the same goal:

```python
import os
import json

# Settings
PROCESS_DMS = True
PROCESS_GROUPS = True
PROCESS_GUILD_CHANNELS = False

channel_ids = []
for folder in os.listdir():
    if os.path.isfile(folder):
        continue
    with open(os.path.join(folder,"channel.json"), "r") as f:
        channel = json.load(f)
        if ((channel["type"] == 0 and PROCESS_GUILD_CHANNELS)
         or (channel["type"] == 1 and PROCESS_DMS)
         or (channel["type"] == 3 and PROCESS_GROUPS)):
            channel_ids.append(folder)
print(" ".join(channel_ids))
```

Put this script in the `messages` folder of your takeout package, set the settings and run it. The output will be a list of channel IDs based on your settings that looks something like this: `106818467547163713 182588652098697417 289270027775765538 510326469454178206`.

You can then use it with DiscordChatExporter like this `DiscordChatExporter export -c 106818467547163713 182588652098697417 289270027775765538 510326469454178206 -t "..."`. The Linux command line has no problem running very long commands, so while it's a bit ugly to have hundreds of channel IDs on the command line like that, it should work just fine.

**Comment by Tersordo** [comment]
Slightly modified code if anyone needs it, because the previous one didn't work for me:
```javascript
import os
import json

# Settings
PROCESS_DM = True
PROCESS_GROUP_DM = True

channel_ids = []
for folder in os.listdir():
    if os.path.isfile(folder):
        continue
    with open(os.path.join(folder,"channel.json"), "r") as f:
        channel = json.load(f)
        if ((channel["type"] == "DM"  and PROCESS_DM)
         or (channel["type"] == "GROUP_DM" and PROCESS_GROUP_DM)):
            channel_ids.append(folder[1:])
print(" ".join(channel_ids))
```
