### ISSUE TITLE
Show names of standard emoji when hovering over them

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#599]
### Export format

HTML

### Details

I don't exactly know how to call them, but when you hover over certain "standard emoji", that are integrated in Windows, the emoji name isn't shown but instead it's the actual emote in a different style:
![image](https://user-images.githubusercontent.com/81419612/120080588-f9f50800-c0b9-11eb-8d05-b88be5d533cd.png)

When you hover over a custom emote, the name of it is shown:
![image](https://user-images.githubusercontent.com/81419612/120080649-48a2a200-c0ba-11eb-8031-30e3316a4ba1.png)

I don't know what other people think about this, but to keep it consistent I think when you hover standard emoji it should also show their name. And in general, I think that way it's just way better.

**Comment by Tyrrrz** [comment]
I welcome suggestions on how to identify emojis by name ;)

**Comment by CanePlayz** [comment]
Oh, that's unfortunately not where **I** can help you, naive me thought that if you can get the name of custom emoji from the API and put it in there, you could do it for standard emoji as well and easily put it in the "title" parameter (at least I think that's where it goes).

**Comment by Tyrrrz** [comment]
Unfortunately standard emojis are not identified in any way, they are just contained within the text body as characters.

**Comment by CanePlayz** [comment]
Ok I see, but from as much as I understand, while some actually aren't, those for which the emoji matcher works, are contained as emoji in the HTML file. For example, :smile: is a standard emoji but is actually contained as an emoji in the HTML file and not just as a character: 
![image](https://user-images.githubusercontent.com/81419612/120194156-8cfa8300-c21d-11eb-8b5a-3618f1341c34.png)
Wouldn't it be possible then to at least do it for those, since they are contained as emoji in the file? Or do I understand that wrong, and them being contained as emoji still doesn't make it possible to show their actual name?

**Comment by Tyrrrz** [comment]
Well what I mean by that is that 😄 is a character (or a rune to be precise). It's identified by its codepoint(s), which is U+1F604 in this case.
To resolve their "names", we'd need some sort of table that maps those codepoints to something like "smile". It may also be useful for other issues like #549.

**Comment by CanePlayz** [comment]
Okay, I understand.

> To resolve the emoji "name", we'd need some sort of table that maps those codepoints to something like "smile". It may also be useful for other issues like #549.

Would it be possible for me even without much background knowledge (I understand most of it, I'm just not into coding) to help out with that table with instructions from you and it's just simple work but takes a lot of time (I would be down to do that) or does creating a table like that actually require some more deep knowledge I would need?

**Comment by Tyrrrz** [comment]
> Would it be possible for me even without much background knowledge (I understand most of it, I'm just not into coding) to help out with that table with instructions from you and it's just simple work but takes a lot of time (I would be down to do that) or does creating a table like that actually require some more deep knowledge I would need?

Yeah it's mostly just manual work. The goal is to find all emoji names that Discord has and put them into a table like this:

```csv
Name|Emoji
:pensive:|😔
:joy:|😂
```

Some emojis may have multiple names too I think. I'm not sure what's the most efficient way to approach this other than to meticulously go through each emoji in the emoji picker (maybe there's a list somewhere?).

**Comment by CanePlayz** [comment]
I haven't found a list somewhere, but I'll start creating one as soon as I have time. Just one more quick question: If there are multiple names for one and the same emoji (for example `:thinking:` and `:thinking_face:`), how do I put them into the table?

**Comment by Tyrrrz** [comment]
Thanks!
You can put them next to each other, i.e.

 ```
:thinking:|🤔
:thinking_face:|🤔
```

**Comment by CanePlayz** [comment]
Ok.

So the closest thing to a list I could find was this json file from the Android app: https://drive.google.com/file/d/13ytMWyBq_ZpGsub_GCoLP1qEBAY8tfKn/view?usp=sharing
While I don't think it's really useful for that, I thought it's worth a try. And even if it doesn't help in the first place, I can use that file to copy the names and emojis faster to my own list.

**Comment by 96-LB** [comment]
Is this straight from Discord itself? That actually looks really useful.

**Comment by CanePlayz** [comment]
Yes, it's from one of the latest android apks

**Comment by 96-LB** [comment]
I think we could reasonably extract a mapping between names and codepoints from that file. That would probably help #548 as well since this lists every emoji which Discord renders, allowing us to cross-reference it before rendering it in Twemoji. It looks as if it includes the zero-width joiner sequences such as the family emoji and different skin tones, so maybe we can get support for those too.

**Comment by Tyrrrz** [comment]
Yeah looks useful

**Comment by CanePlayz** [comment]
Does that mean you don't need me to manually put together that list?

**Comment by 96-LB** [comment]
Probably not. It'd be much easier to either write a quick progam that converts the JSON file into our `:thinking:|🤔` format, or just use the JSON file itself. If needed/wanted, I can convert it to that table format and upload it here.

**Comment by Tyrrrz** [comment]
The table format itself doesn't matter, we just need the mapping, which the JSON file seems to provide (assuming it's complete).

**Comment by 96-LB** [comment]
It seems to be complete. One thing to watch out for is that some emoji are nested inside others as "diversity children". For example, the JSON object for 👍 has child properties for 👍🏻, 👍🏽, 👍🏿, etc. instead of the latter being listed at the top of the hierarchy.

**Comment by Tyrrrz** [comment]
> It seems to be complete. One thing to watch out for is that some emoji are nested inside others as "diversity children". For example, the JSON object for 👍 has child properties for 👍🏻, 👍🏽, 👍🏿, etc. instead of the latter being listed at the top of the hierarchy.

They still have all the required information it seems, so it's fine. I think ideally we'd want to convert it to a planar representation (similar to the table format I mentioned). We could probably just extract the data from JSON file and convert it to static C# code (dictionary of name<->codepoints mapping) so we don't have to deal with it at runtime.

**Comment by 96-LB** [comment]
> We could probably just extract the data from JSON file and convert it to static C# code (dictionary of name<->codepoints mapping) so we don't have to deal with it at runtime.

Something like a file containing the following?
```cs
static Dictionary<string, string> emojiMap = new()
{
    ["grinning"] = "😀",
    ["laughing"] = "😆",
    ["satisfied"] = "😆",
    //...
};
```
(and vice versa)

**Comment by Tyrrrz** [comment]
Yes.

**Comment by CanePlayz** [comment]
With the release of Twemoji 13.1 just two days ago in Discord, there have been new emotes added. Here is the new json file including the new ones as well: https://drive.google.com/file/d/1lZ3IcSAEnUOHODQhkOieiwJ1cx68G0XO/view?usp=sharing

**Comment by 96-LB** [comment]
I've got a lot going on right now, but I've extracted the emoji lists into Dictionaries and attached them to this message in case anyone wants to use them for a PR.
[surrogatesToNames.txt](https://github.com/Tyrrrz/DiscordChatExporter/files/6672141/surrogatesToNames.txt)
[namesToSurrogates.txt](https://github.com/Tyrrrz/DiscordChatExporter/files/6672142/namesToSurrogates.txt)

**Comment by Tyrrrz** [comment]
Thanks @96-LB!
This should make the issue quite straightforward for anyone who wants to contribute.
