### ISSUE TITLE
Add time range option.

### ISSUE THREAD

**Issue by FangsMcWolf** [Tyrrrz/DiscordChatExporter#6]
Simple enough.  Add ability to limit the date/time range of logs to get. Allow use of dynamic ranges as well.

```
/range:12d
12 days (d/h/m = days/hours/minutes)
```

IF POSSIBLE, also allow these options (not sure what the API allows you to do):
```
/range:[from date]~[to date]
(if from or to not given, then assume the max, otherwise use date range given)

/range:2017-01-01~
from Jan 1st, 2017 to current

/range:2017-01-01
get logs for only the one day.

/range:2017-01
get logs for that month (sort of like 2017-01-01~2017-01-31)
```

**Comment by FangsMcWolf** [comment]
Thank you, I'm sure many people will make a lot of use from this addition. 👍

**Comment by Tyrrrz** [comment]
Available in new release :p

**Comment by FangsMcWolf** [comment]
Awesome.  Too bad Discord doesn't include this (exporting logs) as a default option.  Oh well, gives you a chance to show off your skills.

Kudos for this added feature.
