### ISSUE TITLE
Discord embeds are not exported

### ISSUE THREAD

**Issue by wxMichael** [Tyrrrz/DiscordChatExporter#60]
Discord Embeds from bots and self-bots as well as BetterDiscord plugins such as Quoter are excluded from the export, resulting in empty or missing messages.

**Comment by Tyrrrz** [comment]
They are supported, but the feature has not been released yet. Implementing it doubled the cyclomatic complexity so it's being refactored right now. I'll leave this issue open until it's released.

**Comment by mattmarich** [comment]
If I pull master and compile should i be able to export embeds from the bots we use or have those changes not been pushed?

**Comment by Tyrrrz** [comment]
Yes you will be able to

**Comment by Tyrrrz** [comment]
It's ready for release, except that the light theme doesn't support embeds yet :p
