### ISSUE TITLE
Save dialog reports file not found when saving an exported DM

### ISSUE THREAD

**Issue by Wayne-Ca** [Tyrrrz/DiscordChatExporter#600]
### Version

2.27.0

### Flavor

GUI (Graphical User Interface)

### Details

I am following the steps as directed. The DM shows up in the list of channels and DMs I have. I select the DM to export and click the download icon. I get a dialog with the name of the DM, and am given options. I have tried selecting a before date option, and I have tried leaving the date option blank. I am assuming the date and time options are optional and not mandatory, as not selecting either should indicate select all.

Update: I tried selecting a before date and a before time just in case they were both mandatory. I get the same result.

I have selected html and txt and both result in the same error. I click the export button and get the save dialog. I click save and get the error dialog saying the file isn't found. Why would a save dialog produce that error?

Everything here is what I did. You can reproduce the error by following the same steps I outlined here.

### Steps to reproduce

assuming you have already entered your developer id, beginning with the list of channels/servers/DMs you have.

select the dm to export
click download
select file type, and optionally a before date or just leave it blank
click export
click save

**Comment by Wayne-Ca** [comment]
The problem was windows. I forgot that the security blocks all attempts to write to disc until I authorize the app

**Comment by Tyrrrz** [comment]
Glad you resolved it. I would have had no idea ;)
