### ISSUE TITLE
"Unable to load dll 'wpfgfx_cor3.dll' or one of its dependencies" in Windows 7

### ISSUE THREAD

**Issue by augthespoon** [Tyrrrz/DiscordChatExporter#627]
### Version

2.28

### Flavor

GUI (Graphical User Interface)

### Details

I somehow cannot open it in Windows 7 Professional 64 bit. it will output [this error message](https://cdn.discordapp.com/attachments/816763017701883935/860945358791376916/error.png) every time im trying to launch this app. works fine on windows 10 tho.

### Steps to reproduce

try to open the app

**Comment by Tyrrrz** [comment]
Can you try uninstalling and installing `.NET Runtime (WindowsDesktop)`?
