### ISSUE TITLE
libhostpolicy.so

### ISSUE THREAD

**Issue by KarelWintersky** [Tyrrrz/DiscordChatExporter#628]
### Version

2.28

### Flavor

CLI (Command Line Interface)

### Export format

HTML

### Details

A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/arris/dotnet/export/'.

Failed to run as a self-contained app. If this should be a framework-dependent app, add the /home/arris/dotnet/export/DiscordChatExporter.Core.runtimeconfig.json file specifying the appropriate framework.

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.0"
    }
  }
}
```

```
$ dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

after installing `sudo apt-get install -y aspnetcore-runtime-5.0` : 
```
$ dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

But:
```
/home/arris/dotnet/export$ dotnet DiscordChatExporter.Core.dll export -t "...."                                  

Cannot use file stream for [/home/arris/dotnet/export/DiscordChatExporter.Core.deps.json]: No such file or directory
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/arris/dotnet/export/'.

Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/home/arris/dotnet/export/DiscordChatExporter.Core.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/home/arris/dotnet/export/DiscordChatExporter.Core.runtimeconfig.json' file and specify the appropriate framework.
```

Really, this file does not exist in release archives. 

### Steps to reproduce

- install runtime just as expected in readme
- run `dotnet DiscordChatExporter.Core.dll export -t "...." `

**Comment by Tyrrrz** [comment]
Are you missing `DiscordChatExporter.Core.runtimeconfig.json` in your directory?

**Comment by KarelWintersky** [comment]
> Are you missing DiscordChatExporter.Core.runtimeconfig.json in your directory?

yeah. No such file in archive. 

![изображение](https://user-images.githubusercontent.com/2164874/124474052-bb352a80-dda8-11eb-8348-9204677c40e0.png)

**Comment by Tyrrrz** [comment]
Okay, I missed the elephant in the room.

This is wrong:

```
dotnet DiscordChatExporter.Core.dll export -t "...."
```

Should be:

```
dotnet DiscordChatExporter.dll export -t "...."
```

**Comment by Tyrrrz** [comment]
Also, you downloaded the GUI version (judging by the files in the last screenshot), which only works on Windows. You'll want to use CLI on other OSs.

**Comment by KarelWintersky** [comment]
> You'll want to use CLI on other OSs.

I downloaded all available archives.

**Comment by Tyrrrz** [comment]
OK, so, finally, you'll need to call `dotnet DiscordChatExporter.Cli.dll` 🙃 Just like it mentions in the wiki: https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#using-the-cli
