### ISSUE TITLE
Update the in-app instructions for getting user token

### ISSUE THREAD

**Issue by virtuallyvlad** [Tyrrrz/DiscordChatExporter#630]
### Version

2.28.0

### Flavor

GUI (Graphical User Interface)

### Details

It seems the old instructions for pulling a user token no longer work.  I [updated the wiki](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs#how-to-get-a-user-token) but could you please update the initial in-app instructions?

Perhaps it would be better to just link/load the wiki page, as these instructions can change again in the future.

Regarding the updated instructions, it seems you now need to enable the device toolbar (Device Mode) to get the token to appear.  Also, I don't believe CTRL+R does anything anymore but I left it in just in case.  Additionally, I couldn't update the GIF so you may want to update that or remove it.

### Steps to reproduce

- Open the app on a new/unconfigured profile/machine
- Old, no longer working instructions will appear

**Comment by Yudi** [comment]
I'm quite sure that the old instructions are working just fine. 
Maybe the token is just [disappearing too quickly](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Troubleshooting#my-token-is-disappearing-too-quickly-i-cant-copy-it) for you…?

I don't think that most people know the wiki exists despite the amount of notices, so it's just better to keep the in-app instructions.

**Comment by virtuallyvlad** [comment]
> I'm quite sure that the old instructions are working just fine.
> Maybe the token is just [disappearing too quickly](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Troubleshooting#my-token-is-disappearing-too-quickly-i-cant-copy-it) for you…?

Even if the old instructions still work for you, this improves them by avoiding the disappearing token issue, which may confuse users since that too is not mentioned anywhere on the in-app instructions.
> I don't think that most people know the wiki exists, despite the amount of notices, so it's just better to keep the in-app instructions.

I'm not sure what you mean.  I was suggesting to have the app either [link to the wiki's instructions](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs#how-to-get-a-user-token) or load it directly in-app, to avoid having to update two places in the event of any changes.

**Comment by Tyrrrz** [comment]
FYI the app already links to the wiki (not directly to the "how to obtain token" page, but it's there)

![image](https://user-images.githubusercontent.com/1935960/125109643-79ea9680-e098-11eb-8395-73a9de113691.png)

**Comment by virtuallyvlad** [comment]
Yep, I mean't link directly to the instructions and not have a separate copy in-app as it may get out of date.  But that was just a separate suggestion... you can continue to maintain the two separately if that's preferred.

**Comment by Tyrrrz** [comment]
I think it helps to save a click, even if the instructions don't work some of the time. Also, for what it's worth, I can still get the token using the old method (on Discord's desktop app for Windows).

**Comment by virtuallyvlad** [comment]
> I think it helps to save a click, even if the instructions don't work some of the time.

Agreed, I'd prefer to avoid the click as well, which is why I mentioned loading the wiki page within the app window.
> Also, for what it's worth, I can still get the token using the old method (on Discord's desktop app for Windows).

Interesting -- I didn't test via the Windows app, but rather discord.com within the browser, so perhaps that's the difference.  If the new instructions work on both perhaps that's better?  Likewise, perhaps better for avoiding that annoying disappearing token issue, which has required a second set of instructions.

**Comment by Tyrrrz** [comment]
> which is why I mentioned loading the wiki page within the app window.

Yeah the loading will be tough. Most likely won't happen for technical reasons and the headaches it would bring.

> Interesting -- I didn't test via the Windows app, but rather discord.com within the browser, so perhaps that's the difference. If the new instructions work on both perhaps that's better? Likewise, perhaps better for avoiding that annoying disappearing token issue, which has required a second set of instructions.

One thing to note about your changes in the wiki is that you recommend opening Discord in a browser. Depending on the browser, the steps may very likely be different. For the Desktop app is always the same, on the other hand, because it's using Electron. So can we edit that part?

Also I wonder why the device mode may be necessary? 🤔

**Comment by Yudi** [comment]
> Also I wonder why the device mode may be necessary? 🤔

It seems that Discord always shows the token on mobile devices, so device mode must be messing with their detection.  


Perhaps we can keep the old instructions and replace the [header workaround](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Troubleshooting#my-token-is-disappearing-too-quickly-i-cant-copy-it) with the new method.
Might break in the future, but it's more user-friendly.

However, the **Ctrl+Shift+M** shortcut might cause some confusion since:
• It's also the shortcut for muting the mic, so the user must click on the developer window before pressing it;
• It's different in Safari and Firefox for macOS. 
But the icon ![](https://user-images.githubusercontent.com/12040397/125126345-55f77700-e0d1-11eb-97a4-562c7ba8bfe1.png) is consistent across browsers (except Safari).

Displaying the icon and listing the different shortcuts would add unnecessary clutter to the in-app instructions, but I think it's fine on the wiki.

**Comment by virtuallyvlad** [comment]
> > which is why I mentioned loading the wiki page within the app window.
> 
> Yeah the loading will be tough. Most likely won't happen for technical reasons and the headaches it would bring.

Yep, figured that may be tougher to do.  Well, it was just a suggestion anyway.  If it has to be kept as a separate page, that's understandable.

> > Interesting -- I didn't test via the Windows app, but rather discord.com within the browser, so perhaps that's the difference. If the new instructions work on both perhaps that's better? Likewise, perhaps better for avoiding that annoying disappearing token issue, which has required a second set of instructions.
> 
> One thing to note about your changes in the wiki is that you recommend opening Discord in a browser. Depending on the browser, the steps may very likely be different. For the Desktop app is always the same, on the other hand, because it's using Electron. So can we edit that part?
> 
> Also I wonder why the device mode may be necessary?

I edited the instructions to note the use of desktop app, but also mentioned that it works in Chrome & Brave.  Some users avoid or don't have the desktop app, so this supports both.

---

> Perhaps we can keep the old instructions and replace the [header workaround](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Troubleshooting#my-token-is-disappearing-too-quickly-i-cant-copy-it) with the new method.
> Might break in the future, but it's more user-friendly.

The old instructions are pretty unfriendly.  If you're on the browser, those instructions won't work and you'll need to install the Discord desktop app just to get the token.  And even if you are already using the Discord desktop app, you may encounter the disappearing token issue and have to follow a whole 'nother set of instructions which are not even mentioned on the in-app steps.  The new steps work for both desktop app and Chrome-based browsers and should avoid the disappearing token issue in both.

> However, the **Ctrl+Shift+M** shortcut might cause some confusion since:
> • It's also the shortcut for muting the mic, so the user must click on the developer window before pressing it;

It shouldn't require an extra click since it's right after step 2, which puts focus on the Developer tools pane.

> • It's different in Safari and Firefox for macOS.
> But the icon ![](https://user-images.githubusercontent.com/12040397/125126345-55f77700-e0d1-11eb-97a4-562c7ba8bfe1.png) is consistent across browsers (except Safari).

I updated it to note that it also works via Chrome & Brave browsers.  So can leave as is or can add/update steps to include Safari/Firefox as well.

**Comment by Yudi** [comment]
Aight.
I'll update the page to fix some formatting issues and make the instructions clearer. 

Then let's wait for Tyrrrz.

**Comment by Tyrrrz** [comment]
Yeah, if someone wants to send a PR to update the instructions, it should only require trivial changes in two places:

https://github.com/Tyrrrz/DiscordChatExporter/blob/524b30b09b8ea86ccf1ab3ac155fc1dc5abd4037/DiscordChatExporter.Gui/Views/RootView.xaml#L158-L183

https://github.com/Tyrrrz/DiscordChatExporter/blob/524b30b09b8ea86ccf1ab3ac155fc1dc5abd4037/DiscordChatExporter.Cli/Commands/GuideCommand.cs#L14-L24
