### ISSUE TITLE
Display messages from other servers correctly

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#633]
### Export format

HTML

### Details

Currently, messages from announcement channels posted in your own servers are shown like that in the exported HTML file:

![image](https://user-images.githubusercontent.com/81419612/125178567-b1675900-e1e6-11eb-8afb-5038642b8cb2.png)

However, they should be shown like that: 

![image](https://user-images.githubusercontent.com/81419612/125178572-c3e19280-e1e6-11eb-955c-2ac8bc057ae5.png)

**Comment by Tyrrrz** [comment]
Interesting, I wonder where the message reference is coming from.

**Comment by Tyrrrz** [comment]
Is there a public server with those that I can get invited to for testing purposes?

**Comment by Tyrrrz** [comment]
@CanePlayz can you replicate this in the test server so I can debug it?

**Comment by CanePlayz** [comment]
> @CanePlayz can you replicate this in the test server so I can debug it?

Sure. In which channel should I set up the feed?

**Comment by Tyrrrz** [comment]
Looks like the only clue in the data is the fact that `message_reference.guild_id` points to a different guild.

```json
{
  "id": "1072165330853576876",
  "type": 0,
  "content": "This is a test message from an announcement channel on another server",
  "channel_id": "866459871934677052",
  "author": {
    "bot": true,
    "id": "1072165140180512849",
    "username": "The Whoops #test",
    "avatar": "250f3093fce446b7204e2cae6bc69d33",
    "discriminator": "0000"
  },
  "attachments": [],
  "embeds": [],
  "mentions": [],
  "mention_roles": [],
  "pinned": false,
  "mention_everyone": false,
  "tts": false,
  "timestamp": "2023-02-06T14:42:14.744000+00:00",
  "edited_timestamp": null,
  "flags": 2,
  "components": [],
  "webhook_id": "1072165140180512849",
  "message_reference": {
    "channel_id": "1072148163282075668",
    "guild_id": "605409151270518785",
    "message_id": "1072165295013253140"
  }
}
```
