### ISSUE TITLE
Show call messages properly

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#635]
### Export format

HTML

### Details

Currently, call messages are shown like this in the HTML file:

![image](https://user-images.githubusercontent.com/81419612/125179031-bc23ed00-e1ea-11eb-99fe-c559a3814cfa.png)

However, on Discord they are shown like this and should also be shown like that in the HTML file:

![image](https://user-images.githubusercontent.com/81419612/125179048-de1d6f80-e1ea-11eb-98bf-6cb485f39629.png)

**Comment by Tyrrrz** [comment]
Related to #571 (same underlying issue)
