### ISSUE TITLE
Support showing Unix Timestamps

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#637]
### Export format

HTML

### Details

Recently, Discord has added support for unix timestamps. If you put the timestamp into a format like <t:1625962971> or with an additional parameter like <t:1625962971:R>, it shows up like that:
![image](https://user-images.githubusercontent.com/81419612/125179645-871a9900-e1f0-11eb-938b-f50f0ca19006.png)

With the Chat Exporter, it's not supported yet in the HTML file and will just show the characters.
![image](https://user-images.githubusercontent.com/81419612/125179729-47a07c80-e1f1-11eb-9b5f-bb5dac91acc4.png)

**Comment by Tyrrrz** [comment]
Is there a reference on this format? What other parameters except 'R' does it accept? Does it work only with unix timestamps?

**Comment by Tyrrrz** [comment]
For now I implemented it without respecting the 'R' parameter because I think there is not much sense in showing relative timestamps in an export. If people start requesting it, we can improve this by updating the relative timestamp dynamically in the export via JavaScript.

**Comment by CanePlayz** [comment]
> Is there a reference on this format? What other parameters except 'R' does it accept? Does it work only with unix timestamps?

Under "Timestamp Styles" on https://discord.com/developers/docs/reference, there is documentation about the different timestamp styles available.

> For now I implemented it without respecting the 'R' parameter because I think there is not much sense in showing relative timestamps in an export. If people start requesting it, we can improve this by updating the relative timestamp dynamically in the export via JavaScript. But for now I think it's okay, we'll see how many people are actually using it.

Good, thanks 👍
