### ISSUE TITLE
Set a "speed limit" when reading messages

### ISSUE THREAD

**Issue by tyto-alba-alba** [Tyrrrz/DiscordChatExporter#64]
I have to say that I love this tool, since there is no way in Discord to backup our messages.
However, something that I am worried about is that, if I understood right, usage of the user account token is theorically prohibited by Discord, and I could get my account banned because of that (officially because of API flooding issues)
I've read through the APIs docs lately, but it seems there is no "legal" way to save the DMs of an user (we can only save the server's messages).

So I wanted to ask, is there a kind of "speed limit" that would "humanize" the reading of messages (and making the tool "banning-proof") ? A normal Discord client behavior would be to fetch the messages by segments and waiting for a little time of loading between them. If the tool fetches like 100 messages at once, I guess our account could get flagged as suspicious by the API.

If not, this may be a good feature to add (this could be a mode to enable, with a checkbox for example)

Thanks in advance!

**Comment by Tyrrrz** [comment]
Out of scope for now, until this becomes a concern. I don't know of anyone being banned by using this tool, so I don't really see the need for this.
