### ISSUE TITLE
Parts of embedded messages not formatted correctly

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#640]
### Version

2.28.0

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

HTML

### Details

Parts of embedded messages are not formatted correctly.

Original message on Discord:
![image](https://user-images.githubusercontent.com/81419612/125356719-e26e9780-e366-11eb-8a6a-ec089c883023.png)

Message in the exported HTML file:
![image](https://user-images.githubusercontent.com/81419612/125356740-eac6d280-e366-11eb-906c-0ad60365a0b1.png)

### Steps to reproduce

Export a chat including a message with the embedded messages formatting in question.

**Comment by CanePlayz** [comment]
Oh uhm, should this be changed to be a feature request? I didn't really know because it's not really requesting a whole new feature but also not a bug in the traditional sense.

**Comment by Tyrrrz** [comment]
I couldn't reproduce this, do you have an invite to that channel I can use?

**Comment by CanePlayz** [comment]
> I couldn't reproduce this, do you have an invite to that channel I can use?

There is the embed message with that bottom line in question: https://discord.gg/5HzAm6p6

**Comment by Tyrrrz** [comment]
Fixed

![image](https://user-images.githubusercontent.com/1935960/126870921-a3307598-626f-4515-bb85-89a658ec88ad.png)
