### ISSUE TITLE
Show join messages properly

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#641]
### Export format

HTML

### Details

I think it would be quite good to make the join messages look more like the ones in Discord, if that's possible.

How it's shown in the HTML file currently:
![image](https://user-images.githubusercontent.com/81419612/125358317-06cb7380-e369-11eb-80a0-59f5c41ed8ae.png)

How it's shown on Discord:
![image](https://user-images.githubusercontent.com/81419612/125358352-121e9f00-e369-11eb-9fa6-226ee3ac8eac.png)

**Comment by Tyrrrz** [comment]
Also related to #635 and #571.
