### ISSUE TITLE
Support for message components (buttons and dropdown menus)

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#642]
### Export format

HTML

### Details

Recently, Discord has added support for buttons and dropdown menus for bots. Here is an example how buttons look:
![image](https://user-images.githubusercontent.com/81419612/125358985-efd95100-e369-11eb-8910-a3bbdf583006.png)

Because it hasn't been implemented yet, they just don't appear in the HTML files as of yet, but I think eventually they should be integrated.

**Comment by Tyrrrz** [comment]
I don't know how integral this is to the export. Would you really need to know what kind of options were presented to the user, given that you won't be able to actually click on anything?

**Comment by CanePlayz** [comment]
I mean it'd be nice to have them, but you're totally right, they wouldn't serve a purpose in the export. So yeah, I think it's fine if we not render them. 👍

**Comment by Tyrrrz** [comment]
Ok let's close it then 🙂
