### ISSUE TITLE
Original messages cannot be loaded if replied to a very old message

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#645]
### Export format

HTML

### Details

Sometimes, if you reply to a very old message, the original message is not displayed and instead, the HTML file just shows "Original message was deleted." 
![image](https://user-images.githubusercontent.com/81419612/125510191-b9fd5694-5910-4e7c-8d0e-3da838c64b18.png)
In the case of other replies to very old messages though, it actually shows the original message properly, so that error only happens with some messages.
When I go to that reply on Discord, it shows the following and also does not load the message properly (even after I've went manually to that message, it still shows the following).
![image](https://user-images.githubusercontent.com/81419612/125510015-163c8116-c13f-4cd9-857c-d612930fdf2d.png)
Most of the times, if the error occurs in the HTML file, it also occurs on Discord and the other way around, however though, that does not apply to all the messages not being displayed correctly in one of the cases.

**Comment by Tyrrrz** [comment]
I wonder how to discern between deleted messages and messages that could not be loaded.

**Comment by CanePlayz** [comment]
I mean it's really weird that Discord cannot load the message, so I think that's something they have to fix first.

**Comment by Tyrrrz** [comment]
Alternatively we can also change the text to say "Original message was deleted or could not be loaded" to cover both cases. Otherwise I'm just leaning towards leaving it as it is.

**Comment by CanePlayz** [comment]
Yeah, I think that's the best possible solution for now 👍
