### ISSUE TITLE
Option to rename downloaded media with date posted as preffix

### ISSUE THREAD

**Issue by HASJ** [Tyrrrz/DiscordChatExporter#646]
### Details

`filename.ext` would be renamed to `yyyy-MM-dd_hhmmss_filename.ext` (or whatever was the chosen date format) if the option was checked.

**Comment by Tyrrrz** [comment]
That wouldn't work with the reuse media option, that relies on the name to be deterministic. Also, you can just use the file dates for, well, dates, instead of putting it inside of the name.
