### ISSUE TITLE
Improve how quotes look in replies

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#647]
### Export format

HTML

### Details

How it's done in Discord:
![image](https://user-images.githubusercontent.com/81419612/125690970-9354d285-89f8-4b90-88d7-4d68be4f750d.png)

How it's currently done in the HTML file:
![image](https://user-images.githubusercontent.com/81419612/125691100-ab8e9f20-358e-4fe8-8934-0e05d8d10902.png)

**Comment by Tyrrrz** [comment]
This one is an interesting inconsistency, because I feel like Discord should actually be rendering the quotes there, instead of leaving the `>` character. I would argue having the quote visible makes more sense, although some visual improvements might be in order to make it look nicer. Thoughts?

**Comment by CanePlayz** [comment]
I think we can go for our own version here, because - as you said - it looks better and more consistent. Some visual improvement would of course be very appreciated. Speaking of that, it's not the most important, but the line going to the original message if you replied to something could also be a bit more like the original one in Discord, it that's possible.

**Comment by Tyrrrz** [comment]
Okay I'll change the issue then.

> Speaking of that, it's not the most important, but the line going to the original message if you replied to something could also be a bit more like the original one in Discord, it that's possible.

Yeah, feel free to open another issue for that (in case there isn't one already).

**Comment by Tyrrrz** [comment]
What would help make it look better by the way? Any suggestions?

**Comment by CanePlayz** [comment]
It's not really related to quotes in replies specifically, but I also think the icon for the quote itself looks different in Discord and the HTML file (I think they changed it at some point). Regarding quotes in replies, I think with the improved icon they would actually look fine already.

**Comment by Tyrrrz** [comment]
> Regarding quotes in replies, I think with the improved icon they would actually look fine already.

Closing this issue in favor of #654 because that covers it already
