### ISSUE TITLE
Document message filtering on wiki

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/DiscordChatExporter#651]
### Details

We've added message filters recently (thanks @96-LB). However, they are not correctly documented on the wiki. Because they are quite difficult to use with many nuances, it's pretty important to document it so that the users know how to use it.

Some examples of what is possible to do with filters now:

- Filter by user

```
from:Tyrrrz
```

- Filter by user (with discriminator)

```
from:Tyrrrz#1234
```

- Filter by message content (allowed values: `link`, `embed`, `file`, `video`, `image`, `sound`)

```
has:image
```

- Filter by mentioned user (same rules apply as with `from:` filter)

```
mentions:Tyrrrz#1234
```

- Filter by contained text (has word "hello" and word "world" somewhere in the message text):

```
hello world
```

- Filter by contained text (has the string "hello world" somewhere in the message text):

```
"hello world"
```

- Combine multiple filters ('and'):

```
from:Tyrrrz has:image
```

- Same thing but with an explicit operator:

```
from:Tyrrrz & has:image
```

- Combine multiple filters ('or'):

```
from:Tyrrrz | from:"96-LB"
```

- Combine multiple filters using groups:

```
(from:Tyrrrz | from:"96-LB") has:image
```

- Negate a filter:

```
-from:Tyrrrz | -has:image
```

- Negate a grouped filter:

```
-(from:Tyrrrz has:image)
```

- Escape special characters (`-` is escaped below so it's not parsed as negation operator):

```
from:96\-LB
```

**Comment by Tyrrrz** [comment]
Note: when using the CLI and the first filter is a negation filter (for example `-from:Tyrrrz`) then the user needs to quote the value and prepend it with a space so that the `-f` is not treated by the CLI as an input for the format option. In other words:

This breaks:

```
DiscordChatExporter.Cli export [...] --filter "-from:Tyrrrz"
```

This works (note the space):

```
DiscordChatExporter.Cli export [...] --filter " -from:Tyrrrz"
```

I don't think there's an easy way to fix it, so we should mention it in the docs as the recommended workaround. Otherwise, if the negation filter isn't the first filter in the string, then it also works completely fine.

Additionally, when using the CLI, it's recommended to use single quotes for contingent string of characters rather than double quotes (so it doesn't collide with the double quotes used in the terminal). E.g.:

This breaks:

```
DiscordChatExporter.Cli export [...] --filter "from:"Some name with spaces""
```

This works:

```
DiscordChatExporter.Cli export [...] --filter "from:'Some name with spaces'"
```

**Comment by Tyrrrz** [comment]
@Yudi do you have a suggestion where best to add this on the wiki? Should it go under "Using the GUI/CLI" section? I feel like it might be too big for that and might need a separate page of its own.

**Comment by Yudi** [comment]
I agree that a separate page is better. We can link it on the "Using the GUI/CLI" page.

**Comment by Tyrrrz** [comment]
Ok added to the wiki. It's a bit crude but it's a start 🙂
