### ISSUE TITLE
Support different formatting styles for timestamps in markdown

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#662]
### Export format

HTML

### Details

We've already talked about it here and there, but since the other issues including that topic have been closed, I wanted to open one specifically for this. Under "Timestamp Styles" on https://discord.com/developers/docs/reference, there is documentation of the different timestamp designs currently available to be used in Discord. As of now, we render every timestamp in the format which the user has set in the settings, but at some point we need to include the different ones, expect maybe the one with the relative time because that would change all the time.

**Comment by Tyrrrz** [comment]
For posterity sake:

![image](https://user-images.githubusercontent.com/1935960/127169379-99c13b90-3b62-4fee-af63-2122e6e193b5.png)

We can probably format the dates using short/long date/time formats that use current locale. And then use the format configured in settings for when a timestamp doesn't have the format provider.

**Comment by CanePlayz** [comment]
Yeah, that's probably the best solution to also respect the custom time format set by the user.

**Comment by Tyrrrz** [comment]
The parsing would need to be added here: https://github.com/Tyrrrz/DiscordChatExporter/blob/e00f126a5e39bcfed6f8fc405690d8b29b343676/DiscordChatExporter.Core/Markdown/Parsing/MarkdownParser.cs#L283-L301

We can extract Discord's formatting parameter and store it in the corresponding node. Then apply formatting in the visitors:

https://github.com/Tyrrrz/DiscordChatExporter/blob/e00f126a5e39bcfed6f8fc405690d8b29b343676/DiscordChatExporter.Core/Exporting/Writers/MarkdownVisitors/HtmlMarkdownVisitor.cs#L212-L232

https://github.com/Tyrrrz/DiscordChatExporter/blob/e00f126a5e39bcfed6f8fc405690d8b29b343676/DiscordChatExporter.Core/Exporting/Writers/MarkdownVisitors/PlainTextMarkdownVisitor.cs#L83-L94

**Comment by Tyrrrz** [comment]
Timestamp formatting in the client seems to be inconsistent with the API docs:

![image](https://user-images.githubusercontent.com/1935960/218315215-3fabe34c-a1ee-416c-bd22-04e95bbfcf0c.png)

I'm going to use the client as the source of truth instead. At least until #879.

**Comment by Tyrrrz** [comment]
Also, Discord seems to no longer render `Invalid date` on broken timestamps, but it's probably a bug on their end:

![image](https://user-images.githubusercontent.com/1935960/218315426-5fa393fd-fd98-4088-8368-c034643c04ef.png)

**Comment by CanePlayz** [comment]
> Timestamp formatting in the client seems to be inconsistent with the API docs:
> 
> ![image](https://user-images.githubusercontent.com/1935960/218315215-3fabe34c-a1ee-416c-bd22-04e95bbfcf0c.png)
> 
> I'm going to use the client as the source of truth instead. At least until #879.

I think it's consistent but the docs show the British version.

**Comment by Tyrrrz** [comment]
> > Timestamp formatting in the client seems to be inconsistent with the API docs:
> > ![image](https://user-images.githubusercontent.com/1935960/218315215-3fabe34c-a1ee-416c-bd22-04e95bbfcf0c.png)
> > I'm going to use the client as the source of truth instead. At least until #879.
> 
> I think it's consistent but the docs show the British version.

Ah, so it's not constant but also depends on the language setting in the client.

**Comment by CanePlayz** [comment]
> Ah, so it's not constant but also depends on the language setting in the client.
Unfortunately, yes. But it should get solved with #879 anyways.
