### ISSUE TITLE
Add the option to save messages in servers (or multiple) live as they're happening.

### ISSUE THREAD

**Issue by TheCamperGamer** [Tyrrrz/DiscordChatExporter#668]
### Details

The option to save all messages after a certain date (or just in general), and when they're all saved, continuing to save messages that are currently being sent. 

The only effective way I see this working is if you have the ability to save messages from multiple servers, in multiple different formats at the same time. 
Eg. You can save messages from multiple servers in the selected formats at the same time (by first setting the location of where each format and server should be stored).

Along with saving all formats, I suggest the ability to save with media (Eg. saving JSON, CSV, TXT, HTML, and HTML Media at the same time)

It'd also be cool if you could pause and resume whenever needed, and it will check for messages to save during the time it was paused.

**Comment by Tyrrrz** [comment]
It has already been suggested before, but live export is out of scope for the project.
Multiformat export is proposed here: #265
