### ISSUE TITLE
Add default file name if the given path is a directory

### ISSUE THREAD

**Issue by TVdata** [Tyrrrz/DiscordChatExporter#67]
Something like this in MainViewModel.cs
https://pastebin.com/3pihkrVZ

What this does is that when you give the program a directory with -o it doesn't throw an error but instead uses that directory with the default file name.

I had to make this modification because I wanted to use a script to automatically save many channels and it doesn't have access to any names.

**Comment by Tyrrrz** [comment]
As a workaround for now, you can also set the working directory of the executing process.
