### ISSUE TITLE
Allow the filter to also search on embed fields like the original Discord search behavior

### ISSUE THREAD

**Issue by Ricardonacif** [Tyrrrz/DiscordChatExporter#670]
### Details

On the original search bar on Discord, if you search for an string present inside a `embeds` field, it works. I tried the same on DiscordChatExporter but it does not work. Since we are trying to mimic the original filter Discord behavior (with keyworks and everything), I think we should also search on those fields.

**Comment by Tyrrrz** [comment]
Makes sense
