### ISSUE TITLE
Option to have shorter file names when exporting channels in the GUI

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#676]
### Flavor

GUI (Graphical User Interface)

### Details

If you export one or multiple channels at once in the GUI, currently they all get names including the server name, category name, channel name, and channel ID. I can see the advantage of that, however, I personally would prefer the files just to have the name of the channel so browsing the channels gets way easier. Since renaming all of them by hand can be quite much work, I would like to suggest an option in the GUI where you can decide if you want to use the current file naming system or a shorter one.

**Comment by 96-LB** [comment]
It's a bit of a hack, but you can actually use [filename templates](https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#generating-the-filename-and-output-directory-dynamically) in the GUI too as a temporary workaround. Just make a new folder like so:
![image](https://user-images.githubusercontent.com/21089343/128641938-cade4484-9962-41cc-bd29-00e4c32fbf55.png)
Selecting it when you export will give you the desired filenames as long as it ends in ".html".

Obviously, this is a pretty terrible UX, so we should definitely figure out a way to integrate the templates more nicely into GUI.

**Comment by CanePlayz** [comment]
Perfect, thanks for the tip
