### ISSUE TITLE
Markdown timestamps can overflow and cause crash

### ISSUE THREAD

**Issue by hlaaftana** [Tyrrrz/DiscordChatExporter#681]
### Version

ver 2.30.0

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

JSON, CSV

### Details

<t:20000000000000:d> shows "Invalid date" in discord, while it crashes exports.
![firefox_2021-08-11_00-24-26](https://user-images.githubusercontent.com/10591326/128937096-1be8451c-2c50-49b4-bb3a-dfcd79f39f16.png)
![dotnet_2021-08-11_00-21-12](https://user-images.githubusercontent.com/10591326/128937094-695c2ec2-9bce-4a9b-974d-58552972d4eb.png)

### Steps to reproduce

- Put <t:20000000000000:d> in a message
- Try to export

**Comment by Tyrrrz** [comment]
Interestingly, `<t:2000000000000000000>` does not show `Invalid date` but instead just renders `<t:2000000000000000000>` as is.
