### ISSUE TITLE
Hide URLs to embedded media if there is no other text

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#682]
### Export format

HTML

### Details

There are two ways to send embedded content on Discord. You can use a link to the content that goes like `cdn.discordapp.com` or one that goes like `media.discordapp.net`. While the first one is the one users get when they right-click on something and select copy link, media. is the proxy. 

So Discord hides the message content if it's just the link to the embedded content regardless of whether you use the first or the second option. However, DCE currently only hides the link if you use `cdn.discordapp.com`, as you can see here:

![image](https://user-images.githubusercontent.com/81419612/129446666-9a031e88-7455-4a63-a69d-4c722a47c6f0.png)

**Comment by 96-LB** [comment]
Note that image links from external sites (i.e., not `cdn.discordapp.com` or `media.discordapp.net`) are also hidden and displayed as if they were attachments.

**Comment by Tyrrrz** [comment]
Done in https://github.com/Tyrrrz/DiscordChatExporter/commit/edba9f36a71a309b75a30a840c1e69faa881ce26
