### ISSUE TITLE
Bring embed styling more in line with Discord

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#684]
### Details

Currently, the embed style in the HTML file has a couple of differences to the one used by Discord itself. Here's a comparison:

Discord embed:
![Screenshot 2021-08-15 134951](https://user-images.githubusercontent.com/81419612/129489142-d2083499-7d32-4caf-83a0-a4484931f2b0.jpg)
DCE embed:
![Screenshot 2021-08-15 134901](https://user-images.githubusercontent.com/81419612/129489146-7c7abb46-16d2-4671-b76f-b87f44be219d.jpg)

Here are some of the things I noticed:

- Dark/black areas are too bright in the HTML file
- The big embed field is too bright in general
- Discord seems to leave more space on the upper and lower end of the embed to the first/last text
- ~~Mentions of users and channels are not updated to the new style introduced by Discord as part of the rebrand~~ (moved to #703)
- The big embed field in Discord is only as wide as it needs to be, DCE applies a default width

There might be some things I missed (maybe with the font?), but for now, that's everything I noticed that needs to be improved somewhere down the road.

**Comment by matej118111** [comment]
No, nothing is perfect... can't you just deal with it?

**Comment by Tyrrrz** [comment]
Should be better now
