### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by Param-Pam-Pam** [Tyrrrz/DiscordChatExporter#69]
Hi, 

I just downloaded v2.51 from softpedia, extracted the zip, opened the .exe, and this shows up. Am I being a noob and not doing something properly, or is something wrong? I'm on Windows 7 32-bit. Let me know if you need more  info.
![capture](https://user-images.githubusercontent.com/41147101/42624549-4622cba6-85ce-11e8-89be-a0bacac63d01.PNG)

Thanks.

**Comment by Tyrrrz** [comment]
Hi. This looks weird.
Can you make a screenshot of the folder where you extracted all files?

**Comment by Tyrrrz** [comment]
What version of .net framework do you have?
Can you make sure you have .net 4.6.1 installed? https://www.microsoft.com/en-us/download/details.aspx?id=49981

**Comment by Param-Pam-Pam** [comment]
You're right, I had an earlier version. I updated it and everything is going well, it ran and exported successfully. Thanks

**Comment by Tyrrrz** [comment]
Awesome
