### ISSUE TITLE
Partition by message date

### ISSUE THREAD

**Issue by Mattlau04** [Tyrrrz/DiscordChatExporter#691]
### Details

Currently, you can partition by filesize or message number, but that's hard to browse, especially when you're looking for something from a specific date.
The ability to partition based on message date would be useful for this situation
3 partitioning options by date would be good: by day, month or year

**Comment by Tyrrrz** [comment]
@emillly-b
They mean being able to export all messages within a date range, but partition them by time intervals, for example one file for one day's worth of messages. So if you export a month of messages, you'll get 30 files.

**Comment by Tyrrrz** [comment]
No, but you can script it via a CLI for now

**Comment by Tyrrrz** [comment]
> > No, but you can script it via a CLI for now
> 
> Is there an existing solution for this? I'd like to know before spending a little time learning the cli and writing this script.

Not for your exact use case I think
