### ISSUE TITLE
Channel export in a server crashed twice

### ISSUE THREAD

**Issue by herbertstew** [Tyrrrz/DiscordChatExporter#692]
### Version

2.30

### Flavor

CLI (Command Line Interface)

### Details

I was exporting the entire server the first time and all the channels exported successfully except one channel and it printed this exact error log both times and it stopped at similar percentage https://pastebin.com/Naw7Dd0c . The second time i tried exporting only this channel with its ID but it failed like this.

### Steps to reproduce

First time when exporting entire server: 

`./dotnet /path/to/DiscordChatExporter.CLI/DiscordChatExporter.Cli.dll exportguild --guild <guild-id-here> -t <bot-token-here> -b --parallel 20 -o /path/to/backup-destination --media --reuse-media`

Second time when exporting the failed channel: 

`./dotnet /path/to/DiscordChatExporter.CLI/DiscordChatExporter.Cli.dll export -c <channel-id-here> -t <bot-token-here> -b -o /path/to/backup-destination --media --reuse-media`

Environment: Linux Mint 20.1 XFCE, .NET core runtime 3.1

**Comment by Tyrrrz** [comment]
Maybe eventually fixed with #521 🤔

**Comment by herbertstew** [comment]
i read your reply to #669 and the network issue thing happened to me too. it lagged at 66% for at least 10 minutes and the internet speed was slowly decreasing until nothing wanted to load in the browser. after it crashed the internet speed went back to normal.

**Comment by Tyrrrz** [comment]
Does it also look for you as if multiple channels are being exported at the same time regardless of the `--parallel` option?

**Comment by Tyrrrz** [comment]
Try the latest CI build and see if it works. You will need to install the latest .NET 6 runtime (if you're using GUI, it should install automatically).
https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/1441485193

If the issue persists, please re-open it.

**Comment by herbertstew** [comment]
> Try the latest CI build and see if it works. You will need to install the latest .NET 6 runtime (if you're using GUI, it should install automatically). https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/1441485193
> 
> If the issue persists, please re-open it.

Using the latest DCE CLI version and .NET 6 runtime it works perfectly. All channels exported successfully! Thank you for making this extremely useful program.
