### ISSUE TITLE
Improve the integration of tweets containing multiple images

### ISSUE THREAD

**Issue by Kwakoxium** [Tyrrrz/DiscordChatExporter#695]
### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

I don't know if it's possible, but it would be interesting to modify the integration of tweets that contain several images, more precisely the arrangement of these. They are placed one above the other and it is not always very practical to read, especially if there are several links.

The way it appears on Discord:
![Screenshot 2021-08-30 at 18-06-13 Serveur 1 - général 2](https://user-images.githubusercontent.com/87956094/131371937-0beb3ddc-193d-4759-8859-2fc5907e937f.png)

The way this appears in HTML format, it may be less convenient:
![Screenshot 2021-08-30 at 18-06-13 Serveur 1 - général](https://user-images.githubusercontent.com/87956094/131372156-766dc2bd-978a-499f-85e3-4d5eba4adfd1.png)

It's an idea, but it might be easier to put them together in pairs.

**Comment by Tyrrrz** [comment]
Interestingly, Discord API actually returns 4 different embeds in this case, instead of a single embed with 4 images (which is supposed to be supported by their protocol). This makes it more annoying to work around this issue.

**Comment by Tyrrrz** [comment]
So the reason Discord API splits these embeds in multiple parts is because Discord's protocol does not support embeds with multiple images. We'll have to figure out a way to deal with it.
