### ISSUE TITLE
Virus found in v2.30.1 (GUI)

### ISSUE THREAD

**Issue by Jay2k1** [Tyrrrz/DiscordChatExporter#696]
### Version

2.30.1

### Flavor

GUI (Graphical User Interface)

### Details

I downloaded the latest release GUI zip, unzipped it and tried running the .exe (which had a default icon). After clicking through the unsigned code warning, Windows told me it couldn't run the program because a virus was found and it removed the file. Subsequent tries to fully extract the zip file failed.
I even tried redownloading it in Chrome, but this time Chrome told me "Error - virus found":

![image](https://user-images.githubusercontent.com/2070503/131375231-ff3b27f1-c8e6-4b60-ac62-ca1ec34cb3d2.png)

Virustotal confirms that Microsoft classifies this as dangerous: https://www.virustotal.com/gui/file/b0b9a5452dc4f6af5ab83a6417717d72b5b1f7adbd5cf9874f4834a12518861a/detection

I then picked the previous release (2.30.0) and extracted it; this time, the exe had a blue custom icon and actually executes.

### Steps to reproduce

Download 2.30.1 on a windows computer with the stock antivirus (Windows Defender/Security Essentials) and try running it

**Comment by Kwakoxium** [comment]
This just happened to me launching it now and I also have Microsoft Defender. This is very surprising, because there was no problem a few hours ago.

**Comment by Tyrrrz** [comment]
Looks like Microsoft Defender updated their definitions overnight and is now tagging `DiscordChatExporter.exe` as a virus. You can proceed with "remove threat" but then you'll have to run DCE with command line (`dotnet DiscordChatExporter.dll`). Note that nothing changed within that file since the last version.

I've submitted a dispute request, we'll see how it goes.

**Comment by Tyrrrz** [comment]
![image](https://user-images.githubusercontent.com/1935960/131392300-6d1b4eef-d92d-4414-8659-6a4d5a8757ec.png)
