### ISSUE TITLE
Easier way of extracting DM channel ID

### ISSUE THREAD

**Issue by bholtdwyer** [Tyrrrz/DiscordChatExporter#705]
### Details

Hi! This is just a quick note saying that when I try following your directions at
https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs

to get a DM channel ID, I can't get one because no window.location.href appears under "console". However, in Discord you can just hit the three dots next to any message in the DM, hit "Copy Message Link," and then copy the first string of numbers, e.g. the link will be "https://discord.com/channels/@me/1897169870984709487/0985709387059874" and "1897169870984709487" is the channel ID. Just a suggestion for the documentation.

**Comment by Tyrrrz** [comment]
FYI, you can just edit the wiki page

**Comment by emillly-b** [comment]
Added in 7f27ad2

**Comment by Tyrrrz** [comment]
Thanks!
