### ISSUE TITLE
Breaks cursor after cancelling

### ISSUE THREAD

**Issue by 5HT2** [Tyrrrz/DiscordChatExporter#716]
### Version

v2.30.1

### Flavor

CLI (Command Line Interface)

### Details

I ran an exportguild command, and cancelled it partway through. My terminal's cursor (where I'm typing) is invisible, and it doesn't work until I restart my terminal

Tested across

- Konsole on an Arch system
- Konsole running ssh on a Ubuntu system

### Steps to reproduce

- Start an export
- Press Ctrl C to cancel the command

**Comment by 96-LB** [comment]
I remember running into this before while debugging other issues. I'm 99% sure it was caused by Spectre, so hopefully the update fixes it.

**Comment by Tyrrrz** [comment]
Actually I think the issue is not really on Spectre's side. I think I know how to fix it.

**Comment by Tyrrrz** [comment]
> Thanks!

You're welcome. You can use the CI build to try it out.
