### ISSUE TITLE
System.TypeLoadException: Could not resolve type with token 0100005e from typeref

### ISSUE THREAD

**Issue by Minabsapi** [Tyrrrz/DiscordChatExporter#718]
### Version

2.30.1

### Flavor

CLI (Command Line Interface)

### Details

I was trying to export my DMs using first the version 2.22.0 of this software, then the latest only for it to fail everytime with this traceback (note: this one is for the latest version, but the previous was similar):

```
System.TypeLoadException: Could not resolve type with token 0100005e from typeref (expected class 'System.Collections.Generic.IAsyncEnumerable`1' in assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) in /12b418a7818c4ca0893feeaaf67f1e7f:0
  at DiscordChatExporter.Cli.Commands.ExportDirectMessagesCommand.ExecuteAsync(CliFx.Infrastructure.IConsole console) in /ab65f7c1c0584277854b19fd2f3629d8:0
  at CliFx.CliApplication.RunAsync(CliFx.Schema.ApplicationSchema applicationSchema, CliFx.Input.CommandInput commandInput) in /36d7145dd82441589e85da3f8004d8fb:0
  at CliFx.CliApplication.RunAsync(System.Collections.Generic.IReadOnlyList`1[T] commandLineArguments, System.Collections.Generic.IReadOnlyDictionary`2[TKey,TValue] environmentVariables) in /36d7145dd82441589e85da3f8004d8fb:0
```

This seems to be a .NET Core related issue, but my searches yield nothing, so I'm asking here in hope I could have some light on what's happening.
I've installed all the dependencies for my GNU/Linux Ubuntu 20.04 machine [as described here](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-) the first time. I updated them in case it could be related, same result. Also same result after removing dotnet-sdk-5.0 after I skim-read this version causes problem (of course I'm having .NET Core 3.1 installed)
I am not so sure about it, but I kind of remember it used to work normally on this install. Regardless, I already used it on another GNU/Linux Ubuntu 20.04 install with all requirements and it all worked well, so there's no reason it won't here.

### Steps to reproduce

1. Try to export DMs with this command:
```
cd /usr/local/bin/DiscordChatExporter.CLI
./DiscordChatExporter.Cli.dll exportdm -t <token> --media
```
(Note that help dialogs and main entrypoint work without dropping errors. Only the export commands seem affected, although I didn't test all of them)

**Comment by Tyrrrz** [comment]
Seems right. I don't know what's wrong. 🤷🏻 
Maybe the installation got corrupted somehow.

**Comment by Minabsapi** [comment]
I did a fresh reinstall by removing + purging every dotnet related package (including packages-microsoft-prod), removing DiscordChatExporter just in case, cleaning apt's cache, reinstalling .NET SDK version 3.1 only and downloading then running DiscordChatExporter. Still the same error

**Comment by Minabsapi** [comment]
I just tried running an older version to test. Version 2.21.2 works and is currently exporting as I write this comment

**Comment by Tyrrrz** [comment]
> I just tried running an older version to test. Version 2.21.2 works and is currently exporting as I write this comment

Is that the latest version that still works? Or is there some newer version that also works?

**Comment by Minabsapi** [comment]
The 2.21.2 version works. The 2.22.0 doesn't, as well as the 2.31.0 (current latest), so I suppose any version in-between doesn't work as well

About this remark in my initial report:

> I am not so sure about it, but I kind of remember it used to work normally on this install. Regardless, I already used it on another GNU/Linux Ubuntu 20.04 install with all requirements and it all worked well, so there's no reason it won't here.

It was a little stupid. Last time I used this program on the other Ubuntu install the latest version at the time might have been version 2.21.2 or older. So it isn't relevant here, I'll remove it

**Comment by Tyrrrz** [comment]
Try the latest CI build and see if it works. You will need to install the latest .NET 6 runtime (if you're using GUI, it should install automatically).
https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/1441485193

If the issue persists, please re-open it.

**Comment by Minabsapi** [comment]
Tried some hours ago exporting DMs and a guild, everything works again
