### ISSUE TITLE
`error NETSDK1100: Windows is required to build Windows desktop applications.` running `dotnet build` on ubuntu

### ISSUE THREAD

**Issue by luphoria** [Tyrrrz/DiscordChatExporter#734]
### Version

092f0cade9040e0d49d613ce0a4564373ba802b6

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

I was following build instructions, installed dotnet 3.1 and 5.0, and tried to build from a clone of the repo with Ubuntu. 
Running `sudo dotnet build` still did not work, though. As shown:
```
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/usr/share/dotnet/sdk/3.1.414/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(59,5): error NETSDK1100: Windows is required to build Windows desktop applications. [/home/trent/DiscordChatExporter/DiscordChatExporter.Gui/DiscordChatExporter.Gui.csproj]

Build FAILED.

/usr/share/dotnet/sdk/3.1.414/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(59,5): error NETSDK1100: Windows is required to build Windows desktop applications. [/home/trent/DiscordChatExporter/DiscordChatExporter.Gui/DiscordChatExporter.Gui.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.30
```

### Steps to reproduce

- use Ubuntu
- `git clone https://github.com/Tyrrrz/DiscordChatExporter/`
- `wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb`
- `sudo dpkg -i packages-microsoft-prod.deb`
- `rm packages-microsoft-prod.deb`
- `sudo apt-get update`
- `sudo apt-get install -y apt-transport-https`
- `sudo apt-get update`
- `sudo apt-get install -y dotnet-sdk-5.0`
- `sudo apt-get install -y dotnet-sdk-3.1`
- `cd DiscordChatExporter`
- `sudo dotnet build`

**Comment by Tyrrrz** [comment]
You won't be able to build the GUI app on Linux as it's Windows-only. If you want to build the CLI, change into that directory and run `dotnet build` there instead.

**Comment by luphoria** [comment]
> You won't be able to build the GUI app on Linux as it's Windows-only. If you want to build the CLI, change into that directory and run `dotnet build` there instead.

Can this be added to the tutorial, though? There is no mention of a difference building either, and i even got the implication that it builds both..

**Comment by Tyrrrz** [comment]
> > You won't be able to build the GUI app on Linux as it's Windows-only. If you want to build the CLI, change into that directory and run `dotnet build` there instead.
> 
> Can this be added to the tutorial, though? There is no mention of a difference building either, and i even got the implication that it builds both..

Sure, please submit a PR

**Comment by luphoria** [comment]
Hello,
sorry for not getting back to this server. Does this repo have any major guidelines to contribution and/or formatting of code/readme?

**Comment by Tyrrrz** [comment]
> Hello, sorry for not getting back to this server. Does this repo have any major guidelines to contribution and/or formatting of code/readme?

Nothing specific, just try to follow the pre-existing format/style as much as it makes sense.
