### ISSUE TITLE
Allow appending to existing export

### ISSUE THREAD

**Issue by BLucky-gh** [Tyrrrz/DiscordChatExporter#735]
### Details

Right now if I want to update my exported chat I would neet to export all of it again from zero, and for large servers it would take a while, so how about a feature that stores a machine readable version of the export along with whatever format the user as (unless the user exported a machine readable format already), and just append the updates to the chats to the existing exports (and maybe also add an option to mark messages that have since been deleted as such maybe?)

A way to implement it would be binary searching until you reach the first new message and start exporting from there if that' possible? or maybe exporting from bottom to top (aka in reverse chronological order) and stopping when you reach a message that has already been exported and cached.

I know that there's the --reuse-media flag, but it only does it for media files, and I'm not even sure if it reuses media for subsequent exports, but text messages remain uncached and you still have to deal with the overhead of waiting for the API to give you all the messages one by one which is pretty small for every individual message but adds up when exporting very large servers with thousands of messages, and it could still be an issue on smaller servers but exporting on a slower network.

**Comment by Tyrrrz** [comment]
This is out of scope because the export formats are intentionally kept write-only.
See also #49 #295 #444 #485 #688

**Comment by Heath123** [comment]
> 
> 
> This is out of scope because the export formats are intentionally kept write-only. See also #49 #295 #444 #485 #688

You don't neccesarily need to parse all the data though, just the dates. Alternatively you could add a tiny bit of metadata witha  timestamp. Would a PR that does one of these be accepted?

**Comment by Heath123** [comment]
This is possible to do manually using the "after" option but a little bit annoying
