### ISSUE TITLE
Newlines in messages contaminate CSV data

### ISSUE THREAD

**Issue by a-random-lemurian** [Tyrrrz/DiscordChatExporter#736]
### Version

2.30.1

### Flavor

CLI (Command Line Interface)

### Export format

CSV

### Details

I have the contents of an entire Discord server (about 1 million messages), which I have inside of an SQLite database. I noticed while manually inspecting the .csv files that there were newlines in the messages which contaminated the AuthorID field with message content.

I like doing data science on Discord servers and this just annoys me, since that means the data is inaccurate. Please make CSV exports ignore newlines by default.

### Steps to reproduce

- Find any channel whose messages contain newlines
- Export as CSV
- Read the CSV, and there, annoying newlines

**Comment by Tyrrrz** [comment]
> I like doing data science on Discord servers and this just annoys me, since that means the data is inaccurate.

I don't understand this, how does it make the data inaccurate? If the messages contain new lines, but you remove them, then _that_ would make it inaccurate.

If you need to ignore newlines, then you can just filter them out during import in whatever script you are using. It doesn't make sense to mutate the original message content by default.

Also, CSV is a deprecated export format that is not recommended for use and isn't getting updates anymore. You should use JSON instead for automation scenarios.

**Comment by a-random-lemurian** [comment]
> > I like doing data science on Discord servers and this just annoys me, since that means the data is inaccurate.
> 
> I don't understand this, how does it make the data inaccurate? If the messages contain new lines, but you remove them, then _that_ would make it inaccurate.
> 
> If you need to ignore newlines, then you can just filter them out during import in whatever script you are using. It doesn't make sense to mutate the original message content by default.
> 
> Also, CSV is a deprecated export format that is not recommended for use and isn't getting updates anymore. You should use JSON instead for automation scenarios.

Time for me to bear the pain of handling 876MB-ish files...

**Comment by Tyrrrz** [comment]
> > > I like doing data science on Discord servers and this just annoys me, since that means the data is inaccurate.
> > 
> > 
> > I don't understand this, how does it make the data inaccurate? If the messages contain new lines, but you remove them, then _that_ would make it inaccurate.
> > If you need to ignore newlines, then you can just filter them out during import in whatever script you are using. It doesn't make sense to mutate the original message content by default.
> > Also, CSV is a deprecated export format that is not recommended for use and isn't getting updates anymore. You should use JSON instead for automation scenarios.
> 
> Time for me to bear the pain of handling 876MB-ish files...

You can parse & read JSON files in a streaming manner, so that you don't have to load the entire thing in memory.
