### ISSUE TITLE
When exporting a thread, its parent channel is shown as "category"

### ISSUE THREAD

**Issue by Zackaryia** [Tyrrrz/DiscordChatExporter#737]
### Version

2.30.1

### Flavor

CLI (Command Line Interface)

### Export format

JSON

### Details

When exporting a thread in the DCE CLI, the channel metadata is not set correctly. If the threads in a server are set as follows.
![image](https://user-images.githubusercontent.com/30780411/141695233-5890e060-e423-439e-bc78-c5de1ffa75a8.png)
Then you would expect exporting the thread `bar` to give the following Json export
![image](https://user-images.githubusercontent.com/30780411/141695633-a0bb1809-ea4b-4ae8-aec8-00100c53aaa7.png)
But it instead returns the following which is much more confusing and harder to understand
![image](https://user-images.githubusercontent.com/30780411/141695681-a01dfa72-6252-4d05-add7-95b7f2825ff7.png)

### Steps to reproduce

- Step 1
Copy the ID of a thread

- Step 2
Export that thread like a regular channel

**Comment by Zackaryia** [comment]
On second review this isnt *really* a bug but I dont know of a better way to report this.

**Comment by Tyrrrz** [comment]
Are you referring to the fact that the value of `category` is `foo` instead of `buzz`?

**Comment by Zackaryia** [comment]
Yes, it dosent really make sense.

**Comment by 96-LB** [comment]
Thread exporting isn't really supported yet (see #663), so whatever you see is a side effect from how channels are exported. This is happening because Discord's API decided to make a thread's "category" actually the channel which contains it, and DCE is just giving you exactly what Discord does.

**Comment by Tyrrrz** [comment]
> Yes, it dosent really make sense.

Does it even make sense for a thread to have a "category"? What should it resolve to, the parent channel's category? 🤔

**Comment by Zackaryia** [comment]
Yes that makes more intuitive sense to me than the channel being the category.

**Comment by Tyrrrz** [comment]
Should be a relatively easy change to have a switch on channel type for this purpose.

**Comment by Voxuel** [comment]
Hey, where can I find this in the sln and what do you  want changed?

**Comment by Tyrrrz** [comment]
Ideal solution: change the `Category` property from `string` to `Channel` and rename it to `Parent`. Then, depending on the kind of parent (i.e. category or channel) write either "Category" or "Parent" in the export.

**Comment by Voxuel** [comment]
Where do I find the `Category` property in the code? Sorry for asking but I'm fairly new to programming and I'm trying to learn by doing :)

**Comment by 96-LB** [comment]
Hi @Voxuel, thanks for looking into this issue! No need to apologize.

Within the code, every `Channel` object is given a `Category` property as shown here:

https://github.com/Tyrrrz/DiscordChatExporter/blob/6621c10ae06b3f0fbf41915f8a9d470a6cccd0fd/DiscordChatExporter.Core/Discord/Data/Channel.cs#L10-L17

Then, within the `JsonMessageWriter`, the `Category` property along with some others is used to write the channel's metadata at the beginning of the export:

https://github.com/Tyrrrz/DiscordChatExporter/blob/6621c10ae06b3f0fbf41915f8a9d470a6cccd0fd/DiscordChatExporter.Core/Exporting/Writers/JsonMessageWriter.cs#L227-L235

**Comment by Voxuel** [comment]
Oh Ok! But then, How do I change the Category property to `Channel` as in the example you sent the Category is an `ChannelCategory` object and not an `string`?

**Comment by 96-LB** [comment]
If I understood @Tyrrrz's suggestion correctly, we should update the JSON export to change how it handles exporting categories and make it write an object instead of a string with the category's name like it currently does. Might want to have him confirm that, though.

**Comment by Voxuel** [comment]
Is this done by changing the _writer.WriteString to like _writer.WriteChannel?

**Comment by Voxuel** [comment]
Saw now that that is not an command

**Comment by Tyrrrz** [comment]
I'm not entirely sure that I understand my own comment from November, but I think I was suggesting that for normal channels we would write `category`/`categoryId` in the output, while for threads we would write `parent`/`parentId` instead. To differentiate between the two, we would have to amend the current data model (in DCE itself, not in the export format) to keep track of the full parent channel information, and not just its title (i.e., the category as it is now).
The idea is that, even though Discord had the concept of parent channels for a long time, in DCE I chose to simplify things by simply having a string `category` field (assuming parent channels are always category channels). That made sense in the pre-thread era, but now the concept of a parent is relevant in DCE too.

**Comment by Tyrrrz** [comment]
I think the best solution is to just rename the `category` field to `parent`, but seeing as it's a breaking change and the project is in maintenance mode, I'm leaning more towards classifying it as a minor but acceptable bug and marking the issue out of scope.
