### ISSUE TITLE
Show threads in CLI

### ISSUE THREAD

**Issue by Zackaryia** [Tyrrrz/DiscordChatExporter#738]
### Flavor

CLI (Command Line Interface)

### Details

When running the channels command on a guild, making an option to also display all the threads in the guild would be cool. 

Currently in discord there is no way to list all threads in a server so adding this feature would make exporting threads 100x easier. Plus this would also allow for exporting all threads in a server much easier.

**Comment by Zackaryia** [comment]
It looks like there is an api for listing archived threads (`https://discord.com/api/v8/channels/{channel_id}/threads/archived/public`) but I believe active threads are handeled via `wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream` which is what im guessing is a websocket.

**Comment by Zackaryia** [comment]
It seams that you can also request active threads on the rest API at `https://discord.com/api/v8/channels/{Channel_ID}/threads/active` but this returns a error of 
> Only bots can use this endpoint

**Comment by Tyrrrz** [comment]
> It seams that you can also request active threads on the rest API at `https://discord.com/api/v8/channels/{Channel_ID}/threads/active` but this returns a error of
> 
> > Only bots can use this endpoint

Maybe this endpoint can be used for this?

https://discord.com/developers/docs/resources/guild#list-active-guild-threads

**Comment by ipkpjersi** [comment]
So I tested this out, and it doesn't appear to be working for me. 

I used the following syntax:

`dotnet DiscordChatExporter.Cli.dl' exportguild -g guildnumber -t token --include-threads true`

However, it says:

Unrecognized option(s):
--include-threads

DiscordChatExporter.Cli v2.39.1


I have the DiscordChatExporter.Cli release from here: https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/5045096816

Am I missing something, or doing something wrong?

**Comment by Tyrrrz** [comment]
@ipkpjersi that option is only available in the `guild` command at the moment

**Comment by ipkpjersi** [comment]
Oh, I see. Is exporting threads not supported currently? 

I tried `dotnet DiscordChatExporter.Cli.dll export -c threadchannelid -t token` but it says Failed to export 1 channel(s) and then it says: Channel is empty or contains no messages for the specified period.

**Comment by Tyrrrz** [comment]
> Oh, I see. Is exporting threads not supported currently?

Not in bulk, but your approach should work. It seems that the thread is empty, though.

**Comment by ipkpjersi** [comment]
Oh, I am more sleep deprived than I realized. I just realized that I wanted to dump posts from a forum, not a thread. I would guess that dumping posts/forums is not supported?

**Comment by Tyrrrz** [comment]
> Oh, I am more sleep deprived than I realized. I just realized that I wanted to dump posts from a forum, not a thread. I would guess that dumping posts/forums is not supported?

You probably will get forums threads if you run `channels` on the parent guild/server, but right now there isn't a more natural way to do that.
