### ISSUE TITLE
Inclusion of DCE into Chocolatey Package Manager

### ISSUE THREAD

**Issue by BrandonKMLee** [Tyrrrz/DiscordChatExporter#739]
### Flavor

GUI (Graphical User Interface)

### Details

Currently, the files are in a ZIP, instead of an installer. Chocolatey is a Windows Package Installer, and it would be useful to add DCE to it.
https://github.com/chocolatey-community/chocolatey-package-requests/issues/1095

**Comment by Tyrrrz** [comment]
I currently have no plans to include any "official" Chocolatey distribution but the community is welcome to make their own 3rd-party packages for it, just like the existing one on AUR: https://aur.archlinux.org/packages/discord-chat-exporter-cli
