### ISSUE TITLE
Can't unzip big files cuz of auto-renaming

### ISSUE THREAD

**Issue by tyrexforlife** [Tyrrrz/DiscordChatExporter#755]
### Details

I downloaded server where one guy uploads his files by zip chunks (part 1, part 2 and etc [.part019-2C105]), discord exporter is renaming while downloading by adding additional symbols in the end of names. I downloaded his archive with 700 connected zip chunks, it will take 4er to rename them manually, can you please add some feature in settings to not adding those symbols in name?

**Comment by Tyrrrz** [comment]
DiscordChatExporter does not add any additional symbols at the end of the name.
The file name template is: `<original filename> [part <N>].<original extension>`.

**Comment by tyrexforlife** [comment]
I wrote example above
part019-2C105      -    every archive have an unique number like this [-2C105] with ciphers and alphabets on the end, so unpacker cant do his thing

**Comment by Tyrrrz** [comment]
I understand what you mean now. The "download with media" option is solely for the purpose of creating self-contained exports. It's not meant as a way to download files of a server. URL hashes (the suffix in the filename) is an important part of that. If your intent is to download files of a server, there are probably better and more efficient tools to do that. This use case is out of scope for DiscordChatExporter though.

**Comment by tyrexforlife** [comment]
Understood, thx for answering and explanation! Im not english speaking guy so probably i explained it wrong, sorry. I'll try to search another program yeah, renaming all 700 parts is too long.
