### ISSUE TITLE
No token in local storage

### ISSUE THREAD

**Issue by LoliWizard** [Tyrrrz/DiscordChatExporter#76]
Discord changed the way they handle tokens is there any other method to get your discord token?

**Comment by Robin-M** [comment]
I'm having the same issue. After updating to a new version I noticed that the token was gone in the Discord developer console.

**Comment by Tyrrrz** [comment]
It looks like it's indeed gone. Gonna mark it as a bug because the steps to obtain user token are no longer valid.

Also, note that old user tokens still work so if you still have your token saved somewhere -- make sure you don't lose it until workaround is found.

**Comment by Robin-M** [comment]
Unfortunately I don't have my old token anymore. Even if I had, I have updated my password to see if the token returned, but it didn't.
Thank you for looking into it.

**Comment by Tyrrrz** [comment]
As a more technical work-around you can do the following:

1. Open developers console
2. Click *Network* tab
3. Go to any channel in any guild
4. There should be a new request made `messages?limit=50` or something similar, you may have to scroll to find it
5. Click it
6. On the right, make sure the *Headers* tab is open
7. Scroll down to *Request headers*
8. Find the *authorization* header and copy the value

**Comment by Robin-M** [comment]
Thank you, that works for me.

**Comment by faithsloan** [comment]
WOW! THANK YOU! Worked like a charm, Tyrrrz!

#QueenWiki

**Comment by yeahalti** [comment]
I can't find the _authorization_ header. Can anyone else find it?

**Comment by llamasking** [comment]
The workaround works for me.
Make sure to save your token.

**Comment by sorarocks531** [comment]
So.... I still can't find this authorization header.... In fact, I have no idea what you mean by "Go to any channel in any guild" And I don't even have a "Headers" Tab... Help please?

**Comment by llamasking** [comment]
![screenshot_20180812_080423](https://user-images.githubusercontent.com/21324788/44003408-13eb2088-9e07-11e8-9c3c-016d9876bbea.png)
@sorarocks531 
@yeahalti

**Comment by MaybeGoogle** [comment]
Note for blind people (I'm one of them): You don't have to use `messages?limit=50`. Any request to discord that would require you to be logged in should work. Most stuff towards the bottom without a file extension (`science`, `applications`, `library` are the additional ones I saw) will work. 

Also, random observation: In `science`, a section called "Request Payload" has a property `token` which, at least for me, is slightly shorter than and ends differently from the `authorization` entry above. I'm too lazy to test if this one works, but I'm guessing it does...

**Comment by Tyrrrz** [comment]
Yes, it doesn't have to be `messages?limit=50` but it's generally the easiest to consistently find since it shows up every time you change channels.

**Comment by yeahalti** [comment]
Yep, got it! Thank you so much.

**Comment by BrianPetkovsek** [comment]
Found a way of getting the token.

1.  Open developers console
2.  Click Console tab
3.  reload the window with `window.location.reload();`
4.  The token should reappear back on the Application tab

**Comment by Tyrrrz** [comment]
It would be nice if we could find perhaps an even easier solution, so that a non-technical person would be able to get token with minimal work, ultimately without having to go through Network tab at all.

**Comment by Soheab** [comment]
> 3\. window.location.reload();

GG!

**Comment by Soheab** [comment]
> Found a way of getting the token. (Only works on Discordapp)
> 
> 1. Open developers console
> 2. Click Console tab
> 3. reload the window with `window.location.reload();`
> 4. The token should reappear back on the Application tab

Great ty! that works!

**Comment by FOCI-DEV** [comment]
> The instruction notes have been updated in the app and in the wiki

To automate this: https://github.com/FOCI-DEV/Get-Discord-Token

**Comment by generic-github-user** [comment]
Can't you be banned for using your user token in an automated program?

**Comment by Soheab** [comment]
> Can't you be banned for using your user token in an automated program?

Yes it against discord’s T.O.S but people still do it xD

**Comment by ArnRdy** [comment]
Interestingly, the token is visible briefly in the Application tab as soon as you reload the page. This suggests they are removing it from localStorage as soon as the page loads and inserting it back when the page is about to close.

Now, to get the access token, one simple way is to **add a network profile in the networking tab and set download, upload speed to 0.01kb/s or some small value or set latency to really high value and reload the page**. The access token will be available for you to copy a little longer depending on your network settings.

**Comment by Tyrrrz** [comment]
This only seems to affect the web client right now. In my experience, you can still copy the value fast enough -- you just have to double click it and press Ctrl+C. It's fine if it still contains parentheses, they will get trimmed by DCE

**Comment by Goldfire345** [comment]
hey there im new here but I did want to add to this little discussion 

I actually did find a way to get it without using any kind of programming that anyone can do with some dexterity  but it was abit tedious to do. if you have any kind of screencap progam with a hotkey  make sure to extend the developer window to its full size atleast full enough so you can see every character in the token at once   then as you reload (youll probably need to do this more than once if you aren't used to how long it is)
the token will appear briefly then as it does 
quickly screen cap the whole window and bam. the tedious part is you have to type the token in manually and have to make sure every character is typed exactly as you see it but its something that pretty much anyone can do and it lets you save the token for when this happens in the future 


the other part that makes it tedious is the token only pops up (atleast for me once every time I start the app so if you aren't fast enough with the screncap you have to restart the discord app as in close it completely then re run it)

**Comment by Tetrahedon** [comment]
The "Authorization" entry with the Token can now be found under HEADER > ACK (on the left)  and then you will see the "authorization" entry on the right.

**Comment by leumasme** [comment]
> > The instruction notes have been updated in the app and in the wiki
> 
> To automate this: https://github.com/FOCI-DEV/Get-Discord-Token

consider using gist.github.com for single files @FOCI-DEV

**Comment by jaemin1508** [comment]
Open chrome developer tools and turn on device toolbar.
when site looks mobile, token will be saved in localstorage.

**Comment by leumasme** [comment]
Here's a little script that you can paste into your dev console to get the token:
```js
(webpackChunkdiscord_app.push([[''],{},e=>{m=[];for(let c in e.c)m.push(e.c[c])}]),m).find(m=>m?.exports?.default?.getToken!==void 0).exports.default.getToken()
```
Alternatively
- open the developer tools
- go to the network tab
- perform any action in discord that sends a request that needs your authentication (such as loading messages, sending a message, etc)
- click on the request that appeared (which will be called "messages" for example when sending a message
- switch to the header tab
- scroll down to request headers
- the value next to "Authorization" will be your discord token

**Comment by flashbackboi** [comment]
> As a more technical work-around you can do the following:
> 
> 1. Open developers console
> 2. Click _Network_ tab
> 3. Go to any channel in any guild
> 4. There should be a new request made `messages?limit=50` or something similar, you may have to scroll to find it
> 5. Click it
> 6. On the right, make sure the _Headers_ tab is open
> 7. Scroll down to _Request headers_
> 8. Find the _authorization_ header and copy the value

yea so i copy token it says invalid
helpppppp

**Comment by Ashio-Kun** [comment]
Hi, I was doing some research to find a way to get a token and I found this page. So I did what was said but I don't get the same token on web app as on desktop app, I notice the characters in the token change after the first dot. Does anyone know why ?

**Comment by Yudi** [comment]
> Hi, I was doing some research to find a way to get a token and I found this page. So I did what was said but I don't get the same token on web app as on desktop app, I notice the characters in the token change after the first dot. Does anyone know why ?

@Ashio-Kun the token format changed around the time Discord introduced the Devices tab. I suppose it allows differentiation between sessions and their independent termination.

**Comment by Toxicisity** [comment]
> > Can't you be banned for using your user token in an automated program?
> 
> Yes it against discord’s T.O.S but people still do it xD

funny thing about this, i have made a whole account and use it as a portable bot, it has AI intelligent and more
