### ISSUE TITLE
Option to group channels by category

### ISSUE THREAD

**Issue by Robin-M** [Tyrrrz/DiscordChatExporter#77]
In Discord, all channels are part of a category which can be collapsed. In the application UI for a given server all channels are ordered alphabetically. This is fine if you just need to export one channel, but if I want to export everything from a category in a server with more than 100 channels I have to scroll a lot.

Would it be possible to include an option to put all channels under their category just like in Discord?

**Comment by infominer33** [comment]
any chance to get this in Cli? 

not sure if I ever showed u what I'm creating: https://sourcecrypto.pub/discolog

and making another one for [decentralized identity](https://didecentral.com). 

Even if category info was listed in the CSV or simply the title of each file, it would be simple from there, for organization.

Thank you!

--
once these projects get off the ground, I'm sure there will be contributions and I'll be more than happy to share what I'm able. your work is greatly appreciated.

It would be really interesting to see all of the ways people are using this app!

**Comment by Tyrrrz** [comment]
Yeah, I'm planning to improve CLI in the future. Please create a separate issue meanwhile.
