### ISSUE TITLE
Option to anonymize users

### ISSUE THREAD

**Issue by benui-dev** [Tyrrrz/DiscordChatExporter#776]
### Details

It would be useful if the exporter allowed the option of replacing all usernames with anonymized alternatives. There could be a few options for this flag:

Usernames:
* Show display name
* Show username
* Show anonymized username (replace with random number, one for each user)
* Strip usernames entirely

**Comment by Tyrrrz** [comment]
This is out of scope. I recommend just doing a search & replace on the output file yourself.
