### ISSUE TITLE
Friend exporter

### ISSUE THREAD

**Issue by Chaython** [Tyrrrz/DiscordChatExporter#785]
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

TXT, JSON, CSV

### Details

How about a friend exporter[Export user id/current tag]?
Chat exporter seems to only view open DMs and doesn't open DMs from all friends.... 
Would like this function thanks.

**Comment by Tyrrrz** [comment]
1. Only chat exporting capabilities are in scope for the project (hence the "chat" in the name).
2. Discord doesn't provide a programmatic way of retrieving the list of user's friends, so even if we wanted to do it, we wouldn't be able to

**Comment by Chaython** [comment]
> 2. Discord doesn't provide a programmatic way of retrieving the list of user's friends, so even if we wanted to do it, we wouldn't be able to

Ya really just need to write an ahk script to scroll down the friends list and copy each user ID. Or can you think of a better way?

**Comment by Tyrrrz** [comment]
> > 2. Discord doesn't provide a programmatic way of retrieving the list of user's friends, so even if we wanted to do it, we wouldn't be able to
> 
> Ya really just need to write an ahk script to scroll down the friends list and copy each user ID. Or can you think of a better way?

Yeah that's probably the most efficient way to do it
