### ISSUE TITLE
Update token extraction guide to mention that you need to open Discord in a browser

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/DiscordChatExporter#790]
Recently, Discord app was updated to prevent `Ctrl+Shift+I` from being used to open dev tools. As far as I can tell, there are no accessible ways to open dev tools anymore in the standalone electron version of Discord.

We need to update the guide text to highlight that you need to open Discord in browser first. The rest of the steps should continue working.

1. https://github.com/Tyrrrz/DiscordChatExporter/blob/40d833cd576fb6e070c6878e1bc6bbddd54d8704/DiscordChatExporter.Cli/Commands/GuideCommand.cs#L18

2. https://github.com/Tyrrrz/DiscordChatExporter/blob/40d833cd576fb6e070c6878e1bc6bbddd54d8704/DiscordChatExporter.Gui/Views/RootView.xaml#L160

Side note: I wonder if there's a way to extract the token automatically (with user approval)? Read memory maybe?

**Comment by Tyrrrz** [comment]
Spawned from #787

**Comment by 96-LB** [comment]
> Side note: I wonder if there's a way to extract the token automatically (with user approval)? Read memory maybe?

I think the token is indeed stored somewhere—I believe that's the basis behind token loggers. Not sure if implementing one would be the greatest idea, though.

**Comment by RoadrunnerWMC** [comment]
Hi, I'd just like to point out that [the wiki](/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs) is still out of date. Thank you!

**Comment by RoadrunnerWMC** [comment]
Actually, I just found some additional pertinent information.

> As far as I can tell, there are no accessible ways to open dev tools anymore in the standalone electron version of Discord.

Turns out there actually is a way! [Explained by a Discord developer on Reddit:](https://www.reddit.com/r/discordapp/comments/sc61n3/cant_inspect_element_anymore/hu4fw5x/)

> Indeed this is correct. Because people keep getting socially engineered into opening the inspector and having their accounts compromised, we've disabled this functionality on Stable.
>
> However, I do think that being able to poke at how the app works is cool. So you have two options, you can still open the web inspector in the browser. Or you can turn it back \*on\* using by setting `"DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true` in `%appdata%/discord/settings.json`.
>
> I'll caveat this with an important disclaimer though:
> \- Don't paste things in the console that other people send you. Such things can compromise your account, and even your computer.
> \- Don't screenshare or send screenshots of the web inspector, especially the \*requests\* tab. Sensitive information such as your account credentials may be on screen and allow someone to compromise your account.

I just tested it (on Linux -- the equivalent path is `~/.config/discord/settings.json`), and it works for me.

I think this should be added to the guide (both copies) as a second option, since changing this setting would probably be much more convenient long-term for those who regularly use the standalone app.

**Comment by Yudi** [comment]
> Hi, I'd just like to point out that the wiki is still out of date. Thank you!

I'm on it

**Comment by Tyrrrz** [comment]
> Actually, I just found some additional pertinent information.
> 
> > As far as I can tell, there are no accessible ways to open dev tools anymore in the standalone electron version of Discord.
> 
> Turns out there actually is a way! [Explained by a Discord developer on Reddit:](https://www.reddit.com/r/discordapp/comments/sc61n3/cant_inspect_element_anymore/hu4fw5x/)
> 
> > Indeed this is correct. Because people keep getting socially engineered into opening the inspector and having their accounts compromised, we've disabled this functionality on Stable.
> > However, I do think that being able to poke at how the app works is cool. So you have two options, you can still open the web inspector in the browser. Or you can turn it back *on* using by setting `"DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true` in `%appdata%/discord/settings.json`.
> > I'll caveat this with an important disclaimer though:
> > - Don't paste things in the console that other people send you. Such things can compromise your account, and even your computer.
> > - Don't screenshare or send screenshots of the web inspector, especially the *requests* tab. Sensitive information such as your account credentials may be on screen and allow someone to compromise your account.
> 
> I just tested it (on Linux -- the equivalent path is `~/.config/discord/settings.json`), and it works for me.
> 
> I think this should be added to the guide (both copies) as a second option, since changing this setting would probably be much more convenient long-term for those who regularly use the standalone app.

I think using the browser app is still easier for majority of use cases. Plus you don't have to repeat these steps every time if you choose to save your token. If you want, you can add it to the wiki as an alternative, but I think we should keep the guide in the app to the simplest possible set of actions with the fewest points of failure. :)
