### ISSUE TITLE
Show threads in GUI

### ISSUE THREAD

**Issue by DrOctapus** [Tyrrrz/DiscordChatExporter#792]
### Flavor

GUI (Graphical User Interface)

### Details

I was using the GUI version because Im an amature and can work a lot quicker with it but noticed there is no way to export threads with it [i hope Im not missing something obvious] becuase GUI doesnt even show you threads in the channel list it provides for every server. I know through CLI you can use a thread Id to easily solve this but it would be ideal to be able to do it in both.

What I would suggest as a solution would be to add an option in the GUI to, instead of selecting a channel from the list provided, input a channel/thread Id. That way you wouldnt need to mess with the viewer at all to add the threads, considering how messy that would be with the active/innactive and public/private threads.

How Im imagining this solution would be to add a field in the top of the channel list in the GUI that says "Channel/thread id: ....  " and the user can use that instead of the channel slector.

**Comment by 96-LB** [comment]
Most of the discussion about implementing official support for threads is happening over at #663 if you'd like to take a look and contribute there.

**Comment by DrOctapus** [comment]
> Most of the discussion about implementing official support for threads is happening over at #663 if you'd like to take a look and contribute there.

Yes, I am aware but thank you for bringing this to my attention regardless. I thought it would make sense for me to make a different post because what Im suggesting is different in nature.

Its not about the HTML export integrating threads but more about finding the threads using the GUI version because as of right now as far as Ive come to understand, the GUI version does not showcase threads.

It would be difficult, I presume, to make it showcase the threads amongst the channels in the channel list, so that is why I think it would be a more simple and more elegant solution to simply include an id box in the GUI version, where you can input the id of the channel [or the thread] instead of selecting it from the channel list.

Sorry Im repeating myself a bit but Im trying to properly communicate my suggestion.

**Comment by 96-LB** [comment]
Yup, I understand your suggestion. There's discussion about how to provide access to the threads in the GUI version in the linked thread as well, but I see why you'd want to separate it here.

> It would be difficult, I presume, to make it showcase the threads amongst the channels in the channel list, so that is why I think it would be a more simple and more elegant solution to simply include an id box in the GUI version, where you can input the id of the channel [or the thread] instead of selecting it from the channel list.

I think one of the biggest advantages of the channel list is the ease with which multiple channels/threads can be selected, which becomes harder with a textbox (even if it supports inputting multiple IDs). A textbox is definitely a possible route, but personally I'd hope that we can implement the threads into the current channel list. Since there's a cap on the number of active threads, I imagine that we could at least find a way to display those.

**Comment by DrOctapus** [comment]
Ah, I see, I must have missed parts of 663 due to my haste while reading it.

> I think one of the biggest advantages of the channel list is the ease with which multiple channels/threads can be selected, which becomes harder with a textbox (even if it supports inputting multiple IDs).

I have to agree with you there. I just dont know how feasible such a feature would be, considering the complexity of the threads system if you take into account both the active and the archived ones. That would definitely be the ideal solution, but a texbox would also be perfectly adequate.

**Comment by Tyrrrz** [comment]
Closing in favor of #1119 which has a more well-defined scope and already overlaps with this issue.
