### ISSUE TITLE
Show individual channel progress in GUI

### ISSUE THREAD

**Issue by Miepee** [Tyrrrz/DiscordChatExporter#794]
### Flavor

GUI (Graphical User Interface)

### Details

Currently, when exporting multiple channels, the progress gets divided into `amount-of-channels` steps, which gets gets confusing if the channels are all of varying degrees of length. If I export 10 channels, but 9 channels only had one message sent in them and the 10th has 1B messages, it's gonna be stuck at 90% for a very long time, making it hard to tell if progress is being made.
From what I can tell, it seems that CLI tracks the progress of each channel individually, which would be nice to have for GUI as well.

**Comment by Tyrrrz** [comment]
I can't think of a nice way to implement this without incorporating some level of per-channel progress reporting, similar to how [YoutubeDownloader](https://github.com/Tyrrrz/YoutubeDownloader) reports progress for each downloaded video:

![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/1935960/32e5d359-7e3e-40d9-a477-890d19a7a989)

This requires quite a big rework on both the presentation layer and the data layer. While I recognize the merit of this feature request, I don't think it's worth the effort, considering the project is in maintenance mode right now.
