### ISSUE TITLE
Sort output of the downloaded media folder

### ISSUE THREAD

**Issue by Miepee** [Tyrrrz/DiscordChatExporter#795]
### Details

Currently, DiscordChatExport just dumps everything into the _files folder. This makes it very messy.
It would be nice if:
- the output would get seperated into several subfolders. Having folders like `Profile Pictures`, `Emojis`, `Audio`, `Images`, `Videos`, `Documents` and `Other` would make it much more sorted already.
- the downloaded media is sorted via appearance in chat (either via a number prefix that starts at 1 and keeps increasing, a date-prefix or somehow else). This would make it easier to figure out when certain attachments were posted.

**Comment by Tyrrrz** [comment]
The `_files` folder is an implementation detail, it's not meant for the user to look at. Its purpose is to provide the ability to make self-contained exports, where the media files are exported alongside text. As long as that media is loaded and rendered correctly in the export file, that feature is working as expected.

If you need to scrap files from Discord channels, I recommend looking at other software or building your own, as this is out of scope for this project.
