### ISSUE TITLE
Command `exportguild` should not allow the user to accidentally write all exports to the same file

### ISSUE THREAD

**Issue by p-i-** [Tyrrrz/DiscordChatExporter#799]
### Version

v2.32.0

### Flavor

CLI (Command Line Interface)

### Export format

JSON

### Details

```
dotnet DiscordChatExporter.Cli.dll  exportguild  -t $DISCORD_TOKEN  -g $DISCORD_GUILD_ID  -f json  -o out.json
```
I was expecting a single file, containing a JSON structure for the whole guild

Instead, it's overwriting the same file with every channel it scrapes.

This is because it's seeing `.json` and inferring a file.

Given that the output of `exportguild` is ALWAYS a folder, it should consider `-o foo.bar.quux` as a folder, regardless of whether it has dots in it.

In my own code I'll be using `-o foofolder/` with trailing `/` to make is_folder explicit.

### Steps to reproduce

Fail:
```
dotnet DiscordChatExporter.Cli.dll  exportguild  -t $DISCORD_TOKEN  -g $DISCORD_GUILD_ID  -f json  -o out.json
```

Win:
```
dotnet DiscordChatExporter.Cli.dll  exportguild  -t $DISCORD_TOKEN  -g $DISCORD_GUILD_ID  -f json  -o out.json/
```

**Comment by Tyrrrz** [comment]
Note: the output is not _always_ a folder. It can be a filename template, for example `%C.json`, where `%C` is replaced with channel name. See more here: https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#generating-the-filename-and-output-directory-dynamically

I think the command should fail if the user attempts to export 2 or more channels to what effectively resolves to the same file path (even after token replacements).
