### ISSUE TITLE
Crash when exporting big channels

### ISSUE THREAD

**Issue by Magnaboy** [Tyrrrz/DiscordChatExporter#8]
https://i.imgur.com/DdMX0Ax.png  

Crashed when trying to export a channel, is there a max size/message limit?

**Comment by Tyrrrz** [comment]
Maybe. Does it work for you on smaller channels?

**Comment by tyler361** [comment]
It crashes for me too, I think it's because the channel has too much messages.

**Comment by Tyrrrz** [comment]
Yeah it seems like HtmlAgilityPack is running out of memory when trying to create html tags once it goes over approximately 220k messages. Looks like storing the entire DOM in memory wasn't the best idea as it's also eating around 3gb of RAM as well. :p

**Comment by Tyrrrz** [comment]
Also it looks like HtmlAgilityPack is leaking memory.

**Comment by Magnaboy** [comment]
Perhaps you can cut it up into different pages every 10k messages or so.

**Comment by Tyrrrz** [comment]
It would be annoying to do with grouping and having to actually make a valid HTML output. I'll just rewrite the exporter so it doesn't allocate any memory. It will work on much larger channels and will not eat any memory on top of storing all messages (which is about 1mb per 1000 messages). That said, it will still probably crash on incredibly large channels (over ~3 million messages) but I feel like at that point rendering those HTML logs in browser will be a bigger problem.

**Comment by Tyrrrz** [comment]
Try the new release.
