### ISSUE TITLE
Ability to Multi-Select which Servers/DM's to Export via GUI

### ISSUE THREAD

**Issue by AppTester7** [Tyrrrz/DiscordChatExporter#80]
Having the ability to Multi-Select which Servers/DM's to Export via the GUI interface
would be of such a convienience.

App is fantastic - with so many servers and the number of DM's people have - a manual
one-by-one export backup can take literally hours to do
Because the list of Servers/DMs is already in the list, instead of having to manually click
on each one and export it - a way to select either individual ones or all of them for export
would be very much appreciated

Suggestions for methodology of Multiple Selections:

1. Tick mark next to Server/DM Name
2. Use of a controller key, like 'Shift' or 'CTRL' to highlight the Server/DM as one for export

This can be particularly useful for Server Admins that need to pull-data on an certain
individual that is in multiple servers (or server channels) for evidence or behaviour

After the export(s) the server admin can then review such logs - obviously having to manually export each individual Server/DM by hand takes a long time and takes away
a server admins time way from their normal duties

**Comment by Tyrrrz** [comment]
Related to #12
