### ISSUE TITLE
Include alt text for image attachments

### ISSUE THREAD

**Issue by Exabits1** [Tyrrrz/DiscordChatExporter#805]
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

HTML

### Details

A couple of months ago Discord introduced the feature for users to be able to add alt text to images.

It shouldn't be that difficult to integrate, as you can just use the alt tag attribute in HTML.

**Comment by Tyrrrz** [comment]
For attachments?

**Comment by Exabits1** [comment]
Yes, though only for image attachments.
