### ISSUE TITLE
Continue failed export

### ISSUE THREAD

**Issue by abb128** [Tyrrrz/DiscordChatExporter#818]
### Flavor

CLI (Command Line Interface)

### Export format

JSON

### Details

It can take several days to export a massive Discord server. During this time, if the power goes out city-wide in midst of a [Russian conflict](https://en.wikipedia.org/wiki/2021%E2%80%932022_Russo-Ukrainian_crisis), there doesn't appear to be any possibility of continuing the failed export.

Other than to manually go through each channel's JSON, find the last message ID that was downloaded, input that as the --after argument and download each channel again individually.

It would be useful if there was a way for the exporter to automatically recover from a failure and continue where it left off. Maybe it could be done by storing a temporary file in the same directory as the export folder, which would contain the last message IDs that were exported for every channel.

**Comment by Tyrrrz** [comment]
This is out of scope. I recommend using `--after` like you said.
