### ISSUE TITLE
Error pulling guilds and channels

### ISSUE THREAD

**Issue by foresta86** [Tyrrrz/DiscordChatExporter#823]
### Version

2.32.0

### Flavor

GUI (Graphical User Interface)

### Details

I pasted the token and when clicked the arrow this error appeared. Never happened before.
![Immagine 2022-02-26 202409](https://user-images.githubusercontent.com/25081296/155856419-6aac4b69-6ff1-4ae3-9eec-91a39fe22bd4.png)

### Steps to reproduce

- Step 1: Paste the token
- Step 2: Click the arrow

**Comment by MakotoAme** [comment]
This is not invalid. Maybe there is a change in the way tokens are formatted on some clients now. I'm getting the same error, copying the token exactly as it is.

The token string is 132 characters in length and reported as invalid because of the presence of a `/` in the token string.
