### ISSUE TITLE
Missing a significant amount of messages from exportguild

### ISSUE THREAD

**Issue by NeonWizard** [Tyrrrz/DiscordChatExporter#824]
### Version

2.32

### Flavor

CLI (Command Line Interface)

### Export format

TXT, JSON

### Details

I'm using the exportguild command to export all messages from a specific user in a guild. The command completes successfully, but the output is missing a significant amount of messages. I've ran the command many times, and tried outputting as PlainText and Json, and also tried exporting all messages without filtering by user. Every time a significant amount of messages are missing. There doesn't seem to be any pattern other than most of the missing messages being more recent ones (within the last couple months).

Using export for just a single channel works fine, and I haven't noticed any missing messages.

I'm running the CLI version on MacOS Catalina.

### Steps to reproduce

I ran the following command:
```bash
dotnet DiscordChatExporter.Cli.dll exportguild -t TOKEN -g GUILD_ID -o output.json -f Json --filter "from:User#0001"
```

Then I searched the output file for random messages from the discord server, and noticed many were missing.

**Comment by nightpool** [comment]
See https://github.com/Tyrrrz/DiscordChatExporter/issues/799. It seems like `-o` should refer to a *folder*, not a `.json` file.

**Comment by Tyrrrz** [comment]
It can also be a filename if you're using template tokens, but if it's a static name then every channel is exported into the same file, overwriting it.

**Comment by Tyrrrz** [comment]
Closing in favor of #799
