### ISSUE TITLE
Wrong embedded file paths using before date and time

### ISSUE THREAD

**Issue by Comahar** [Tyrrrz/DiscordChatExporter#827]
### Version

3.33.2

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

HTML

### Details

Exporting with date and time set, as well as download media selected causes resources to not load. 
```
The path embedded in the HTML is in the form of (with encoding removed)
Direct Messages - Private - name [id] (before 2022-04-07).html_Files/filename.png
it should be
Direct Messages - Private - name [id] (before 2022-04-07 3.00 PM).html_Files/filename.png

or the foldername can be changed from
Direct Messages - Private - name [id] (before 2022-04-07 3.00 PM).html_Files
to
Direct Messages - Private - name [id] (before 2022-04-07).html_Files
```

### Steps to reproduce

Export as HTML with download media ticked, only before date and time set

**Comment by Tyrrrz** [comment]
Can't reproduce, the time portion is not present in the path. It's just `(before 2022-04-07)`.
