### ISSUE TITLE
Filter to conversation between two people 

### ISSUE THREAD

**Issue by Wolfciku** [Tyrrrz/DiscordChatExporter#829]
### Details

I don't know if I couldn't find it. I tried all the codes for 3 hours. Could you please tell me how to filter conversations between two people. How do I filter a conversation between two people in public chat..hope it was explanatory.

**Comment by 96-LB** [comment]
`from:person1 | from:person2` will filter out only messages sent by either "person1" or "person2". You may need to use quotes around the names if they contain spaces or some special characters.

**Comment by Wolfciku** [comment]
> `from:person1 | from:person2`yalnızca "kişi1" veya "kişi2" tarafından gönderilen mesajları filtreler. Boşluk veya bazı özel karakterler içeriyorsa, adların etrafında tırnak işaretleri kullanmanız gerekebilir.

I just want the conversation between person 1 and person 2. 3 daily transcripts of person 1 and person 2. With no one else. can i do this? thank you

**Comment by 96-LB** [comment]
> I just want the conversation between person 1 and person 2. 3 daily transcripts of person 1 and person 2. With no one else. can i do this? thank you

Yes, you can do it with the filter I gave you in the previous message. Check [here](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Message-filters) for more information.

**Comment by Wolfciku** [comment]
> > Ben sadece 1. kişi ile 2. kişi arasındaki konuşmayı istiyorum 1. kişi ile 2. kişinin günlük 3 transkriptini. Başka hiç kimse olmadan. bunu yapabilir miyim? teşekkür ederim
> 
> Evet bir önceki mesajda verdiğim filtre ile yapabilirsiniz. Daha fazla bilgi için [burayı](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Message-filters) kontrol edin .

I tried what you said many times. on the list: the writings of person1 and another speaker. person2 and another speaker are coming out.And conversations between person 1 and 2 with someone. I've looked everywhere man :(

**Comment by Wolfciku** [comment]
> > Ben sadece 1. kişi ile 2. kişiyle iletişim kurmak 1. kişi ile 2. kişiyle iletişim kurmak. Hiç kimse olmadan. bunu yapabilirim? teşekkür ederim
> 
> Evet bir mesajda verdiğim filtre ile yapabilirsiniz. Daha fazla bilgi için [burayı](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Message-filters) kontrol edin.

from:xxxxxx#xxxx | from:xxxxxx#xxxx  Is this true? Person other speakers should not come out 🤗

**Comment by 96-LB** [comment]
If two people have the same username, you should use the discriminator (the "#1234" part) to pick which one, yes. If it is still not working, can you show the exact command/filter you are using?

**Comment by Wolfciku** [comment]
> İki kişi aynı kullanıcı adına sahipse, hangisini seçmek için ayrımcıyı ("#1234" kısmı) kullanmalısınız, evet. Hala çalışmıyorsa, kullandığınız tam komutu/filtreyi gösterebilir misiniz?

I don't know if you understand me. What I want is a conversation between two people. I don't want 3-4-5-6 or anyone else. only conversations of persons 1 and 2. The code I use: 
![Uploading IMG_20220411_080342.jpg…]()

**Comment by Wolfciku** [comment]
![IMG_20220411_080252](https://user-images.githubusercontent.com/103402154/162668377-44f9240d-b275-4adb-8433-9bf7fb719108.jpg)

**Comment by Wolfciku** [comment]
![Uploading IMG_20220411_075934.jpg…]()

**Comment by Wolfciku** [comment]
![Uploading IMG_20220411_075700.jpg…]()

**Comment by Wolfciku** [comment]
from:shjahsk#8788 | mentions:jehsjsj#7782  it is true?

**Comment by 96-LB** [comment]
I do understand what you're asking. I can only see the second image you posted (the other links are not working), but `from:bonibon#4559 | from:cgrsw#9680` looks correct to me. Are you sure the export is showing other users?

> from:shjahsk#8788 | mentions:jehsjsj#7782 it is true?
This one is not correct. They should both be "from".

**Comment by Tyrrrz** [comment]
What do you mean by conversion between two people? The filter above will get you all messages sent by either of the two people, but they may not be addressing each other. Do you mean only messages where one replies to another or something? If so, then that's not possible.
