### ISSUE TITLE
Mentions appear as @unknown when exporting (inside embeds)

### ISSUE THREAD

**Issue by dan771** [Tyrrrz/DiscordChatExporter#830]
### Version

2.33.2

### Flavor

CLI (Command Line Interface)

### Export format

TXT

### Details

I exported to .TXT with plain text and all the mentions just appear as @unknown

### Steps to reproduce

Export message with a mention inside to plain text

**Comment by Tyrrrz** [comment]
Did you use date ranges?

**Comment by dan771** [comment]
@Tyrrrz The exact way i export is by using python: `os.system(f'cmd /c "dotnet DicordChatExporter.CLI\\DiscordChatExporter.Cli.dll export -t "{token}" -c 939905115505180682 -o Chat.txt -f PlainText"')`

**Comment by dan771** [comment]
@Tyrrrz I forgot to mention they're carl bot messages so they look like this (are they called embeds) 
![image](https://user-images.githubusercontent.com/49430372/162744089-0d4437ba-6736-44bb-9d4a-fe56362c9b75.png)

**Comment by dan771** [comment]
oh that was quite a while ago
