### ISSUE TITLE
Getting authentication token is invalid for a fresh token (using the latest version)

### ISSUE THREAD

**Issue by pawann-2000** [Tyrrrz/DiscordChatExporter#835]
### Version

2.34.0

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

##Both CLI and GUI are giving out the same error while trying to export the chats,

.NET Runtime 6.0 is installed before running as prompted

- GUI
![image](https://user-images.githubusercontent.com/59572141/164885904-3053278d-2447-4f43-b88a-1a0f36b1bf34.png)

- CLI
![image](https://user-images.githubusercontent.com/59572141/164885913-b0ac636c-ce16-4355-ad49-3d45f3ca2b35.png)

### Steps to reproduce

- Chat Exporter opened
- token copied using the dev tools from discord
- pasted in the Chat exporter (both CLI and GUI)
- entered the command: dotnet .\DiscordChatExporter.Cli.dll exportall -t token
- clicked the right pointed arrow on GUI
- error comes up the same both in CLI and GUI

**Comment by Tyrrrz** [comment]
Is this something that only started recently or have you not been able to use this before either?
You can try getting the token using [this method](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Troubleshooting#i-cant-findcopy-my-token) instead.

**Comment by h5isablunder** [comment]
Hello, also having this problem, tried changing my token but that didn't fix anything. Also tried using the different method to get token but wasn't able to find "messages?limit=50".

**Comment by DarkDullahan** [comment]
This is an issue I'm having as well. It only started after recent update.

**Comment by Tyrrrz** [comment]
> This is an issue I'm having as well. It only started after recent update.

Does the linked method above work?

**Comment by JustCallMeSimon26** [comment]
Hi just here to confirm that the linked Method worked for me (I had the same Problem)

**Comment by DarkDullahan** [comment]
After retrying using above linked method, yes. It resolves the issue.

**Comment by Tyrrrz** [comment]
Sounds like we need to update the token retrieval guide
