### ISSUE TITLE
Render embeds in PlainText

### ISSUE THREAD

**Issue by my32130** [Tyrrrz/DiscordChatExporter#84]
Whenever I'm trying to archive my log channels for later use in plain text. It cannot grab the embeds for plain text.

I need my embeds to be in plain text so I can be willing to parse them easily.

**Comment by Tyrrrz** [comment]
Hey, yes, this is correct.
Do you have a suggestion regarding how to display embeds in plain text?

**Comment by Tyrrrz** [comment]
Marking as "wontfix" because I don't think embeds can be displayed nicely in PlainText anyway.
