### ISSUE TITLE
Add the option to filter messages (with images, with downloads, by contents, by user, edited) in the exported HTML file

### ISSUE THREAD

**Issue by vielavlrs** [Tyrrrz/DiscordChatExporter#840]
### Details

Discord History Tracker's exported HTML contains these filter options and it is very useful for users. Users can also jump to the message from the filter results.

**Comment by 96-LB** [comment]
Most of these are already implemented: https://github.com/Tyrrrz/DiscordChatExporter/wiki/Message-filters

**Comment by vielavlrs** [comment]
> Most of these are already implemented: https://github.com/Tyrrrz/DiscordChatExporter/wiki/Message-filters

Yes but that implemented message filter only applies to export settings ie
![as](https://user-images.githubusercontent.com/93360948/166057283-9005067b-cfb5-4271-9a42-bbf84a5f612f.png)
 what to include or not. This suggestion is on the exported HTML file. Expected implementation is similar to that of Discord History Tracker.

**Comment by Tyrrrz** [comment]
I prefer the export files being dumb, that way the core logic is concentrated in the exporting phase, which also allows us to reuse more features between different export formats. So I would say this is out of scope -- the recommended approach is just to filter during export (and possibly make multiple exports).
