### ISSUE TITLE
Option to export list of server

### ISSUE THREAD

**Issue by nalllen** [Tyrrrz/DiscordChatExporter#847]
### Details

pretty much what the title say, just a basic option to export list of all servers that you are in.

Example of a txt export

[Username] Server list:
Minecraft
Rainbow 6
RandomServer
RandomServer
etc

**Comment by Tyrrrz** [comment]
In CLI you can use the `guild` command and pipe it to a file, e.g. `discordchatexporter guild -g 1234 > output.txt`

**Comment by Tyrrrz** [comment]
> ~In CLI you can use the `guild` command and pipe it to a file, e.g. `discordchatexporter guild -g 1234 > output.txt`~ Nevermind, that would export the list of channels in a guild.

Nevermind again, the command is `guilds` and it does exactly what you need – outputs all servers your account has access to.

You can pipe the output to a file via:

```
dotnet DiscordChatExporter.Cli.dll guilds -t TOKEN > guilds.txt
```

Everything else is out of scope.
