### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing

### ISSUE THREAD

**Issue by x3221** [Tyrrrz/DiscordChatExporter#849]
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

I've been trying to make a backup of a quite large server. After about a day, it always seems to run into the following error.

`System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.`

Being able to set the number of retries may be able to help in this issue.

**Comment by Tyrrrz** [comment]
What version are you using?

**Comment by x3221** [comment]
> What version are you using?

2.34 with .NET 6.0

**Comment by turtletowerz** [comment]
I was running into a similar issue earlier this week with the same version, and now i'm receiving
`Failed to perform an HTTP request.` with an error message `StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent`. This times out the CLI before any message is exported, but I'm not sure if this is a Discord API issue or a chat-exporter issue.

**Comment by Tyrrrz** [comment]
`Internal Server Error` signifies a server-side issue which means Discord API might be having issues

**Comment by x3221** [comment]
Which is why I was asking for a potential retry arg or infinite retry flag.

**Comment by Tyrrrz** [comment]
I introduced some additional retry policies in the latest release, see if it helps
