### ISSUE TITLE
Option to disable automatic opening of output file

### ISSUE THREAD

**Issue by TheTerrorByte** [Tyrrrz/DiscordChatExporter#85]
I've had this problem when exporting large chat logs with >10,000 messages in HTML format. The program will automatically open the file by default, and if the generated file is large enough, it would lock up the browser, or whatever program it decides to open. This makes it impractical to export large logs in HTML format, because as it stands right now, there is no way to prevent your browser from crashing after generating a large enough file, even on high end PCs.

A simple setting would completely resolve this issue, by not attempting to open the file immediately after generation, thus making the program practical for exporting huge amounts of messages.

Additionally, automatically having files open when done is just annoying.

**Comment by Tyrrrz** [comment]
Thanks for reporting. I can see this being a problem.
