### ISSUE TITLE
Directory sorting and file naming

### ISSUE THREAD

**Issue by x3221** [Tyrrrz/DiscordChatExporter#850]
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

Would be great if the first file could be named [part 1] and if the files pertaining to a certain channel could be moved into a folder. 
I was trying to make a backup of a server and ended up with tens of thousands of pdf in the root directory. It makes navigating quite difficult.

**Comment by Tyrrrz** [comment]
There is no way to have it named `part 1` because the number of messages or the total export file size is not known ahead of time.
