### ISSUE TITLE
Docker DCE CLI should not run as root by default on Linux machines

### ISSUE THREAD

**Issue by alxpettit** [Tyrrrz/DiscordChatExporter#851]
### Version

6621c10ae06b3f0fbf41915f8a9d470a6cccd0fd

### Flavor

CLI (Command Line Interface)

### Details

When running CLI via Docker, per wiki instructions, DCE runs as root. This is true as of both the `stable` build, and the latest `Dockerfile` available at HEAD. (6621c10ae06b3f0fbf41915f8a9d470a6cccd0fd as of this writing)

This seems like an unnecessary security compromise, and should be fixed to at least run as user 1000.

### Steps to reproduce

1.

```
docker run --volume /app/out:"$HOME/Discord"  tyrrrz/discordchatexporter export -c [is secret] -t [is also secret]
```

2.
```
sudo htop
```

3.

*Watch in awe as your security model is disregarded.*

**Comment by Tyrrrz** [comment]
Related to #401?
Also, welcome to PRs providing a fix.
