### ISSUE TITLE
JSON format does not format dates

### ISSUE THREAD

**Issue by Noorquacker** [Tyrrrz/DiscordChatExporter#859]
### Version

2.34.0

### Flavor

CLI (Command Line Interface)

### Export format

JSON

### Details

When exporting with the JSON format with `--dateformat unixms`, the date format is still in ISO8601 timestamps. Normally, this isn't an issue, but since python's datetime library refuses to parse them, I figured I might open an issue since unixms is broken anyways.
I forked the project and added a crappy solution in [this commit](https://github.com/Noorquacker/DiscordChatExporter/commit/ca53608e34440dda0b7259ca82123198828d0456), it solved the issue even though now unixms is encoded as a string, but it still works for my use case.
I was planning on opening a PR for this until I read that I should open an issue first to discuss other options. I _could_ clean up my code and write the timestamps as numbers when selecting unix or unixms, but I barely know C# as is, and I'm surprised this works on Linux as is.

### Steps to reproduce

- Export with `-f Json --dateformat unixms`
- Open your json
- Observe as the timestamps are written as `"2022-06-03T14:00:46.652+00:00"`

**Comment by Tyrrrz** [comment]
Yeah, the dates are formatted according to the standard-ish JSON date format, which is what JavaScript outputs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON

I don't think date format should apply on JSON because of this, even though it's confusing.

**Comment by Noorquacker** [comment]
The issue for me is that not everything uses the JSON date format. JSON is the most flexible and compatible data format, making it my first choice, and so is unix time stamps. I do get the reason for wanting to use JSON date formats, but it also breaks compatibility as not all JSON readers support reading JSON datetime. Sure, it's their fault, but it hurts compatibility ever so slightly, which is the goal with exporting as JSON

**Comment by Tyrrrz** [comment]
Yeah, it is weird that some JSON readers don't support it, given how ubiquitous it is. Maybe something like this can help?
https://stackoverflow.com/a/10805633/2205454

**Comment by Noorquacker** [comment]
Sorry about the late comment!
I was initially using strptime and kept erroring on certain dates, but now I've finally gotten it work with `dateutil.parser.parse`. I'll close this, but I do also see that when requesting data from Instagram, they give unix ms timestamps by default when you request JSON format.
It'd be a nice feature to have, but I get it'd be a little contradictory. Maybe I was just confused because this is my first time actually encountering proper JSON dates in the wild, and finding out Python needs 3 libraries to make sense of it.
