### ISSUE TITLE
Add message link in HTML export

### ISSUE THREAD

**Issue by binwiederhier** [Tyrrrz/DiscordChatExporter#863]
### Flavor

CLI (Command Line Interface)

### Export format

HTML

### Details

Love this project. Thank you. I'm trinking of adding it to a nightly CI pipeline and export my project Discord channel nightly and upload it to a GitHub page.

I'd love to be able to click on a message to directly jump to it, basically this:

![image](https://user-images.githubusercontent.com/664597/172679677-c9c918d8-412b-4e12-9c8f-8b6d63a630f4.png)

``` html
<a href="#chatlog__message-container-984142428846035014"><span class="chatlog__timestamp">08-Jun-22 05:10 PM</span></a>
```

I'm happy to add it in code if you like. Should be trivial, but only if you think it's a good idea. What do you think?

**Comment by Tyrrrz** [comment]
Sounds reasonable I think

**Comment by binwiederhier** [comment]
See https://github.com/Tyrrrz/DiscordChatExporter/pull/864.
