### ISSUE TITLE
.csv export cram in 2.6.0.0

### ISSUE THREAD

**Issue by Eclipse2025** [Tyrrrz/DiscordChatExporter#87]
noticed when exporting .csv file, the text dates and everything tends to cram and displace. the v2.4.1.0 came out perfectly, and if you could fix the little bug or typo causing it to cram that would be great. images for each version are below.
V2.4.1.0
![v2 4 1 0](https://user-images.githubusercontent.com/42637379/44514457-230f2f80-a6fb-11e8-84b3-c6e51654c6fa.png)
V2.6.0.0
![v2 6 0 0](https://user-images.githubusercontent.com/42637379/44514468-27d3e380-a6fb-11e8-8ccd-9796cb9e6755.png)

**Comment by mosguinz** [comment]
The app now uses semicolons as delimiters for .csv files. You need to import the .csv file into Excel and change the delimiter (as the default is comma).

Under the _Data_ tab, select _From Text/CSV_.
![image](https://user-images.githubusercontent.com/20041393/44785892-8ced7480-abe6-11e8-8af5-7b7124ee7eed.png)

Select the .csv file and set the delimiter as semicolon.
![image](https://user-images.githubusercontent.com/20041393/44785781-2bc5a100-abe6-11e8-80e0-65dee8f5f806.png)

**Comment by Eclipse2025** [comment]
awesome, thanks. though i can assume this has to be done each time... it sucks but at least i dont have to sit in 2.4 anymore.

**Comment by mosguinz** [comment]
> though i can assume this has to be done each time...
Yes. Or you could change the default delimiter to be semicolon for your computer, but keep in mind that most .csv files (that I've seen — at least) uses commas as delimiter.

To change the default delimiter, open Run (`WinKey` + `R`) and type `intl.cpl`.
![image](https://user-images.githubusercontent.com/20041393/44828481-2dd24300-ac6c-11e8-9517-86a64c8020c1.png)

Under the _Formats_ tab, click on _Additional Settings..._.
![image](https://user-images.githubusercontent.com/20041393/44828527-6a05a380-ac6c-11e8-9b1f-072b443304f4.png)

Type `;` for the _List separator_ and click _OK_ to save changes.
![image](https://user-images.githubusercontent.com/20041393/44828559-9b7e6f00-ac6c-11e8-9d6b-88275683c1ee.png)

**Comment by Tyrrrz** [comment]
Sorry for breaking reverse compatibility. It appears that the column delimiter is locale specific so users from different parts of the world may be getting similar issue.
