### ISSUE TITLE
Timezone indication and default date format

### ISSUE THREAD

**Issue by zabszk** [Tyrrrz/DiscordChatExporter#870]
### Details

Yes, I'm aware of the fact that you can customize the time format, however I would like to suggest two changes related to timestamps:

1. The date and time format in the Internet and international usage **has been standarized**. We have documents such as ISO 8601 and RFC 3339, but for some reason the default time format is completely different. The default format should be either **user's local date and time format** (C# provides features to read OS regional settings, including date and time format) or **the international format** (eg. `yyyy-mm-dd HH:mm`). Currently DCE for some reason ignores regional settings, ignores ISO standards, ignores RFCs and just uses custom format. That's why operating systems have regional settings (and C# has API for it), that's why there are standards - to use them, not to ignore them.

2. Timezone should be indicated in the export. I know that you add `K` to the date and time format to add the timezone to every timestamp, but in my opinion adding timezone to every single timestamp is not necessary and may negatively affect the readability. In my opinion timezone should be indicated in the preamble (where DCE indicates channel name, After/Before fields, etc...) or in the footer. Currently if you receive a DCE export from someone, you can't really rely on the timestamps, because you don't know the timezone. That's even more problematic if you receive a bunch of DCE exports made by different people. That's why it would be really beneficial to simply indicate the timezone in the preamble or footer of the export. Of course the timezone indication can (and should) be omitted if UTC timestamps are used (eg. date and time format set to `u`).

**Comment by Tyrrrz** [comment]
The dates are formatted according to standards in JSON export. The default format used elsewhere was based on Discord's own format circa 2016-2017. I'm not sure whether it was different per locale or I just used whatever it was on my machine (my locale's date format is different though).

Adding the timezone to preamble sounds messy. Ultimately, we should remove date format setting altogether and format the date with time zone identifier.

**Comment by Tyrrrz** [comment]
Related to/superseded by #879

**Comment by Tyrrrz** [comment]
Closing in favor of #879
