### ISSUE TITLE
Add ID tags to messages

### ISSUE THREAD

**Issue by Bluscream** [Tyrrrz/DiscordChatExporter#872]
### Export format

HTML

### Details

Would be need if you would add id tags to messages so they can be "anchored"/jumped to by using `http://localhost/channel.html#<message id>`

**Comment by 96-LB** [comment]
They do have ID tags; they're just prefixed with "message-". For example, you can jump to `1234567890` with `http://localhost/channel.html#message-1234567890`.

**Comment by Technetium1** [comment]
> They do have ID tags; they're just prefixed with "message-". For example, you can jump to `1234567890` with `http://localhost/channel.html#message-1234567890`.

That's news to me. I haven't had that feature working on Chromium, maybe I should try again.

**Comment by Tyrrrz** [comment]
> That's news to me. I haven't had that feature working on Chromium, maybe I should try again.

It's not in stable yet. It was added by this commit: https://github.com/Tyrrrz/DiscordChatExporter/commit/0e49936e38f1b612f13ef046b63b15fc8d9f9ad3.

You can download a CI build to get access to this feature.
