### ISSUE TITLE
Export text chat in voice channels

### ISSUE THREAD

**Issue by itsmeboy0** [Tyrrrz/DiscordChatExporter#874]
### Details

Discord has recently unveiled [Text chat in Voice Channels](https://support.discord.com/hc/en-us/articles/4412085582359#h_01FMJT3SP072ZFJCZWR0EW6CJ1), and it would be great to be able to export them.
![image](https://user-images.githubusercontent.com/75471378/174799138-714bb528-8fb2-4724-8675-468282393033.png)

**Comment by Tyrrrz** [comment]
Implemented in https://github.com/Tyrrrz/DiscordChatExporter/commit/94ef4b69817403a03cdda603f1592fed1f2d516f
