### ISSUE TITLE
Some emoji get exported as Unicode escape sequences

### ISSUE THREAD

**Issue by ItamarOlmert** [Tyrrrz/DiscordChatExporter#875]
### Version

v2.34.1

### Flavor

CLI (Command Line Interface)

### Export format

JSON

### Details

When exporting a channel as JSON, messages containing some emoji won't have that emoji exported as the expected character or even the emoji name, but rather as an escaped Unicode surrogate byte sequence.
For example, the emoji :wink: ends up as `\uD83D\uDE09`.

### Steps to reproduce

- Send a message with some emoji, such as ":wink: :shrug: :robot:": 
![Discord_32OzPErEhV](https://user-images.githubusercontent.com/29255731/174911826-8e3ab783-0078-4d93-b629-3ca2e3068936.png)
- Export channel to JSON
- The emoji appears in the JSON file as a Unicode escape sequence: ![Code_b1P4HWlm0s](https://user-images.githubusercontent.com/29255731/174912099-111a7b23-2263-4450-ab80-6220b47ee35b.png) instead the actual emoji, like so: 
![Code_zuPavUT39s](https://user-images.githubusercontent.com/29255731/174912330-c2ceb7e3-d4a8-404d-a428-c33ded025fa3.png)

**Comment by Tyrrrz** [comment]
It's quite common to encode special characters in JSON. Your JSON parser should be able to decode these easily.
