### ISSUE TITLE
Zero-pad `guilds` output

### ISSUE THREAD

**Issue by sus-impost0r** [Tyrrrz/DiscordChatExporter#877]
### Flavor

CLI (Command Line Interface)

### Export format

none

### Details

When one runs the CLI with the `guilds` argument, one is greeted with simple output of this form:

```
guild-id | guild-name
```

This is nice, but guild-id should be zero-padded to some amount, perhaps 19 (actually since UINT64_MAX is 20 chars, we should just use that) chars, in the style of `printf("%018" PRIu64 " | %s", id, name);`, in order to align all the names.

Current state:
```
0 | Direct Messages
841635913184712568 | some server
```

Desirable state:
```
0000000000000000000 | Direct Messages
0841635913184712568 | some server
```

**Comment by Tyrrrz** [comment]
What is the benefit of this, besides aligning the columns?

**Comment by omegasome** [comment]
Aligning the columns is the benefit, it improves legibility

**Comment by 96-LB** [comment]
Why not pad with whitespace instead if all you care about is the columns? I can't think of a single spot where Discord zero-pads their IDs.

**Comment by sus-impost0r** [comment]
@96-LB That would also work IMO.
