### ISSUE TITLE
Change the README to state you can be BANNED for using this software.

### ISSUE THREAD

**Issue by pedrosantos53** [Tyrrrz/DiscordChatExporter#878]
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

Please state on the README that you can get banned for using this. I saw no warning, except after getting my work's Discord account banned for downloading our server's posts to back them up for data collection/cleaning. The warning on the application itself is incredibly small and practically hidden when trying to find your own token.

An ideal warning would be a large font, bold, underlined statement at the top of the README on the Github page stating that you can be banned for violating Discord's TOS, as well as a large warning (similar to the one stating Ukraine is under attack and needs support) at the beginning of launching the application.

#211 references this same issue and it was partially fixed (in my opinion). A more clear warning would be highly beneficial to future users, as this application works as advertised, but with (previously unknown) risks associated with its usage.

Thank you, and I hope you implement these simple changes soon!

**Comment by Bonfire** [comment]
Fully agree. I think that while I'm sure many users haven't been banned DiscordChatExporter, stating that it is against Discord Terms of Service should be front-and-center.

**Comment by Tyrrrz** [comment]
It's already there: 
![image](https://user-images.githubusercontent.com/1935960/175501413-1c531cbb-ed90-4480-a747-f12f878708dc.png)

If you're afraid of getting banned, use a bot or a throw-away account.

**Comment by Tyrrrz** [comment]
Reordered the steps so that the warning appears first

**Comment by EpicLPer** [comment]
> I saw no warning, except after getting my work's Discord account banned for downloading our server's posts to back them up for data collection/cleaning.

How and what exactly did you do there? Did you set the parallel download speed in any capacity?

**Comment by Kayo4life** [comment]
bump
