### ISSUE TITLE
Option to use the older way of media downloading (don't download CSS, JS, fonts files and reference them offline)

### ISSUE THREAD

**Issue by jiatern** [Tyrrrz/DiscordChatExporter#881]
### Flavor

CLI (Command Line Interface)

### Export format

HTML

### Details

I have been using the older 2.33.2 version to export chats from a discord channel that corresponds to a live stream chat reactions, and I convert the HTML + its asset files to a single standalone HTML file for archiving using https://github.com/kinchanmaemo/standalone-html. The result is a big HTML file but within 50MB which is fine for me.

Since version 2.34, all CSS, JS and font files will be downloaded and this uses more space regardless I am converting to a standalone HTML file or not. If I do convert to a standalone HTML, the embedded CSS, JS and font files don't work because they are stored in base64.

Is it possible to have an option or a flag to use the 2.33.2 ``--media`` download method, where CSS, JS and font files are linked instead of downloaded and referenced offline? Thank you.

**Comment by jiatern** [comment]
Turns out the big file size is not due to the fonts but larger user avatars (now it's 512px). I will figure out other ways myself since it's my own unique purpose.

**Comment by Tyrrrz** [comment]
Yeah, that was added in https://github.com/Tyrrrz/DiscordChatExporter/pull/826
