### ISSUE TITLE
Undocumented change in folder output in docker version

### ISSUE THREAD

**Issue by Tokariew** [Tyrrrz/DiscordChatExporter#884]
### Version

2.35

### Flavor

CLI (Command Line Interface)

### Export format

TXT

### Details

With latest version of docker version default output folder was changed from `/app/out` to `/out`.
No info in changelog or in wiki… so to currently export succesfully chat command should look something like this
`podman run --rm  -it -v /media/hdds/test:/out:z tyrrrz/discordchatexporter:stable exportdm -t "token" -f PlainText`

### Steps to reproduce

- Run latest stable version of docker/podman `podman run --rm  -it -v /media/hdds/test:/app/out:z tyrrrz/discordchatexporter:stable exportdm -t "token" -f PlainText`
- Nothing is exported
- Being confused

**Comment by Tyrrrz** [comment]
Really sorry about that. Updated the wiki docs.
