### ISSUE TITLE
Discriminatory against Russian devs

### ISSUE THREAD

**Issue by MaxRockatasky** [Tyrrrz/DiscordChatExporter#890]
### Version

all

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

The terms of use field in Readme.md is discriminatory against Russian developers. You may not demand those who use your project to hold certain beliefs.

You are given the privilege of removing these outrageous terms before this repository is reported to GitHub, Inc. and taken down.

### Steps to reproduce

read Readme.md

**Comment by Tyrrrz** [comment]
> You are given the privilege of removing these outrageous terms before this repository is reported to GitHub, Inc. and taken down

Lol

**Comment by kovalensky** [comment]
I was kinda saddened seeing this, for first time I see a political banner on a software downloaded from GitHub :(
And I'm not even in Russia.

Nevertheless it's Oleksei's effort creating this wonderful software, for which I'm thankful.
