### ISSUE TITLE
Full guild as a single json file

### ISSUE THREAD

**Issue by BuyMyMojo** [Tyrrrz/DiscordChatExporter#891]
### Export format

JSON

### Details

When exporting to json I'd love to be able to parse all of the data at once instead of needing to go through seperate files or merge them myself before hand.
An option to export a single guild per file would be very uself.

My specific usecase is loading the json into Rust and parsing as structs based on input so being able to handle the entire output at once within a single struct would be useful.

<sub>I don't think this is a repost of another issue but I'm sorry if it is</sub>

**Comment by Tyrrrz** [comment]
What output format are you expecting?

**Comment by BuyMyMojo** [comment]
Basically a slight modification of how it already exports channels where it starts with the guild and date info then a list of channels and those channels contain there own list of messages.

```json
{
  "guild": {
    "id": "123456",
    "name": "GuildName",
    "iconUrl": "https://"
  },
  "dateRange": {
    "after": null,
    "before": null
  },
  "channels": [
    {
      "id": "12345",
      "type": "GuildTextChat",
      "categoryId": "123456",
      "category": "ComunityName",
      "name": "ChannelName",
      "topic": null,
      "messages": [
        {
          "id": "123456",
          "type": "Default",
          "timestamp": "2017-01-29T08:56:04.687+00:00",
          "timestampEdited": null,
          "callEndedTimestamp": null,
          "isPinned": false,
          "content": "MessageContets",
          "author": {
            "id": "123456",
            "name": "AuthorName",
            "discriminator": "1337",
            "nickname": "AuthorName",
            "color": null,
            "isBot": false,
            "avatarUrl": "https://"
          },
          "attachments": [],
          "embeds": [],
          "stickers": [],
          "reactions": [],
          "mentions": []
        } // End of message
      ] // End of message list
    } // End of channel
  ] // End of channel list
} // End of guild
```

**Comment by Tyrrrz** [comment]
I see. This is out of scope for this project, sorry.
