### ISSUE TITLE
Adding user role details into JSON exports

### ISSUE THREAD

**Issue by hahaschool** [Tyrrrz/DiscordChatExporter#892]
### Flavor

CLI (Command Line Interface)

### Export format

JSON

### Details

Hi guys, 

I really love this tool and have used it to dump multiple channels for some hobby analysis. However, I found user roles of message authors, which could be important information, missing in the JSON outputs. While role info has been crawled when retrieving user colors, it's really a waste not printing them out in detail in the final output.

I have prepared a PR for this feature, would be great if this could be added.

Adam

**Comment by hahaschool** [comment]
Link to PR: https://github.com/Tyrrrz/DiscordChatExporter/pull/893

**Comment by Tyrrrz** [comment]
Closing as out of scope. Explained more here: https://github.com/Tyrrrz/DiscordChatExporter/pull/893#issuecomment-1247191082
