### ISSUE TITLE
Style the way you export as text

### ISSUE THREAD

**Issue by silvxrcat** [Tyrrrz/DiscordChatExporter#894]
### Flavor

GUI (Graphical User Interface)

### Export format

TXT

## Style the way you export as text

Let's say you want to export a channel without the dates, tags, empty messages (before/after filter) or <Attatchment>/emoji indicators but instead want a clean design like "nickname: message" or without line breaks. Well, you can't really do that without doing it manually.

Instead, I prepose that you can choose how you want the text to look like in the output. The user would edit a text to format it, like this (in handlebars):

```handlebars
{{#unless empty}}
{{user no-tag nick}}: {{message no-emoji}}
{{/unless}}
```

and if they wanted line breaks they could simply create a new line after that. When you output, the program should read and utilize the text for the wanted output, therefore making: 

```
silver: hello there!
SleepyManZzzzz: yo look at my cool emoji
```

As you can see, it has been filtered with the user in mind. This would help with ease-of-reading and just wanting only the messages!

**Comment by Tyrrrz** [comment]
This is out of scope of the project. If you want something like this, it's easier to fork the repo and edit the templates yourself.
