### ISSUE TITLE
Choose the name of the exported file

### ISSUE THREAD

**Issue by CreaCloudz** [Tyrrrz/DiscordChatExporter#899]
### Flavor

CLI (Command Line Interface)

### Export format

HTML

### Details

I would like to be able to put the desired name of the file when exporting.

**Comment by 96-LB** [comment]
[This is already possible.](https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#changing-the-output-filename)

**Comment by CreaCloudz** [comment]
Very well I had not seen that with the -o we could also choose the path but also the name as much for me
