### ISSUE TITLE
Export Options

### ISSUE THREAD

**Issue by Magnaboy** [Tyrrrz/DiscordChatExporter#9]
As a solution/alternative for the issue of not being able to export (or render) extremely large channels, I suggest adding the ability to export to different, more data-driven formats, or just .txt, in which case channels with very large amounts of messages can be 'explored' practically. In the case of a .txt output, an even further enhancement could be to allow customization of the output in a manner such as "{timestamp} -  {username}: {message}" or if you only want to see the raw messages on each line "{message}", etc.

**Comment by Tyrrrz** [comment]
This is already implemented

**Comment by Magnaboy** [comment]
In that case, how do you customize the output format in txt? & in terms of UX I'd suggest that the file-type export option is made more clear, e.g. a drop drown menu to pick it inside the app itself, and possibly a Progress Bar (search the channel to see the total amount of messages in it to calculate that?) so I know if I'm waiting 10 mins or a few hours.

**Comment by Tyrrrz** [comment]
> In that case, how do you customize the output format in txt?
You can't. But it's a good idea, you should implement it. 😛 

Yeah I'm aware the export dialog isn't very intuitive. I'll look into improving it.

**Comment by Tyrrrz** [comment]
Closing this issue as technically the TXT output is already there. If you end up implementing custom format, make a pull request, I don't plan on doing this feature myself. The other suggestions were moved to other issues.
