### ISSUE TITLE
Improve Wiki by adding macOS instructions and fixing formatting

### ISSUE THREAD

**Issue by RenanYudi** [Tyrrrz/DiscordChatExporter#90]
Hello! Thank you for posting my Linux usage instructions on the Wiki, but I think they aren't properly formatted and the instructions could be clearer. As I can't submit an edit, I've Forked the project's Wiki [here](https://github.com/RenanYudi/DiscordChatExporter/wiki). You can correct my broken English, of course :p.

I also finished the [installation script](https://github.com/RenanYudi/DiscordChatExporter/blob/master/maclinux.command). It works on both Mac and Linux (Debian/Ubuntu). It's not perfect, but surely will make things a little easier.It is light, so it can be included inside the CLI.zip, but one of the script options is to download and extract the zip, so it will be overwriting itself… but it looks like it still works anyway (let's say it's a self-update feature lol). Or it could be available as a release asset, since not many people will be using it.

Depending on where the script will be available, it's better to tweak the Wiki pages, but I wrote this as a placeholder for now. And maybe the [Token Instructions](https://github.com/RenanYudi/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs) Images should be hosted somewhere else.

![replace](https://user-images.githubusercontent.com/12040397/44133976-f84d5b82-a038-11e8-991d-9a0dffb57c4a.png)

***
It would also be nice to document the date formats used on`--datefrom` and `--dateto`, if it is DD-MM-YYYY, MM/DD/YYYY or something else. And also on `--dateformat`.

 I'll be making a pull request for the script. Once you say where the script will be, I'll edit the fork's Wiki. The fork will be deleted after this issue is closed.

Thank you!

**Comment by RenanYudi** [comment]
Updated Wiki with [Docker instructions](https://github.com/RenanYudi/DiscordChatExporter/wiki/Docker-usage-instructions) in case app gets "dockerized", and [Cron instructions](https://github.com/RenanYudi/DiscordChatExporter/wiki/Scheduling-Exports-with-Mono-&-Crontab).
Tweaked [the script](
https://github.com/RenanYudi/DiscordChatExporter/blob/master/maclinux.command) a little bit, and added a "Cron Scheduler Assistant".

The wiki pages are on .txt [here, on Google Drive](https://drive.google.com/drive/folders/1KC4ubnYYVO8-nILRwXCr3jHAnYo7tXNr?usp=sharing).

**Comment by Tyrrrz** [comment]
Hi,
Thank you for finding the time for this!
I replicated your changes to this wiki and enabled editing it to contributors so you can make changes directly in the future.

**Comment by RenanYudi** [comment]
Sent you an email.
