### ISSUE TITLE
TOU acceptance list

### ISSUE THREAD

**Issue by cbanek** [Tyrrrz/DiscordChatExporter#901]
### Flavor

CLI (Command Line Interface)

### Export format

TXT

### Details

I love your terms of use so much, I'd love to say that I permanently accept them, and I want to use this tool to export some discord messages.  Don't worry, Ukraine is going to hold out.  I have the faith, and I'm going to do whatever I can for them, and I promise that in writing here on the github.  You should maybe have like a CONTRIBUTORS file where you say who's accepted it and people can give you a PR to sign it?  I'd love to give you more a PR, but I'm sure it works just fine already.  And a PR is how you prove you use something! <3

**Comment by cbanek** [comment]
I love your terms of use so much, I'd love to say that I permanently accept them, and I want to use this tool to export some discord messages. Don't worry, Ukraine is going to hold out. I have the faith, and I'm going to do whatever I can for them, and I promise that in writing here on the github. You should maybe have like a CONTRIBUTORS file where you say who's accepted it and people can give you a PR to sign it? I'd love to give you more a PR, but I'm sure it works just fine already. And a PR is how you prove you use something! <3 just cause I edited the message, no editing this time!

**Comment by cbanek** [comment]
Give it a thought though!  I think it could be fun.

**Comment by Tyrrrz** [comment]
Thanks for suggestion but I think that a list would be unnecessary :)
