### ISSUE TITLE
AuthorID sometimes incorrect when exporting as CSV

### ISSUE THREAD

**Issue by invisi-splat** [Tyrrrz/DiscordChatExporter#902]
### Version

v2.35.0

### Flavor

GUI (Graphical User Interface)

### Export format

CSV

### Details

I've been attempting to use this program to export messages in a channel to CSV format for a Discord bot as opposed to manually implementing this. I've found that sometimes the AuthorIDs outputted in the CSV don't match up with the true IDs (the ones retrieved from calling the Discord API with my bot or right clicking on the user's profile).

It seems to be some weird rounding error, as they are very close in value.

Some examples -- some are correct:

`458304698827669504` instead of
`458304698827669536` 

`485020107559403520` instead of
`485020107559403522`

`668035632475537408` (is correct)
`668035632475537408`

`343688240718675968` instead of
`343688240718675969`

`667122566720126976` (is correct)
`667122566720126976`

### Steps to reproduce

- Export channel as CSV
- View generated CSV file

**Comment by Tyrrrz** [comment]
Would be nice if you could provide a channel to reproduce it on.

**Comment by invisi-splat** [comment]
Channel ID: `824389387319377950`

**Comment by Tyrrrz** [comment]
Do you have a server invite?

**Comment by 96-LB** [comment]
Follow-up question since I couldn't reproduce:

How are you viewing your CSV files? Some programs (e.g. Excel) don't display the ID quite right since they convert it to a number and then lose precision, but when I opened it in Notepad it was fine.

**Comment by invisi-splat** [comment]
Apologies for taking up your time -- I've just realised I've been automatically running it through an R script to clean the data and it seems to be something wrong there with how R reads CSV files. I checked the original file and the IDs are all fine there.

Sorry for being stupid!
