### ISSUE TITLE
[Feature Request] Pagination

### ISSUE THREAD

**Issue by Rovoska** [Tyrrrz/DiscordChatExporter#904]
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

HTML

### Details

I tried this tool recently, and it instantly proved itself unusable by creating an html file that was well over a hundred megabytes and browsers struggled to load it. The tool needs to create a new page every few hundred messages or so, as otherwise it seems the files become incredibly unwieldy.

sorry if this was a repeat, I searched for pagination and nothing came up that was relevant

**Comment by 96-LB** [comment]
There's already a feature to partition files. It's available in the advanced settings menu on the GUI or with `-p` on CLI.
