### ISSUE TITLE
No error handling for failed requests

### ISSUE THREAD

**Issue by signalhunter** [Tyrrrz/DiscordChatExporter#908]
### Version

v2.35.0

### Flavor

CLI (Command Line Interface)

### Export format

JSON

### Details

Sometimes the Discord API will fail and return an error code (5xx). I expected DiscordChatExporter to have a request retry mechanism, but there doesn't seem to be one? For context, I am downloading a medium-sized guild with around a million messages.

CLI args: `DiscordChatExporter.Cli exportguild -f Json -p 25mb --media --reuse-media --parallel 2 -o [PATH] -g [SERVER ID]`

Here is my CLI log (redacted): [dce-error-redacted.txt](https://github.com/Tyrrrz/DiscordChatExporter/files/9400250/dce-error-redacted.txt)

### Steps to reproduce

- Download messages using the CLI `exportguild` option

**Comment by Tyrrrz** [comment]
Probably should just put all 5XX errors here:

https://github.com/Tyrrrz/DiscordChatExporter/blob/6c039ebfa6023e7a0e8649b7a34f4b9ed2c11f9f/DiscordChatExporter.Core/Utils/Http.cs#L16-L19
