### ISSUE TITLE
--filter option doesn't work with parentheses

### ISSUE THREAD

**Issue by Boarworm** [Tyrrrz/DiscordChatExporter#909]
### Version

2.35.0

### Flavor

CLI (Command Line Interface)

### Details

I was doing export using --filter option and phrase "(max)" but got error: No messages found for the specified period.
p.s. maybe something wrong with boundaries `(\bMax\b)`

### Steps to reproduce

Export messages that contains phrase "(max)", or any other word with parentheses, ex. `--filter "'(max)'"`

**Comment by Tyrrrz** [comment]
Note that event a simple parser like `max` fails because it parses `m` and expects it to end with `ention:` to lead into `MentionsParser`.
