### ISSUE TITLE
DiscordChatExporter.CLI.zip contains a trojan

### ISSUE THREAD

**Issue by slashdottir** [Tyrrrz/DiscordChatExporter#910]
### Version

current

### Flavor

CLI (Command Line Interface)

### Details

I checked with Virustotal and your download file contains a trojan

Trojan.Malware.300983.susgen

<img width="844" alt="image" src="https://user-images.githubusercontent.com/47145634/186535022-ea27b2bb-4704-45b1-ab95-d147c00e2910.png">

### Steps to reproduce

download the package
upload it to with virustotal.com
trojan reported

**Comment by slashdottir** [comment]
Then again, just checked the file with Kapersky and it looks ok there.  Several people on reddit say the results from MaxSecure are often false positives

<img width="975" alt="image" src="https://user-images.githubusercontent.com/47145634/186536311-02bfe460-ac43-4b7a-8bb1-5f65b29d9c67.png">

**Comment by Yudi** [comment]
The false positive scan was made 1 month ago.
<img width="343" alt="image" src="https://user-images.githubusercontent.com/12040397/186536624-10b8c57d-bb10-46e2-a9f4-f5194520cde3.png">

Always reanalyse files to get current results.
<img width="343" alt="image" src="https://user-images.githubusercontent.com/12040397/186536644-bd82b5ff-ebf0-4cce-b7b6-0f0596ae24b7.png">

https://www.virustotal.com/gui/file/0b9d336dab90d158cdd7f9b8f81d61b15595e9cac4ed0345cb847fe70bbf2c57

**Comment by slashdottir** [comment]
ok thank you
