### ISSUE TITLE
Export a single DM channel

### ISSUE THREAD

**Issue by erincerys** [Tyrrrz/DiscordChatExporter#911]
### Flavor

CLI (Command Line Interface)

### Export format

HTML, TXT, JSON, CSV

### Request

This request is to support exporting a single DM channel.

**Current behavior**

Currently, DCE only supports exporting _all_ DMs from a user account. 

The `exportdm` command is named in a misleading way, implying it already supports this. However, the `-c` argument isn't supported for it.

The `export` command cannot be used for this either, as passing a DM channel ID to the `-c` argument produces an error:

    DiscordChatExporter.Core.Exceptions.DiscordChatExporterException:
        Requested resource (channels/CHANNEL_ID_HERE) does not exist.

**Proposed behavior**

Either implement support for specifying a DM channel ID in `exportdm` or `export` with the `-c` argument.

**Workarounds**

1. **Export all DMs.** My account is over 4 years old, and a full export is quite time consuming. The earliest DM channel that the program always exports first is with an ex who I was with for many years. I'm presently running an export as I type this. It's been over 15 minutes, and it's only 17% finished.

2. **Copy and paste the messages.** This is fraught, as formatting is lost, and adequate line breaks for readability aren't there. I usually spend quite some time _reformatting_ conversation snippets such as that.

2. **Take screenshots and stitch them together.** This works well for mobile users, as there are apps to do the stitching that work pretty well. However, I'm primarily a desktop user, and the apps available to this are exclusively browser addons that _don't_ work reliably to produce the expected results.

### Use case

It would be exceptionally useful for me to be able to export a single DM channel. Sometimes I want to grab the text from a short-lived DM that I've had recently with someone to share.

I already have scripts written that will take channel IDs, run DCE, upload the resulting log to my personal CDN, and copy the resulting link to my clipboard. Expanding support to a single DM channel would integrate wonderfully with this!

### Related discussion

Even when reusing pre-existing media that has been exported in a prior run (`exportdm --media --reuse-media`), the app appears not to scan the directory to do an incremental export of messages. It starts over from the beginning, collecting all messages in all channels. This is useful for catching edits, which some may desire.

Not having the _option_ of incremental backups here is inefficient in this use case.

Incremental backups have been suggested in the past (#564) and support for them was refused, citing a workaround being the `--after` argument. This argument isn't available for the `exportdm` command. That argument _could_ be implemented if said command supported a single DM channel, though!

There is a case for supporting this in that the sensing and reuse of media  is already supported for this exact same goal - efficiency. Regardless, that's out of the scope of this request, and not something I highly value seeing in the program at the moment. Merely food for thought!

**Comment by erincerys** [comment]
I've just realised that this is [supported,](https://github.com/Tyrrrz/DiscordChatExporter/discussions/822) but that `export` doesn't accept a user ID, rather a DM channel ID. I can script/hack around that. Closing.

**Comment by 96-LB** [comment]
It should be possible to do this already with the `export` command. Make sure you're [following these steps](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs#how-to-get-a-direct-message-channel-id) and not accidentally copying the user ID instead.

**Comment by 96-LB** [comment]
Looks like you beat me to it 😅
