### ISSUE TITLE
Error pulling guilds and channels

### ISSUE THREAD

**Issue by zackmark29** [Tyrrrz/DiscordChatExporter#913]
### Version

2.35.1

### Flavor

GUI (Graphical User Interface)

### Details

I'm getting this error below when I'm trying to input the token which I get from the network tab.

![image](https://user-images.githubusercontent.com/62680932/187404481-884e67ed-d1c3-4166-bfa0-742532c9fc66.png)

### Steps to reproduce

....

**Comment by 44aa44** [comment]
please re-open the issue it just happened to me too
