### ISSUE TITLE
No DMs and only 4 servers are showing up in GUI

### ISSUE THREAD

**Issue by Lishistoria** [Tyrrrz/DiscordChatExporter#916]
### Version

2.35.1

### Flavor

GUI (Graphical User Interface)

### Details

After inputting the token when you select the channels you want to export almost nothing shows up except four servers (out of 100). Direct Messages are just blank and a Project server i made and am the administrator of doesn't show up.

![Screenshot](https://user-images.githubusercontent.com/71313764/187705762-08f1fda2-ff63-4934-8241-2403a47fc802.png)

### Steps to reproduce

Input Token as described
Click Arrow to get to the next page

**Comment by Tyrrrz** [comment]
Did you use a bot or personal token?
