### ISSUE TITLE
Output path validation is broken when exporting DMs

### ISSUE THREAD

**Issue by rafalh** [Tyrrrz/DiscordChatExporter#917]
### Version

2.35.1

### Flavor

CLI (Command Line Interface)

### Export format

TXT

### Details

I was running 
```
docker run --rm -v $PWD/discord-export:/out tyrrrz/discordchatexporter:stable exportdm -t '<token>' -f PlainText
```
and got an error:
```
Attempted to export multiple channels, but the output path is neither a directory nor a template.
```
I was using `export` command before with the same Docker volume attached and it worked fine. `discord-export` is clearly a directory. I tried adding `-o /out` but it didn't help. 
After finding the error in source code (https://github.com/Tyrrrz/DiscordChatExporter/blob/master/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs#L113) I tried to workaround the problem using a template: `-o /out/dms/%c` but I don't really like the nested directory structure I received.

### Steps to reproduce

```
mkdir discord-export
docker run --rm -v $PWD/discord-export:/out tyrrrz/discordchatexporter:stable exportdm -t '<token>' -f PlainText
```

**Comment by rafalh** [comment]
I think I found the root cause: https://github.com/Tyrrrz/DiscordChatExporter/blob/504c3c53cd6d1d32d474e44126647c695e0f555c/DiscordChatExporter.Core/Utils/PathEx.cs#L21
It expects path ending with a slash. This is not intuitive in my opinion. I propose to remove this restriction and instead check if output path is really a directory using `File.GetAttributes` (see https://stackoverflow.com/questions/1395205/better-way-to-check-if-a-path-is-a-file-or-a-directory). I think it would be nice if it would also create the output directory if it does not exist

**Comment by Tyrrrz** [comment]
Files without extensions are also valid, so there's always going to be confusion in this area.

**Comment by DeRusGAMING** [comment]
I actually cannot export anything when I use exportguild, it outputs this error everytime, even not using the -o argument

**Comment by Tyrrrz** [comment]
Please try the CI/latest build
