### ISSUE TITLE
All messages are blank

### ISSUE THREAD

**Issue by httpwemel** [Tyrrrz/DiscordChatExporter#918]
### Version

2.35.1

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

HTML

### Details

Every message is blank in the exported file even if you have the download media option enabled when you export a server even with admin rights for the bot.

### Steps to reproduce

Use the program normally with all defaults.

**Comment by 96-LB** [comment]
Discord disabled message content intents on all bots by default recently. You have to make sure this setting is flicked:
![image](https://user-images.githubusercontent.com/21089343/188887333-a4a412c3-c84d-4691-8b37-d41e086c0f23.png)

**Comment by lynerlok** [comment]
Yeah, it works perfectly ! I miss this new feature, thx !
