### ISSUE TITLE
The ★(STAR) in log exported HTML is a broken link

### ISSUE THREAD

**Issue by sina2** [Tyrrrz/DiscordChatExporter#923]
### Version

v2.35.1

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

The ★(STAR) image in log exported HTML is a broken.

I found this link ( https://twemoji.maxcdn.com/2/svg/2605.svg ) is not found (404 error).

![image](https://user-images.githubusercontent.com/3647788/189507500-0778815a-a07f-4d3c-bf65-174d3f8967fc.png)

### Steps to reproduce

-  Export the channel log (HTML) included character "★".
- The browser opens the channel log (HTML).

**Comment by ZarakiKanzaki** [comment]
Hi! may I contibute to this issue?

**Comment by ZarakiKanzaki** [comment]
> Sure. What's your plan?

As far as I'm understanding the problem, I would look for another icon from the twemoji website that would resemble the star and make the export refer to that new resource, or  if we want to keep a Legacy item, it would be useful to have a resource inside our project/solution.
What do you think?

**Comment by Tyrrrz** [comment]
How does the star render in the client? I suspect it's not supposed to be turned into an emoji, in which case the emoji matching regex needs to be fine-tuned somehow.

**Comment by ZarakiKanzaki** [comment]
Seems legit! 😊  So the idea would be to improve the regex so the client won't render the star, but what about the broken link? sorry for the late reply but I was at a conference in the last few days.

**Comment by Tyrrrz** [comment]
Well, if the parser won't recognize the star as an emoji (if that's intended) then the link (i.e. `<img>`) won't be rendered

**Comment by CanePlayz** [comment]
> Well, if the parser won't recognize the star as an emoji (if that's intended) then the link (i.e. <img>) won't be rendered

Not much I can contribute here, but I can at least confirm that indeed, the client doesn't render it as an emoji, it just shows the unicode character ★.

![image](https://user-images.githubusercontent.com/81419612/213330742-ade6c519-d106-49f2-a150-e160d396eab6.png)

**Comment by Tyrrrz** [comment]
Yeah, so we'd need to exclude the star (u2605) from this regex:

https://github.com/Tyrrrz/DiscordChatExporter/blob/f505ff3f1e58048181096a8a985459e9add15331/DiscordChatExporter.Core/Markdown/Parsing/MarkdownParser.cs#L157-L165

I wouldn't just blindly make an exception and figure out if we have other false positives (like u2600, u2601, u2603, u2604, for starters).

**Comment by CanePlayz** [comment]
So are the ones that need to be tested just the 256 miscellaneous symbols of unicode or any other ones too? Cause if we could narrow down the ones that need to be tested I could test them.

**Comment by Tyrrrz** [comment]
> So are the ones that need to be tested just the 256 miscellaneous symbols of unicode or any other ones too? Cause if we could narrow down the ones that need to be tested I could test them.

Yes, and I think also characters in this range: U2600 - U26FF.

**Comment by CanePlayz** [comment]
> Yes, and I think also characters in this range: U2600 - U26FF.

From https://en.wikipedia.org/wiki/Miscellaneous_Symbols#Emoji:

![image](https://user-images.githubusercontent.com/81419612/214323852-179ed3db-c511-4341-90cd-b3ef1eb9ad5e.png)

**Comment by Tyrrrz** [comment]
> > Yes, and I think also characters in this range: U2600 - U26FF.
> 
> From [en.wikipedia.org/wiki/Miscellaneous_Symbols#Emoji](https://en.wikipedia.org/wiki/Miscellaneous_Symbols#Emoji):
> 
> ![image](https://user-images.githubusercontent.com/81419612/214323852-179ed3db-c511-4341-90cd-b3ef1eb9ad5e.png)

Even better, means there's overlap 😀

**Comment by CanePlayz** [comment]
I've updated the regex with the list from Wikipedia, and interestingly, two things happen now:

1. Not surprisingly, this issue is fixed.

2. Emojis with a ️Variation Selector-16 behind them (i. e. https://emojipedia.org/person-bouncing-ball/, see Codepoints) don't get rendered as images anymore. I have no idea why that is, technically nothing should have changed for them, they're still in the regex.

Old export:

![image](https://user-images.githubusercontent.com/81419612/215006632-a6528806-3139-4a7b-820c-782736333769.png)

New export:

![image](https://user-images.githubusercontent.com/81419612/215006647-19c67dc4-0dba-4320-8e05-2836fca7eee9.png)

**Comment by CanePlayz** [comment]
We could fix this issue now at the cost of some emoji not being rendered. The emoj matcher eventually needs an update anyways (see #548).

**Comment by Tyrrrz** [comment]
> We could fix this issue now at the cost of some emoji not being rendered. The emoj matcher eventually needs an update anyways (see #548).

Are the emoji you're referring to being rendered in the current version? In other words, is it a regression or a separate missing feature?

**Comment by CanePlayz** [comment]
They're currently being rendered. No idea why they're not rendered anymore with the new regex. So a regression.

**Comment by Tyrrrz** [comment]
> They're currently being rendered. No idea why they're not rendered anymore with the new regex. So a regression.

That would probably imply that the new non-twemoji-emoji regex erroneously matches on those emoji?

**Comment by CanePlayz** [comment]
What do you mean by non-twemoji-emoji regex? So far I thought this regex just checks for emoji codepoints in a series of characters and the twemoji stuff comes later.

**Comment by Tyrrrz** [comment]
> What do you mean by non-twemoji-emoji regex? So far I thought this regex just checks for emoji codepoints in a series of characters and the twemoji stuff comes later.

Oh right, my bad. I got it confused with another issue, sorry.

Maybe if you open a draft PR, we can look at the code and try to debug it together.

**Comment by CanePlayz** [comment]
Sounds good, I will open a PR.
