### ISSUE TITLE
Add User UID to the log

### ISSUE THREAD

**Issue by Vastrix** [Tyrrrz/DiscordChatExporter#93]
Hey,

First of all, great app! :)
Second, **would it be possible to add the UserUID to the log as well?**

This because both name and discriminator can be changed, whilst, the UID persists.. :)

Cheers

**Comment by Tyrrrz** [comment]
Yes, that is possible. How do you think it should be represented in the output?

**Comment by Vastrix** [comment]
hmmm

For HTML, maybe add it to the tooltip when hovering over the name `Vastrix:7097 (1337UID1337)`
For CSV, to make parsing easier (keeping regex in mind), maybe `Vastrix#7097|1337UID1337`
For Plain Text, I would again go for the more readable of the two because, if you are going to parse the data, you're not gonna use plain text `Vastrix:7097 (1337UID1337)`

Thanks for the fast response!

**Comment by Tyrrrz** [comment]
HTML option of `Vastrix#7097 (1337UID1337)` adds too much visual noise when hovering, I don't like it

**Comment by Vastrix** [comment]
Yeah, I can see that :s
Got an alternative?

**Comment by Vastrix** [comment]
Can be fairly hidden on HTML tbh, Even an HTML code comment suffices *in my opinion*
(as long as it's still somewhere)

**Comment by Vastrix** [comment]
If I wanna parse it I'll always use csv
  
But If I just wanna read it and thus save as html, and I come across two people pretending they're each other, I wanna be able to tell who's who.. :)
  
This rarely happens ofc, which is why I think a html code comment suffices as well

**Comment by Vastrix** [comment]
If I wanna parse it I'll always use csv
  
But If I just wanna read it and thus save as html, and I come across two people pretending they're each other, I wanna be able to tell who's who.. :)
  
This rarely happens ofc, which is why I think a html code comment suffices as well

**Comment by Vastrix** [comment]
Is it me or is github freaking out?
![](https://puu.sh/BW79x/52a1acc129.png)

**Comment by Tyrrrz** [comment]
Are you interested in just reading it or parsing it?

**Comment by Vastrix** [comment]
*fixing the timeline*
![](https://puu.sh/BWF7S/35a4ab66bc.png)

**Comment by Tyrrrz** [comment]
DST switch? 😛

**Comment by l0c4lh057** [comment]
I think it would be fine if it is a property of the author text, e.g. `<span class="chatlog__author-name" title="username#0000" userId="1234567890">nickname</span>`

**Comment by Vastrix** [comment]
Sure, as long as it's there :)
