### ISSUE TITLE
Messages are not showing up in exported HTML

### ISSUE THREAD

**Issue by mango-ki** [Tyrrrz/DiscordChatExporter#932]
### Version

2.35.2

### Flavor

GUI (Graphical User Interface)

### Details

I tried exporting an archive of my server channels for backup purposes, but lately it isn't saving any of the messages in the exported document.
Here's what it looks like when I try to export a channel as normal. I'm using a bot token to do this, and have been doing so for a while with no issues.
![image](https://user-images.githubusercontent.com/57552959/190399395-ec248cf4-73df-44cf-b1ec-be51d96fceda.png)
I tried viewing the exported HTML in another browser with no extensions, it still shows the same.

### Steps to reproduce

- Select channel/s
- Click yellow download button
- Set location (same as always)
- Click "export"

**Comment by 96-LB** [comment]
See #918

**Comment by mango-ki** [comment]
thank you!
