### ISSUE TITLE
Export fails with "Requested value 'tweet' was not found"

### ISSUE THREAD

**Issue by TomArrow** [Tyrrrz/DiscordChatExporter#936]
### Version

v2.36.0

### Flavor

GUI (Graphical User Interface)

### Export format

JSON

### Details

Welp, sorry for already having found another bug right as you fixed the other (thanks by the way, will test later!).

This time it seems to be something related to tweets. Here is the error message:
![2022-09-19 04_53_44-DiscordChatExporter v2 36 0](https://user-images.githubusercontent.com/6640421/191047969-ad5bcc64-0e1b-4494-9311-c45f5643dc98.png)
![2022-09-19 04_53_52-DiscordChatExporter v2 36 0](https://user-images.githubusercontent.com/6640421/191047987-19700c7c-d9cb-4488-8735-d883c678e197.png)
![2022-09-19 04_54_01-DiscordChatExporter v2 36 0](https://user-images.githubusercontent.com/6640421/191047998-b97334cd-f88c-498b-b7ec-0096374eb301.png)
![2022-09-19 04_54_08-DiscordChatExporter v2 36 0](https://user-images.githubusercontent.com/6640421/191048008-1c8a57a9-89c1-4c13-afab-000c520d836f.png)

Starts with: ```System.ArgumentException: Requested value 'tweet' was not found. at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64 result)```

The outputted JSON file does not appear to be broken but it ends a few messages above what I think likely causes the issue: And old Tweet (Twitter) message from August 2016. Maybe something related to an embed that changed?

### Steps to reproduce

I'd guess, find some old popular discord and try to export a channel that has Tweets linked in it around August 2016.

**Comment by mgunnin** [comment]
Getting the same error.. Only seems to happen with certain channels though

**Comment by Tyrrrz** [comment]
Please try the CI build

**Comment by TomArrow** [comment]
That fixed it, thanks!
