### ISSUE TITLE
Error exporting channel(s)

### ISSUE THREAD

**Issue by basshitsu** [Tyrrrz/DiscordChatExporter#937]
### Version

2.36.0

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

I get an error when attempting to export direct messages; see the screenshot. I believe this issue only appeared after the latest update, as I had successfully exported direct messages just a week ago before this update.

![error_exporting_channels](https://user-images.githubusercontent.com/13185782/191524530-a56bceec-4b35-4dbc-954a-f1af1d85e3ac.png)

### Steps to reproduce

— Click Export.
— Click Save.

**Comment by Tyrrrz** [comment]
Can you try downloading the latest version manually?

**Comment by basshitsu** [comment]
This did indeed fix the issue. Should have thought to try it myself. Thanks.
