### ISSUE TITLE
Discord Chat Exporter does not work after upgrade

### ISSUE THREAD

**Issue by paulqui** [Tyrrrz/DiscordChatExporter#941]
### Version

Latest update

### Flavor

GUI (Graphical User Interface)

### Details

DHT w

### Steps to reproduce

Discord Chat Exporter was working well until today on Win 10 system.  When I opened the GUi it said something about updating to latest version.  The update completed and thereafter am no longer able to open the GUI.

**Comment by hyzchip** [comment]
I have hit this exact same bug.  Directly downloading version 2.36.1 also doesn't work, the program silently fails to launch.  Downloading version 2.36 and not updating works fine, though.  I was also using Windows 10.

**Comment by Tyrrrz** [comment]
@paulqui can you uninstall all versions of .NET Runtime and try running the application again?

**Comment by Tyrrrz** [comment]
Try the CI version please

**Comment by hyzchip** [comment]
I am very late, but I can confirm that the new version 2.36.2 works perfectly!  Thank you for the great work on this project :+1:
