### ISSUE TITLE
The latest version doesn't work

### ISSUE THREAD

**Issue by Jokashi** [Tyrrrz/DiscordChatExporter#942]
### Version

2.36.1

### Flavor

GUI (Graphical User Interface)

### Details

Since the latest update, I can't run DiscordChatExporter.exe. When I try to launch it nothing happens. I have to remove it and extract an older version to have it work. Then it updates itself automatically when I close it and I have to come back to the older version again.

### Steps to reproduce

- Install the latest version.
- Try to run DiscordChatExporter.exe
- Nothing happens.

**Comment by Tyrrrz** [comment]
Can you try the CI build?

**Comment by Tyrrrz** [comment]
Duplicate of #941
