### ISSUE TITLE
I cannot find the token anymore with any browser following instructions

### ISSUE THREAD

**Issue by jpfl** [Tyrrrz/DiscordChatExporter#956]
### Version

2.36.2

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

I cannot find the token anymore with any browser following instructions
in there networktab are just gibberish .js entries listed
nothing anymore like messages?limit 
I have tried to click random ones and search in the headers tab / request headers for a authorization header but didn't find any or any token.
it was always very easy in the past following the instructions.
I have tried chrome (my normal browser) and firefox.
both latest versions

### Steps to reproduce

logging into discord
going into dev mode / inspect element mode
reloading page
looking for messages, limit by search and also manually scrolling down the list without a search

**Comment by Tyrrrz** [comment]
Can you try clicking around between different servers? Usually it should cause the request to appear
