### ISSUE TITLE
Filter has:embed doesn't work

### ISSUE THREAD

**Issue by Ilirski** [Tyrrrz/DiscordChatExporter#958]
### Version

2.36.3

### Flavor

CLI (Command Line Interface)

### Export format

TXT

### Details

Trying to filter using `"has:embed"` does not return any results, while negating the filter using `" -has:embed"` returns empty messages.

Expected behaviour is messages with embeds are returned when using `"has:embed"` (Discord search functionality does this), and vice-versa when the filter is negated.

Below is example of empty messages returned, the usernames blocked out.
![image](https://user-images.githubusercontent.com/24876805/197519973-4346e618-2a43-4c02-9713-ace939d4c739.png)

### Steps to reproduce

Use parameter --filter "has:embed" when exporting with CLI

**Comment by Tyrrrz** [comment]
Are you exporting using a bot that doesn't have message content intent enabled?

**Comment by Ilirski** [comment]
Yes, my bad! Didn't realize that was off. Works fine now.
