### ISSUE TITLE
include both name and code for reactions in json output

### ISSUE THREAD

**Issue by ToyKeeper** [Tyrrrz/DiscordChatExporter#962]
### Version

ver 2.36.4, git master head as of 2022-11-05

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

JSON

### Details

DCE's json exports include the unicode value for reaction emojis, but not the plain-text name.  Could the name be added?

Without this, I need to process the json exports a second time with a different tool, to add the missing data.  This tool must import DCE's lookup table (Utils/EmojiIndex.cs) to convert codes to names, and it would be much easier if the data was simply part of the export to begin with.

I don't have the toolchain to build and test it, but maybe something like...

```diff
diff --git a/DiscordChatExporter.Core/Exporting/Writers/JsonMessageWriter.cs b/DiscordChatExporter.Core/Exporting/Writers/JsonMessageWriter.cs
index 9d9a125..aad3cdd 100644
--- a/DiscordChatExporter.Core/Exporting/Writers/JsonMessageWriter.cs
+++ b/DiscordChatExporter.Core/Exporting/Writers/JsonMessageWriter.cs
@@ -209,6 +209,7 @@ internal class JsonMessageWriter : MessageWriter
         _writer.WriteStartObject("emoji");
         _writer.WriteString("id", reaction.Emoji.Id.ToString());
         _writer.WriteString("name", reaction.Emoji.Name);
+        _writer.WriteString("code", reaction.Emoji.Code);
         _writer.WriteBoolean("isAnimated", reaction.Emoji.IsAnimated);
         _writer.WriteString("imageUrl", await Context.ResolveAssetUrlAsync(reaction.Emoji.ImageUrl, cancellationToken));
         _writer.WriteEndObject();
```

I'm also a little confused why the ".Name" field contains the raw unicode, while the ".Code" field seems to contain the plaintext name... but I assume that can't be changed without breaking backward compatibility.

Adding an extra field, though, seems pretty safe and would avoid the need to parse the lookup table into other tools and then convert data a second time.  Programs generally use the fields by name, and having an extra name in the hash table will typically cause it to just be ignored by programs which don't use it.

### Steps to reproduce

1. Export json for a channel which has emoji reactions in its history

Expected result:
```json
"reactions": [
        {
          "emoji": {
            "id": "",
            "code": "\uD83E\uDD76",
            "name": "cold_face",
            "isAnimated": false,
            "imageUrl": "...channel.json_Files/1f976-5917C.svg"
          },
          "count": 7
        },
        ...
```

Actual result:
```json
"reactions": [
        {
          "emoji": {
            "id": "",
            "name": "\uD83E\uDD76",
            "isAnimated": false,
            "imageUrl": "...channel.json_Files/1f976-5917C.svg"
          },
          "count": 7
        },
        ...
```

... though to keep backward compatibility, the name/code fields shouldn't be un-swapped.  This is just a request to add the plaintext name as another field, anywhere it isn't currently made available.

**Comment by Tyrrrz** [comment]
> I'm also a little confused why the ".Name" field contains the raw unicode, while the ".Code" field seems to contain the plaintext name... but I assume that can't be changed without breaking backward compatibility.

https://github.com/Tyrrrz/DiscordChatExporter/blob/b672c30071461a600fb546993a3f613f719c6793/DiscordChatExporter.Core/Discord/Data/Emoji.cs#L11-L23
