### ISSUE TITLE
Being able to see VC Channels

### ISSUE THREAD

**Issue by HAHOOS** [Tyrrrz/DiscordChatExporter#966]
### Version

2.36.4

### Flavor

GUI (Graphical User Interface)

### Details

I was testing the application when suddently I have found that there is a VC channel, I tried to download it and I got an error saying "No messages found for the specific period(channel-name)". I tried it on HTML and JSON.

### Steps to reproduce

- Open the application and type the token.
- Select a VC channel
- Download the file
- You will receive an error

**Comment by 96-LB** [comment]
Not a bug - exporting a voice channel downloads the chat log for its associated pop-out text channel. You got an error because there were no messages in the channel you tried to export.
