### ISSUE TITLE
Docker unable to execute due to missing file

### ISSUE THREAD

**Issue by LIPDProductionsInc** [Tyrrrz/DiscordChatExporter#967]
### Version

2.36.4

### Flavor

CLI (Command Line Interface)

### Details

In the latest version release, there appears to be no file named `DiscordChatExporter.Cli.dll` which cause docker to be unable to execute DiscordChatExporter on a Raspberry Pi.

### Steps to reproduce

- Follow the instructions in the [Docker Usage Instructions](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Docker-usage-instructions)
- Execute `DiscordChatExporter`
- Receive Unhandled exception.

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly '/DiscordChatExporter.Cli.dll'. The system cannot find the file specified.

Filename: '/DiscordChatExporter.Cli.dll'
```

**Comment by Tyrrrz** [comment]
Hi

> ...which cause docker to be unable to execute DiscordChatExporter on a Raspberry Pi

Are you pulling the image from the registry or building it yourself? I'm asking because, if I remember correctly, it took some extra steps to run the image on Raspberry Pi.

**Comment by LIPDProductionsInc** [comment]
> Are you pulling the image from the registry or building it yourself? I'm asking because, if I remember correctly, it took some extra steps to run the image on Raspberry Pi.

I am following the steps in the Docker guide for the Raspberry Pi exactly as listed. Clone the git, CD into the new folder, and then build the image. I get the error on the last step

**Comment by Tyrrrz** [comment]
Can you post as much of the build log as possible? I couldn't reproduce it

**Comment by LIPDProductionsInc** [comment]
![image](https://user-images.githubusercontent.com/11858305/205423201-77e3dd78-2182-404e-822c-cb48342d01b4.png)
![image](https://user-images.githubusercontent.com/11858305/205423229-acbc8744-fdf6-4745-9d56-917062373d83.png)

**Comment by LIPDProductionsInc** [comment]
Also the output of cloning the repo using `git clone http://github.com/Tyrrrz/DisscordChatExporter.git`
![image](https://user-images.githubusercontent.com/11858305/205423744-63fbd7f0-034f-4441-97aa-4948aa5e72de.png)

**Comment by hyzchip** [comment]
I'm not entirely familiar with Docker, so this is just speculation...perhaps the issue has to do with the fact that the missing file is a DLL?  This appears to be a Linux system, which doesn't use DLLs unlike Windows.

**Comment by Tyrrrz** [comment]
> I'm not entirely familiar with Docker, so this is just speculation...perhaps the issue has to do with the fact that the missing file is a DLL? This appears to be a Linux system, which doesn't use DLLs unlike Windows.

No, that's irrelevant.

**Comment by LIPDProductionsInc** [comment]
Now working as expected
