### ISSUE TITLE
DiscordChatExporter no longer is able to export chats

### ISSUE THREAD

**Issue by TheMajorTechie** [Tyrrrz/DiscordChatExporter#969]
### Version

2.36.4, 2.34.X, 2.29.0, and seemingly all previous versions

### Flavor

GUI (Graphical User Interface)

### Export format

HTML, TXT, JSON, CSV

### Details

I was attempting to make an export of a Discord server I run, but DiscordChatExporter currently is only able to export the avatars and message dates of each message. The actual contents/text of the message being sent is left entirely blank.

Judging by the fact that all previous versions I've tried are also no longer functional, my guess is that Discord broke compatibility with the bot at some point with a recent update.

Attached below is what all exports look like. .txt and .csv exports are also blank.

![image](https://user-images.githubusercontent.com/29270676/206835834-2aa93428-8124-43aa-915d-93c10848cfe7.png)

### Steps to reproduce

Open DiscordChatExporter and enter the token
Navigate to a server channel to export
Select the channel(s) to export
Click "export"

**Comment by Tyrrrz** [comment]
If you're exporting using a bot, you need to enable message content intent. Discord made announcements about this change multiple times. It's also mentioned in the usage guide in the application.
