### ISSUE TITLE
Token getting instructions don't work

### ISSUE THREAD

**Issue by SavantSusi** [Tyrrrz/DiscordChatExporter#975]
### Version

2.36.4

### Flavor

GUI (Graphical User Interface)

### Details

I followed the instructions on both firefox and chromium and "messages?limit=50" didn't appear when searching in the network tab of either and refreshing. I followed what I believe are the old instructions and went to the application tab > local storage > discord.com, refreshed and searched for "token" and tokens showed up but they disappeared too fast to copy them

### Steps to reproduce

the instructions on the program

**Comment by Tyrrrz** [comment]
What if you click around the app, switch to a different server etc., does `messages?limit=50` show up?

**Comment by SavantSusi** [comment]
Oh, I didn't think to try that. Works now, thanks.
