### ISSUE TITLE
GPLv3 incompatible with additional terms of use

### ISSUE THREAD

**Issue by lopho** [Tyrrrz/DiscordChatExporter#979]
### Version

All

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

GPLv3, section 7 (with reference to section 10)
```
If the Program as you
received it, or any part of it, contains a notice stating that it is
governed by this License along with a term that is a further
restriction, you may remove that term.
```
Additional usage restrictions as stated in the readmes TOU are not applicable with the GPLv3.

You can of course voice your support for whatever you deem fit, but not as usage restrictions on top of GPLv3 licensed code.

**Suggestion:**
Remove wording as terms of use, but retain your points of view.

Reword "You" as "I"

---

~~Terms of use~~

~~By using this project or its source code, for any purpose and in any shape or form, you grant your implicit agreement to all the following statements:~~

- ~~You~~ I condemn Russia and its military aggression against Ukraine
- ~~You~~ I recognize that Russia is an occupant that unlawfully invaded a sovereign state
- ~~You~~ I support Ukraine's territorial integrity, including its claims over temporarily occupied territories of Crimea and Donbas
- ~~You~~ I reject false narratives perpetuated by Russian state propaganda

### Steps to reproduce

Read the license.

**Comment by Tyrrrz** [comment]
That's okay.

**Comment by KaspianDev** [comment]
lmao, by using this program you agree to have the same opinions as me :trollface:

**Comment by KaspianDev** [comment]
> That's okay.

y so mad

**Comment by zarlo** [comment]
it just means the terms of use are irrelevant

but it also breaks githubs TOS so...

**Comment by Genfilf** [comment]
The software is not your private army. Keep your political bullshit outside of the code.

**Comment by SupahFox** [comment]
Reported your entire account for bringing geopolitics into software 😂👌
