### ISSUE TITLE
Visual difficulties when exporting many empty channels

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#988]
### Version

2.37.1

### Flavor

CLI (Command Line Interface)

### Details

When trying to export an empty channel (which happens quite often when you try to export a server with many voice channels), it gets skipped, stays at 0% in the progress interface, and at the end of the export, you get an error message that looks like this:

![Screenshot (3)](https://user-images.githubusercontent.com/81419612/213214897-00232f33-86de-41b9-a608-a9f304d12992.png)

However, this message only appears after the entire export has been completed. So when you're trying to export a server with many empty channels, it does end up looking quite messy. In this case, all of the not-empty channels got pushed off the screen which makes it basically impossible to keep track of the export:

![Screenshot (12)](https://user-images.githubusercontent.com/81419612/213215623-c4f8caf7-8d24-4ef1-9cd7-6794c6a05fbf.png)

There are multiple possible solutions for this:

A) Once the program notices that a channel is empty, set its progress to 100%. This way it would be easier to keep track of how many channels still have to be exported since you could differentiate between not-empty channels at 0% and empty channels.

B) Do the same as in A) but make the entire progress bar red or add an error message directly in the channel's line to differentiate between a successful export and a failed export.

C) Check if a channel is empty before listing it. By doing that, empty channels could be completely excluded from the progress interface which would make it way less cluttered.

### Steps to reproduce

Export multiple empty channels and you might run into visual difficulties.

**Comment by Tyrrrz** [comment]
@CanePlayz I made a change that makes failed tasks appear as completed (basically your suggestion A). I can't test it now because I have limited internet availability. Can you check the latest CI build (once it finishes) if it fixes your issue?

**Comment by CanePlayz** [comment]
Yes, works perfectly fine, thanks for the quick fix. Still, if there are many empty channels, at one point you won't be able to see the channels that are still being exported anymore because they got pushed so far to the top, but that's acceptable, it does look way better than before. 👍
