### ISSUE TITLE
Finding it impossible to make extractions in to a website format

### ISSUE THREAD

**Issue by TechUser1927** [Tyrrrz/DiscordChatExporter#99]
Hi! More detail here.

I've been exporting channels and there has been the issue that it is coming up as file:///C:/Users/NAME/Downloads/DiscordChatExporter/Model%20Hogwarts%20-%20ye-olde-qs.html when it opens in my browser (Opera, also does the same in Internet Explorer)

I'm not sure if it's supposed to be like that but it is causing problems as it's for a server that needs this sort of thing.

**Comment by Tyrrrz** [comment]
Hi,
Is there a question you're trying to ask? Or a goal you are trying to achieve unsuccessfully?

**Comment by TechUser1927** [comment]
I'm wondering if it back up channel link that comes up in the HTML bar are supposed be like the example above or if they can be formatted in to a website link? I've opened previous links to view backed up channels which have appeared as a website link.

**Comment by Tyrrrz** [comment]
They're supposed to be like that. The files are not uploaded to a remote webhost, they're on your local file system, thus the URL looks exactly as it should.

**Comment by TechUser1927** [comment]
Alright, thanks!
